### PR TITLE
Roomsettings: Make blacklist cmd perms toggleable

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by bumbadadabum** [comment]
I don't like this. I have considered it but decided a 1 year ip ban is too
much power for roommods

**Comment by bumbadadabum** [comment]
This should also never be a large concern.  If you need to use blacklists
so much the ROs can't handle it, you have different problems as a room.

**Comment by bumbadadabum** [comment]
I also don't like the idea of roommods being able to mass ban a room.

**Comment by panpawn** [comment]
> If you need to use blacklists so much the ROs can't handle it, you have different problems as a room.

Is it a matter of "this room doesn't have active ROs," or a matter of "this room has active ROs and trusts their roommods with blacklists"?

I think it's the later.

>I also don't like the idea of roommods being able to mass ban a room.

... they can already do that with /roomban

>too much power for roommods

Uh, well, before this was a thing server-side, how it worked was ROs would have roommod bots, and they would usually give roommods+ access to that bot's blacklist command.  I don't see how allowing them to use the server-side blacklist command is much different than a bot blacklist command.

I understand that it is IP based, and I also understand what uncommon offenses should be blacklisted for.  If a staff or roommods also understands this, and the RO recognizes that fact, then I see no reason for that room to not allow roommods to use this command.

If someone is unfairly blacklisted or a roommod fucks up, then that room will handle that specific instance accordingly, as with all other forms of room punishment.

maybe there's just something I'm not getting here, or maybe I don't really see what's wrong here, but in terms of actual power, I don't see this as a huge policy change.

As a matter a fact, some rooms specifically aren't using the server-side blacklist system BECAUSE it doesn't allow roommods to use it. 

I think our mission should be to eliminate bots from being needed for all forms of moderating, and this is a good final step towards that goal.

**Comment by bumbadadabum** [comment]
> I think it's the later.

No it's the former. Most rooms have (and should) have <25 people on the blacklist. An active RO should be able to deal with that by themselves even.

> ... they can already do that with /roomban, in theory

In practice this makes it a lot more convenient, and harder to stop midway.

>Uh, well, before this was a thing server-side, how it worked was ROs would have roommod bots, and they would usually give roommods+ access to that bot's blacklist command. I don't see how allowing them to use the server-side blacklist command is much different than a bot blacklist command.

The bot blacklists ONLY worked on names and could not even check the IP of users. It also didn't work ALL the time, only when the user attempts to join the room. The serverside blacklists are actually the longest punishment based on IP ON THE SIM. Granted, they're from a single room, but I would very much prefer to only have this available to people who have directly received the necessary trust from staff.

>I understand that it is IP based, and I also understand what rarer offenses should be blacklisted for. If a staff or roommods also understands this, and the RO recognizes that fact, then I see no reason for that room to not allow roommods to use this command.

Again, if they understand how uncommon it should be, there should be even less reason to allow more people to use it.

>As a matter a fact, some rooms specifically aren't using the server-side blacklist system BECAUSE it doesn't allow roommods to use it, and are still using bot-based blacklist systems.

Then they can do it. This feature is only there to provide an option. Rooms can choose themselves whether they use the options given to them. The key is to provide the right options to the right people, and I don't think that is the case here.

>I think our mission should be to eliminate bots from having a purpose of moderating of all forms for rooms, and this is a good final step towards that goal imo.

I disagree that bots should not be allowed to moderate at all. There are things a bot provides more flexibility for and allows to fit a room's specific needs more, as they are sometimes better done externally.

>(Also probably worthy to note: After discussing this with several users in higher global/room policy positions on PS, there overall seems to be a want for this change)

I've talked with multiple ROs that are strongly against this change. I also would like to note that some of the decisions are also made from a technical perspective, and trying to meet as many demands as possible while still trying to leave little margin for errors.

I hope this clears up my perspective more.

**Comment by panpawn** [comment]
>In practice this makes it a lot more convenient, and harder to stop midway.

I mean, if you have a roommod mass banning users in a room, then you have more pressing matters to be concerned about.

>The bot blacklists ONLY worked on names and could not even check the IP of users.

Well, roombans __are__ IP based... so, not really.

 >Again, if they understand how uncommon it should be, there should be even less reason to allow more people to use it.

Some larger rooms use blacklists pretty regularly, namely Lobby and Wi-Fi, afaik
(and there's probably more this would be applicable to, too)

>Then they (ROs) can do it.

Some rooms don't have extremely active ROs in terms of actual room visits/day.  

>This feature is only there to provide an option.

So would this roomsettings option... ?_?

>I disagree that bots should not be allowed to moderate at all. 

Never did I say that they shouldn't _be allowed_ to moderate, but that they _shouldn't have to_.

>I've talked with multiple ROs that are strongly against this change. 

Then those ROs can keep this setting turned off, and nothing will change for that room's policy.  But with this logic, don't let one room's policy interfere with that of another's... :|

**Comment by bumbadadabum** [comment]
>I mean, if you have a roommod mass banning users in a room, then you have more pressing matters to be concerned about...

This is still a concerning matter considering various mods have gone renegade before. ROs on the other hand undergo an intensive vetting process that is (and should be) more intensive than for mods.

>Well, roombans are IP based... so, not really. The only actual difference is the duration.

Yes but someone has to join the room on the blacklisted name unlike the serverside blacklists.

>Some larger rooms use blacklists pretty regularly, namely Lobby and Wi-Fi, afaik
(and there's probably more this would be applicable to, too)

Zarel and I agreed that the Wi-Fi room was using the blacklists wrong, and should even keep a bot for blacklists for scamming (this is actually the case as of today)
[19:51:24] Zarel: again, tell them to keep the bot for trade blacklists (relevant quote)

>Some rooms don't have extremely active ROs in terms of actual room visits/day. 

In the meantime, a user could be roombanned, which could be extended to a blacklist when a RO does come online.

>Never did I say that they shouldn't be allowed to moderate, but that they shouldn't have to.

And they don't have to.

>Then those ROs can keep this setting turned off, and nothing will change for that room's policy. But with this logic, don't let one room's policy interfere with that of another's... :|

It changes how blacklists work sitewide and established permissions. By implementing this feature you are effectively allowing ROs to pass on RO features to mods bypassing the public RO approval thread.

**Comment by panpawn** [comment]
>This is still a concerning matter considering various mods have gone renegade before. ROs on the other hand undergo an intensive vetting process that is (and should be) more intensive than for mods.

Just as easily as a rouge roommod could go by roombanning everyone, they could also blacklist, and both log, so both are just as easy to reverse by that logic.

>Yes but someone has to join the room on the blacklisted name unlike the serverside blacklists.

I mean, once they get roombanned (by a bot blacklist or in general), they get IP banned (from that room).

>Zarel and I agreed that the Wi-Fi room was using the blacklists wrong, and should even keep a bot for blacklists for scamming (this is actually the case as of today)

Wi-Fi isn't the only room that has a large blacklist.  Is that to say all rooms that have a large blacklist use it wrong? I think that might be a stretch, if so...

>In the meantime, a user could be roombanned, which could be extended to a blacklist when a RO does come online.

My point still remains:
>I would argue that because it's harder to find an active RO on at any given time, that someone who might of deserved a blacklist might only get away with a roomban in it's place because of the hassle of remembering to tell a RO to blacklist them.

>It changes how blacklists work sitewide and established permissions. By implementing this feature you are effectively allowing ROs to pass on RO features to mods bypassing the public RO approval thread.

It doesn't change "established permissions," as this won't change anything by default.

What determines that this is a RO feature, but yet a bot blacklist isn't?  That sounds like room-policy territory to me.

**Comment by bumbadadabum** [comment]
>Just as easily as a rouge roommod could go by roombanning everyone, they could also blacklist, and both log, so both are just as easy to reverse by that logic.

I think this entire line of conversation is getting incredibly petty and blown out of proportion.

>I mean, once they get roombanned (by a bot blacklist or in general), they get IP banned (from that room).

This still needs to happen. If the troll is using a different username on the same IP (which isn't hard to do), he can enter the room with no problems.

>Wi-Fi isn't the only room that has a large blacklist. Is that to say all rooms that have a large blacklist use it wrong? I think that might be a stretch, if so...

You were listing specific examples so I decided to elaborate on one of them given I'm roomstaff in the room in question.

>My point still remains:

No it doesn't. The roomban can be extended into a blacklist with ease, and nowhere did I suggest people could "get away with a roomban". If roommods aren't competent enough to remember to tell a RO to blacklist, should we be trusting them with the blacklist permission itself?

>It doesn't change "established permissions," as this won't change anything by default.

There is a permission established since the PR for roomblacklists. There were ample opportunities to voice your concerns then (the PR was open for literally months), but you didn't do that before a command (with a permission) was already implemented on PS.

>What determines that this is a RO feature, but yet a bot blacklist isn't? That sounds like room-policy territory to me.

As I've said before, the severity of the punishment and the necessary trust in a RO.

**Comment by panpawn** [comment]
>I think this entire line of conversation is getting incredibly petty and blown out of proportion.

??
Perhaps I misunderstood what you meant then, could you elaborate?

>This still needs to happen. If the troll is using a different username on the same IP (which isn't hard to do), he can enter the room with no problems.

Blacklists aren't particularly much harder to evade, though.  I also fail to see how this ties in at all.

>You were listing specific examples so I decided to elaborate on one of them given I'm roomstaff in the room in question.

But my point is is that those aren't the only rooms that this might be helpful for, that those were just some of them... :|

>No it doesn't. The roomban can be extended into a blacklist with ease, and nowhere did I suggest people could "get away with a roomban". If roommods aren't competent enough to remember to tell a RO to blacklist, should we be trusting them with the blacklist permission itself?

Yes, they can be extended "with ease."  Does this mean that every single mod remembers to pass on names who should be on the blacklist in every single instance? No.  Does this make them a bad mod? I personally don't think so, but you're entitled to your own opinion here.

>There is a permission established since the PR for roomblacklists. There were ample opportunities to voice your concerns then (the PR was open for literally months), but you didn't do that before a command (with a permission) was already implemented on PS.

As I said on that PR, that entire PR was merged pre-maturely, and I could say that the "lack of expression on that PR" for this was a consequence of that.

Refs:
>For what it's worth, I think big refactors like this should take a considerable amount of time. I feel as though this instance was rushed in the way that there were still a lot of things not really addressed and it all kind of had a "thrown together" vibe to it when all was said and done.

**Comment by bumbadadabum** [comment]
>Blacklists aren't particularly much harder to evade, though. I also fail to see how this ties in at all.

You need to change your IP, which a lot of (mostly younger) users cannot do.

>But my point is is that those aren't the only rooms that this might be helpful for, that those were just some of them... :|

Where do I imply otherwise, I just responded to your example with an example.

>Yes, they can be extended "with ease." Does this mean that every single mod remembers to pass on names who should be on the blacklist in every single instance? No. Does this make them a bad mod? I personally don't think so, but you're entitled to your own opinion here.

If someone should be blacklisted, there is usually a policy discussion within the room, since blacklists are not a punishment like a lock or ban, but intended for long-term problem users in the room who should not be allowed in the room at all (definition of a blacklist in this context). A RO should always be involved with this discussion, and it seems only logical to me that they are the one making the decisions.

>As I said on that PR, that entire PR was merged pre-maturely, and I could say that the "lack of expression on that PR" for this was a consequence of that.

There were a whole lot of replies on that PR, and not a single one about the permission. The time it took for the PR is definitely enough to bring up these concerns in my opinion.

Also, can you provide a source and context for that quote?

**Comment by panpawn** [comment]
>You need to change your IP, which a lot of (mostly younger) users cannot do.

Roombans were IP based, they were before this refactor and still are... (still failing to see relevancy with this though)

>If someone should be blacklisted, there is usually a policy discussion within the room, since blacklists are not a punishment like a lock or ban, but intended for long-term problem users in the room who should not be allowed in the room at all (definition of a blacklist in this context). A RO should always be involved with this discussion, and it seems only logical to me that they are the one making the decisions.

Yes, and different rooms obviously feel differently about this.

>There were a whole lot of replies on that PR, and not a single one about the permission. The time it took for the PR is definitely enough to bring up these concerns in my opinion.

I would like to agree with this, but there were so many things that weren't addressed that before I looked at it closer on a more serious note, I was waiting for it to get into, what I considered, its final stadges... of which, never happened.

>Also, can you provide a source and context for that quote?

My latest comments on: https://github.com/Zarel/Pokemon-Showdown/pull/2545

**Comment by bumbadadabum** [comment]
>Roombans were IP based, they were before this refactor and still are... (still failing to see relevancy with this though)

My point is that evading blacklists wasn't IP based. I'm tired of repeating myself.

>Yes, and different rooms obviously feel differently about this.

I'm not saying what my opinion was, but rather the idea of the entire feature to begin with.

**Comment by Zarel** [comment]
Strong no. Mods can roomban until ROs come around.

**Comment by Morfent** [comment]
I ran into a similar situation to this while hosting BoTTT, so I guess I should mention it.  At one point I was forced to add a regex variant of autobans to it because people were evading autobans on server resets and taking advantage of the easy name recognition by keeping a pattern of names. I couldn't trust room mods with the command like I could with regular autobans though because like with server blacklists, few room mods knew what they were doing to avoid autobanning far more users than intented. Likewise, few room mods in the majority of rooms now are capable of seeing user IPs to avoid blacklisting an entire school because of one user, for example. I can't trust room mods with blacklists for the same reason I only trusted a few people with regex autobans; they have no way to be able to see just how many different users they're blacklisting from a room.

**Comment by panpawn** [comment]
>they aren't guaranteed to be able to gauge what effect blacklisting someone would have.

Well, not all ROs are global mod+ that they can see IPs to gauge that, either.

**Comment by Morfent** [comment]
>Well, not all ROs are global mod+ that they can see IPs to gauge that, either.

I don't see how this helpa either of our arguments.

**Comment by panpawn** [comment]
So, I take it I should close this since among the people who have commented, the general consensus is that this shouldn't be a thing.

If I am wrong in this assumption, then someone can feel free to reopen this.

**Pull request closed without merging**
