### PR TITLE
Improve help provided by commands

### PR DESCRIPTION
**Pull request by Bryan-0**
- Send a help reply if there is no target in /roomowner and /roomdeowner command.
- Add 2 new aliases for pm faq.

### CODE REVIEW

**Comment by Slayer95** [comment]
@Bryan-0 I think it's about time for you to start writing proper commit messages.

https://github.com/pyinstaller/pyinstaller/wiki/Development-Commit-Messages

In particular, the first line should not include implementation details, such as ``Add parse``. What does that even mean?

Also, while it's great that you have opened a single PR for these changes, a single commit should not include two totally unrelated changes such as 1) Reply with help for lack of target in /[de]roomowner, and 2) Add new alias. Instead, make two separate commits <i>within</i> this pull request, or -alternatively- merge them in a single general-purpose commit named like "Improve help provided by commands", followed by a list of specific changes.

That's all I can say for now.

**Comment by Bryan-0** [comment]
All fixed and updated.

**Comment by Slayer95** [comment]
Good!

**Comment by Bryan-0** [comment]
Yay!

**Comment by Zarel** [comment]
> @Bryan-0 I think it's about time for you to start writing proper commit messages.
> 
> https://github.com/pyinstaller/pyinstaller/wiki/Development-Commit-Messages

...

> For best results, stay within 72 characters per line. Don't go over 80.

...pot, kettle, etc

**Comment by Zarel** [comment]
> Try to end summary lines with a period. Ending punctuation other than a period should be used to indicate that the summary line is incomplete and continues after the separator; "..." is conventional.

PS convention is not to use periods. Do projects usually use periods? Should we be switching?

> Write your commit message in the present tense: "Fix bug" and not "Fixed bug." Consider these messages as the instructions for what applying the commit will do. Further this convention matches up with commit messages generated by commands like git merge and git revert.

To be exact, this is imperative mood, not a tense.

> Bullet points are okay, too:

PS convention is to use `-` and not `*` for bullet points, although this isn't a big deal.

**Comment by Slayer95** [comment]
Well, that's the best link I found in a quick web search, sorry ;w;

**Pull request merged**
