### PR TITLE
Fix Mold Breaker interaction with Damp

### PR DESCRIPTION
**Pull request by ascriptmaster**
Damp should be suppressed by Mold Breaker.

### CODE REVIEW

**Comment by Marty-D** [comment]
Uh, when I said "redirection is ignored" I meant Mold Breaker ignores redirection by the Abilities. As in, everything about Lightning Rod and Storm Drain is negated while a Mold Breaker Pokemon is attacking.

**Comment by ascriptmaster** [comment]
But the bug with Damp is correct, right?

**Comment by Marty-D** [comment]
Correct.

**Comment by ascriptmaster** [comment]
Hmmmm, like so?

**Comment by Marty-D** [comment]
Yeah that looks better. :+1:

Whoa, were all those tests there last time I viewed this? If they were I definitely missed them; very nicely done! I'll have to skim through it later.

**Comment by ascriptmaster** [comment]
All the tests (and test wording changes) were there from the beginning of the PR, but I had to re-tweak the Lightning Rod/Storm Drain ones based on the new information.

**Comment by Zarel** [comment]
Skim at your leisure, @Marty-D.

**Pull request merged**
