### PR TITLE
Regression in /ds fake out, extreme speed

### PR DESCRIPTION
**Pull request by urkerab**
Only Smeargle can legally learn both at once.

This is basically a backout of eb8d2ab but with some extra changes to fix the crash in a different way.

### CODE REVIEW

**Comment by Zarel** [comment]
@asgdf, can you review?

**Comment by Zarel** [comment]
Wait GitHub has a button for that now.

**Comment by Zarel** [comment]
Wait no that's only for collaborators

**Comment by Zarel** [comment]
```
> Tools.getTemplate('raichu').eventPokemon
undefined
> Tools.getTemplate('raichu').learnset.holdhands
[ '6S33', '6S34', '6S35', '6S40', '6S42' ]
```

Well, this is still crashing

**Comment by asgdf** [comment]
Well my JS knowledge is limited, but I don't think a deep clone of the dex is made anywhere here, so the actual templates' learnsets are being modified. Then again, `dex = JSON.parse(JSON.stringify(dex))` should have created a deep clone in the old version and that didn't work either.

**Comment by Zarel** [comment]
Yes, I fixed that between then and now.

**Comment by Zarel** [comment]
For this, I'm still waiting for @asgdf to comment.

**Comment by asgdf** [comment]
Oh, movesearch was also modifying the learnsets, that explains it.
I did comment? - but I suppose I can make my comment more specific then: 
`dex = JSON.parse(JSON.stringify(dex))` should be re-added. I only removed it because I also removed the whole learnset compilation part.

**Comment by Zarel** [comment]
`Object.assign` seems to be sufficient; I don't think you need a deep copy here?

**Comment by urkerab** [comment]
`dex` is a local object, so calling `Object.assign` on it doesn't seem to achieve anything. However, the code does assign to the `fullLearnset` property of each template; if this is unwanted, I could shallow clone each template, or add a separate object to hold the full learnsets i.e. replace `dex[mon].fullLearnset` with `fullLearnset[mon]` throughout.

**Comment by Zarel** [comment]
A shallow copy is done by `dex = Object.assign({}, dex)`

**Comment by urkerab** [comment]
`dex` is already a uniquely referenced local object, so making a shallow copy achieves nothing.

**Comment by DeathlyPlays** [comment]
@urkerab BUMP

**Comment by urkerab** [comment]
Looks like @sirDonovan might have fixed this a better way in bce279e.

**Comment by Zarel** [comment]
Good to know

**Pull request closed without merging**
