### PR TITLE
Transform should ignore Roost's effects

### PR DESCRIPTION
**Pull request by MacChaeger**
Looks like we'll have to hard-code something Roost-related after all.

### CODE REVIEW

**Comment by Marty-D** [comment]
What if the Roost user's type changes between Roost and Transform?

**Comment by MacChaeger** [comment]
I made sure that the getType event was called immediately before that check so typeWas would be updated.

**Comment by ascriptmaster** [comment]
Can't you just, like, not copy the Roost volatile? Or does it need to be copied for some other things?

**Comment by MacChaeger** [comment]
It's not that it was copying the volatile, it's that it was copying  the
Roost-modified type by using the getType function. Transforming is the only
case where Roost removing the flying type isn't actually supposed to ma-

Actually, we could avoid hard-coding for this by just having the transform
function copy the target's types directly without using that function, and
then manually running the Type event on itself, rather than on the opposing
Pokemon.

Also, is Reflect Type supposed to ignore Roost too? Because it's not rn.

**Comment by ascriptmaster** [comment]
That's basically what I was thinking tbh, I always assumed it would copy the type directly, plus the Reflect Type volatile and whatever else was needed

**Comment by Marty-D** [comment]
Reflect Type does not copy the Flying type during Roost, so that's fine.

**Pull request merged**
