### PR TITLE
Implement Battle Factory

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by Slayer95** [comment]
The file `data/factory-sets.json` is built from https://github.com/Slayer95/Pokemon-Showdown-Factory.
(Will transfer ownership on request)

**Comment by TheImmortal** [comment]
I wouldn't include LC. It's a different thing altogether. Also, I'd vote for it to be under OMs. The reason Randoms is in Singles is to be on top because it's the default format.

**Comment by Slayer95** [comment]
I don't mind removing LC, but I'll wait for further feedback before actually doing it.

**Comment by TheImmortal** [comment]
No.

**Comment by TheImmortal** [comment]
Above CC is fine.

**Comment by Slayer95** [comment]
Updated.

We also need to decide whether we are going to use Team Preview or not.
Traditionally, Battle Factory has lacked it; however, we could add it <strike>just because we can</code> as it would more properly reflect game mechanics and it would help further distinguishing them from RandBats.

**Comment by TheImmortal** [comment]
Hmm, I say include Team Preview. This is meant to make competitive teams and team preview is part of competitive Pokemon as you cannot have a battle vs someone in-game without it.

**Comment by ascriptmaster** [comment]
I am in favor of Team Preview. :+1:

**Comment by Slayer95** [comment]
So be it

**Comment by xfix** [comment]
<del>What about forcing Stealth Rock in every team, because every team is objectively better with rocks.</del>

**Comment by Slayer95** [comment]
90% teams with SR, and a similar amount with Defog/Rapid Spin. Is that enough rocks? :P

**Comment by Zarel** [comment]
I think TI owns OM? Meh, one of you figure out who wants to be in charge of this.

**Comment by Rhythms88** [comment]
Both Joim and The Immortal are a part of the OM team; The Immortal and Eevee General lead it.

**Comment by TheImmortal** [comment]
I will probably improve something if I see it is needed in the future but right now I'm on LoA so Joim can review this.

**Comment by Joimer** [comment]
I have been playing locally and the teams generated are decent, this is good enough for an initial release, but we should listen to feedback to improve them.

I'd like if we had a good way for users to submit or request set editions / additions on the json, I understand why it's in one line, but just a thought there.

I think the format should be above CAP, as it is supposed to be a spotlight format. Also it seems that there are two kind of battle factories, bring 6 choose 3 and 6v6, the latter seems fine for the moment.

**Comment by Disaster-Area** [comment]
The former version [bring 6 pick 3] is more closely related to the BF in the actual games, whilst 6v6 is a more.. natural form since we're making teams using pokemon designed for 6v6 metagames.

As a general rule every team (100%) should have one (and no more than one) stealth rock setter, that's pretty much an absolute as far as I understand it. I've heard top players describing it as more mandatory than say Snorlax in GSC OU.

You should definitely work with people involved in the respective tiers to get respectable and up-to-date sets. As a primary task maybe making sure at least that every set is considered analysis-worthy, and then after that point get finer variations, and then at that point, you need to create some sort of facility for players to interact with you on a regular basis when new sets rise to popularity in the high-end competitive community (think anything from the creation of DD chestorest kingdra in DPP when BW was the main meta, to the evolution of gliscor sets in gen 6, to the new variants of pokemon seen in NU with recourse to SPL (check out issue 42 of the smog ;D).

Unfortunately I'm not qualified to really assist at a high enough level for it to be worth mine or your time for me to involve myself in this, but at the same time if in a few weeks I see dire totally unviable sets still in use I'll at least pop Joim a vm and see what's up =]

**Comment by TheImmortal** [comment]
>I think the format should be above CAP, as it is supposed to be a spotlight format, but it is not important.

After thinking about it, it should be above CAP because it's based on all the standard formats and not like other random formats. But, we should wait until it is good enough and then move it.

**Pull request merged**
