### PR TITLE
Fix Battle Bond + Skill Link in Shared Power

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by urkerab** [comment]
I don't suppose you'd mind explaining what this was fixing? As I see it, if Skill Link processes first, it sets multihit to 5, but then Battle Bond sets it back to 3; if Battle Bond processes first it sets multihit to 3 which Skill Link then ignores.

**Comment by KrisXV** [comment]
The OM room seemed that Batrle Bond shouldn’t be overridden, similar to how the OM community decided on how poison heal and magic guard interact

**Comment by KrisXV** [comment]
Deemed* I would edit but mobile isn’t letting me

**Comment by urkerab** [comment]
I don't think it was being overridden. In fact, I actually had a complaint from a user on ROM that it wasn't, and I had to explain that Battle Bond was overriding Skill Link.

**Comment by KrisXV** [comment]
They had the same priority so it randomly applied one effect over the other; people complained to me about it randomly proccing one over the other on the ladder.

**Pull request merged**
