### PR TITLE
Fix up Desolate Land/Primordial Sea tests

### PR DESCRIPTION
**Pull request by ascriptmaster**
aka: I got home late and for some reason decided I want to keep up my pointless Github streak

### CODE REVIEW

**Comment by Zarel** [comment]
...is this test useful for something? I can't think of a regression that would break this...

**Comment by ascriptmaster** [comment]
idk I'm sleepy

**Comment by ascriptmaster** [comment]
I was going to set up an alias for Random Monotype Battles instead (randmono) but for some reason I did this

**Comment by ascriptmaster** [comment]
Bleh, better not let this PR go to waste. Here's an actual thing that can be fixed. I discovered off-by-one errors while writing Cloud Nine tests for #1830 so I figured it's better for these tests to check the `BasePower` event directly.

**Comment by Slayer95** [comment]
Am I the only one uncomfortable with monkeypatching <code>Battle#runEvent</code>?
It has been done before in Weight tests, but still :|

**Comment by ascriptmaster** [comment]
I guess I could monkey-patch `BattlePokemon#damage` instead like what we did in our Roost tests.

**Comment by ascriptmaster** [comment]
In the end I just decided to call a `BasePower` event for each manually. It's easier that way.

**Pull request merged**
