### PR TITLE
Update datacenters & IP-tools

### PR DESCRIPTION
**Pull request by Lusamine**
This also fixes an error from [here](https://github.com/Zarel/Pokemon-Showdown/pull/5879/files).

### CODE REVIEW

**Comment by Zarel** [comment]
Why did you open a new PR instead of using #5876? It looks like you do know how to force-push...

**Comment by Lusamine** [comment]
I had no idea how to fix it and the people who were on at the time couldn't tell me either.

**Comment by Zarel** [comment]
Interesting. Did you not know _how_ to force-push? Or did you get an error message when trying to force-push?

**Comment by Lusamine** [comment]
Several commits had gotten merged in between when I opened the PR and fart's erroneous ranges got merged.  Pulling his changes ended up including all those in-between commits as well, and I couldn't figure out how to handle that.

**Pull request merged**
