### PR TITLE
use origin/master as basis for replay version tag

### PR DESCRIPTION
**Pull request by yuzeh**
See #5412

### CODE REVIEW

**Comment by Zarel** [comment]
In general, Main should never be running with unpushed commits.

I think using local head is better, because in the exceptions:

1. Sometimes Main runs on a detached HEAD on an older version, if there's a critical bug in origin/master HEAD.

2. If there _is_ an unpushed commit, it'll probably be pushed soon.

**Comment by Slayer95** [comment]
Would you be fine with reporting some sort of compound version from the latest ``HEAD`` commit and the ancestor in ``origin/master`` ?

**Comment by Zarel** [comment]
Sure, if they differ.

**Comment by yuzeh** [comment]
Not sure I completely follow. What should this look like?

This is my idea:
```
>version-HEAD `git merge-base HEAD HEAD`
>version-master `git merge-base master HEAD`
>version-origin-master `git merge-base origin/master HEAD`
```

**Comment by Zarel** [comment]
I would say `>version` as before, and `>version-origin` only if they differ.

**Comment by Slayer95** [comment]
Fixed in #5542.

**Pull request closed without merging**
