### PR TITLE
Refactor lastAttackedBy to hurtBy

### PR DESCRIPTION
**Pull request by bgsamm**
Replaced the 'lastAttackedBy' attribute of a Pokemon with an array of attacks that the Pokemon has recently received. This corrects a bug in double battles arising from lastAttackedBy always getting replaced by the most recent attack, which caused Avalanche and Revenge to not double in power when they otherwise should have (e.g. see https://replay.pokemonshowdown.com/gen7doublescustomgame-796785834). This also addresses the corresponding task in #2444.

### CODE REVIEW

**Comment by bgsamm** [comment]
Closing to address mocha test

**Comment by bgsamm** [comment]
bump

**Comment by Marty-D** [comment]
Hi, very sorry about the delay, I didn't get any of these alerts.

This looks pretty good! Would you mind creating a `lastHurtBy()` function as a shortcut for `hurtBy[target.hurtBy.length - 1]`? Makes uses of it much more readable. This is otherwise a great improvement, thanks!

**Comment by bgsamm** [comment]
Yep, can do. And no worries about the delay.

**Pull request closed without merging**
