### PR TITLE
Add some regression tests for Substitute

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by Slayer95** [comment]
Imo move properties/flags should be tested on each move, the same way as abilities' Mold Breaker interaction is planned.

Also, regarding DRY: I didn't really "repeat myself": it was all code automatically generated from a template.

This would also be aligned with more tests to come regarding Chatter -to mention an specific move-, (e.g. Chatter's interaction with Chatot/non-Chatot, confusion+subs, etc...), as well as other moves.

**Comment by ascriptmaster** [comment]
Fair enough. I removed the sound.js test and kept substitute.js for now. Maybe I'll expand to add Screech and the stat-drop sound moves as tests later.

**Comment by Zarel** [comment]
> Also, regarding DRY: I didn't really "repeat myself": it was all code automatically generated from a template.

I think that still counts as repeating yourself

**Comment by Slayer95** [comment]
Well... then maybe we should have in each move something like

```var utils = require('somepath');
it('should pierce through Substitutes', utils.ignoresSubs.bind(null, 'moveName', details))
```

Where <code>details</code> is a parameter such as <code>'damage'</code> or <code>'boost'</code> which can be generically coded in the utilities.

Does that sound appropriate for you?

**Comment by ascriptmaster** [comment]
That would probably work well. It's not something I'm planning to add for this PR, but it's a good idea.

**Comment by Zarel** [comment]
I don't know how much I care about repetition in tests, as long as entire tests aren't being duplicated.

**Comment by Zarel** [comment]
I'm going to assume this is good. Just, if these are already tested elsewhere, remove the redundant tests.

**Pull request merged**
