### PR TITLE
Acid, Aurora Beam, Bubblebeam Effect chances

### PR DESCRIPTION
**Pull request by Guernouille**
In Stadium, Effect chance for Acid is 51/256, Effect chance for Aurora Beam is 77/256, and Effect chance for Bubblebeam is 77/256.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Can you provide your source?

**Comment by Joimer** [comment]
Checked it, seems right.

**Comment by Guernouille** [comment]
http://datacrystal.romhacking.net/wiki/Pokémon_Stadium:ROM_map#Acid.2C_Aurora_Beam.2C_Bubble.2C_Bubblebeam.2C_Psychic

Acid, Aurora Beam, Bubble, Bubblebeam and Psychic have a 33.2% chance to lower the target's stat one level. My apologies about this.
I have tested each of these moves to be 100% sure, just in case.

Do I submit another pull request right away ?

**Comment by TheImmortal** [comment]
Go ahead.

**Pull request merged**
