### PR TITLE
Add Psycho Cut as Gallades signature attack

### PR DESCRIPTION
**Pull request by TheGoldenChampion**
Adding Psycho Cut as Gallade`s signature move

Flavor-wise it makes a lot of sense for Gallade to get Psycho Cut. It`s one of  It would also give him a more accurate, powerful alternative to zen headbutt. Gallade is near the middle of RU, which is fine, but Mega Gallade is at the bottom of OU. Mega Gallade has no benefits at all from what NEXT has so far, and takes up a mega slot, so of all OU pokemon he is the one most needing of something little to help him.

### CODE REVIEW

**Comment by Zarel** [comment]
You just added it to the Readme. You need to actually make it its signature move.

**Comment by Zarel** [comment]
Also we don't generally buff OU pokemon in NEXT.

**Comment by Zarel** [comment]
Also NEXT commits should start with "NEXT:"

**Comment by Zarel** [comment]
I would accept a small buff to Psycho Cut, but not making it Gallade's signature move.

**Comment by Zarel** [comment]
Maybe make it 100 bp?

**Comment by Zarel** [comment]
Basically: The other Pokemon who get Psycho Cut need it more than Gallade, so there's no reason to buff Gallade rather than Psycho Cut itself.

**Comment by ascriptmaster** [comment]
If we take Attack Order as the precedent, it should probably get 90 BP. We could also use Aeroblast/Spacial Rend as a precedent for 100 BP but I don't think we should use legendary signature moves as precedents.

Also, Mega Medicham with a 100 accurate 90 BP Psychic STAB is going to be fun

**Comment by Zarel** [comment]
Attack Order is 100 bp in NEXT...

Did not realize Mega Medicham was in OU, though. That actually does preclude buffing Psycho Cut itself.

**Pull request closed without merging**
