### PR TITLE
Battle Engine no longer sets EVs to 84 with blank EV sets

### PR DESCRIPTION
**Pull request by ascriptmaster**
This system is problematic for people who enter games without having
filled out their EVs, as their stats will not reflect the stats shown
in the teambuilder and can influence damage calculations, resulting in
many erroneous bug reports.

---

@Zarel since he was the one who mentioned that it needed to be changed.

### CODE REVIEW

**Comment by Slayer95** [comment]
If this were done in `Tools#unpackTeam` we could avoid the harm to the test suite.

**Comment by ascriptmaster** [comment]
I could do that as well. Having EVs fill in at 84 when not present seems counter-intuitive though...

**Comment by Zarel** [comment]
I much prefer this solution.

**Comment by Zarel** [comment]
Do random battles set it to 84-flat though?

**Comment by Zarel** [comment]
Make sure random battles are still at 84-flat.

**Comment by ascriptmaster** [comment]
Random Battles are not 84-flat, technically, because they're 85-flat :P

**Comment by Zarel** [comment]
Okay, good enough.

**Pull request merged**
