### PR TITLE
AAA: Let event Pokemon change their ability

### PR DESCRIPTION
**Pull request by MacChaeger**

### CODE REVIEW

**Comment by MacChaeger** [comment]
Don't be fooled by the comparison; all I did was add an if statement around the preexisting code and indent it, but GitHub didn't quite get that.

**Comment by TheImmortal** [comment]
@Zarel do you think this is the right way to implement this

**Comment by Zarel** [comment]
I'd prefer if we just passed a boolean "ignore abilities" instead of calling `getRuleTable` fifty times.

**Comment by MacChaeger** [comment]
What if we just store `ruleTable` as a global instance variable?

**Comment by Zarel** [comment]
It's not a global, it's associated with the format which is associated with the validator which is non-global; you can't make it global.

I guess you could make it a member. I wouldn't be opposed.

**Comment by MacChaeger** [comment]
So like define `this.ruleTable` in the constructor?

**Comment by Zarel** [comment]
Yeah.

**Comment by Zarel** [comment]
Maybe even define a method `this.hasRule`

**Comment by Zarel** [comment]
I still think "ignore abilities" should be a boolean to pass into `validateEvent`.

**Comment by MacChaeger** [comment]
I disagree. `validateEvent` is called by both `validateSet` and `validateSource` so you'd need to either pass that parameter to `validateSource` even though that function doesn't doesn't need that itself, or call `.hasRule` once in `validateSource` instead of calling it once in `validateEvent` which neither saves time nor simplifies the code. Better to just declare `this.ignoreIllegalAbilities` once in the constructor than to have to constantly pass a parameter around just so one function can use it once per call.

**Comment by Zarel** [comment]
I think it makes sense for individual callers to determine whether or not they care about illegal abilities.

**Comment by MacChaeger** [comment]
Individual callers don't get to choose. It's entirely dependent on the ruleset of the format which is stored as a `const` in the constructor. The value of the parameter would literally never change until you constructed a new validator for a different format altogether, so there's no reason to pass it as a parameter as if it could ever be different from call to call.

**Comment by Zarel** [comment]
...fair, I guess.

**Pull request merged**
