### PR TITLE
Modjoin: Clarify functionality in help command

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
"Global rank" is also not the full picture. "Rank in parent room" is also relevant.

**Comment by Zarel** [comment]
LIke a modjoin @ subroom is useful as a staff room for a parent room.

**Comment by panpawn** [comment]
How would you phrase it?

**Comment by Zarel** [comment]
`"Users lower than the specified rank can't join this room unless they have a room rank."`

**Comment by panpawn** [comment]
Updated

**Pull request merged**
