### PR TITLE
Alias /modlog with /ml

### PR DESCRIPTION
**Pull request by Aurolux**

### CODE REVIEW

**Comment by panpawn** [comment]
I've never thought that ``/modlog`` really needed an alias

**Comment by Aurolux** [comment]
Second commit adapted /modloghelp

I don't see why it can't have one, I mean all the punishments have aliases, but I totally understand if you guys don't want to push it.

**Comment by Zarel** [comment]
I could understand it being used enough to want the alias.

I don't _think_ there is or would ever be a need for any other command with that alias? Anyone else want to chime in?

**Comment by panpawn** [comment]
Closest thing is someone mistaking ``/wl`` (weeklock) with ``/ml``, but I don't think any current command would benefit (or even make sense) from the ``/ml`` alias besides modlog

**Comment by Aurolux** [comment]
w is on the opposite corner of the keyboard to m... It peobably won't happen, and modlog gets tiring to type if you're exploring some user, it becomes modlog this and modlog that /ml would just be so much nicer

**Comment by Zarel** [comment]
Looks good, thanks!

**Pull request merged**
