### PR TITLE
Make CAP LC CAPmons show as CAP LC

### PR DESCRIPTION
**Pull request by DeathlyPlays**
Also gave Voodoom it's new move Flash Cannon, which gave it much more viability

### CODE REVIEW

**Comment by HoeenCoder** [comment]
This would involve adding `CAP LC` as a tier on client too.

**Comment by DeathlyPlays** [comment]
Oh ok @HoeenCoder I can make a PR for it in tandem then

**Comment by Zarel** [comment]
You have to support CAP LC on the client, first.

**Comment by DeathlyPlays** [comment]
In tandem with ^

**Comment by Marty-D** [comment]
Uh, there are multiple problems here. Not all CAP prevos qualify for LC, and by changing their tier from "CAP" they're all going to be illegal in CAP formats. Did you even test this?

Also @Zarel can we stop merging nonessential things instantly? Give people who have more than general knowledge in the relevant area like, several hours of time to review, please.

**Pull request merged**
