### PR TITLE
Sleep should prevent Ice Ball and Rollout from locking

### PR DESCRIPTION
**Pull request by urkerab**
Reported [here](https://www.smogon.com/forums/posts/7757283), so I copied Outrage/Petal Dance/Thrash, although they might not be 100% correct either.

### CODE REVIEW

**Comment by Zarel** [comment]
What are ways to use moves while sleeping? e.g. `Sleep Talk`? How do they interact with Ice Ball and Rollout?

**Comment by Zarel** [comment]
@Marty-D

**Comment by Zarel** [comment]
How does Komala's fake-sleep interact with Thrash and friends?

**Comment by urkerab** [comment]
I've got confirmation that Ice Ball and Rollout don't lock if you're asleep at the time, but do lock if you get put to sleep, unlike Thrash and friends.

Komala's fake sleep doesn't count for either effect, so if you use Sleep Talk, you'll still get locked into any of the aforementioned moves.

**Comment by Marty-D** [comment]
Shouldn't this be somewhere other than in `onResidual`? It doesn't look like you changed anything between commits.

**Comment by urkerab** [comment]
That was my bad; `git commit --amend` doesn't warn you that you forgot to `git add`.

**Comment by Zarel** [comment]
Yeah, because renaming a commit is a common use-case of `git commit --amend`

**Comment by urkerab** [comment]
(I would probably have used `git commit --amend --no-edit` anyway, but that doesn't warn me either.)

**Pull request merged**
