### PR TITLE
Help Tickets: Allow ticket creators to close their own tickets

### PR DESCRIPTION
**Pull request by HoeenCoder**
Fresh from the policy table.

Also gives users tips on handling semilocks to reduce the number of those tickets we get.

### CODE REVIEW

**Comment by Zarel** [comment]
Help tickets should be a roomgame, roomgames should auto-warn that you can't leave them.

**Comment by AustinXII** [comment]
Aren’t battles basically room games? Is that a good idea

**Comment by Zarel** [comment]
@AustinXII yes? I'm not sure what your question is.

**Comment by AustinXII** [comment]
@Zarel “roomgames should auto-warn that you can't leave them.” why would we warn that you can’t leave a battle when you most definetly can. It was just your wording that through me off

**Comment by Zarel** [comment]
You can't, though? Like, try to leave a battle on PS right now. The only options are "Forfeit" and "Cancel". You can't leave a battle without forfeiting, except by outright disconnecting.

**Comment by HoeenCoder** [comment]
I'm pretty sure thats a client function from my research on the RoomGame class for mafia, and from my searching into that popup client side, I could probably work on making that a thing for RoomGame (assuming its not atm, havent had time to work on/research this again yet).

**Comment by AustinXII** [comment]
@Zarel you just outright said “can’t” which I wouldn’t consider is the same as “you can’t, unless you forfeit or close the battle” sorry yeah it was just your wording that through me off :P

**Comment by Zarel** [comment]
I consider those exceptions implicit. Like when we say "you can't switch out" for Shadow Tag, there's no need to add "unless you faint". Similarly, when we say "you can't leave a battle", there's no need to add "unless the battle is over" or "unless you close the tab".

**Comment by panpawn** [comment]
>Edit: Or maybe I could try implementing something server side with game.leaveRoom and connection.popup.

This would require some kind of client work regardless, since standard popups have an "OK" button to close them (even if their modal).

**Comment by HoeenCoder** [comment]
Forfeit popups handled in https://github.com/Zarel/Pokemon-Showdown-Client/pull/1110

**Pull request merged**
