### PR TITLE
Weight Refactor: Do not modify weight in ModifyPokemon

### PR DESCRIPTION
**Pull request by ascriptmaster**
Added a new event, `ModifyWeight`, to deal with weight changes from items,
abilities, and moves. Add a function `getWeight` to call the event and
return a Pokemon's current weight.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Once again, calling @Marty-D to verify that all the weight-based mechanics are here.

I forgot to put regression tests for Sky Drop's weight calc, but oh well

**Comment by Marty-D** [comment]
Looks like everything is here! The only thing I would recommend is to also check that Transform copies the right weight. Come to think of it, I wonder if it even does that correctly before this change.

**Comment by ascriptmaster** [comment]
It should, I think... because `BattlePokemon#transformInto` calls `BattlePokemon#formeChange`, which in turn overwrites `pokemon.template` with the new template, and that should have the proper weight. The old code did the rest by updating `pokemon.weightkg` with the template's weight at every update before calling `ModifyPokemon`, while this `getWeight` simply goes off the `pokemon.template.weightkg`.

But thanks for mentioning this, since Autotomize is still using `pokemon.weightkg`, which by all means should be deprecated now, and should be checking against `pokemon.template.weightkg`. So I'll have to fix that anyways.

**Comment by ascriptmaster** [comment]
Huh. Why is Heavy Metal giving these sorts of off-by-one errors? And I don't even know what the actual damage is because node's assert module doesn't give me access to a `lessThan`...

**Comment by ascriptmaster** [comment]
Don't push right now. I suspect that the new RNG is doing something that I don't understand, and since it'll be a pain to merge everything into here I'm going to force Travis to run the build again and grab data from `console.log`.

**Comment by ascriptmaster** [comment]
Is gamut-was-taken's damage calc slightly off? The damages being rolled are currently 1 less than the reported ranges.

And to think that it was working just fine yesterday...

**Comment by DanUgore** [comment]
Can always calculate them by hand

**Comment by DanUgore** [comment]
@ascriptmaster Why are you setting the seed for your weight tests?

**Comment by ascriptmaster** [comment]
I'm setting the seed to prevent critical hits from messing up the damage calc... but apparently it's wrong anyways!

What I'll probably do later to prevent messiness with damage calcs is hook the `runEvent` function and snag the base power provided by Grass Knot's `basePowerCallback`.

**Comment by ascriptmaster** [comment]
I fixed the tests to now catch the `BasePower` event by overriding `Battle#runEvent`.

I also fixed up the abilities/items to no longer use `chainModify`, since that actually forces the weight to an integer, which is bad.

**Comment by Zarel** [comment]
> node's assert module doesn't give me access to a `lessThan`...

can't you just assert `varName < 20, true` or something?

**Comment by Zarel** [comment]
Also, is this ready for merge?

**Comment by ascriptmaster** [comment]
> can't you just assert `varName < 20, true` or something?

Yes, and that's what I was doing, but "Assertion Error: false !== true" is always *so incredibly informative*

Zarel, if you're willing to take the extremely small risk of the weight calc not working with Transform, even though the Transform code indicates that it should work properly, then yes, it's ready for merge.

**Comment by Zarel** [comment]
Why not test with Transform?

**Comment by ascriptmaster** [comment]
Because I trust the code. Transform calls `transformInto` which calls `formeChange` which overwrite's a Pokemon's `template`. And all the weight calcs now use `pokemon.template.weightkg` instead of `pokemon.weightkg`, which was reset to `pokemon.template.weightkg` on every `ModifyMove` cycle anyways.

Basically, if it worked before this refactor, basically, it'll work after the refactor. And yet, no matter now sure I am of the code, I still can't trust myself enough to simply say "it's ready to merge no questions asked".

**Comment by Zarel** [comment]
...you could just test.

**Comment by ascriptmaster** [comment]
I can't right now, and I guess I should've said that instead of dancing around the issue.

Tomorrow, then.

**Comment by Zarel** [comment]
Sounds good.

**Comment by ascriptmaster** [comment]
My tests say that it works properly with Transform. I'd commit them here but there are some errors in Gen 4's Transform code that need fixing first.

**Comment by Zarel** [comment]
...should I merge now or wait for your Gen 4 fixes?

**Comment by ascriptmaster** [comment]
Merge now. Gen 4 Transform is a separate issue anyways and deserves its own pullreq.

**Comment by ascriptmaster** [comment]
Transform fixes are sent in #1656.

**Pull request merged**
