### PR TITLE
Fix disabling mafia

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm confused why this is necessary?

**Comment by whalemer** [comment]
Deleting it removes it from the object, stopping it from getting saved.

**Comment by Zarel** [comment]
Isn't that the point? To stop it from getting saved?

**Comment by whalemer** [comment]
Mafia defaults to enabled, the property needs to be explicitly falsey to disable it, and it needs to be ``false`` to be saved.

**Comment by Zarel** [comment]
Oh, that makes sense.

**Comment by Zarel** [comment]
We should probably not have settings that work like that. I'd rather call it `mafiaDisabled` or something.

**Comment by whalemer** [comment]
I thought about that but avoided it because it'd break backwards compatibility.

Though since disabling doesn't work, it's not like that'd change anything...

**Pull request merged**
