### PR TITLE
Make !roomhelp compact

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by panpawn** [comment]
Don't make more than one PR for the same thing and close/open new ones over and over...

**Comment by Lord-Haji** [comment]
that thing was closed idiot @panpawn

**Comment by Lord-Haji** [comment]
#2482

**Comment by panpawn** [comment]
That wasn't closed the time I wrote that, and it isn't currently, either...

**Comment by Zarel** [comment]
@Lord-Haji, please refrain from calling people "idiot"...

**Pull request closed without merging**
