### PR TITLE
Add privacy policy command

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
I have no clue what this has over ``<<privacy>>``

**Comment by AustinXII** [comment]
Nothing besides documentation from the looks of it

**Comment by Zarel** [comment]
Like, maybe show a tl;dr like

> We log PMs for reporting reasons - staff can't look at them without permission unless there's a law enforcement reason.

> We log IPs to enforce bans and mutes.

> We use cookies to save your login info and teams.

> We use Google Analytics and AdSense.

**Comment by panpawn** [comment]
Updated

**Pull request merged**
