### PR TITLE
[APRIL FOOLS] I'm tired of your BS

### PR DESCRIPTION
**Pull request by mathfreak231**
Happy april fools!

EDIT: I was not expecting this to become a serious-ish discussion

### CODE REVIEW

**Comment by xfix** [comment]
Merging in...

**Comment by xfix** [comment]
Oops, pressed a wrong button. I have no idea how to use computers.

**Comment by xfix** [comment]
There is some reopen button, but I think I should contact @Zarel before pressing it, after all he insisted for Air Balloon to stay.

**Comment by Zarel** [comment]
I have always insisted that Air Balloon should be removed... I don't know why it's stayed all these years.

**Comment by Zarel** [comment]
Like, not even kidding, every time this has come up I've said it should be replaced with Ring Target.

**Comment by AustinXII** [comment]
It stayed because everyone else thought you wanted it 🤷🏻‍♂️ Lol

**Comment by Zarel** [comment]
But _every time_ it's _ever_ been brought up, I _always_ say it should be replaced. _Never once_ have I said it should be kept, since, like, six years ago.

Does no one ever look at chat logs in which I actually say things?

**Comment by xfix** [comment]
So... should this be just merged?

**Comment by HoeenCoder** [comment]
Im 90% sure last time i asked you, you insisted it stay in lmao

**Comment by Zarel** [comment]
Can you provide chat logs?

**Comment by HoeenCoder** [comment]
Naw, I don't remember exactly when or where it happened and I don't want to search the entire log viewer since its not a huge issue anyways :)

**Pull request closed without merging**
