### PR TITLE
Random Battle: Add Decidium-Z

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
I'm also considering adding Incinium-Z, but unlike Decidium, it isn't used as much (15% vs 38%). Instead, Incineroars are known to carry Assault Vest instead (50% usage) so maybe adding that particular Z-Crystal isn't a super-great idea.

Actually, does Incineroar even load with Assault Vest in the current script, or does it end up with a Choice Band? If it's Choice Band, it might be worth adding Incinium-Z.

**Comment by TheImmortal** [comment]
Could we have it only with setup? I feel it's a waste otherwise.

Can get AV: ``{name: "Incineroar", species: "Incineroar", gender: "", moves: ["uturn", "knockoff", "flareblitz", "fakeout"], ability: "Intimidate", evs: {hp: 85, atk: 85, def: 85, spa: 85, spd: 85, spe: 85}, ivs: {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31}, item: "Assault Vest", level: 81, shiny: false}``

**Comment by TheImmortal** [comment]
And if we do that, we can make it 100% since that's pretty much the Smogon set.

**Comment by ascriptmaster** [comment]
I'm completely fine with only having it with setup. I think Incineroar gets band if it doesn't get fake out, but I'll skip deciding on it until later

**Pull request merged**
