### PR TITLE
Revert "Remove explicit decimal radix from parseInt"

### PR DESCRIPTION
**Pull request by Slayer95**
Reverts Zarel/Pokemon-Showdown#2359

### CODE REVIEW

**Comment by Zarel** [comment]
Why is this being reverted?

**Comment by Zarel** [comment]
@Slayer95, can you give a better explanation than "wtf no"?

**Comment by Zarel** [comment]
I actually personally asked Bumba to make that commit for me; it makes the code more readable and behaves sanely in ES5+, which includes every version of Node and iojs we support.

**Comment by Zarel** [comment]
You could at least come into the Dev room to talk about it first. :|

**Comment by Slayer95** [comment]
They are not the same... Supporting non-decimal bases is not "sane" except in few cases.
And the "as-needed" label is a terrible misnomer.

**Comment by Zarel** [comment]
You realize that `parseInt("050") === 50` in ES5+, right?

**Comment by Slayer95** [comment]
Yes. But ``0x10`` is ``16``, not ``0``.
``parseInt`` should take user input, as base 10 unless there are reasons not to.
If we are just "casting" a string to a (base 10) numeral due to IPC protocol or something, it would be better to use ``Number()``.

**Comment by bumbadadabum** [comment]
Wait, do you mean that 0x10 SHOULD be 0? Why is it a problem to have !dt 0x100 work?

**Comment by Slayer95** [comment]
Because the commands are intended for users, not for programmers?

**Comment by Zarel** [comment]
If you realized that, I no longer understand why you thought this reversion was so urgent as to overrule my decision without even asking me. :|

I'm fine with allowing `0x10` as user input to mean `16`. Some users are also programmers/mathematicians, and unlike `010`, a user isn't going to "accidentally" type in `0x10` thinking it means something else.

**Comment by Slayer95** [comment]
Neither programmers nor mathematicians are going to do that though, unless they do it to annoy others with broadcasts. Allowing hex would be acceptable, on the other hand, for commands accepting raw modifiers. Say ``'0x14CD`` in some calculator...

**Comment by Zarel** [comment]
Anyway, I'd consider `parseInt` more readable than `Number` because it implies that the input is a string, and guarantees that the output is an integer, both of which are pretty important to how we use it.

**Comment by Zarel** [comment]
Unless you want to argue that this is a security vulnerability of some sort, I'm reimplementing this (or, more specifically, reverting your reversion).

**Comment by Slayer95** [comment]
I want to, but the code I suspected vulnerable was already using ``Number`` lol <_<.

``parseInt`` doesn't guarantee that the output is an integer though.

```
// Number.isInteger(parseInt('9'.repeat(1000)))
// false
```

Which is one of the reasons why I often suggest checking that input is a safe integer...

Really, though, I hastily reverted it due to the octal issue, which I later found to be no longer an issue. I apologize for that; but oh well... Better safe and sorry.

**Comment by Zarel** [comment]
Well, not being `Infinity` isn't a guarantee `Number` offers, anyway.

**Pull request merged**
