### PR TITLE
Trivia: make searching results scroll

### PR DESCRIPTION
**Pull request by CheeseMuffin**

### CODE REVIEW

**Comment by Zarel** [comment]
Why?

**Comment by CheeseMuffin** [comment]
The results that come up can have thousand of results, so this makes it easier to navigate so it doesn't flood your screen. While normally queries don't have that many results, it still just makes it easier to navigate.

**Comment by Zarel** [comment]
Morfent, please don't merge things like this without my permission.

**Comment by Zarel** [comment]
Morfent, I've been *consistently* against having scrollboxes for anything other than roomintros. I don't think you were _intending_ to overrule me, but really be careful about stuff like this.

**Comment by CheeseMuffin** [comment]
should I change the other trivia stuff to not use scrollboxes then?

**Comment by AustinXII** [comment]
To Morfents defence you do usually leave trivia PRs to him although he was premature since you didn’t reply to cheeses answer

**Comment by Zarel** [comment]
The basic rule is: if it broadcasts, it should scroll, if you use the command on yourself, it shouldn't.

**Comment by CheeseMuffin** [comment]
ah ok, my bad sorry

**Comment by Slayer95** [comment]
To be clear about "things like this", CSS is Zarel's exclusive territory.

**Pull request merged**
