### PR TITLE
Random Battle: Update Zygarde

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by TheImmortal** [comment]
I put Iron Tail to hit Fairy. Stone Edge is pretty bad because it has Thousand Arrows now.

**Comment by TheImmortal** [comment]
Also, Hikari didn't like the set because it had no setup and wasn't CB, not because it had Iron Tail over Stone Edge.

**Comment by ascriptmaster** [comment]
Well in that case Hikari just needs to suck it up and live with it. I'm still worried about Iron Tail's viability since the only things that Thousand Arrows+Outrage doesn't hit are Rimbombee and Tapu Bulu.

I can take out Stone Edge, though. And do you agree about Zygarde-50 getting Thousand Arrows?

**Comment by TheImmortal** [comment]
Sure. You can replace Stone Edge with Iron Tail there too.

**Comment by ascriptmaster** [comment]
Banded Espeed is still solid on Zyg10. I really don't know if Iron Tail is good for it for the reasons I mentioned (Thousand Arrows > all) plus that low accuracy, but Zygarde doesn't really have a solid fourth move for Band sets, so it's a toss-up between Stone Edge and Iron Tail anyways.

What about Iron Tail Zyg50?

**Comment by TheImmortal** [comment]
Yes, replace Stone Edge with Iron Tail on 50. I wanted some difference in the sets so I suggested removing ES. I guess Sub will have to be the only difference.

**Comment by ascriptmaster** [comment]
If you really want them to be different we can always swap 10's Iron Tail for Stone Edge anyways. Thousand Arrows is just plain better to use when Banded compared to Iron Tail even if you're in on a Fairy anyways.

Sub Zygarde is ridiculous if you have Power Construct tbh

**Comment by Zarel** [comment]
Thousand Arrows gives Zygarde impressive neutral coverage, but Stone Edge is still useful for hitting Bug types, which are more common in Randbat than usual.

**Pull request merged**
