### PR TITLE
Random Battle: Update Comfey

### PR DESCRIPTION
**Pull request by MacChaeger**

### CODE REVIEW

**Comment by TheImmortal** [comment]
I don't see this change as good. It's too weak for Calm Mind and CM + Draining Kiss sounds pretty lackluster. Also, Toxic works well in my experience.

**Comment by MacChaeger** [comment]
This is the standard set on the RU ladder, according to the RU room. Frankly, it should have Taunt, too, and not U-turn, but as long as it's getting Natural Cure, I figured Taunt wasn't a good fit for an RU mon in randbats. It is pretty fast, though...

**Comment by MacChaeger** [comment]
I was clearing out old branches and accidentally deleted this one, whoops.

**Comment by TheImmortal** [comment]
Either way, I'm not convinced of any change here. Tagging @ascriptmaster for his opinion.

**Comment by MacChaeger** [comment]
Even if you disagree with the moveset changes, the changes to scripts.js is
necessary, because without it, Draining Kiss will always be rejected on any
Comfey set.

**Comment by ascriptmaster** [comment]
Please make the scripts.js change. Scrap the rest.

**Comment by TheImmortal** [comment]
Did the scripts change in 618456f

**Pull request closed without merging**
