### PR TITLE
Add a chat plugin for hangman

### PR DESCRIPTION
**Pull request by bumbadadabum**

### CODE REVIEW

**Comment by panpawn** [comment]
I feel like ``room.game`` is ambiguous for this... especially if more games get implemented later that use room variables...

I think something like ``room.hangman`` would be better, imo

**Comment by bumbadadabum** [comment]
The name is ambiguous on purpose, since the plan is actually to include
different games as well, that won't be able to run concurrently, therefore
using the same variable to indicate it would be nice, as this simplifies
checks for "is there any kind of game going on right now".

**Comment by Slayer95** [comment]
See for reference the discussion in #1826, @panpawn

**Comment by panpawn** [comment]
Thanks

**Comment by panpawn** [comment]
A command to change the max number of mistakes might be a nice addition to this script, considering some hangmans are harder than others to guess

**Comment by bumbadadabum** [comment]
I don't see that as much of a priority to be honest.

**Comment by Zarel** [comment]
This works for now, but you should adapt it to my Game system when I release it.

**Comment by bumbadadabum** [comment]
I will definitely. (Didn't I mention that to you before?)

**Pull request merged**
