### PR TITLE
Some New Aliases

### PR DESCRIPTION
**Pull request by HiTechFlufi**
Added some more ability/Pokemon/item aliases.

### CODE REVIEW

**Comment by AustinXII** [comment]
A lot of these are.....bad

**Comment by Zarel** [comment]
Can anyone tell me which of these are sufficiently commonly-used?

**Comment by AustinXII** [comment]
Bdrill and Karp are fine imo

**Comment by LegoFigure11** [comment]
In addition to above, I've heard megasnow used for Mega Abomasnow maybe once and WP used for Weakness Policy quite frequently.
Things like hpower though could get confusing (as hidden power is commonly referred to as hpower, as hp can get confused with the HP Stat of the pokemon) and pp is used for the amount of times that a Pokemon can use a move, rather than as a shortening of Pure Power.

**Comment by AustinXII** [comment]
I'd be fine with megasnow and probably wp unless it causes confusion with other things

**Comment by Zarel** [comment]
maybe we should bring client's fuzzy search to server, so we don't have to manually generate some of these aliases...

**Comment by AustinXII** [comment]
@Zarel that seems much better

**Pull request merged**
