### PR TITLE
Fix crash in `/modlog public`

### PR DESCRIPTION
**Pull request by asgdf**
Since we're using a child process now, Rooms was no longer defined there.

### CODE REVIEW

**Comment by Hidden50** [comment]
@Zarel can this be merged quickly? /modlog currently isn't working at all, since the child process is crashed.

**Comment by Zarel** [comment]
I don't like the idea of loading Rooms in a child process. It's not designed for that.

**Comment by asgdf** [comment]
Hmm, but it's required for /modlog public. I guess another option would be replacing `public` with a list of actual room names *before* passing it to the child process,

**Comment by panpawn** [comment]
That's probably a good solution

**Comment by asgdf** [comment]
Okay, I changed it so `public` is resolved in the main process, so there's no need to load rooms data in the child. 
If we ever want to support checking multiple rooms at once in one modlog command, we're already halfway there because it's already treating it as a list instead of a single roomid now, so that's good.

**Pull request merged**
