### PR TITLE
Refactor to use .hasOwnProperty in favor of in

### PR DESCRIPTION
**Pull request by panpawn**
#Zarel: hasOwnProperty is allowed now
#Zarel: since it's useful for a lot of the non-null-prototype objects we have to deal with
#Zarel: i.e. basically all of data/
#Zarel: in fact we should probably stop using in entirely
#Zarel: it should all be either hasOwnProperty or refactored to Map

### CODE REVIEW

**Comment by panpawn** [comment]
>@MORFENT ⊙¿⊙: objects with no prototype can't use hasOwnProperty

So, I'm not sure on if this would be okay or not, with that in mind...

**Comment by Zarel** [comment]
Emphasis on:

#Zarel: it should all be either hasOwnProperty or refactored to Map

As in, null-prototype Objects can't use `.hasOwnProperty` and should be refactored to `Map` instead.

In context, you can leave alone null-prototype Objects for now. Just refactor the `{}` objects.

**Comment by panpawn** [comment]
I'll update this shortly

**Comment by Zarel** [comment]
Specifically this refactor should be mostly touching Tools

**Comment by kotarou3** [comment]
You could also do `for (const key of Object.keys(object))`

**Comment by Zarel** [comment]
@kotarou3, this is about `in`, not `for...in`. `for...in` already doesn't iterate uniterable keys, but `in` still returns `true` for them.

**Comment by panpawn** [comment]
I think a refactor before this should be that objects shouldn't have a null prototype.

With that in mind, I'm going to be closing this for now.

**Comment by Zarel** [comment]
No, most dictionary-objects _should_ have a null prototype.

`hasOwnProperty` is for the ones that can't; namely the ones in `config.js` and in `data/`

**Pull request closed without merging**
