### PR TITLE
Fix grammatical and punctual flaws in users.js

### PR DESCRIPTION
**Pull request by KrisOnline**
There were some things that I tested for that appear as improper in the code, such as checking if more than one person is trying to get onto an account only having an open quotation, but when I tested them those flaws were gone (there was a closing quotation in practice).

### CODE REVIEW

**Comment by Zarel** [comment]
None of these are actual grammatical issues, just alternate style. Ironically, your commit description has a grammar issue: it's "punctuation" (symbols like `.` and `,`), not "punctual" (on time).

**Comment by KrisOnline** [comment]
Lol, that was a mistake on my part. However, while I do know that there are different uses of commas, the way they're used in the instances that I changed were incorrect. In the first comma change, that's not a properly constructed sentence, as the second part is not an independent clause, which means that either the comma should be removed, or the "was" needs to be changed to "they were".

The second change has an excessive comma (the first one that I removed), and the second comma should only exist if the list has "either" (which I added) before it, as well as a noun/pronoun (which I also added) after the FANBOYS to have two independent clauses. If there was not a noun/pronoun after the FANBOYS, the second comma would need to be removed as well.

**Comment by Zarel** [comment]
After further research, you're right about the comma in front of `, and was automatically demoted`.

The comma in the lock note is intentional, though. "Using a proxy" and "in a country where other people commonly hack" are two different situations one might be locked.

Although we stopped using DNSBLs by default, so "in a country where other people commonly hack" is no longer a likely lock reason. We still sometimes semilock ISPs that have near-country-wide monopolies to deal with spam, though, so it might as well stay.

**Comment by Zarel** [comment]
Actually, I still think the comma should remain on `, and was automatically demoted`.

Wikipedia says:

> In the following sentences, where the second half of the sentence is not an independent clause (because it does not contain an explicit subject), those guides prescribe that the comma be omitted: ...

> The above guidance is not universally accepted or applied. Long coordinating clauses are nonetheless usually separated by commas: ...

English grammar doesn't have too many hard-and-fast rules; it's mostly about readability. I think leaving the comma in makes it more readable and emphasizes that two things happened.

**Pull request closed without merging**
