### PR TITLE
Update devDependencies to the latest build

### PR DESCRIPTION
**Pull request by Irraquated**

### CODE REVIEW

**Comment by Zarel** [comment]
Have you tested this and confirmed there are no errors?

**Comment by Zarel** [comment]
@Slayer95, I think you usually do this

**Comment by Irraquated** [comment]
Have tested, and can confirm that there are no errors.

**Comment by Slayer95** [comment]
lgtm, but could you update ``es6-shim`` as well since we are updating deps just because?

**Comment by Slayer95** [comment]
Should be merged when ``npm update`` is run.

**Pull request merged**
