### PR TITLE
add gen 7 1v1

### PR DESCRIPTION
**Pull request by InactiveUser**
http://www.smogon.com/forums/threads/1v1.3587523/

This will add the gen 7 1v1 format, if it's not needed please let me know.

### CODE REVIEW

**Comment by TheImmortal** [comment]
OMs will be switched to gen 7 once gen 7 is stable enough.

**Comment by swagmoneygod** [comment]
i don't want these emails and i don't want to be subscribed anymore

**Comment by panpawn** [comment]
Then feel free to unsubscribe...?

**Comment by Zarel** [comment]
@swagmoneygod, click the "Unsubscribe" button; we can't do it for you.

**Pull request closed without merging**
