### PR TITLE
/mnm: Remove redundant parts of warning messages

### PR DESCRIPTION
**Pull request by KrisOnline**
I'm purposely not accounting for regular Greninja, as it has more than one ability in its base forme.

I also removed unnecessary information from warning messages, as it just elongated them for no reason.

### CODE REVIEW

**Comment by MacChaeger** [comment]
@Marty-D didn't you say this behavior isn't intentional?

**Comment by KrisOnline** [comment]
[19:42:50] ~Marty: by the way urkerab, that Mix and Mega behaviour isn't intentional
[19:43:56] ~Marty: the only effects that can overwrite those Abilities are Transform, Mega Evolution, Primal Reversion, Ultra Burst, and Shaymin Sky reverting to Land

now im confused

**Comment by KrisOnline** [comment]
if the above is the case, i'll just remove the stuff i added and just remove the unnecessary error lengths

**Comment by Marty-D** [comment]
Yeah something like what I did with Transform in `setAbility` needs to be done to the rest of those. I didn't bother even thinking about it back when I added the exception years ago since nothing with a forme-changing Ability can Mega Evolve, until Mix and Mega happened.

**Comment by Zarel** [comment]
@Marty-D? @TheImmortal?

**Comment by KrisOnline** [comment]
i still havent gotten to doing what marty asked; ill do it in a bit.

**Comment by Marty-D** [comment]
@MacChaeger dealt with it already in https://github.com/Zarel/Pokemon-Showdown/commit/8d571be74eec0258ccbb68fb1ce5c9406024db18, so feel free to make the other changes you described here.

**Comment by KrisOnline** [comment]
done @Marty-D , i never realized thats what macchaeger's pr did

**Pull request merged**
