### PR TITLE
Launch Script: install optional dependencies if configured for use

### PR DESCRIPTION
**Pull request by Morfent**

### CODE REVIEW

**Comment by Morfent** [comment]
crashlogger.js will still log crashes if it's not installed in case people still launch PS through `node app.js` or if for whatever reason someone decides to uninstall nodemailer while the server's running

**Comment by Morfent** [comment]
Don't merge yet; I want to abstract this to be able to handle ensuring all dependencies that PS is configured to use are installed

**Comment by Morfent** [comment]
Done

**Comment by Zarel** [comment]
Honestly, this is a pretty bad hack and doesn't account for editing `config` while PS is running...

**Comment by Zarel** [comment]
And `npm` is now actively removing the things we install because they're not mentioned in `package.json` etc. I think we might have to straight-up give up on our `nonDefaultDependencies` hack.

**Comment by Morfent** [comment]
>Honestly, this is a pretty bad hack and doesn't account for editing config while PS is running...
Fair. I didn't take into account disabling Config settings and making the server crash.

Config deciding when dependencies should be installed seems redundant when npm is supposed to be handling that. What would a better way to deal with nonDefaultDependencies be? devDependencies could work, since they're not essential for making the server run, but ofe might cause some issues since it using node-gyp makes it dependent on what dev tools are installed

**Comment by Zarel** [comment]
I'd say `optionalDependencies`, and then make the initial install `no-optional`.

**Comment by Morfent** [comment]
``optionalDependencies`` won't work for this. I tested ``npm install --no-optional`` after pulling your latest commits, but the optional dependencies still install. [npm](https://docs.npmjs.com/cli/install)'s docs don't seem to allow the flag when you're installing your own package, just with others'.

**Comment by Zarel** [comment]
Oh well, we're just installing optionals normally now. :[

**Pull request closed without merging**
