### PR TITLE
Update priority of switches when a player has no actives

### PR DESCRIPTION
**Pull request by ascriptmaster**
Switches and runSwitch were recently updated to priority 7 and 7.1, so
this part needs to be updated as well.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Actually what we might want to do is `decision.priority += 0.2` to prevent issues with this ever again

**Comment by Zarel** [comment]
What happened to a97d9f6a22065?

**Comment by ascriptmaster** [comment]
In situations with double-KO, it gets overwritten anyways by the line I'm changing :\

**Comment by Zarel** [comment]
Is there any negative consequence to just removing those two lines entirely?

**Comment by Zarel** [comment]
Perhaps we should have two events: `switch` and `instaswitch`, where `instaswitch` is the one that happens to replace fainted pokemon.

**Comment by ascriptmaster** [comment]
Git blame showed that those four lines are from https://github.com/Zarel/Pokemon-Showdown/commit/99aba198c96d35edb6442d0e80f37d9bfc172937 in 2012.

The other change (that half doesn't work), which sets priority to 101, was https://github.com/Zarel/Pokemon-Showdown/commit/a97d9f6a22065ee5e37d452ae098e559074d6272 in 2014.

Since they both aim to solve the same thing we can probably remove those four lines. Removing them didn't fail any unit tests when I ran it locally.

**Comment by Zarel** [comment]
I would like to replace both of them by having `instaswitch` as a separate event from `switch`.

**Comment by ascriptmaster** [comment]
Which is which? `instaswitch` for double-KO scenarios or the other one?

**Comment by Zarel** [comment]
For double-KOs.

**Comment by ascriptmaster** [comment]
My hands are typing things

The `instaswitch` solution seems a little inelegant, oh well

**Comment by Zarel** [comment]
bleh, this got clobbered by my Leppa changes, you'll need to redo this tomorrow :/

**Comment by ascriptmaster** [comment]
what do you mean?

**Comment by Zarel** [comment]
nvm, I made a mistake but I realized it was an uncommitted mistake so no one needs to know

**Pull request merged**
