### PR TITLE
Tournaments: Be less case sensitive

### PR DESCRIPTION
**Pull request by MacChaeger**
I've seen people having problems with this lately.

### CODE REVIEW

**Comment by Zarel** [comment]
This is the wrong place for this code?

**Comment by Zarel** [comment]
Like, this only affects display, not actual recognition.

**Comment by MacChaeger** [comment]
Oh! You're right. I really should learn not to do this at 3:00 AM.

**Comment by MacChaeger** [comment]
...Okay, maybe I'm still too tired to understand. Why doesn't this work?

**Comment by Zarel** [comment]
This makes a rule that's capitalized incorrectly display as a rule.

It doesn't make a rule that's capitalized incorrectly actually work.

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/8a4415f59f9c1bf7ef6c48b9b2838254713bee74/sim/dex.js#L489

is the line you need to change to be case-insensitive.

**Comment by MacChaeger** [comment]
I really wish the github search function would work better :/

**Comment by Zarel** [comment]
now normalize it somewhere, so you only need to do the case-insensitive check once. :p

**Comment by MacChaeger** [comment]
Well, it functions properly with just one, but the other one is needed so that everything looks right in the chat, isn't it?

**Comment by MacChaeger** [comment]
Oh my god I didn't even read that right. What is wrong with me?

**Comment by sirDonovan** [comment]
Fixed in 0c94145c4074e6df55521aecd29c45d65c4598ff.

**Pull request closed without merging**
