### PR TITLE
Use strict mode and let and const instead of var

### PR DESCRIPTION
**Pull request by Joimer**
This commit also fixes some duplicated variable declarations.
It also removes the slow let hack for jshint.

Tested with iojs 2.3.3, node 4.1.0 and node 5.0.0.

It's about time we start running on strict mode, using let and const instead of var, declaring variables outside of switches, and overall moving to a better syntax.

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Are you guys looking forward to convert your code to ES6?
I may be able to help you if you need this.

**Comment by Joimer** [comment]
That's the idea long term, yeah. For now we need to run with iojs 2.3.3, but people are encouraged to use that or current node versions in their servers.

Also travis is using node 0.12.7

**Comment by lucasfcosta** [comment]
@Joimer Ah, seems good.
I may start doing some changes this weekend then.
Thanks for the clarification, I was eager to contribute on the project.

**Comment by Slayer95** [comment]
"Converting" to ES6 may be a bit too big.
There are certain features we'd rather stay away from (such as modules -not that they are supported by Node.js), and should be evaluated in a case-by-case basis.

**Comment by lucasfcosta** [comment]
@Joimer you may want to rebase on this #2253 so your build won't get broken.

@Slayer95 I understand your concern, I think we should first start cleaning some code with the new syntax's help. We can start doing some minor things such as using the new arrow functions and template strings and things like that. I'll make sure to keep my changes on very separate PR's so you guys can take a look and evaluate it in an easy way.

**Comment by Zarel** [comment]
Unsurprisingly, basically any commit would cause conflicts with this. Let's get this merged before we do anything else.

**Comment by Slayer95** [comment]
This is hurting readibility in some cases... See e.g.
https://github.com/Joimer/Pokemon-Showdown/blob/use-let/data/scripts.js#L1178-L1182
https://github.com/Joimer/Pokemon-Showdown/blob/use-let/battle-engine.js#L3884-L3890

**Comment by Slayer95** [comment]
Let's follow this in #2255 to get this done fast.

**Pull request closed without merging**
