### PR TITLE
Disallow people from seeing private room auth

### PR DESCRIPTION
**Pull request by AustinXII**
this is helpful for keeping the private rooms that don't have modjoin on private.

### CODE REVIEW

**Comment by panpawn** [comment]
If they don't have modjoin on, then what's to stop people from just joining the room as is and finding out about it that way?

**Comment by AustinXII** [comment]
@panpawn this is helpful for the staffroom

**Comment by Zarel** [comment]
How does the staffroom block joining, then? The same thing should be done here.

**Comment by xfix** [comment]
@Zarel: It checks if `room.staffRoom && !user.isStaff`` is true.

**Comment by xfix** [comment]
It checks ``targetRoom.staffRoom && !user.isStaff``. User is a staff if he has a global status or is roomauth in a room with ID `staff`.

**Comment by Zarel** [comment]
Easy enough to do the same thing here, then.

**Comment by Zarel** [comment]
> User is a staff if he has a global status or is roomauth in a room with ID `staff`.

This sounds a bit hardcoded and should be looked into at some point probably.

**Comment by Zarel** [comment]
Done in c027fe6e4520b9deb661.

**Pull request closed without merging**
