### PR TITLE
Bold room notifications on room/global promotions

### PR DESCRIPTION
**Pull request by panpawn**
[16:27:41] ~The Immortal: what if promotion messages were bold?? right now they don't stand out at all but promotions are pretty important.

### CODE REVIEW

**Comment by Zarel** [comment]
ummmm

I personally don't like this idea... I don't think they need to stand out that much, and some people don't like standing out, anyway.

**Comment by panpawn** [comment]
@TheImmortal

**Comment by TheImmortal** [comment]
I think it should stand out because it's a big thing. Tournaments and winners are bolded, for example. Someone being promoted is much more important and long-lasting than a tournament. I've seen it first hand that this message is easy to miss. And then like 5 minutes later someone notices the symbol change and say "oh grats". You can't hide a promotion, people notice the symbol change and/or the position on user list change. This message not standing out means it doesn't fulfill its purpose of announcing said promo.

**Comment by Zarel** [comment]
Its purpose isn't announcing the promo, it's just to log it. I think it fulfills that purpose fine.

**Comment by CrestfallPS** [comment]
Global promotions however are much more "significant" @Zarel. If my opinion matters here (just as a user not staff) I think it'd be nice for global promotions (usually only Voice and Driver are done in public rooms anyways) and those are obviously goals or achievements for many people. Seems fair to give them a one announce-esque message of congratulations that really stands out more. 

And if it's purpose is simply to log it then that could be done privately - it however, is not. Obviously there was some sort of public information decision at a point and this is no different.

**Comment by Zarel** [comment]
Yes, it's public information, but that's distinct from a public announcement. It's intended to be there for the people who care, but it's not intended to be all in-your-face about it.

**Comment by panpawn** [comment]
I feel pretty neutral on this topic, but I also don't see little to any harm in making it stand out in the room.

**Comment by Zarel** [comment]
The emphasis treadmill will make everything bold and shouty, which is clearly bad. What we need is some sort of criteria for what sort of things we think should be emphasized and why.

I think if a promotion is a big deal, the mod who promoted the user can easily just say **everyone congratulate $NEWLY_PROMOTED_USER**, if they think it should be a big deal. But personally, I've never thought promotions should be a big deal.

**Comment by Zarel** [comment]
I am going to close this soon, because so far I haven't been convinced.

**Comment by xfix** [comment]
I would be fine with bold promotions only in Staff room myself (if it's important enough to be marked here, probably only global promotions and room owner promotions would meet the threshold if even those). There should be no reason to bold promotions in public room, and from a point of view of an user, those aren't all that important.

And besides, a staff member can tell chat to congratulate an user in a more personal way than a random message generated by server itself.

**Pull request closed without merging**
