### PR TITLE
Stadium: Add Move Descriptions

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Marty-D** [comment]
These moves should all be in the Gen 1 mod since they had the same behaviour then. What does "33% rounded down" even mean?

**Comment by DeathlyPlays** [comment]
I should probably do 1/3 rounded down?

**Comment by Marty-D** [comment]
Well apparently this was merged while I was typing so I'll handle all the mistakes here.

**Comment by DeathlyPlays** [comment]
Oh ok

**Comment by AustinXII** [comment]
Just an fyi you should almost never represent irrational fractions in rounded percent form...

**Pull request merged**
