### PR TITLE
Actually fix Clangorous Soulblaze vs. Protect

### PR DESCRIPTION
**Pull request by MacChaeger**
I did some bad things when trying to fix a merge conflict so the commit message got messed up somehow.

### CODE REVIEW

**Comment by MacChaeger** [comment]
wait that's the wrong title

**Comment by Zarel** [comment]
This seems like the wrong approach...

**Comment by MacChaeger** [comment]
That’s what I thought too, but I didn’t have any better ideas.

**Comment by MacChaeger** [comment]
Actually I do have an idea. If you don’t beat me to it I’ll do it tomorrow.

**Comment by urkerab** [comment]
If you want to fix it the way I meant to fix it, just clear `zBrokeProtect` at the beginning of `tryMoveHit` instead of `moveHit`. That way it really does run in between each Protect check.

**Comment by Zarel** [comment]
Yeah, that one sounds right to me. But incorporate these tests. :p

**Comment by MacChaeger** [comment]
I think it makes the most sense to actually just set `move.zBrokeProtect` in the modifyDamage event when we actually need it instead of setting it early and clearing it even earlier.

**Comment by Zarel** [comment]
How would you know when to set it?

iirc that would break in the case of doubles, where e.g. Tectonic Rage hits a Flying-type using Protect, and then someone else hits it afterwards.

**Comment by MacChaeger** [comment]
In that case, the ground immunity would stop the Z Move ever getting to the
modifyDamage event at all, thus stopping zBrokeProtect from having been
set, wouldn't it?

**Comment by MacChaeger** [comment]
By "set" I meant to true, not false.

**Comment by Zarel** [comment]
Hm, I think that's correct mechanics anyway? But anyway we definitely needed `zBrokeProtect` for a specific reason, and iirc that reason was because we needed to remove the Protect volatile and calculate damage in different parts of the code.

**Comment by Zarel** [comment]
@urkerab can you pullreq your version? Also add tests.

**Comment by MacChaeger** [comment]
Oh, yeah, I wasn't saying that to mean that would be wrong.

**Pull request closed without merging**
