### PR TITLE
Refactor Punishments to be an object literal

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
Quick poll, who things this looks better?

**Comment by Zarel** [comment]
@Slayer95, you just commented on a different pullreq so I assume you're not too LoA and can give an opinion here.

**Comment by Slayer95** [comment]
Eh, looks like pure code churn to me?

Imo it would be nice to let punishments.js showcase a new standard of PS development best practices, and ruining git blame gratuitously doesn't fit in that 'best practices model'.

For the record, my other comment was because I have checked broadcast vs broadcasted endless times in that snippet, and it caught my eye. I am ignoring most Github repos (seems like a new feature), which means mentions don't notify me, but %panpawn pointed me here.

**Comment by panpawn** [comment]
By that logic, don't a lot of refactors "ruin git blame"...?

**Comment by Zarel** [comment]
Yes, they do, but most style refactors have stronger reasons for why it's better than the old way of doing it.

**Comment by Zarel** [comment]
I think this style might be more compatible with TypeScript/Flow? But that's only suspicions. Why do you personally prefer this style to the old style? That's the question we need to answer, to determine whether or not it's worth ruining `git blame` for.

**Comment by panpawn** [comment]
I prefer this because doing ``Punishments.`` over and over kind of looks unnecessarily repetitive to me.

This also looks more organized and the flow just looks better to me, personally.  I also like being able to use ``this`` when referring to another ``Punishments`` function within these.

**Comment by Zarel** [comment]
We prefer not to use `this` in singletons, mostly on the off-chance that you'd want to use one as a callback.

**Comment by Zarel** [comment]
Your other point is valid, but again, I'd like to hear other devs' opinions.

**Comment by panpawn** [comment]
Should I rebase this, or is this not a desired change?

**Comment by Zarel** [comment]
I'm waiting for outside opinions. @bumbadadabum? @sirDonovan? @Slayer95?

**Comment by sirDonovan** [comment]
I prefer the current code style over this.

**Comment by Slayer95** [comment]
Seems to be a no here

**Comment by Zarel** [comment]
Ironically, we'll probably need to do this if we ever move to TypeScript.

**Comment by panpawn** [comment]
If that happens, feel free to re-open this :p

**Pull request closed without merging**
