### PR TITLE
Sky Drop deactivates Follow Me effects on the first turn

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Actually, somebody should check if it negates Lightning Rod and the like as well

**Comment by Marty-D** [comment]
:+1: The Abilities do still redirect while in the air.

**Comment by ascriptmaster** [comment]
What triggers on that scenario, Lightning Rod immunity or the airborne property causing it to miss?

**Comment by Marty-D** [comment]
Unless some No Guard-like effect is in play, it just misses.

**Comment by ascriptmaster** [comment]
Oh, what happens if you use Sky Drop, then Gravity cancels it? Will Follow Me resume working, or no?

**Comment by Marty-D** [comment]
Nope; as soon as you get taken into the air, the effect is over.

This reminds me though, I don't think we ever implemented two-turn moves ignoring redirection on the first turn.

**Pull request merged**
