### PR TITLE
Add extra commands in the "/help" command.

### PR DESCRIPTION
**Pull request by Soku-Hi**
Just a few commands I think that are important that are missed out.

### CODE REVIEW

**Comment by SolarisFox** [comment]
if we're going to be updating this, I personally feel that we don't need to tel users about the `/avatar` command because it's mostly useless in comparison to the menu, which the command just tells them to use anyways.

Also I personally think `/msg` should be changed to `/pm` since all the experience I've had trying to explain how to pm a user, more users understood what `/pm` might do rather than `/msg`

**Comment by Soku-Hi** [comment]
SolarisFox I agree on the PM one but I think the avatar one should stay.

**Comment by Zarel** [comment]
@Soku-Hi, can you explain why you think the avatar one should stay?

**Comment by Soku-Hi** [comment]
@Zarel I always use /avatar and never use the other way so many it's just a preference thing.

**Comment by Slayer95** [comment]
Unless you already know which avatar you want, <i>and</i> its code, the GUI is much better for that.

Also, the syntax for ``/chall`` is not user-friendly for formats with teams. I have gotten a lot of bug reports from people who do that (my answer was always "don't do that")

**Comment by Soku-Hi** [comment]
@Slayer95 changes will be made!

**Comment by Zarel** [comment]
@Slayer95, actually, `/chall` is fine now, you're probably referring to an older implementation of `/chall`.

**Comment by Soku-Hi** [comment]
@Zarel @Slayer95 @SolarisFox So am I getting rid of "/avatar" and replacing "/chall" with "/challenge"? (I can't squash tonight as I'm on my phone).

**Comment by Soku-Hi** [comment]
Also I know "/chall" is fine but "/challenge" seems more correct.

**Comment by Soku-Hi** [comment]
Sorry about was having copy and pasting issues from my other commits I was copying the "+" signs as well. :(

**Comment by panpawn** [comment]
rip unknown repository

**Pull request closed without merging**
