### PR TITLE
Fix confusion problem with Unaware

### PR DESCRIPTION
**Pull request by Tigerball890**
See "Known Mechanics Bugs" #2367

### CODE REVIEW

**Comment by Tigerball890** [comment]
Why is build failing? Can someone explain this?

**Comment by Zarel** [comment]
If you click the "x", it'll tell you.

Alternatively, you could run `npm test` on your local computer.

**Comment by Tigerball890** [comment]
I did, @Zarel. "262 === 66"

**Comment by Tigerball890** [comment]
Never mind. Just manually going to suggest edit rather than PR.

**Comment by Zarel** [comment]
...? GitHub's "suggest edit" feature is just another way of creating a PR.

**Comment by Zarel** [comment]
The full error is:

```
  1) Battle simulation Abilities Unaware should ignore attack stage changes when Pokemon with it are attacked:
      AssertionError: 262 === 66
      + expected - actual
      -262
      +66
      
      at Context.<anonymous> (test/simulator/abilities/unaware.js:24:10)
```

in other words, your change breaks Unaware.

**Pull request closed without merging**
