### PR TITLE
Random Battle: Remove some mediocre moves from sets

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by TheImmortal** [comment]
Signal Beam ain't that bad. It hits a lot of Pokemon. Ludicolo, Jynx, Celebi, Exeggutor, Abomasnow, Bruxish, Hoopa, Malamar, Slowbro, Slowking, Starmie, and anything else I'm missing.

**Comment by TheImmortal** [comment]
I think Grass Knot hits as many Pokemon as Ice Beam. It ain't a bad coverage move on Slowking.

**Comment by TheImmortal** [comment]
Pursuit is a good move on non-setup sets because it's boosted by Tough Claws. It's also on the Smogon analysis.

**Comment by ascriptmaster** [comment]
After taking out the Grass mons that are still hit by Ice Beam, you mostly get a bunch of Water mons and not enough to justify Signal Beam's low Base Power. If anything, it's better to follow Golduck's usage stats and replace it with Psyshock, which deals more damage when neutral and still hits almost every Water mon in the game for neutral besides the Slowbro family and Starmie.

**Comment by ascriptmaster** [comment]
Updates. I'm still not moving on the Signal Beam decision, though, so I added Psyshock.

**Comment by TheImmortal** [comment]
Fine.

**Pull request merged**
