### PR TITLE
Modjoin: escape HTML for banner display

### PR DESCRIPTION
**Pull request by sparkychildcharlie**

### CODE REVIEW

**Comment by panpawn** [comment]
... ranks are hard-coded, so this really isn't necessary.

... Also, this should be using ``Chat.html`` since this is a template string.

**Comment by sparkychildcharlie** [comment]
Side servers often create their own ranks; having it in config file isn't the same as hardcoding.  This escaping is done in the /modchat command anyways

**Comment by panpawn** [comment]
Having it located in a static file that doesn't change by any kind of commands is kind of the definition of hardcoding.

We shouldn't really support the case of a side-server making their own Config rank that happens to include HTML, if they do that then that's their problem to escape it where necessary imo, nor ours

**Comment by Zarel** [comment]
Literally `Chat.html` exists for this.

I have no problem supporting side servers making `<` a rank in Config. That's a valid situation to support.

**Pull request merged**
