### PR TITLE
Metronome Battle: Increase BST limit cap

### PR DESCRIPTION
**Pull request by Ridaz**

### CODE REVIEW

**Comment by Zarel** [comment]
Mega Aerodactyl? Sounds pretty arbitrary...

**Comment by TheImmortal** [comment]
I mean you could just remove the BST message if you wanted. So it’d basically be the same as hardcoding all the Megas.

**Comment by Zarel** [comment]
I don't have a problem with the BST message, I'm just waiting for a link to the policy thread.

**Comment by KrisXV** [comment]
@Zarel I just skimmed through the entire Metronome Battle thread on Smogon, and unless I missed something, there is no announcement regarding this. @Ridaz considering you own the Metronome Battle thread, I'd make the announcement first if I were you before making a Pull Request.

**Comment by Ridaz** [comment]
https://www.smogon.com/forums/threads/metronome-battles.3632075/post-7997043

**Pull request merged**
