### PR TITLE
[commands.js] comment out deregisterchatroom

### PR DESCRIPTION
**Pull request by Chirou-Cat**
We have deleteroom now, I commented it out because it may needed another day, But it probs isn't used anymore.

### CODE REVIEW

**Comment by panpawn** [comment]
You do realize these commands do two separate things, right?

Deleteroom immediately deletes a room, whereas deregistering a room deletes it upon the next server restart.

**Comment by Chirou-Cat** [comment]
I know

**Comment by Zarel** [comment]
I don't really have an objection to removing `/deregisterchatroom` (I can't think of a use-case not better served by `/deleteroom`), but commenting it out is definitely not the right way to do it.

If anything, it should just show an error message: "You're looking for `/deleteroom`"

**Comment by bumbadadabum** [comment]
Squash your commits and fix the commit messages

**Comment by Zarel** [comment]
Also this still doesn't show the error message -_-

**Comment by Zarel** [comment]
Honestly, `/deregisterchatroom` already says "NOTE: You probably want to use `/deleteroom` now that it exists".

I think it's fine as-is.

**Pull request closed without merging**
