### PR TITLE
Random Battle: Update Mandibuzz

### PR DESCRIPTION
**Pull request by ascriptmaster**
Removing Brave Bird prevents Banded sets.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Eh, I think removing Knock Off is the play. It's pretty much secondary to Foul Play on every analysis. Brave Bird is good so you aren't just setup bait for Fighting mons.

**Comment by TheImmortal** [comment]
I mean ideally we'd reject Knock Off with Foul play anyway but that isn't bad on offensive mons like Yveltal

**Comment by ascriptmaster** [comment]
I chose Brave Bird because while Knock Off is secondary to Foul Play on every analysis, Brave Bird isn't on any analysis outright. That said, 1760 usage has both at around the same usage, although the 1500 Knock Off usage is double Brave Bird's. 

I do wonder about which is better though, since I don't know how much Brave Bird can do off that base 65 attack and no offensive item....

**Comment by TheImmortal** [comment]
Foul Play is twice as much as Knock Off on usage. While Brave Bird is low, Flying STAB isn't guaranteed in Randoms so it should be fine.

Also, sample damage: 85 Atk Mandibuzz Brave Bird vs. 85 HP / 85 Def Infernape: 206-246 (79.5 - 94.9%)

**Comment by TheImmortal** [comment]
U-turn is even less usage than Brave Bird if we took stats into account

**Comment by ascriptmaster** [comment]
Hmmm. How useful is Mandibuzz having a slow U-Turn in randoms?

**Comment by TheImmortal** [comment]
Not sure. It's useful is OMs, I know that. I don't have much experience with it in Randoms but worth keeping for now.

**Comment by TheImmortal** [comment]
Whirlwind is something we could consider for removal if we wanted it to roll more useful moves.

**Pull request merged**
