### PR TITLE
Implement persistence module

### PR DESCRIPTION
**Pull request by Morfent**
This abstracts the logic for handling JSON, CSV, and TSV files from the
modules that use those files for persistent data.

WIP

### CODE REVIEW

**Comment by Zarel** [comment]
Async writing should really just be a feature of fs.js

**Comment by Morfent** [comment]
Yeah, most of the logic for that would fit better in fs.js.

This doesn't implement what I want persistence.js to be doing well. This is meant to be an abstraction for how a file's data should be manipulated, not so much the FS itself.

**Comment by Zarel** [comment]
Hmm... Give me some time to add the API I want to `fs.js`, and we'll see how this fits into it.

**Comment by Zarel** [comment]
So... What's your plan with this now?

**Comment by Morfent** [comment]
My plan was to help abstract the way JSON, CSV, and TSV data update their state so they can be more easily migrated to SQLite eventually, while still being compatible with their old formats if configured not to. Safe writes do help a lot with this, but an API for common ways these files update their state could be translatable to SQL queries later on. `GlobalRoom.chatRoomData`  and `Punishments` are the type of data that could benefit from this, I think

But I'm debating whether or not this would be realistic to do without creating spaghetti.

**Comment by Zarel** [comment]
That makes sense, but flat files do have their advantages. They're compatible with sed/awk, they're compatible with grep, they're compatible with any text editor including the super fancy modern ones like VS Code.

Meanwhile, SQLite has, like, a GUI editor I guess. And a commandline UI.

To be fair, I do think abstracting the storage engine is a good idea.

**Comment by Morfent** [comment]
SQLite's CLI is pretty good, but it doesn't match the convenience of the base system's tools for those flat files, I agree. I'm not sure how to approach handling that, since something like a script might be too risky to let handle data.

I'm relieved you think this is worth looking into developing

**Pull request closed without merging**
