### PR TITLE
Fix /statcalc to round between applying modifiers

### PR DESCRIPTION
**Pull request by Hidden50**
!statcalc gardevoir, spe 252+ scarf
Base 80 at level 100 with 31 IVs, 252+ EVs at +1: 427. (should be 426)
!statcalc gardevoir 252+ spe
Base 80 at level 100 with 31 IVs, 252+ EVs: 284.

### CODE REVIEW

**Comment by Zarel** [comment]
Should be imperative mood: "Fix", not "Fixed". Do you know how to amend a commit?

**Comment by Zarel** [comment]
Also tagging @bumbadadabum because I don't care about `/statcalc`

**Comment by bumbadadabum** [comment]
Oh yeah that seems like me misreading a formula if that's actually incorrect. My bad. Feel free to merge this

**Comment by TheImmortal** [comment]
>Base 80 at level 100 with 31 IVs, 252+ EVs at +1: 427. (should be 426)

I can confirm this statement is true.

**Comment by Hidden50** [comment]
It's because /statcalc currently doesn't round in between applying the 1.1* and 1.5* multipliers from nature and scarf.
1.1 * [252spe gardevoir] = 284.9
correct /statcalc: 1.5 * 284 = 426
current /statcalc: 1.5 * 284.9 = 427.35

**Pull request merged**
