### PR TITLE
Tournaments: always enforce scouting setting

### PR DESCRIPTION
**Pull request by sirDonovan**
Previously players were able to join battles as soon as they ended

### CODE REVIEW

**Comment by Zarel** [comment]
Hm, what happens if a completed match expires?

**Comment by sirDonovan** [comment]
I changed it slightly to avoid references to match rooms. Completed expiring matches already don't call `onBattleWin()` so now there shouldn't be any change in behavior.

**Comment by sirDonovan** [comment]
@Zarel is this ok now?

**Comment by Zarel** [comment]
Looks good, although maybe `completedMatches` should be an array?

**Pull request merged**
