### PR TITLE
Fix minor Typescript bugs in dex-data.ts

### PR DESCRIPTION
**Pull request by scheibo**
- BasicEffect#weather's type got messed up during the rewrite in .ts
- Add Template#originalMega? to match the declaration in globals.ts

### CODE REVIEW

**Comment by Zarel** [comment]
`originalMega` shouldn't exist; it sounds like an OM thing.

**Comment by scheibo** [comment]
Ah, it looks like 'Mix and Mega' specific. If I remove it from `dex-data.ts` and `globals.ts` I get [type errors](https://gist.githubusercontent.com/scheibo/35215c595f6386655f606f5f7a9bb474/raw/1c3d27eb7b23a6f709ade92ecc8520a55b73d706/errors). Should 'Mix and Mega' be using like a `ModdedTemplate` interface? Or just `@ts-ignore` or something?

**Comment by Zarel** [comment]
`ts-ignore`.

**Comment by scheibo** [comment]
Ugh, branch somehow got botched. Need to rebase and force.

**Pull request merged**
