### PR TITLE
Add juniper avatar

### PR DESCRIPTION
**Pull request by TapoCollino**
hopefully

### CODE REVIEW

**Comment by Zarel** [comment]
Juniper was uploaded as an avatar to be specific to Help staff. I don't know how they'd feel about making it a generally usable avatar.

**Comment by TapoCollino** [comment]
Oh didn't know about that. Someone brought it up and I thought you guys just forgot to add it.

**Comment by scheibo** [comment]
> Juniper was uploaded as an avatar to be specific to Help staff

FWIW, Help Staff say they can't access it either - did you actually upload it?

**Comment by Zarel** [comment]
> FWIW, Help Staff say they can't access it either - did you actually upload it?

I did, I even coded up an ACL for avatars, just for them, and then they wanted an ACL that automatically updated as help staff got promoted/demoted :| and I couldn't find time to do that.

**Comment by scheibo** [comment]
Perhaps worth just going with the manual list for now as opposed to blocking indefinitely on the 'best' solution?

**Comment by Zarel** [comment]
Good point. Done.

**Pull request closed without merging**
