### PR TITLE
Roomsettings: Use 'button' class in UI

### PR DESCRIPTION
**Pull request by panpawn**
BEFORE:

(well, that's what it looked like for me, at least.)
AFTER:

### CODE REVIEW

**Comment by Zarel** [comment]
What does it look like in light mode? Doesn't look very clear in dark mode...

**Comment by panpawn** [comment]
Thoughts?

**Comment by Zarel** [comment]
That looks a bit subtle... we may need to do something about that.

**Comment by panpawn** [comment]
What does, specifically? The disabled buttons...?

**Comment by panpawn** [comment]
Updated preview:

**Comment by panpawn** [comment]
Thoughts?

**Comment by Zarel** [comment]
That does look a lot better.

**Comment by panpawn** [comment]
Thanks,  and thanks for specifying what you meant by "subtle" in Dev for me!  :)

**Pull request merged**
