### PR TITLE
Consistency Fixes

### PR DESCRIPTION
**Pull request by QxC4eva**

### CODE REVIEW

**Comment by TheImmortal** [comment]
The descs are on purpose. Remove those changes and I will accept the seasonal one.

**Comment by QxC4eva** [comment]
So when does additional detail go into shortDesc but not desc?

**Comment by Slayer95** [comment]
When the long desc hasn't been properly written yet, @QxC4eva.

**Comment by Marty-D** [comment]
`desc` fields are for http://pokemonshowdown.com/dex/ mostly. The reason Sucker Punch and Bug Bite are mentioned where they are is because in the dex, stuff like Iron Fist can just link to a list of moves or whatever is relevant like this: http://pokemonshowdown.com/dex/tags/fist. `shortDesc` is for the teambuilder and /data commands, where it can actually be a useful tidbit without having to go elsewhere for more information.

Also, all `desc` and `shortDesc` are already as up to date as possible (for Gen 6 at least).

**Comment by QxC4eva** [comment]
Gotcha, thanks.

**Pull request merged**
