### PR TITLE
Fix crash in thing-of-the-day

### PR DESCRIPTION
**Pull request by HoeenCoder**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Fixed in 90498f03281c430577715cf6a64c904c7698270f and I didn't see it.

**Comment by HoeenCoder** [comment]
Never mind this is still needed.

**Comment by bumbadadabum** [comment]
I knew I forgot it somewhere....

**Comment by Zarel** [comment]
This does not actually fix the crash. You still need to wrap `selectHandler` in a `try` block. Typoes shouldn't crash the server.

**Comment by HoeenCoder** [comment]
In that case maybe it should return `false` instead of crashing and then be handled in the commands (this.errorReply)?

**Comment by bumbadadabum** [comment]
I threw an error because this code should have 0 chance to ever be reached,
but I guess an errorReply suffices?

2018-01-24 15:38 GMT+01:00 HoeenHero <notifications@github.com>:

**Comment by Zarel** [comment]
That's not the impression I get from reading the code, but maybe I read it wrong.

**Comment by Zarel** [comment]
Oh, I see. You should be passing the handler ID directly, instead of passing an unparsed message. That's just asking for trouble.

**Pull request merged**
