### PR TITLE
Fix Bonsly's Evolution level

### PR DESCRIPTION
**Pull request by KrisOnline**
Bonsly is required to level up while knowing Mimic

### CODE REVIEW

**Comment by KrisOnline** [comment]
Yikes i messed up

**Comment by Zarel** [comment]
@Marty-D? How do we usually represent this?

**Comment by urkerab** [comment]
It's done by setting `evoMove`. See Ambipom, Lickilicky, Mamoswine, Tangrowth or Yanmega.

Mr. Mime has its `evoMove` set but its `evoLevel` is 1 which is presumably incorrect.

By the way, Veekun seems to think that Tsareena evolves from Steene if it knows Stomp.

**Comment by KrisOnline** [comment]
Veekun is incorrect in that regard, ill look more closely into the other move-based evolutions

**Comment by KrisOnline** [comment]
i just cant seem to do anything correctly, ive done this twice in a row

**Comment by Marty-D** [comment]
No, Veekun is right. I actually completely forgot `evoMove` even existed when I added the Gen 7 Pokemon, since it's used literally nowhere else; not even the PSdex uses it. And it's been around just as long as `evoLevel`, apparently.

I put 29 as the `evoLevel` because Steenee learns Stomp then. And of course, before the games came out no one knew they would let you relearn moves even above your current level. So `evoMove` should be "Stomp" and `evoLevel` should be 19.

**Comment by DeathlyPlays** [comment]
I PR'ed Tsareena fix @Marty-D

**Comment by KrisOnline** [comment]
I mean I could’ve just added the Tsareena fix into here but alright

**Comment by DeathlyPlays** [comment]
Want me to PR it into your fork of this and just send it into this PR @KrisOnline

**Comment by KrisOnline** [comment]
No I'm sure it's fine

**Comment by Marty-D** [comment]
Oh, now I remember why Mr. Mime and Sudowoodo have an `evoLevel` of 1 here; you can just breed them without an Incense to get them at level 1. So I'm just gonna merge the other PR then.

**Pull request closed without merging**
