### PR TITLE
Make forme letters a unique property

### PR DESCRIPTION
**Pull request by Favna**
This ensures a more differentiating factor between Pokemon. Even more ideal would be having 2 character form letters which would mean a lot less hacky letters for Pokemon such as Arceus and Silvally (for whom I both took the first not already occupied letter of each type) and Oricorio (who could be PP for Pom-Pom, Pa for Pa'u, S for Sensu and B for Balle). However for now I kept it at a 1 character length and worked with that.

In general I looked at the form name and took the first available or otherwise sensible letter of that form that was not already taken.

If you're willing to accept 2 letter form letters then I'll gladly add another commit to this PR in order to achieve this.

---

p.s. I am well aware this does not conform to a pull request that fixes bugs as described in the contributing guidelines and therefore I hereby consent that if this PR gets rejected I take no issue to that in any way, shape or form.

### CODE REVIEW

**Comment by Zarel** [comment]
This is probably a good idea in general, but I honestly have no clue if we still want it. I believe Smogon switched to forme names to match PS.

It might be better to remove forme letters entirely?

**Comment by Zarel** [comment]
If we do stick with forme letters, they need to be used somewhere "official" so that we can be synced to that; I have no interest in making up our own forme letters.

**Comment by Favna** [comment]
Well your data set is referenced by discord bots such as [Beheeyem](https://github.com/110Percent/beheeyem) and I think also by [veekun's pokedex bot](https://github.com/veekun/pokedex/tree/master/pokedex/data/csv) although I cannot say that with certainty. However, more importantly for myself, my own [Ribbon](https://github.com/favna/ribbon) bot. I have personally utilized the forme letters as a way to get the form specific dex entry (that's a thing since gen7, thanks gamefreak '_>').

Due to code length and ease of  checking I would therefore say that while not directly for Showdown the form letters do have some use for external users.

Note that in case you wanted to see my implementation of that aforementioned code, it's not yet pushed as I first want to finish the fully updated flavortext file but this is the code part that handles it:

```js
for (let i = 0; i < dexEntries.length; i += 1) { // dexEntries is the array stored in the dex entries json file
	if (pokeEntry.formeLetter) { // pokeEntry is the entry of the pokemon found after the command was issued by the user
		if (dexEntries[i].species_id === `${pokeEntry.num.toString()}${pokeEntry.formeLetter.toLowerCase()}`) { // num is the national dex number and formeLetter speaks for itself. This checks if the speciesID in the dexentries has a form letter
			pokedexEntry = dexEntries[i].flavor_text; // and if it does then it uses that form specific dex entry
			break;
		}
	} else if (dexEntries[i].species_id === pokeEntry.num.toString()) { // but if there are no forms i still want to grab the dex entry of course
		pokedexEntry = dexEntries[i].flavor_text;
		break;
	}
}

if (!pokedexEntry) { // just in case nothing was found. pokedex entry is initialized as just an empty string so this works.
	pokedexEntry = '*PokéDex data not found for this Pokémon*';
}
```

The specific file on my bot can be found [here](https://github.com/Favna/Ribbon/blob/master/src/commands/pokedex/dex.js) but like I said above, it does not yet have the above code just yet. I still got 60 or so dex entries for (U)S(U)M and some megas to plow through before I'll push that.

**Comment by Zarel** [comment]
Is there any reason you're using the forme letter and not the full forme name found in `pokeEntry.forme`?

**Comment by Favna** [comment]
> Is there any reason you're using the forme letter and not the full forme name found in `pokeEntry.forme`?

I suppose.. not really. The only reason I can give is shorter IDs which admittedly is hardly a compelling reason.

**Comment by Favna** [comment]
Yeah giving it some more thought and viewing, I do suppose just referencing it by forme name is much better. In that case if Smogon does indeed not use letters then maybe it is better to remove the letters entirely.

**Comment by Zarel** [comment]
Yeah, that's what I was thinking, too.

**Comment by Favna** [comment]
Well all said and done I suppose this PR can be closed.

**Pull request closed without merging**
