### PR TITLE
Rename TryImmunity to TryInvulnerability

### PR DESCRIPTION
**Pull request by urkerab**
It's a check for semi-invulnerability rather than any sort of immunity.

### CODE REVIEW

**Comment by Zarel** [comment]
Maybe just `onInvulnerability`?

**Comment by Zarel** [comment]
I did say "maybe". What does everyone else think?

**Comment by Zarel** [comment]
Mostly, I feel like `onTryBlah` is only used if we already have an `onBlah` that does something different.

**Comment by urkerab** [comment]
... that's why it's a separate commit so it can be easily reverted.

**Comment by Zarel** [comment]
I didn't say you did anything wrong. :p

**Comment by Marty-D** [comment]
Yes! Thank you!

**Pull request merged**
