### PR TITLE
Add Poké Ball Vivillon

### PR DESCRIPTION
**Pull request by jakobw**
I added the entry for Poké Ball Vivillon (#1318).
I'm not entirely sure if `pokedex.js` is really the only relevant change in this case and whether setting the egg group to `["Undiscovered"]` takes care of it not getting Rage Powder.
This also still needs to be added in the client but I wanted to get some feedback first.

### CODE REVIEW

**Comment by xfix** [comment]
That won't work. Egg groups in Gen6 are mostly ignored entirely by a validator (minus a few case with essence breeding), because Gen6 changed breeding mechanics. And for that matter, egg moves are inherited from base prevo, which has a properly set egg group.

**Comment by jakobw** [comment]
Ah, too bad. Would it work to remove the prevo from the special form and add an entry for it to the learnsets?

**Comment by Slayer95** [comment]
@jakobw, please test your code before submitting pull requests.

Since this forme isn't registered in the client, you could add it to a team by using the ``Import/Export Team`` feature and manually typing its species.

**Comment by jakobw** [comment]
Right, I now managed to test it using the Import/Export function. I removed Vivillon as its `baseSpecies` to make sure it cannot get rage powder or any other egg moves. I'm not sure that's the right way and hope that doesn't have any unwanted side effects though. Since it still has its `num` there cannot be two Vivillons in one team.

**Comment by ascriptmaster** [comment]
I think you should look at how Cosplay Pikachus are implemented -- they still have Pikachu as their `baseSpecies` but still are set up so they cannot gain egg moves.

**Comment by Layell** [comment]
Last I checked Poke Ball Vivillon does not have any special moves, and we don't have any other cosmetically useless mons (before someone says Keldeo we need its base for pre-BW2 metas really).

We don't have the Hold Hands Fancy Pattern either.

Keep me in the loop for the sake of sprites.

**Comment by Slayer95** [comment]
@Layell, it indeed does not have additional moves. The point is that it <i>lacks</i> a move.
This was already discussed in #1318

Seeing that someone was jumped in to try help with the Vivillon formes, I'd assume this is actually something people want.

**Comment by TheImmortal** [comment]
Closing this in favor of #2262.

**Pull request closed without merging**
