### PR TITLE
Random Battle: Minor moveset changes

### PR DESCRIPTION
**Pull request by ascriptmaster**
Remove Healing Wish from Lilligant (useless) and Fire Punch from
Darmanitan (redundant and vastly inferior to Flare Blitz)

@TheImmortal

### CODE REVIEW

**Comment by TheImmortal** [comment]
Want to add HP Rock as an alternative Hidden Power? It's got decent usage in OU/UU/NU. Otherwise its sets are too predictable.

**Comment by TheImmortal** [comment]
Also Healing Wish isn't that bad. It's used on a Scarf set. It's just the Randoms script isn't designed to  make a Scarf Leaf Storm/HP/Sleep Powder/Healing Wish set.

**Comment by ascriptmaster** [comment]
HP Rock is a good idea. Also, Healing Wish has an incredibly low usage on Lilligant and the Smogon analysis in XY no longer recommends it (and even recommends against it due to its inability to threaten with boosted Giga Drains otherwise) despite it being used in BW era.

**Comment by ascriptmaster** [comment]
Everything is good now.

**Pull request merged**
