### PR TITLE
Updated some viablemoves in teambuilder

### PR DESCRIPTION
**Pull request by galbia**
Moves such as Teeter Dance and Stockpile are just awful on everything,
Searing shot is not viable on the only Pokemon that gets it sadly,
Infestation is not good on anything simply and should get close to
zero usage. Retailate is a wasted moveslot on everything. @xfix said
that me doing this was fine :)

### CODE REVIEW

**Comment by Zarel** [comment]
Usually my rule is "has appeared on at least one Smogon set".

**Comment by Zarel** [comment]
I swear I remember seeing Stockpile somewhere.

**Comment by TheImmortal** [comment]
That's a bad rule. A move shouldn't show as "usable" on every Pokemon that learns it if it's so niche. I'd go for something like: "if it's viable on 20% of the Pokemon that can learn it".

**Comment by galbia** [comment]
Well Stockpile usually attracts inexperienced players like a magnet on the ladderbut the only pokemon i fan remember having an analysis with it was Cradily in bw nu (a set then removed AMD just very bad). In general it is a terrible move in any competitive game as even if used to the max it would cause its user to eventually get stalled out because he isn't boosting offenses, statuses, or phased out. If I want to be honest Torment actually was seen in gen 4 on heatran (the "famous" tormenttran) but that set has no use in tournament play and nothing else has used it since gen ,4

**Comment by Zarel** [comment]
> That's a bad rule. A move shouldn't show as "usable" on every Pokemon that learns it if it's so niche. I'd go for something like: "if it's viable on 20% of the Pokemon that can learn it".

No, that's way too high a standard. Usable moves are intended to be so someone never has to scroll past them to make a set.

I'm not sure I want people to scroll past moves like Growl and Tackle when building a surprise set or something.

I'd say to take "only on one set/analysis ever" on a case-by-case basis, and any more is auto-accept.

I'd lean towards yes Torment, no Stockpile.

**Comment by TheImmortal** [comment]
How is it a high standard? By viable I mean on Smogon sets. Growl and Tackle are not on Smogon sets,

**Comment by Zarel** [comment]
Yes, but you want to remove moves that are on Smogon sets if they're not on _enough_ Smogon sets.

**Comment by Zarel** [comment]
I wouldn't be surprised if like Boomburst doesn't pass because of the number of physical attackers that learn it, or something.

**Comment by Zarel** [comment]
Oh, better example! Return doesn't pass.

**Comment by TheImmortal** [comment]
Okay. I get the point. I don't think we can come up with an actual requirement that would be perfect. Using Smogon sets, combined with judgment should suffice, which is what I have done.

**Comment by Zarel** [comment]
The problem is when our judgment disagrees.

I'd much rather have a bad move be considered usable (that's only a few bad moves to scroll past for the move you want) than for a move someone might want to be considered unusable (then there are tons and tons of bad moves to scroll past for the move you want).

**Comment by TheImmortal** [comment]
The problem is that bad players would think the bad move is a good move. Smogon prefer differently than what you said because of that, as can be seen from here http://www.smogon.com/forums/threads/3495758/. I don't think good players scroll; they would just type the move. So, the usable section is really for bad players and we we would want the least possible bad moves listed there rather than what you're saying.

**Comment by Zarel** [comment]
What's why we removed the "viable moves" list completely. The "usable moves" list on the other hand is intended to be a list of moves that anyone might ever use. Do we need to remove that list, too? Ugh.

**Comment by galbia** [comment]
Well if you want to keep torment i am OK since it doesnt have big distribution anyway. I think the better solution would be to use an algorithm like the one @xfix showed me (tho he said it has some problems and needs to be worked on) but while we are using this method, especially considering that if a player that knows his stuff will type in the move anyway, I think we shouldn't be as forgiving as we would be allowing any move that has ever been in an analysis especially considering the current generation is 6 and some of those moves like torment (which idm too much it isn't a "noob magnet" like infestation) haven't been viable for a long time.

**Comment by TheImmortal** [comment]
In other words, it's fine to keep, Zarel; just leave it to my judgment. :)

**Comment by xfix** [comment]
Just to clarify, the method @galbia speaks about is probably not viable to use in actual Showdown client (because it requires lots of extra data, and the plan is to lower the ammount of data downloaded). It's simply storing the viable movesets per Pokemon basis (so stuff like Dynamic Punch on Machamp would be marked as viable).

For example, Machamp has Bullet Punch, Close Combat, Earthquake, Heavy Slam, Ice Punch, Knock Off, Poison Jab, Stone Edge, and Substitute marked as viable. This is unlike the current list, which lists nonsense like Fire Blast or Hidden Power Fighting, and doesn't actually mark important moves as viable, such as Dynamic Punch (the main reason to use Machamp is after all Dynamic Punch). One of main issues with this approach currently is lack of support for doubles (Doubles probably also should add Protect, Rock Slide, Quick Guard, and Wide Guard to the list, but it's not that the current approach does mark good Doubles moves either).

**Pull request merged**
