### PR TITLE
Sockets: decouple cluster workers from connections and other modules

### PR DESCRIPTION
**Pull request by Morfent**
Attaching entire processes to connections is kind of a bad idea.

### CODE REVIEW

**Comment by Zarel** [comment]
...it is? Why?

**Comment by Morfent** [comment]
Because it's information the connection doesn't need to know in order to function. It also makes a Go rewrite of the module a lot more complicated since the other modules wouldn't be able to know more about workers than their IDs and maybe PIDs outside of doing something weird like making mocks of them on the Node side of things. This may or may not help with memory, I have no good way to check though.

**Comment by Zarel** [comment]
> Because it's information the connection doesn't need to know in order to function.

As far as I can tell, your code replaces a process pointer with a process ID. This slows down your process communication for no discernable benefit.

The reason I've historically replaced other pointers with IDs is because I don't trust the GC. Processes never expire so the GC is irrelevant.

> It also makes a Go rewrite of the module a lot more complicated since the other modules wouldn't be able to know more about workers than their IDs and maybe PIDs outside of doing something weird like making mocks of them on the Node side of things.

...I don't understand what you're trying to say here, but I believe you're wrong. You can replace "process" with "process wrapper" if the API is different; all we use in practice is `process.send` and maybe `process.disconnect` afaik.

> This may or may not help with memory, I have no good way to check though.

Mostly sure it doesn't.

**Comment by Morfent** [comment]
>...I don't understand what you're trying to say here, but I believe you're wrong. You can replace "process" with "process wrapper" if the API is different; all we use in practice is process.send and maybe process.disconnect afaik.
it was badly worded. What I meant was there wouldn't be a worker object available at all to the connection since that would be handled in Go. Giving what would be the equivalent of a worker an ID to send over to Node through IPC is fairly simple to do, but the alternative to this would be doing something like giving the connections objects with a similar API to workers that would handle communicating with the Go process, which doesn't really need to be done

>Mostly sure it doesn't.
I wasn't sure whether it would or not, but I can see if I can work out a way to properly check

**Comment by Morfent** [comment]
When I make enough connections to get my IP banned, the original code leaks the socket objects. This doesn't, but instead it's leaking users and connections... I'll see if I can make it so neither do.

**Comment by Zarel** [comment]
> it was badly worded. What I meant was there wouldn't be a worker object available at all to the connection since that would be handled in Go. Giving what would be the equivalent of a worker an ID to send over to Node through IPC is fairly simple to do, but the alternative to this would be doing something like giving the connections objects with a similar API to workers that would handle communicating with the Go process, which doesn't really need to be done

Yes, that is what I'm advocating. Make a wrapper object with the same API as currently.

I think you don't understand how multiprocess code works?

You have a parent process and a child process. The parent process is written in Node, your child process will be written in Go. But the parent process still has a child process object, corresponding to the Go process. That object can be wrapped if its API is different from the cluster API.

> I wasn't sure whether it would or not, but I can see if I can work out a way to properly check

You are making a grand total of approximately three long-lasting objects. It really doesn't matter at all.

> When I make enough connections to get my IP banned, the original code leaks the socket objects. This doesn't, but instead it's leaking users and connections... I'll see if I can make it so neither do.

There are zero socket objects in the main process, only Connection objects which abstract them. The child processes have socket objects but I don't see how they would be leaked.

**Comment by Morfent** [comment]
>Yes, that is what I'm advocating. Make a wrapper object with the same API as currently.

>I think you don't understand how multiprocess code works?

>You have a parent process and a child process. The parent process is written in Node, your child process will be written in Go. But the parent process still has a child process object, corresponding to the Go process. That object can be wrapped if its API is different from the cluster API.     

But I do. Of course the child process would need to be wrapped, but I don't think following cluster's API would work unless it cached which connections belong to which "workers" when they're created or if a wrapper were to be constructed for each "worker" in the child process. I think that would make the wrapper more complex than it really needs to be just for the sake of making it act like a worker

>There are zero socket objects in the main process, only Connection objects which abstract them. The child processes have socket objects but I don't see how they would be leaked.

My bad, they were TCP streams from the cluster, not sockets. It was a dumb assumption

**Comment by Zarel** [comment]
> But I do. Of course the child process would need to be wrapped, but I don't think following cluster's API would work unless it cached which connections belong to which "workers" when they're created or if a wrapper were to be constructed for each "worker" in the child process. I think that would make the wrapper more complex than it really needs to be just for the sake of making it act like a worker

Actually, reading this again: The API is completely fine in its current state. The API as it currently stands is:

`Sockets.socketSend(this.worker, this.socketid, data);`

So the system for sending to workers is already abstracted out and can be easily changed if for whatever reason the communication system is different.

That said, I still don't think you understand how sockets work, because what you're saying right now is mostly nonsense. `Connection` already caches which connection belongs to which worker.

> My bad, they were TCP streams from the cluster, not sockets. It was a dumb assumption

Yes, you have four TCP streams, one per process, created when PS starts and then never created/destroyed, so I don't see how they could possibly leak.

**Comment by Morfent** [comment]
This entire pullreq is one enormous fucking trainwreck

**Pull request closed without merging**
