### PR TITLE
Rest's HP check precedes Snatch

### PR DESCRIPTION
**Pull request by urkerab**
Reported [here](https://www.smogon.com/forums//posts/7794032).

### CODE REVIEW

**Comment by Marty-D** [comment]
The sleep check should also move to the same place. Sleep Talk -> Rest doesn't get stolen by Snatch even if the original user's HP isn't full.

**Comment by urkerab** [comment]
That would be a specific check for Sleep or Comatose in that case? (As I understand it, other effects that prevent Sleep take effect after Snatch.)

**Comment by Marty-D** [comment]
Both; Comatose is checked wherever sleep is checked. Also, don't forget to override the TryMove part in Gen 2.

**Comment by urkerab** [comment]
OK, so I take it that the existing TryMove is actually correct for Gen 2? And I don't really have to worry about Gen 1 since Snatch doesn't exist there anyway?

**Comment by Marty-D** [comment]
The reason you have to worry about Gen 2 at all is because you can use Sleep Talk to call Rest and it will work if your HP isn't full. Gen 2 Rest is already overriding `onHit`, so if you change it here you have to think about how it affects every gen before it.

**Comment by urkerab** [comment]
Right, but I didn't have to worry about that when I was only checking for full HP, so that version of `TryMove` would have worked for Gen 2 anyway.

**Comment by Marty-D** [comment]
Oh, yeah, my bad. I read your original reply off the notification email and didn't notice the edit here. Looks good!

**Pull request merged**
