### PR TITLE
Protocol: Fix Markdown Headers

### PR DESCRIPTION
**Pull request by DeathlyPlays**
I realized that the headers somehow were removed; this will fix that.

### CODE REVIEW

**Comment by Zarel** [comment]
They look fine to me? But I do prefer this code style anyway.

**Comment by Zarel** [comment]
Also: Your commit summaries should be in sentence case, not title case

**Comment by DeathlyPlays** [comment]
Oh ok

**Comment by DeathlyPlays** [comment]
Earlier the header thing didn't show up , Markdown requires a space after the #

**Comment by Zarel** [comment]
..."Markdown" is a poorly-standardized mess.

GitHub Flavored Markdown does not appear to require `#`.

**Comment by DeathlyPlays** [comment]
Hmm.... Interesting... Nevertheless, I noticed it when reading the file last night

**Pull request merged**
