### PR TITLE
Edit move descriptions for Primal abilities

### PR DESCRIPTION
**Pull request by hvk3**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm not sure this is necessary.......

**Comment by hvk3** [comment]
Should I close this, then?

**Comment by Zarel** [comment]
Maybe "if the weather is rainy (Rain Dance, Drizzle, Primordial Sea)"?

A lot of them just say "Rain Dance" instead of mentioning both Rain Dance and Drizzle.

**Comment by hvk3** [comment]
This seems fine, but what about Sunny Day? Would "The sunlight is harsh" be okay?

**Comment by hvk3** [comment]
Updated

**Comment by Zarel** [comment]
"rainy weather" and "sunny weather" seems to cover it

**Comment by Zarel** [comment]
@Marty-D?

**Comment by hvk3** [comment]
I'll wait for @Marty-D to respond before updating, if that is fine.

**Comment by Marty-D** [comment]
>I'm not sure this is necessary.......

Very much this.

When it says for example, "weather is Rain Dance", it means the weather caused by the move Rain Dance and not the move itself. Since Drizzle uses Rain Dance and Primordial Sea has all of the effects of Rain Dance plus more, and that is mentioned in those descriptions, this is unneeded. Not to mention your short description changes don't actually fit the teambuilder.

>I felt that since Rain Dance and Drizzle are being mentioned in the tooltips

Where? What tooltips?

**Pull request closed without merging**
