### PR TITLE
Polls: add "button" class to the button

### PR DESCRIPTION
**Pull request by Lord-Haji**
Looks better than before

### CODE REVIEW

**Comment by TheImmortal** [comment]
Pics for comparison?

**Comment by Zarel** [comment]
Sure.

I'm not asking for a license because I don't think your change is big enough to be copyrightable; feel free to dispute blah blah blah.

**Comment by Lord-Haji** [comment]
u people just merged a PR of permalocked user

**Comment by AustinXII** [comment]
@Lord-Haji you aren't the first person to do that, sorry :(

**Pull request merged**
