### PR TITLE
CommandParser: register global command aliases, optimize TestPattern …

### PR DESCRIPTION
**Pull request by Morfent**
…registration

Aliases like /j used to not work when called from the global room while not in
lobby. Using rest parametres for TestPattern#prototype#register instead of a
single array came out to be faster (on the condition more than one pattern's being added).

/roomtopic also isn't a command.

### CODE REVIEW

**Comment by Slayer95** [comment]
I'm not a fan of this, but since you already did it, hurray for improvements through incremental steps...

**Comment by Morfent** [comment]
What would've been a better way to do it?

**Comment by Slayer95** [comment]
91Well, basically, the way we declare command flags / attributes isn't cutting it.

Let's talk about <strong>aliases</strong>. While declaring them as string properties of ``commands`` is awesome, issues with them are not unheard. To demonstrate it, let's play a game: find the <em>critical</em> bug in #917.

<strong>Help entries</strong>. Declaring them as arrays is an excellent compatibility artifice, though it's maybe too clever. There's also the fact that most of them repeat the command name and even include the command token... <strong>twice</strong> [See e.g. ``/help pokedex``, which refers to ``/data`` and ``!data`` in the output](https://github.com/Zarel/Pokemon-Showdown/blob/a88825e55faf4e30c25ac6901d54c81b21c43789/chat-plugins/info.js#L420-L421).

Now come <strong>multiline commands</strong>.

In the beginning, only ``>> `` and ``>>> `` were supported, and they were hardcoded in no less than ``Users.socketReceive``.  ``CommandParser.multilinePattern`` was introduced as a <em>flexible</em> API, which allowed us to support LF as the one-true separator in case of command parameters ambiguity, and even [CSV input](https://github.com/Zarel/Pokemon-Showdown/commit/77b59e78582cb7eaa59655cb3ff9471417b757d5).

However, the flexibility is only really needed for ``>> `` and ``>>> `` support, and we could live with demoting it to a low-level API. ``/adddatacenters``, and ``/poll`` could be declared as multiline with *some other* more scalable method.

In more recent times, however, the inappropriateness of our command API has become increasingly notorious.

By introducing commands in PMs, the need to recognize which commands support broadcast surfaced, and the ``!data: 'data'`` horror appeared. OK, it works, and the feature is described as "highly experimental", but I still would rather not see it perpetuate. For one, ``!`` is an implementation detail, which could <em>in theory</em> be swapped out any day.

And, now, I added ``CommandParser.globalPattern``... Not because I liked it, but because it was the simplest and fastest way to fix an in-my-easily-impressionable-eyes high-severity vulnerability, while still keeping proper core-plugins communication.

I'd like to deprecate/remove it, as well as every other feature described in this post, and make a unified declarative command attributes API.

**Comment by Slayer95** [comment]
Btw, for future reference, ``#register`` translates to ``.prototype.register``.

**Comment by Zarel** [comment]
> Well, basically, the way we declare command flags / attributes isn't cutting it.

Agreed.

> Let's talk about <strong>aliases</strong>. While declaring them as string properties of ``commands`` is awesome, issues with them are not unheard. To demonstrate it, let's play a game: find the <em>critical</em> bug in #917.

You know, that's something any linter would have found. Making them command attributes actually makes it harder to find these kinds of bugs (although I guess they could print an error on startup).

I think command aliases are one of the few things that do belong directly in the object rather than in command metadata.

> <strong>Help entries</strong>. Declaring them as arrays is an excellent compatibility artifice, though it's maybe too clever. There's also the fact that most of them repeat the command name and even include the command token... <strong>twice</strong> [See e.g. ``/help pokedex``, which refers to ``/data`` and ``!data`` in the output](https://github.com/Zarel/Pokemon-Showdown/blob/a88825e55faf4e30c25ac6901d54c81b21c43789/chat-plugins/info.js#L420-L421).

That's intentional, really. Good to give the canonical name for the command. Maybe we could add a "/pokedex is an alias for /data" at the top.

> By introducing <strong>commands in PMs</strong>, the need to recognize which commands support broadcast surfaced, and the ``!data: 'data'`` horror appeared. OK, it works, and the feature is described as "highly experimental", but I still would rather not see it perpetuate. For one, ``!`` is an implementation detail, which could <em>in theory</em> be swapped out any day. And we may still like to dissociate broadcast-capability from PM-capability. [See e.g. Dono's comment](https://github.com/Zarel/Pokemon-Showdown/commit/6b4eaf94224c8c1bbf3019a3589e4b495c6fe8cb)

Technically, the `"!data": true,` syntax is for commands that don't require `room` to be passed, not commands that support broadcast. For instance, it's used for `/roomauth`, which is not a broadcast command.

**Comment by Zarel** [comment]
But the real thing we should be discussing is: what's the solution? How do we represent command metadata?

We could have a sub-object, so instead of

```
  me(target, room, user, connection) {
    return '/me ' + target;
  },
```

we could do

```
  me: {
    command(target, room, user, connection) {
      return '/me ' + target;
    },
    pmusable: true,
    help: "/me [action] - sends the message '[username] [action]'",
  },
```

Which honestly is a lot more boilerplate than I'd prefer, but I guess I can't think of any better way to do it.

We could have only the metadata separate:

```
  me(target, room, user, connection) {
    return '/me ' + target;
  },
  memeta: {
    pmusable: true,
    help: "/me [action] - sends the message '[username] [action]'",
  },
```

But I don't think that looks any better. :/

**Comment by Zarel** [comment]
Honestly, this is the perfect use case for decorators. Too bad they're stage 2 right now. :(

**Pull request merged**
