### PR TITLE
Fix Quash interaction with self-switching moves

### PR DESCRIPTION
**Pull request by ascriptmaster**
Give the move demoted by Quash a negative priority when rearranging it in
the queue so that it does not get re-sorted to its original position when
self switch moves run.

### CODE REVIEW

**Comment by Slayer95** [comment]
This issue also affects Round, when the target has Eject Button.
Really, the queue shouldn't get re-sorted under these conditions.

**Comment by ascriptmaster** [comment]
Would it be possible to `unshift` in all relevant `runSwitch` decisions instead of sorting them ever? After all, they run almost exclusively after `switch` decisions, and are supposed to run before any other `switch` decisions execute.

**Comment by Slayer95** [comment]
I don't see why not. However, that still leaves the main issue of the queue being reordered on new decisions.

**Comment by ascriptmaster** [comment]
We could go for an insertion sort style for adding new items to the queue -- put it in the right place while leaving the rest of the queue untouched.

**Comment by Slayer95** [comment]
Apparently that wouldn't play well with RNG and speed ties resolving (https://github.com/DanUgore/Pokemon-Showdown/commit/6285322661889d5c8a0e4f08f3c7befbc0c44880)

Tagging @DanUgore to maybe get his input.

**Comment by ascriptmaster** [comment]
Could we do insert-in-place within `addQueue` instead of sorting, and then if `noSort` is on then simply do what is already done? That commit implies we used to have a `sortQueue` function (can't find it in the code any more) that could re-sort the queue if we really needed to.

**Comment by Zarel** [comment]
Yeah, the queue should never get re-sorted. We need to refactor the re-sort stuff out completely.

**Comment by ascriptmaster** [comment]
bleh, can we worry about the re-sort later? it's really hard

**Comment by Zarel** [comment]
Why is not re-sorting hard? We have reason to add things to the end of the queue or the beginning of the queue, but generally not anywhere else...

**Comment by ascriptmaster** [comment]
Figuring out what needs to be refactored to get it working is hard, at least. My last try caused almost every unit test to fail

**Comment by DanUgore** [comment]
So what currently resorts the queue? Afaik only switching does and I guess
that can be fixed by appending to the beginning instead of adding to the
end and sorting?



-- 
-- Hugh Gordon

**Comment by ascriptmaster** [comment]
Technically, Gen 4 Custap will shuffle the queue but it occurs during the BeforeTurn event. That seems to be it according to my quick grep, but I'm unsure.

**Comment by ascriptmaster** [comment]
How's this for preventing runSwitch from resorting?

**Comment by ascriptmaster** [comment]
What's the dealy-deal on this now?

**Comment by Zarel** [comment]
todo: `addQueue` should never auto-sort.

**Pull request merged**
