### PR TITLE
added a /statcalc command

### PR DESCRIPTION
**Pull request by bumbadadabum**
schermafdruk van 2015-07-28 18 26 50

### CODE REVIEW

**Comment by Zarel** [comment]
The text is way too verbose.

**Comment by Zarel** [comment]
I mean, it's on par with other commands that also suck, but let's try to at least not suck going forward.

**Comment by Zarel** [comment]
also, consider accepting `252+` instead of or in addition to `boosting 252`

**Comment by bumbadadabum** [comment]
Tried to fix the issues you listed.

**Comment by Zarel** [comment]
New screenshot?

**Comment by bumbadadabum** [comment]
schermafdruk van 2015-07-30 13 39 34

**Comment by Zarel** [comment]
Might want to clarify how many IVs?

**Comment by bumbadadabum** [comment]
I could implement that, if you really want it. I just neglected it since it's going to be 31 in 99.9% of cases.

**Comment by CrestfallPS** [comment]
0 IVs detrimental nature is sort of relevant (troom comes to mind alongside a few other obscure scenarios).

**Comment by Zarel** [comment]
Also Hidden Power isn't exactly an obscure move...

**Comment by bumbadadabum** [comment]
I'll implement that then tomorrow.

**Comment by bumbadadabum** [comment]
And done.

**Comment by Joimer** [comment]
Seems fine and it is very useful, @Zarel?

**Comment by bumbadadabum** [comment]
I was thinking about rewriting this slightly so the order of the parameters doesn't matter.

**Comment by xfix** [comment]
It feels to me like this should allow providing a Pokemon as an input. While it makes parsing more complex, I think it's possible to implement.

**Comment by Zarel** [comment]
I guess there's no reason to leave this in limbo too long. It's useful in its current form, but feel free to ask for improvements.

**Pull request merged**
