### PR TITLE
Victory Star shouldn't increase accuracy to more than 100%

### PR DESCRIPTION
**Pull request by hvk3**
Since accuracies are in percentages, they should not exceed 100.

### CODE REVIEW

**Comment by Slayer95** [comment]
@Marty-D ?

**Comment by Zarel** [comment]
This is not how math works.

**Comment by Zarel** [comment]
To clarify: The `accuracy` value is a stat used to calculate a move's hit chance. It is not a mathematical probability. You can tell because we multiply it by 1.1, while a real mathematical probability only exists as a concept and not in a computer.

Clamping the accuracy stat at 100 would break its interaction with an opponent's Double Team etc.

Were you trying to change how it looks in the tooltip? This isn't the right place to do that, and you shouldn't do that anyway because letting the number go past 100 lets players know that it will have an increased chance to hit foes with evasion boosts.

**Comment by Marty-D** [comment]
Whoops, saw this earlier and forgot to reply to it. Here's what I was going to say:

Basically, we don't actually have any idea how accuracy modifiers are chained together (besides Wonder Skin) since no one has gone through the Gen 5 source code to find out (as is the case with Speed), so Victory Star could very well come before or after something like Bright Powder.

In a nutshell, who cares; like Zarel said it's just math. With your logic applied to every accuracy modification, if Gravity/Victory Star/+6 accuracy were calculated before Wonder Skin/Tangled Feet/+6 evasiveness, they would be completely ignored on a 100% accurate move. This doesn't make any sense, no matter how things are chained.

**Pull request closed without merging**
