### PR TITLE
Scavengers: autolink links in scavenger hunts.

### PR DESCRIPTION
**Pull request by sparkychildcharlie**
- use link regex from client
- (``ScavengerHunt#parseHint`` line with the replace taken from ``wifi.js``)

### CODE REVIEW

**Comment by Zarel** [comment]
Honestly, I think we should move Wifi's parser to `chat.js` and use it here.

**Comment by sparkychildcharlie** [comment]
Moved the parseText to Chat and added an additional param ``ignoreFormatting`` to selectively choose what to __not__ format in the post, (such as ignoring [[ linking ]] and ** bold ** in scavenger hunts)

**Comment by Zarel** [comment]
is that necessary?

**Comment by Zarel** [comment]
I feel like if you're supporting links, you might as well support other formatting.

**Comment by sparkychildcharlie** [comment]
Im supporting all formatting except formistakefrom [[ ]](dont need mistakes with bad linking) as well as bold which would be redundant

**Comment by Zarel** [comment]
Can you clarify?

I still don't think it's worth adding complications to the parser to support that.

**Comment by sparkychildcharlie** [comment]
I'm fine with it either way, I eventually remembered that I used ``<strong>`` instead of ``<b>`` for formatting in the scavengers messages.  If you prefer not adding complications, I'm fine with that too, I just want to provide more flexibility and options for other places where this may potentially be used.

If you want, I can remove the complications.

ATM, I feel like it would be counterproductive to have links created by [[ word ]] in scavenger hunts, so I'm not marking that type of formatting up.  Emphasis using ** would be lost, so having that as an exception as well would keep the meaning of the hunt.

**Pull request merged**
