### PR TITLE
Updated install info to work

### PR DESCRIPTION
**Pull request by shryme**

### CODE REVIEW

**Comment by kotarou3** [comment]
Why doesn't `./pokemon-showdown` work for you?

**Comment by shryme** [comment]
Oh! Didn't realize it was a unix command! Just tried node pokemon-showdown and it works!

**Comment by Zarel** [comment]
Oh, `./pokemon-showdown` doesn't work on Windows?

What about just `pokemon-showdown`?

**Comment by shryme** [comment]
It does not work too, the message about pokemon-showdown not being a command is shown!

**Comment by ascriptmaster** [comment]
It doesn't work because Command Prompt can't parse the shebang. I use Git Bash as my console program, which processes everything fine, so I never realized it was an issue despite working primarily from Windows

**Pull request closed without merging**
