### PR TITLE
Fix Rollout / Ice Ball target locking

### PR DESCRIPTION
**Pull request by littlefoot22**
#2367 

> If Rollout / Ice Ball targets an ally, the target of Rollout / Ice Ball in subsequent turns during the lock should be the ally

Taking a look at this bug and it seems to me this issue applies not only for locked moves targeting allies but any Pokemon not in the 0 spot of the active Pokemon array. 

It looks like this code(to me) does not really do anything ::
https://github.com/Zarel/Pokemon-Showdown/blob/master/sim/side.js#L385

It runs through runEven and just ends up returning true from this ::
https://github.com/Zarel/Pokemon-Showdown/blob/master/sim/battle.js#L772

This leds to this logic returning a 0 always(true - 1) ::
https://github.com/Zarel/Pokemon-Showdown/blob/master/sim/battle.js#L2402

I made this quick change to pull the mons last lastMoveTargetLoc directly from the object instead of running through runEvent if flagged as a locked move.

Any feedback would be much appreciated :D

### CODE REVIEW

**Comment by Zarel** [comment]
@Marty-D

**Comment by Marty-D** [comment]
Looks like a great solution to me! 👍 Though we probably don't need to keep anything that used the `LockMoveTarget` event anymore. As far as I can tell it was just two-turn moves here:
https://github.com/Zarel/Pokemon-Showdown/blob/82c792f82cff422d34b27ca51f39c3facff55d2e/data/statuses.js#L300-L302
https://github.com/Zarel/Pokemon-Showdown/blob/82c792f82cff422d34b27ca51f39c3facff55d2e/data/statuses.js#L311-L313

**Comment by littlefoot22** [comment]
@Marty-D thanks for the feedback, updated the PR with lines removed(thin that is what you were telling me to do?)

**Comment by Marty-D** [comment]
Two-turn moves are weird.

**Pull request merged**
