### PR TITLE
Allow locked users on same IP to PM eachother

### PR DESCRIPTION
**Pull request by panpawn**
This was suggested on the Smogon thread:

### CODE REVIEW

**Comment by Vacate** [comment]
We'll need to discuss this in staff before it's added.

**Comment by panpawn** [comment]
> We'll need to discuss this in staff before it's added.

That's understandable, no worries <\o.o/>

**Comment by Zarel** [comment]
I would disagree. Locked users should be able to challenge other locked users, though.

**Comment by panpawn** [comment]
Going to close this for now since it doesn't seem like a very-wanted change.

**Pull request closed without merging**
