### PR TITLE
Change Untiered to (DUU) for Doubles

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by KrisXV** [comment]
Bump

**Comment by Zarel** [comment]
See also: https://github.com/Zarel/Pokemon-Showdown-Client/pull/1230

**Comment by Zarel** [comment]
But anyway idk if it's actually better this way. It could be confusing especially since NFE is NFE.

**Comment by TheImmortal** [comment]
That's true. We could also display NFE as dash if you want since NFE isn't a real tier used anywhere at all.

**Comment by Zarel** [comment]
I think NFE Cup is becoming a UM soon.

**Comment by Zarel** [comment]
Let's punt this to Smogon

**Comment by TheImmortal** [comment]
> 
> 
> I think NFE Cup is becoming a UM soon.

Unlikely. NFE isn't used on Smogon Dex either.

**Comment by Zarel** [comment]
Okay, after consulting with Smogon leadership, we've decided:

- Untiered is now (ZU)
- NFE is now (NFE)

Please implement @KrisXV thanks!

**Comment by KrisXV** [comment]
Will do when I get home

**Comment by KrisXV** [comment]
does this apply to doubles Untiered as well? Im assuming yes for now.

**Comment by Zarel** [comment]
Um, use the paren of the lowest played tier for Doubles, yes.

**Comment by KrisXV** [comment]
(DUU) is already used for mega evolutions that are DUU by technicality, and (DNU) is not preferrable

**Comment by KrisXV** [comment]
I'm updating the client-side now

**Comment by Zarel** [comment]
Remember when "Untiered" was called "NU"? I remember. :|

**Comment by KrisXV** [comment]
yes, but people are more willing to complain now so it cant be that simple anymore sadly

**Comment by Marty-D** [comment]
> 
> 
> Okay, after consulting with Smogon leadership, we've decided:
> 
>     * Untiered is now (ZU)
> 
>     * NFE is now (NFE)
> 

When and where did this happen? I was under the impression we were going back to "(PU)" since the PU leader never endorsed the change to "Untiered" in the first place. I also already spent time supporting "Untiered" for ZU tier updates, so I'd prefer to stop being jerked around here. Please make a decision and end it.

**Comment by TheImmortal** [comment]
The original intention was consistency with Smogon as they started using Untiered. However, they have cleared it up that Untiered was just used a filler because something like (PU) wasn't possible. So, I believe they're going to switch to (PU) as chaos confirmed it is possible to have that on the Dex.

Pokemon that are not PU by usage should be (PU) and Pokemon not DUU by usage should be (DUU). I'm not 100% sold on the Teambuilder's use of "PU by technicality" but that's an argument for another time and place.

The other question is handling NFE. Do we lump them in with (PU)? Keep them as NFE? (NFE)? Just ``NFE`` is probably best. Would be an exception to following the Smogon Dex.

**Comment by Zarel** [comment]
Can you guys like stop overruling me?

**Comment by Zarel** [comment]
No one objected to `(ZU)` when I proposed it but I don't _mind_ `(PU)`, but I haven't even heard anyone object to `(NFE)` so it's weird that you'd overrule me on that, too.

**Comment by Zarel** [comment]
But either way, you shouldn't be merging a pull request that does the opposite of what I asked for, without even waiting for my approval.

**Comment by TheImmortal** [comment]
(NFE) is unnecessary. The whole point of the parentheses here is to separate Pokémon from the tier based on usage m. They should either be (PU) or just NFE as they always have been.

**Pull request merged**
