### PR TITLE
Add a better help for /avatar

### PR DESCRIPTION
**Pull request by Bryan-0**

### CODE REVIEW

**Comment by Slayer95** [comment]
Do we want easter egg documentation?

**Comment by TheImmortal** [comment]
How is that better? They still don't know what number is what avatar.

**Comment by Bryan-0** [comment]
So, if they don't know the number the avatars menu should be ordered by 1 - 294, and that's a help because is telling them the numbers of all avatars that can be used by regular users. 

http://play.pokemonshowdown.com/sprites/trainers-ordered/

**Comment by SolarisFox** [comment]
I think we should go with Zarel's suggestion of having `/avatar` without a target open the avatar selection window, then update the help to say `/avatar` does that with your current help entry being a second line to explain that entering a number can switch to that avatar number if a user knows what the number is.

**Comment by Zarel** [comment]
Well, this change is good for now.

The change _I'm_ talking about is actually already implemented in `/avatars`, so we might want to do that instead.

**Pull request merged**
