### PR TITLE
Properly handle ghost connections

### PR DESCRIPTION
**Pull request by Kaiepi**
xhr-streaming connections were the only connections that were becoming
ghost connections. This sets a timeout of the SockJS heartbeat interval
plus one second to account for any delay in receiving the SockJS
heartbeat packet to close the connection if it has been inactive during
that time.

### CODE REVIEW

**Comment by Kaiepi** [comment]
Oops, this doesn't account for keepalive packets and just closes the connection after 5 seconds if no messages are sent. Let me fix this

**Comment by Kaiepi** [comment]
Fixed now

**Comment by Zarel** [comment]
Is this a thing that can be pullreqqed to SockJS?

**Comment by Zarel** [comment]
I would keep the old logger active just to see if this properly fixes it.

**Comment by Kaiepi** [comment]
Updated

**Pull request merged**
