### PR TITLE
Change starthunt separator to |.

### PR DESCRIPTION
**Pull request by xfix**
This frees "," to be used in hunt questions.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
The period at the end of the commit comment made me think that `|.` was the delimiter...

**Comment by TheImmortal** [comment]
Is that necessary? You don't need to use commas as grammar doesn't really matter in this. I'd rather keep it as it is because this is the standard for commands.

**Comment by xfix** [comment]
I figure it's not that much necessary now that https://xfix.github.io/scavengers/ exists (it's a huge, huge, hack however). Weebl (member of GP team as well, so this may have something to do with it) proposed this change in Scavengers room staff PM, and it was agreed on by the staff, because not being to use comma sometimes is an annoyance requiring rewritting an entire question.

Consistency is important, I agree, but here the enforcal of consistency makes things more annoying. I'm aware that Showdown commands are using colons. The difference however is that /starthunt (and /startofficialhunt) unlike literally every other command accepts plain text as non-last argument.

**Comment by TheImmortal** [comment]
Looking at change gave me an idea. How about keep `,` as the default (meaning in help and such) but give priority to `|`. That way if there is a rare question with a comma, the staff can use the pipe.

So you just need to change one line, line 37, to `var targets = (target.indexOf('|') > -1) ? target.split('|') : target.split(',');`

**Comment by xfix** [comment]
@TheImmortal I don't see why not, done.

**Pull request merged**
