### PR TITLE
Cancel searches when user logs out

### PR DESCRIPTION
**Pull request by sirDonovan**
Prevents rated battles on guest accounts

Related: http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-208#post-6153948

### CODE REVIEW

**Comment by kotarou3** [comment]
Technically it's still not prevented, but it stops guest ladderers being matched with people high up on the ladder

**Comment by Slayer95** [comment]
Well, the user <code>mmrCache</code> needs to be cleaned or they will be matched with them anyway.

**Comment by Zarel** [comment]
I thought I already fixed this?

**Comment by sirDonovan** [comment]
You fixed changing names while searching, but not remaining on a guest account after logging out.

**Comment by Zarel** [comment]
Remaining on a guest account is changing names to a guest while searching. Maybe I missed that, though, but this isn't the right way to fix that if that's the case.

**Comment by sirDonovan** [comment]
It is changing names, but unless a new one is chosen, <code>resetName</code> is the only user function that is called.

**Comment by Zarel** [comment]
Yeah, this should be fixed a different way.

**Comment by Zarel** [comment]
Done in 736166035f

**Comment by Zarel** [comment]
You were closer than I thought, but you were missing something.

**Pull request closed without merging**
