### PR TITLE
Allow staff room voices to ignore help tickets

### PR DESCRIPTION
**Pull request by AustinXII**
even though the functionality apparently doesn't work, this would still be useful in the future.

### CODE REVIEW

**Comment by Zarel** [comment]
...why are staff roomvoices notified of help tickets in the first place?

I'm also not sure a PR that doesn't do the thing it says it does is all that useful.

**Comment by xfix** [comment]
Staff roomvoices shouldn't be notified about the tickets, unless the code is buggy.

**Comment by TheJetOU** [comment]
It seems like they shouldn't be notified (https://github.com/Zarel/Pokemon-Showdown/blob/master/server/chat-plugins/helptickets.js#L298 and https://github.com/Zarel/Pokemon-Showdown/blob/master/server/chat-plugins/helptickets.js#L377)? 

Maybe something is wrong with the permission system that makes it think Staff room voices can mute?

**Comment by AustinXII** [comment]
Not showing help tickets to voices seems like the best route

**Pull request closed without merging**
