### PR TITLE
Add BH Viability Rankings to /om bh

### PR DESCRIPTION
**Pull request by ABrambleNinja**

### CODE REVIEW

**Comment by TheImmortal** [comment]
One commit please. Squash it.

**Comment by ABrambleNinja** [comment]
Sorry I'm new to git, I'm not sure exactly how to do that. I'll close this pull and submit a new one I guess.

**Comment by Zarel** [comment]
That is not what "squash" means.

**Comment by TheImmortal** [comment]
I did it @ABrambleNinja 5cd927d023df236e62b303597a31ec572a4655fb

**Pull request closed without merging**
