### PR TITLE
Random Battle: Improve Gyarados

### PR DESCRIPTION
**Pull request by ascriptmaster**
Rest and Sleep Talk are very uncommon on Gyarados. Removing them allows
for a higher chance of using Gyarados' most popular set, Dragon Dance +
Bounce with Flyinium Z.

### CODE REVIEW

**Comment by TheImmortal** [comment]
What do you suggest for gen 6?

**Comment by ascriptmaster** [comment]
No clue because I don't know the gen 6 usage stats.

**Comment by ascriptmaster** [comment]
Rest had a 12% usage on Gyarados in Gen 6 (October 2016, a month before Gen 7) so I don't think Gen 6 needs to be changed. The Z-Crystal was a pretty big factor in DD + Bounce + Waterfall being a popular set, I suppose.

**Comment by ascriptmaster** [comment]
@TheImmortal still waiting for response

**Comment by ascriptmaster** [comment]
Still waiting

**Comment by TheImmortal** [comment]
Sorry, I was occupied last week and couldn't look into it.

**Pull request merged**
