### PR TITLE
Ban impossible Mamoswine sets.

### LINKED ISSUE #2249: Sylveon and Mamoswine can inherit too many moves from their pre-evolutions
Eevee (to Sylveon) and Piloswine both evolve by knowing a certain move (any Fairy-type move and Ancient Power, respectively). This means they should only be able to pass on three other moves. However, this is not implemented in Pokémon Showdown.

Relevant moves for Mamoswine are Tackle, Ice Shard, Flail, Amnesia and Fury Attack. Relevant moves for Sylveon are Refresh, Bite, Growl, Take Down, Double-Edge, Trump Card, Baton Pass. If the three other moveslots are filled, then only one of Covet and Baby-Doll Eyes should be inherited.

Theoretically, this could also apply to Ambipom, Lickilicky, Mr. Mime, Sudowoodo, Tangrowth and Yanmega, however, these Pokémon all have fewer than four moves exclusive to pre-evolutions.

### PR DESCRIPTION
**Pull request by jakobw**
Fixes #2249

### CODE REVIEW

**Comment by Slayer95** [comment]
This should go in the ``Pokemon`` ruleset.

**Comment by jakobw** [comment]
So I should add a check to the `Pokemon` ruleset whether `set.species` is Mamoswine, `this.gen` is lower than 6 and if it's this specific move set and then raise the problem explicitly? Is that really cleaner than banning it for the formats?

**Comment by Slayer95** [comment]
Yes, because this is not a ban. Have you seen the error message when you try to use that Mamoswine set in your current proposal?

You don't need to check ``this.gen`` if you add the check to ``mods/gen5/rulesets.js``

**Comment by Zarel** [comment]
We might want to reserve a section of the validator itself for hardcoded stuff like this.

**Comment by jakobw** [comment]
I updated my solution according to @Slayer95's suggestion!

**Comment by Rhythms88** [comment]
Wait; shouldn't this have the serial comma after "Ice Shard"? Doesn't matter to much but iirc that's what all of PS runs off of.

**Comment by ascriptmaster** [comment]
This is an old pull request from before we made that style change.

**Comment by Rhythms88** [comment]
Oh, my bad. Didn't see the date of last post.

**Comment by Zarel** [comment]
This probably won't be the approach we go with in the end. I'm going to consolidate these issues in #2287.

**Pull request closed without merging**
