### PR TITLE
Bug Bite and Pluck should only activate Belch or Cheek Pouch for edible Berries

### PR DESCRIPTION
**Pull request by urkerab**
By setting the `onEat` of inedible berries to `false`, we can arrange to stop Belch and Cheek Pouch from activating. For the other berries, I don't know whether it's better for `onEat` to be `true` or `function () { }`, so I can remove those changes if desired.

### CODE REVIEW

**Comment by Marty-D** [comment]
This looks like a fine solution, but it only works for Belch. Cheek Pouch only activates if the Berry eaten actually does something for you at the time. So it doesn't activate when you Bug Bite, say, a Yache Berry, or a Pecha Berry when you're not poisoned, or a Petaya Berry when you're already at +6 Special Attack, etc. ("etc" here being undetermined, hence this bug's place in the 'research needed' section.)

**Comment by urkerab** [comment]
OK, so this still doesn't really fix Cheek Pouch, but it makes it so that the fix for Cheek Pouch (which is to make `onEat` return the appropriate value (research needed)) won't affect Belch.

**Comment by Marty-D** [comment]
Looking good, can you apply the same fix to Fling as well?

**Comment by urkerab** [comment]
Like this?

**Comment by Marty-D** [comment]
I still have some research to do regarding the next step(s), but this is a good start! :+1:

**Pull request merged**
