### PR TITLE
Bold tag to strong tag refactor

### PR DESCRIPTION
**Pull request by DieterReinert**

### CODE REVIEW

**Comment by xfix** [comment]
I want to point out that `<b>` is a perfectly valid HTML element, it has its own semantic meaning (which is different to `<strong>`). I have seen advice many times to replace `<b>` with `<strong>`, however blindly changing this is pointless - if it would be that easy, `<strong>` probably would end up deprecated as it means the same thing as `<b>` (which it doesn't). Don't follow whatever HTML purists say, because I saw nightmare stuff like simulating tables using lists, when a table in question was a perfectly fine data table.

For instance, in this line:

```javascript
this.sendReplyBox("<b>This tournament's banlist:</b><br />" + Chat.escapeHTML(tournament.banlist.join(', ')));
```

`<b>` is better semantically than `<strong>`. Feel free to read HTML5 specification.

As `<strong>` uses more bytes than `<b>` (but in the end it probably won't matter due to TCP packet lengths), I'm opposed to merging this, but at the same time, I'm aware that merging this will change absolutely nothing in Showdown, as Showdown needs deeper changes than this to be accessible for screen readers users.

**Comment by xfix** [comment]
That said, I suppose I'm willing to support this if you change this pull request to only change broadcasts (broadcasts probably should have `<strong>`, but it's not that big of a deal). I still don't see much point in it, but hey :smile:, the first step in contributing is important.

**Comment by Zarel** [comment]
I believe all uses of `<b>` in PS code are to draw attention to them, which makes `<strong>` appropriate.

Italics have a lot of meanings in English, but basically all uses of bold fit `<strong>`. I'd normally only use `<i>` and `<b>` in PS situations.

On the other hand, it's true that if basically all uses of bold should be `<strong>`, semantically, it's not saying anything over `<b>`. Which I kind of agree. Situations where the bolding is entirely non-semantic can be handled with CSS (and `<span>`). Otherwise, it might be better to just use `<b>` and `<i>` (which are shorter and more readable) and ignore the semantic bold/italic elements?

**Comment by Zarel** [comment]
I give up, I'm going straight to the spec:

> The `<em>` element represents stress emphasis of its contents.

> The `<strong>` element represents strong importance, seriousness, or urgency for its contents.

> The `<i>` element represents a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term, an idiomatic phrase from another language, transliteration, a thought, or a ship name in Western texts.

> The `<b>` element represents a span of text to which attention is being drawn for utilitarian purposes without conveying any extra importance and with no implication of an alternate voice or mood, such as key words in a document abstract, product names in a review, actionable words in interactive text-driven software, or an article lede.

In other words, `<b>` and `<i>` cover a lot of situations where it would be grammatically appropriate to use bold or italics in English text, except for emphasis, which is covered by `<em>` and `<strong>`.

Which I think is... annoying and unnecessary. A screen reader will most likely treat `<b>` and `<strong>` pretty similarly, ditto `<i>` and `<em>`, so it's not like it's an accessibility concern. It's mostly for I guess scrapers? But scrapers trying to determine semantic meaning are going to be pretty stymied by how misused these four tags are in general, so honestly I'm still thinking we should just use `<b>` and `<i>` for everything.

I could maybe be persuaded to keep `<strong>` for inline headings, like the spec says, I guess...

**Comment by Zarel** [comment]
If we were to keep `<strong>` for inline headings, we'd have to manually review each usage of it, and there are a lot of places where it's arguable. Like,

`Server version: <b>0.10.2</b>`

Is this the important part of a heading, like the spec says, `<h1>Chapter 1: <strong>The Praxis</strong></h1>`? Or is this a keyword, like `<p>You enter a small room. Your <b>sword</b> glows brighter. A <b>rat</b> scurries past the corner wall.</p>`?

I think this is way too much mental effort to spend on something that has zero effect on accessibility, text parsability, or anything like that. So that's why I think we should just use `<b>` and `<i>` for everything. Thoughts?

**Comment by DieterReinert** [comment]
I strongly believe it's worth the mental effort, in the future we could think before placing a <b> or <strong> tag before pr'ing it. I will look over all the tags in this pr with someone (feel free to pm me on PS nickname : Alpha Ninja) or alone and see over that they're all used correctly.

**Comment by AustinXII** [comment]
@DieterReinert that seems like a lot of effort for something so unimportant. Using just <b> and <i> or even <strong> For everything seems fine imo

**Comment by Zarel** [comment]
@DieterReinert, if it were unambiguous, that's one thing, but if we have to have an argument every pullreq with a `<b>` or `<strong>` tag, that's excessive and very much not worth it, I think.

If you think it's worth all that effort, can you at least tell us why? Just saying "I strongly believe it's worth it" doesn't give us much to discuss.

**Comment by DieterReinert** [comment]
@Zarel strong is a logical state, and bold is a physical state. Logical states separate presentation from the content, and by doing so allow for it to be expressed in many ways. Maybe instead of creating and displaying some text as bold you want to make/give it red, or a different size, or underlined, or whatever. It makes more sense to change the presentational properties of strong than it does bold. This is because bold is a physical state; there is no separation of presentation and content, and making bold do anything other than bold text would be confusing and wrong and confusing. 

It is important to note that bold tag does have other uses, when one wants to draw attention without increasing importance.

**Comment by AustinXII** [comment]
@DieterReinert if "you" strongly believe this you shouldn't just copy and paste your reasoning why >:/ https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong

**Comment by DieterReinert** [comment]
@AustinXII  I'll post my own reasoning later on that was just to explain what strong can do

**Comment by DieterReinert** [comment]
The `<b>` tag (physical) and `<strong>` tag (logical) tag result in the same bold markup. However, I prefer to give meaning to the content, so if you want to make something important `<strong>` the better choice. The same for `<i>` and `<em>` that both make cursive markup, but where the text gets a different meaning by putting the emphasis on a part, you use `<em>` tag. However, where the text displays a different mood(example : a dream) then the surrounding text, the `<i>` tag is better. Also note that because the `<strong>`-element is a logical element it should render the element in the most appropriate manner for that browser/environment. Also the `<strong>` tag is more "abstract", so if side servers would like a different way of formatting important text they can override the `<strong>` tag. Example, I would like important text to be red instead of bold, makes more sense to override the `<strong>` tag than the `<bold>`tag.

**Comment by AustinXII** [comment]
@DieterReinert if you still have to copy + paste and then only kinda re-word it, I really don't think this is necessary.

**Comment by DieterReinert** [comment]
@AustinXII I didn't copy paste it from somewhere, it's just a general explanation. After that I gave my personal reasoning, I said something about side servers and I don't think you can copy paste that from somewhere.

**Comment by Zarel** [comment]
Yes, I'm aware of those differences.

The problem is, your MDN quote directly contradicts the spec, which says that both are logical states that do subtly different but overlapping things. So does your later comment.

The other problem is, we might, for instance, at some point, say "look at the bold text". And then at that point, it won't make sense if the text is red instead of bold.

**Comment by Zarel** [comment]
I guess if there are no further comments, I'm closing.

**Pull request closed without merging**
