### PR TITLE
Fix a crash in Users#destroy

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Slayer95** [comment]
In theory, users shouldn't be destroyed if games are active.

The issue that would be fixed by this looks like a desync. Does it happen with any of main's chat plugins?

**Comment by panpawn** [comment]
I think what triggered this on main was when it was pruning an inactive user whose user object was about to expire, but this got caught and crashed.

**Comment by panpawn** [comment]
Although, now that you mention it, [this code](https://github.com/Zarel/Pokemon-Showdown/blob/master/chat-plugins/trivia.js#L231-L243) does look suspicious to me...

**Comment by panpawn** [comment]
@Morfent - can you chime in?

**Comment by Morfent** [comment]
`Trivia#prototype#kickedUsers` is just a set of userids, not the users themselves. Apart from that it functions the same as `RoomGame#prototype#destroy`

**Comment by Morfent** [comment]
Adding something like `user.userid.slice(0)` to `Trivia#prototype#kickedUsers` instead of a direct reference to `user.userid` may or may not help, though

**Comment by Morfent** [comment]
...which it turns out not to

**Comment by panpawn** [comment]
>In theory, users shouldn't be destroyed if games are active.

What?  They are automatically destroyed by ``Users#pruneInactive``, regardless of if games are active (or not, which will crash in certain instances)

**Comment by Slayer95** [comment]
That's true, but ``User`` instances shouldn't have non-existent games registered: the games should be delisted on ``RoomGamePlayer#destroy``.

This might be an issue with renaming, which would manifest with

Set ``Config.inactiveuserthreshold = 500``
1. Create a game in a room, with ``allowRenames: true``.
2. Make a user join the room.
3. Make the user join the game.
4. (Optional) Make the user leave the room.
5. End the game.
6. Disconnect the user from the server.

**Pull request closed without merging**
