### PR TITLE
Add Ultra Spooky Cup

### PR DESCRIPTION
**Pull request by KrisXV**
@TheImmortal https://www.smogon.com/forums/threads/ultra-spooky-cup-ghost-shiny-mimikyu-as-entry-gift.3642514/

@Marty-D (because there was some miscommunication about if `requirePlus` is needed or not)

### CODE REVIEW

**Comment by TheImmortal** [comment]
Why is there a function to add bans instead of placing the bans on the banlist...?

**Comment by Zarel** [comment]
It's a whitelist.

I forgot if my latest refactor of the ruleset system actually supports whitelists yet.

**Comment by TheImmortal** [comment]
Oops. I don't know why I read it as a banlist.

Anyway, can't you check ``template.baseSpecies`` instead of having all those forms?

**Comment by Marty-D** [comment]
Yeah, Pokemon transferred from past gens are allowed, the English PGL is just bad at getting their facts straight when copying off the Japanese one.

@TheImmortal the valid Pokemon for this competition is wildly unorthodox. You'll notice Lycanroc Midnight Form is allowed but neither of the other two Lycanroc, etc. "National Pokédex No. 001 through 807 are eligible, excluding some Legendary Pokémon, most Mythical Pokémon, and all Pokémon that are not spooky" indeed.

**Pull request merged**
