### PR TITLE
Fix stomping tantrum vs. only Protect

### PR DESCRIPTION
**Pull request by MacChaeger**
This works, though I don't know if it's what @Zarel had in mind...

p.s. no idea why the old build even passed, seeing as the original test i wrote was actually wrong.......

### CODE REVIEW

**Comment by mathfreak231** [comment]
i explained it in the other PR, manaphy or w/e it was was just hitting a double Protect, meaning base power wasnt being calculated in the first place

**Comment by MacChaeger** [comment]
No sorry I meant the partial protect test. It should have been failing from the start because Precipice Blades has 120 BP, not 150.

**Comment by mathfreak231** [comment]
same thing, it wasnt hitting either of them

**Comment by MacChaeger** [comment]
oh, right
i think I added it this time because at some point i broke protect lol

**Comment by Zarel** [comment]
Did you ever post your test, @mathfreak231? If you did, that might help a lot.

**Comment by mathfreak231** [comment]
chaeger changed the test so now it is correct now, I did basically the same thing as him (change protect t2 to a dummy move)

**Comment by Zarel** [comment]
Shouldn't we have both tests? Attacking into double Protect, and attacking into a single Protect?

**Comment by MacChaeger** [comment]
Oh, uh, “Manaphy was hitting a double protect” means that the Pokémon using protect in the singles test was getting two successful Protects in a row when it shouldn’t. To my knowledge, no one other than you has thought to write a doubles test where an attack is blocked by two simultaneous Protects, but I can see why that would be a good thing to have.

**Comment by Zarel** [comment]
Oh! In which case you can add that test at your leisure.

**Pull request merged**
