### PR TITLE
Gen5/6: Fix Endure compatibility

### PR DESCRIPTION
**Pull request by xJoelituh**
I just noticed that you can use Pokemon with the Hidden Ability and Endure.
Endure was a Move Tutor in Emerald and after a TM in Gen 4. But after that, the only way to get it was breeding and level up.

And easy example is Blastoise or Charizard, both learned Endure back in Gen 4, but they can't have now HA with Endure because of Dream World/Gen 6 Breeding

The problem is, the list of Pokemon that learns Endure by leveling up/breeding is a bit extensive, so might take a while

( http://bulbapedia.bulbagarden.net/wiki/Endure_(move) http://www.serebii.net/attackdex-xy/endure.shtml )

### CODE REVIEW

**Comment by sirDonovan** [comment]
Did you mean to open an issue or choose the wrong branch?

**Comment by Slayer95** [comment]
We don't trust Bulbapedia nor Serebii :|

**Comment by TheImmortal** [comment]
It's a gen six tutor move.

**Comment by QuiteQuiet** [comment]
No matter where I look, endure isn't listed as a tutor move @TheImortal. The only mentions of endure being a tutor move is from before ORAS was even released.

http://pokemondb.net/mechanics/move-tutors#tutor-oras
https://www.youtube.com/watch?v=pLNjTGslfnQ (It doesn't get much closer to the source than this :| )

**Comment by xJoelituh** [comment]
@sirDonovan Yes, I missclicked 
@TheImmortal There isn't an Endure tutor in ORAS, I tried to find it and there is no where 
Here also are the Move Tutor
http://www.smogon.com/forums/threads/a-quickstart-guide-to-oras-breeding-training.3522921/

**Pull request closed without merging**
