### PR TITLE
Random Battle: Fix Adaptability checks for Pokemon w/ 2 types

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by TheImmortal** [comment]
There's no need to check it if it has one type. We already have STAB checks for that.

Just make it ```if (((hasAbility['Adaptability'] && template.types.length > 1 && !!counter[template.types[0]] && !!counter[template.types[1]])```

**Comment by TheImmortal** [comment]
(I updated my comment because he had a mistake)

**Comment by ascriptmaster** [comment]
Darn I just left the office after making that change according to yours and won't have computer access for at least 4 hours

**Comment by TheImmortal** [comment]
You did it wrong... I guess you didn't copy/paste.

**Pull request closed without merging**
