### PR TITLE
Random Battle: Update Z Moves

### PR DESCRIPTION
**Pull request by MacChaeger**
This allows for the possibility of a Z Move on anything that would have otherwise held a Life Orb, Expert Belt, or Assault Vest (unless the pokemon's ability relies on one of those items).

### CODE REVIEW

**Comment by TheImmortal** [comment]
Majority of the time Z-Moves are not better than standard items. This is completely unnecessary and just makes Random Battle worse. I will add Z-Moves as I deem necessary - such as for error sets like SolarBeam without Sun, which can get Grassium Z.

**Comment by MacChaeger** [comment]
It's kinda hard to trust that you understand when Z Moves are appropriate when you suggest running Grassium Z Solar Beam on a presumed Grass-type instead of just replacing Solar Beam with something useful in the first place. According to Smogon's own analyses, the only time Z Solar Beam is ever used is on Fire-type Pokemon that don't even expect to have sun in the first place, with exceptions of Sunflora, which pretty much needs sun to function at all, and Venusaur. In Venusaur's case, Solar Beam isn't even slashed in the recommended set and is instead mentioned as a possible alternative. In neither case is Grassium Z recommended as an option when you forgot to add sun to your team, whoops.

**Comment by TheImmortal** [comment]
I never suggested running that. I said if the rng screws you and you somehow got stuck with Solar Beam without any Sun then you should get Grassium Z so as to not have a completely useless mind move.

**Comment by MacChaeger** [comment]
I'm saying that you shouldn't even get stuck with Solar Beam and no sun. If you know that you don't have sun, don't run Solar Beam unless you were planning on it being a Z Move anyway. Grassium Z is the wrong way to fix that.

**Comment by TheImmortal** [comment]
Thanks for your opinion but PS staff thought it was a good idea. Although I make the final call, PS staff discuss Random Battle changes based on their on experience and input from the community. In this particular case, the problem was Pyroar getting Scarf Solar Beam, obviously without Sun. The Grassium Z and Power Herb ideas were thrown out by others, before me, and I implemented it. Off course if it were possible to make the RNG better then we'll do that. This is just a worst case scenario.

Anyway, you should post your suggestions in the public Random Battle thread rather than just trying to make major changes yourself. This gauges the community's liking, as well as allows PS staff to see it and discuss it in our private thread.

**Pull request closed without merging**
