### PR TITLE
Use `declare let` in globals.ts

### PR DESCRIPTION
**Pull request by xfix**
Should fix LGTM warnings.

### CODE REVIEW

**Comment by Zarel** [comment]
This pull request **fixes 7 alerts** when merging 6d3e7245cba6198d6eafc672ce464e1a239a7673 into 5d7d3177431e52f3a9b0f3ed9c4bc0fec1744c11 - [view on LGTM.com](https://lgtm.com/projects/g/Zarel/Pokemon-Showdown/rev/pr-7d880cc609faf7bd3de1bd57f2366aa151cc45d2)

**fixed alerts:**

* 7 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Zarel** [comment]
Neat! Unfortunately, we seem to have a whole new world of TypeScript errors due to the change.

**Comment by Zarel** [comment]
Apparently `globals.ts` previously just wasn't doing anything?

**Comment by sirDonovan** [comment]
Now <code>import()</code> is getting the types of the files while before <code>require()</code> just resolved to <code>any</code>.

**Comment by DubbleClick** [comment]
Implemented in #5139.
Can't use declare because the variable will not be assigned anywhere else, can't use import because it returns an asnyc Promise.  Would have to do a whole bunch of changes to the code and wrap usages in asnyc/await blocks, so I refrained from that and just took type hints from the import while using standard require.

**Comment by Zarel** [comment]
Implemented in ffdcff3abcbd67c3

**Comment by Zarel** [comment]
(Thanks, @DubbleClick for reminding me to do this, and also for the approach I ended up using.)

**Pull request closed without merging**
