### PR TITLE
Searing Shot and Water Shuriken are viable

### PR DESCRIPTION
**Pull request by KrisXV**
so is Heart Stamp

### CODE REVIEW

**Comment by TheImmortal** [comment]
Water Shuriken is only viable on Ash-Greninja. Heart Stamp is only viable on Jirachi.

**Comment by Zarel** [comment]
That's not what `isViable` means in moves.js, @TheImmortal :|

**Comment by TheImmortal** [comment]
Then why do you have exceptions in the client? If Heart Stamp is viable, so should Iron Tail and several other moves. Bar Jirachi, Heart Stamps is **not** viable on anything that learns it. Heart Stamp and Water Shuriken should be added to the client exceptions, not be listed as viable for everything. :|

**Comment by Zarel** [comment]
Iron Tail should also be `isViable` probably.

**Comment by Zarel** [comment]
Water Shuriken is also usable on regular Greninja. I've seen Torrent Greninja use it in BSS.

**Comment by TheImmortal** [comment]
That doesn't answer anything. If ``isViable`` is supposed to mean moves that are viable on even one Pokemon, that you're missing a shitton of viable tags. It definitely should not mean that, and it never did mean that.

**Comment by Zarel** [comment]
(And, more importantly, Water Shuriken is not outclassed or near-outclassed by anything, which is the "Usable" cutoff.)

**Comment by TheImmortal** [comment]
You can have Greninja, I don't have an issue. Heart Stamp is the definition of "Usually useless" though. It's only purpose is to flinch with Jirachi's Serene Grace.

**Comment by Zarel** [comment]
`isViable` is supposed to mark moves that are generally not outclassed.

Water Shuriken qualifies, because it doesn't have serious overlap with Aqua Jet.

Heart Stamp qualifies, because it doesn't have serious overlap with Psycho Cut etc.

**Comment by TheImmortal** [comment]
Jynx/Jirachi/Miltank/Swoobat all learn Zen Headbutt.

**Pull request merged**
