### PR TITLE
README.md: Make instructions clearer

### PR DESCRIPTION
**Pull request by panpawn**
There is no "Save" button; this is referring to the "Fork" button.

### CODE REVIEW

**Comment by bumbadadabum** [comment]
First of all, I think this refers to cloning the repo, not per se forking it. Secondly, it's not even "next to the download zip button" anymore, so that should be changed too.

**Comment by Zarel** [comment]
Yeah, the button used to be labeled "Save" but is currently labeled "Clone or Download" -> "Open in Desktop".

**Comment by Zarel** [comment]
And while "Save" has been renamed "Open in Desktop", it's definitely still next to the Download ZIP button:

image

**Comment by bumbadadabum** [comment]
https://imgur.com/NP1VkYh

The button isn't there on linux lol

**Comment by Zarel** [comment]
That's because there's no GitHub Desktop on Linux; presumably anyone using Linux knows how to clone a repo using the command line.

**Comment by Slayer95** [comment]
That might not be the case for someone who doesn't know what ``man`` means, though :^)

**Pull request closed without merging**
