### PR TITLE
Add "bc" alias for blocking challenges.

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by SolarisFox** [comment]
I recommend also adding /unbc in hopes that if somebody sets /bc by mistake it will be more intuitive for how to undo it.

**Comment by Zarel** [comment]
I'm not sure I want to take up a two-letter in the namespace.

"blockchall" or "bchall"?

**Comment by xfix** [comment]
Is it fine now?

**Comment by Zarel** [comment]
Might as well add `blockchalls`.

**Comment by TheImmortal** [comment]
Those aren't really a big difference in length to blockchallenges. How about blockc and unblockc?

**Comment by Zarel** [comment]
`bch`?

**Comment by TheImmortal** [comment]
That works. So, I say no point in adding `blockchall` and `unblockchall`. `bch` and `uch` it is?

**Comment by Zarel** [comment]
`bch`, `unbch`

I'd still also like to add `blockchalls` and `unblockchalls`.

**Comment by xfix** [comment]
Done.

**Pull request merged**
