### PR TITLE
Remove lastCommand check after the command goes through

### PR DESCRIPTION
**Pull request by sparkychildcharlie**
This makes accidentally up-arrowing after using one of these commands less "lethal".  The user will have to go through the 2 layers again before the command executes.

### CODE REVIEW

**Comment by panpawn** [comment]
Maybe you should do ``user.lastCommand = '';`` instead?

**Comment by panpawn** [comment]
It should really be apart of a user's initial user object (``Users`` constructor) as ``''``, too - it's used in several commands, so I think that warrants it

**Comment by Zarel** [comment]
It should definitely be `lastCommand = ''`;

**Comment by sparkychildcharlie** [comment]
i changed setting it to ``''`` instead.

**Pull request merged**
