### PR TITLE
Rooms: don't poke the expire timer on join/leave

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
It's intentional to, though...

**Comment by panpawn** [comment]
I think what this is trying to accomplish is that join and leave messages aren't counted towards activity when it comes to automatically deleting inactive groupchats

**Comment by Zarel** [comment]
Yeah, join and leave messages previously weren't added to the roomlog at all.

**Comment by Zarel** [comment]
Anyway, this is fine, I don't mind groupchats suddenly lasting a lot longer.

**Pull request closed without merging**
