### PR TITLE
Add new CAP LC mon Voodoll

### PR DESCRIPTION
**Pull request by DeathlyPlays**
I was informed this one was not coded in yet, so I took it upon myself to code it

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
I had to delete the Digimon Project for now so this could occur

**Comment by DeathlyPlays** [comment]
@Zarel it's complete now and ready for review

**Comment by sirDonovan** [comment]
@DeathlyPlays you can work on separate branches to avoid having to delete other projects. You also should have just rebased this instead of closing it.

**Comment by DeathlyPlays** [comment]
Well its not ready for release apparently according to Heal, jas said I could do it

**Comment by panpawn** [comment]
Typically, it's easier if you don't do separate projects on your ``master`` branch

**Comment by DeathlyPlays** [comment]
I have the Digimon Showdown project backed up

**Comment by Zarel** [comment]
You should really learn how to branch in Git, it's not too hard. Go through a Git tutorial, those usually teach you about the history DAG.

You should also rebase to remove all the Digimon Showdown references.

**Comment by panpawn** [comment]
Also, you can reopen this and fix it

**Pull request closed without merging**
