### PR TITLE
Re-add Evasion clause to Ubers

### PR DESCRIPTION
**Pull request by WreckDra**
http://www.smogon.com/forums/threads/read-post-44-evasion-discussion-thread.3538869/page-2#post-6237148

### CODE REVIEW

**Comment by Slayer95** [comment]
There has not been any public announcement of this sort.

**Comment by Rhythms88** [comment]
It literally says so in that post (which IS public) though

**Comment by Slayer95** [comment]
Tiering policy requires bans to be broadcast in social networks before any pull request is opened here.

**Comment by Rhythms88** [comment]
That makes more sense; thanks for clarifying.

**Pull request closed without merging**
