### PR TITLE
Prevent guests from joining lotteries.

### PR DESCRIPTION
**Pull request by SilverTactic**

### CODE REVIEW

**Comment by Joimer** [comment]
You missed the semicolon on the line. This fails. Please, fix that.

**Comment by SilverTactic** [comment]
Done.

**Comment by Slayer95** [comment]
This also prevents users in accounts that are not Guest, but have no password, from joining the lottery.
It doesn't seem like a bad change, but it's inconsistent with the commit message, as well as the error message on join attempt.

**Comment by TheImmortal** [comment]
@Slayer95 aacc51ac02158e336c91857737234dac18d79859

**Pull request merged**
