### PR TITLE
Trivia: Update levenshtein function

### PR DESCRIPTION
**Pull request by CheeseMuffin**

### CODE REVIEW

**Comment by CheeseMuffin** [comment]
oh  bump on this

**Comment by Zarel** [comment]
lol, yes, this should definitely happen

**Comment by Zarel** [comment]
Also, apparently we don't have an active maintainer for Trivia? Do you want that job?

**Comment by CheeseMuffin** [comment]
yea Morfent had told me a while back he wasn't as interested so I can, though seems there isn't too much to do with it nowadays

**Comment by Zarel** [comment]
We should maybe add a dynamic Levenshtein comparison, incidentally.

**Pull request merged**
