### PR TITLE
Refactor random booleans into randomChance function

### PR DESCRIPTION
**Pull request by strager**
Often, you just need a random boolean. Throughout Pokemon Showdown's code, there are many creative ways of requesting random booleans. For example:

```js
if (this.random(10) < 3) {
if (this.isWeather(['sunnyday', 'desolateland']) || this.random(2) === 0) {
let shiny = !this.random(1024);
if (uberCount > 1 && this.random(5) >= 1) continue;
if (!this.random(3)) ability = ability1.name;
} else if ((ability === 'Iron Barbs' || ability === 'Rough Skin') && this.random(2)) {
if (typeof secondary.chance === 'undefined' || this.random(256) <= effectChance) {
if (accuracy !== true && this.random(256) > accuracy) {
```

Enable these methods to converge by introducing the PRNG#randomChance function. It accepts a probability and returns true with that probability.

Notes for reviewers:

* Commits are separated to improve archaeology and bug-finding. For example, the changes made in 8612729 and 6e3ffaf should be behaviour-preserving, but the changes made in 4f3059e possibly affect behaviour. Commit 8612729 contains scripted code modifications which should be safe, but commits 6e3ffaf and 4f3059e were made by hand and and are prone to human error. I recommend rebasing or merging these commits as-is and *not* squashing them into a single commit.

### CODE REVIEW

**Comment by Slayer95** [comment]
Also, this introduces some tests that are by-design flaky. Is there some way to mark them as such in Mocha.js and maybe keep long-term track of them in Travis CI?

**Comment by Zarel** [comment]
I don't like `flipCoin` very much, maybe `randomChance` or something?

**Comment by Zarel** [comment]
Also `flipCoin(1 / 2)` is easier to read than `flipCoin(1, 2)`, so assuming there's some way to implement that while preserving functionality (I think there is), that's a pretty good idea

**Comment by strager** [comment]
> I'd suggest renaming `flipCoin` => `chance`, so that `this.chance(1, 1000)` reads as "*do with a chance of 1 in 1000*".

> I don't like `flipCoin` very much as a name, maybe `randomChance` or something?

Yeah, I think `randomChance` is a better name! I'll make adjustments.

> Also `flipCoin(1 / 2)` is easier to read than `flipCoin(1, 2)`

I agree.

Unfortunately, floating point division like that leads to inaccuracies. 1/3 is inexact, for example.

Also, it's impossible to refactor existing calls to random(x) with that API while preserving cartridge RNG behaviour.

> We strive to keep fidelity to the cartridge RNG behaviour, so we absolutely need the `!flipCoin()` pattern.

Alright. I'll undo those changes.

Is `!flipCoin()` needed for random-teams.js?

**Comment by strager** [comment]
I made some changes:

* Rename flipCoin to randomChance.
* Make non-behaviour-preserving changes only to the random team generator.

**Comment by Zarel** [comment]
> Unfortunately, floating point division like that leads to inaccuracies. 1/3 is inexact, for example.

I know, but in theory these inaccuracies don't need to matter. In other words, 1/3 may be inexact, but it's still more precision than the actual in-game RNG does, so as long as we can still go from the inexact value to the value used in-game, the inexactness doesn't need to matter.

**Comment by Zarel** [comment]
Hm, okay, but I'd probably want to simplify a few common calls:

`randomChance(1, 2)` => `randomChance()`

`randomChance(1, n)` => `randomChance(n)`

**Comment by Zarel** [comment]
(Feel free to make a new pullreq for those changes)

**Pull request merged**
