### PR TITLE
Detailed battle logs

### PR DESCRIPTION
**Pull request by Slayer95**
<strike>- Crashlogger now reports more data of the last request. In particular, the moves available for active Pokémon will now be logged, so that meaningful knowledge can be gained from ``move 2`` etc choice logs.</strike>
- Replays will now log players decision, and starting battle seed. This should be extremely useful for handling bug reports. Requires https://github.com/Slayer95/Pokemon-Showdown-Client/blob/7cda6afcd2bc3dc991aa52bad36bf88ec7640ce7/js/battle.js

### CODE REVIEW

**Comment by Zarel** [comment]
Does `.requestData` actually need to be cached?

**Comment by Zarel** [comment]
Seems like the architecture should just be fixed not to need to get it more than once.

**Comment by Slayer95** [comment]
In common conditions it's only needed once.

However, there is a variety of conditions under which we may need the request again. One of these is precisely reporting the last request when a battle crashes. It would be a pity for the battle to crash again if we then ran ``getRequestData()`` instead of safely retrieving a cached value.

Other circumstances include players' cancelling their decisions
In the future, quick access to the last request could even be used to synchronize battle request among multiple connections, regarding moves that turn out to be disabled / pokémon that turn out to be trapped, or [far future] decisions already made.

**Comment by Slayer95** [comment]
Looks like you are taking this over.
Anyway, I just pushed a fix for the only issue i have come to know (choices not being reset for U-turn and the like).

**Comment by Zarel** [comment]
> Other circumstances include players' cancelling their decisions

In theory, the main process should have it cached, not the battle process, but your other points are fair.

**Comment by Slayer95** [comment]
Fixed the tree and restricted this to seeds + decisions in replays.
Maybe maybe we'll get the feature this year. *crosses fingers*

**Comment by Zarel** [comment]
While I'm on leave? Meh, poke in a week so I can code review properly.

**Comment by Slayer95** [comment]
It's just that another bug report that would have been figured out instantly with this popped up today.
Will remind you once you are available though!

**Pull request merged**
