### PR TITLE
Update recent Punishments changes

### PR DESCRIPTION
**Pull request by panpawn**
-add a trailing line back to the end of punishments.js
-make the new Punishments monitor have a Config option to disable it
-fix mute commands (Chat#toDurationString was broken)

### CODE REVIEW

**Comment by bumbadadabum** [comment]
I'll add a config option myself.

**Comment by panpawn** [comment]
If you haven't already yet, then why did you close this?

**Comment by panpawn** [comment]
also ugh, I just force pushed to this not realizing it was already closed, so I guess there is no saving reusing this now.

**Comment by panpawn** [comment]
24 hours later, and still no ``Config`` option to disable this.

Why was this closed?

**Pull request closed without merging**
