### PR TITLE
Fix: Gen 2 Present

### PR DESCRIPTION
**Pull request by Enigami**
This 'fixes' Present in Gen 2 to function as it should in link battles, replacing the attacker's Attack Stat with 10 and Level Stat with the defender's secondary type index, and the defender's Defense Stat with the attacker's secondary type index.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks good to me. @Marty-D?

**Comment by Marty-D** [comment]
@Zarel, I'm good with this if you're good with the variable naming style. Seems out of place with the rest of the codebase, but not a deal-breaker for me.

**Comment by Zarel** [comment]
Oh, good point, but also an easy fix.

**Comment by Enigami** [comment]
Uh, you just screwed up the index code, their numbers aren't sequential, they were as I had listed them in my code. The damage of Present will be wrong with your changes

**Comment by Enigami** [comment]
Rock (5) skips to Bug (7), and Steel (9) skips to Fire (20). Present will be doing way less than it should right now

**Comment by Zarel** [comment]
Oh, I didn't notice. That'll have to be switched back, then.

**Pull request merged**
