### PR TITLE
Fix dependency installation on Windows

### PR DESCRIPTION
**Pull request by QuiteQuiet**
Closes #3397

### CODE REVIEW

**Comment by Zarel** [comment]
@Morfent

**Comment by Zarel** [comment]
Also, `Closes #3397` needs to be in the commit summary, not the pullreq overview.

**Comment by Zarel** [comment]
Also, considering Morfent didn't have this problem, this might even depend on the version of Windows...

**Comment by Morfent** [comment]
It does crash when I test, and should for all versions of Windows. [When I originally wrote the compatibility fix for this](https://github.com/Zarel/Pokemon-Showdown/pull/2889#discussion_r99810253) I included `shell: true` in the options for spawning this child process to deal with this, but neglected to check if it still worked or not after removing it.

Either way of preventing the script from crashing on `npm install` works.

**Comment by Zarel** [comment]
Maybe we should instead reinclude `shell: true` and document why it's needed?

**Comment by Zarel** [comment]
Also you might just use `execSync` if you're going to use `shell: true`; more readable anyway.

**Comment by QuiteQuiet** [comment]
`child_process.execSync('npm install --production', {stdio: 'inherit'})` is probably the cleanest solution for resolving this, which will work on Windows assuming `npm` is properly in `PATH` (which it should be unless someone made a mistake during installation of Node)

**Comment by Zarel** [comment]
Can you explain what the 200k size limit is?

**Comment by Zarel** [comment]
Oh, it's the limit for the `stdio` output buffer. Yeah, that's not remotely a problem.

**Pull request merged**
