### PR TITLE
Dependant support: make sure that relative paths are resolved properly

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by Zarel** [comment]
Can you clarify what exactly this changes?

**Comment by Slayer95** [comment]
When a relative path is passed to a <code>fs</code> method, the base path is <code>process.cwd()</code>. Therefore, if someone calls <code>require('./Pokemon-Showdown/app.js')</code>, a lot of crashes would happen.

This changes it so that absolute paths are passed to <code>fs</code> methods.

**Comment by Zarel** [comment]
With `path.resolve`, do you still need the `./` at the beginning?

**Comment by Slayer95** [comment]
No, though I feel it conveys better the idea of "relative". Should I remove it to save some bytes or something?

**Comment by Zarel** [comment]
I think it's more readable without. I always thought the `./` was ugly.

**Comment by Slayer95** [comment]
Ok, updated

**Pull request merged**
