### PR TITLE
Add Join button to UNO declaration

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by KrisOnline** [comment]
It should say "Click here or type '/uno join' to join" imo

**Comment by panpawn** [comment]
plz no buttons that say "Click here"...

**Comment by panpawn** [comment]
I think just the "Join" button is the best UI choice here.

**Comment by AustinXII** [comment]
@panpawn uhm he already changed that way before you commented

**Comment by panpawn** [comment]
@AustinXII - I meant, no need to have the line under the button saying the command the button does.

**Comment by KrisOnline** [comment]
@panpawn there's really no harm in having both

**Comment by panpawn** [comment]
I'm not saying it is, I'm just saying I don't think that's a good UI is all.

**Pull request merged**
