### PR TITLE
Updateserver: Allow all admins to have access

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Slayer95** [comment]
This isn't really all that great unless the update automatically rolls back in case of merge conflicts, which is.... actually pretty complex to implement.

I gave it a try a couple of years ago and arrived to https://hastebin.com/zocuqojolo.js, but I ultimately abandoned it after finding out that
1. There were still Git-originated edge cases
2. It wasn't really cross-platform (mainly due to PowerShell treating stderr writes as actual execution errors)

IMO, the best way around that would be to use a specialized Git dependency like [NodeGit](https://github.com/nodegit/nodegit)

**Comment by panpawn** [comment]
Or, in the case of merge conflicts, it just makes it so that the hotpatch lock is enabled and it notifies Dev or something.

In theory, there shouldn't be uncommited code that would cause a merge conflict.  In practice, the code that is uncommited should be separated enough from whatever could possibly conflict with what's on the master branch.

**Comment by Slayer95** [comment]
Toggling the hotpatch lock sounds great for most situations, but it still leaves the server files in a bad state for the nowadays increasingly common case of a server crash.

**Comment by panpawn** [comment]
There could be a separate command, ``/serverreset [commit hash]``, that does ``git reset --HARD [commit hash]``.

**Comment by panpawn** [comment]
But yes, doing ``git rebase --abort`` does sound like a good idea. 👍

**Comment by Zarel** [comment]
Does `git rebase --abort` restore uncommitted code and staged code to their previous position?

**Comment by wgma00** [comment]
I thought ``git rebase --abort`` could only be used during an interactive rebase i.e. ``git rebase -i``. If you try to using it after a non-interactive rebase has been completed i.e. ``git rebase HEAD~1`` it responds with "No rebase in progress?".  If you want to undo a rebase you'd have to do what  panpawn suggested or play around with ``git checkout`` and ``git reflog`` to get to the commit point before the rebase (which I believe restores uncommitted/staged code).

**Comment by Slayer95** [comment]
> I thought git rebase --abort could only be used during an interactive rebase i.e. git rebase -i

That's not true. I avoid interactive rebases like the plague, and I still abort rebases every now and then.

Hard resets should be out of the question imo. They are way too risky for an automated task.

**Comment by Morfent** [comment]
I alias `REPO="origin master" git fetch $REPO && git rebase --merge $REPO` to `unfuckmyrepo` in `.zshrc` to handle merge conflicts. `git rebase --continue` after editing the files that conflict and running `git add` so the issues can be resolved. I don't see why admins who aren't devs should be in charge of updating the server if they're likely not capable of fixing potentially dangerous problems that can crop up. Asking a dev later isn't much more than a mitigation to a problem that doesn't need to happen in the first place, especially if `git rebase --abort` is being recommended so problems can be ignored and dealt with another time (despite it being able to prevent the server from being buggy longer than it should be).

I can understand why permitting more people to update the server can be appealing, but I just find it too risky to be worth it. Maybe I'm just paranoid though

**Comment by Slayer95** [comment]
I might have misunderstood what @wgma00 said about aborting rebases...
As it turns, out, ``git rebase --autostash`` can't be aborted with ``git rebase --abort`` if there is a failure in the stash reapply phase.

Autostash failure

**Comment by Zarel** [comment]
So what about if `git pull --rebase --autostash` fails? That's the important one.

**Comment by Slayer95** [comment]
We currently run ``git rebase --autostash`` in ``/updateserver``.

``git pull --rebase --autostash``, on the other hand, seems to have a variety of bugs even on bleeding edge Git releases, as suggested by https://stackoverflow.com/a/30209750. I have verified the fast-forward issue in my own setup: it creates the stash but it isn't applied at all after the pull.

**Comment by Morfent** [comment]
What if this could work like a queue? Admins who aren't devs could push updates to production, and if they have a merge conflict, they could be left to the devs to handle. That'd help keep the best of both worlds without the need to fight git

**Comment by wgma00** [comment]
Has this feature been requested by non-dev admins? I feel like the feature may go unused as they would trust the better judgement of dev-admins.

**Comment by panpawn** [comment]
The idea is that the server could get patched new code more frequently, and that they could consult any tech staff if the server is in a safe state to patch at any given time

**Comment by panpawn** [comment]
>What if this could work like a queue? Admins who aren't devs could push updates to production, and if they have a merge conflict, they could be pushed aside for the devs to handle later, so long as no more updates are pushed beforehand. That'd help keep the best of both worlds without the need to fight git to make it work, but even if it can still occasionally delay updates getting pushed to the server, it'd still be an improvement. I'm not saying to give up, but to take this gradually

I like this idea.  So, this could probably be merged as-is, and then explained to non-tech admins how this works?

**Comment by Zarel** [comment]
I still don't understand how you propose to make this not-dangerous.

**Comment by panpawn** [comment]
As in, security-wise, or with merge-conflicts? Can you elaborate?

**Comment by AustinXII** [comment]
I would assume dangerous to the server.

**Comment by panpawn** [comment]
That still doesn't answer my question @AustinXII

**Comment by Zarel** [comment]
With merge conflicts.

**Comment by AustinXII** [comment]
Oh sorry I meant that in an affecting the server kind of way (breaking the server directly) not the users (breaking into accounts and then server subsequently)

**Comment by Zarel** [comment]
> As it turns, out, ``git rebase --autostash`` can't be aborted with ``git rebase --abort`` if there is a failure in the stash reapply step (tested with Git 2.11.1.windows.1)

This is really frustrating, honestly.

Is there any way to do a rebase with a dirty tree, and completely undo it if it fails?

What if we manually stash?

**Comment by Zarel** [comment]
One thing we could do is manually store the current ref, `stash`, `pull --rebase`, `stash pop`, and if there's a conflict, `reset --hard` that ref, and `stash pop` again.

@panpawn, if you could do that, I'd be willing to give other admins the ability to `/updateserver`.

**Comment by Zarel** [comment]
@panpawn?

**Pull request closed without merging**
