### PR TITLE
Prevent Ubers from being calculated in /mnm and fix another error in banned stone checking

### PR DESCRIPTION
**Pull request by KrisOnline**

### CODE REVIEW

**Comment by KrisOnline** [comment]
i should pay more attention when i test things

**Comment by Spandamn** [comment]
Weird Github isn't letting me comment
The original purpose of the command was for theorymonning, I (and the room) think that banned stones and Pokémon should be allowed.

**Comment by KrisOnline** [comment]
I spoke with Chloe about this and she said it was fine to keep these restrictions in here until there was actually a need to theorymon.

**Comment by KrisOnline** [comment]
Didn't mean to close this oops

**Pull request merged**
