### PR TITLE
Fix nameblacklist target auth check

### PR DESCRIPTION
**Pull request by asgdf**

### CODE REVIEW

**Comment by Zarel** [comment]
Ugh, at this point I'm going to say no, fix the call signatures of these functions.

**Comment by Zarel** [comment]
No function should be taking an `id` parameter instead of a `userid` parameter.

**Comment by Zarel** [comment]
Heck, I'd nearly advocate changing `id` back to `userid` everywhere.

We should maybe even release a `UserID` type.

**Comment by Zarel** [comment]
`toID` should return `ID & UserID`.

**Comment by asgdf** [comment]
The function takes a user object as an argument, but because it just uses the ID from that, we mock up a fake user object that just contains an ID. That's my understanding what's happening here.

**Comment by Zarel** [comment]
Ohhhh. That's fine, then.

**Comment by Zarel** [comment]
I don't like the "fake user" pattern, though; we should maybe do something about that.

**Pull request merged**
