### PR TITLE
Add UB aliases

### PR DESCRIPTION
**Pull request by cantsay**

### CODE REVIEW

**Comment by Kalaxe** [comment]
I think the error is here: ``Line 608`` is already put pheromosa https://github.com/Zarel/Pokemon-Showdown/blob/d31fd3e3533880a31262dfa3d3394795d102aa6f/data/aliases.js#L608

**Comment by KrisXV** [comment]
Then fix it....

**Comment by Zarel** [comment]
@KrisXV I don't know if you can tell but the pullreq author and the commenter pointing out the error are different people.

**Comment by KrisXV** [comment]
I shouldn’t be allowed on the internet at 6 am

**Pull request merged**
