### PR TITLE
Generation 4: Fix Simple

### PR DESCRIPTION
**Pull request by ascriptmaster**
In Generation 4, Simple did not double stat boosts as they changed.
Instead, it treated each stat boost as if it had twice the effect.
Reimplemented the deprecated ModifyBoost event, but with slightly
different functionality as before; it now modifies the live boosts so that
they work properly with Simple.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Is how I implemented the event the correct syntax to do it? If it is, then I can use this code to instantly fix Foresight/Miracle Eye!

**Comment by ascriptmaster** [comment]
Oh right, with this kind of refactoring I'll have to make sure earlier gens have it too?

**Comment by Zarel** [comment]
Who handles Gen 4? @Marty-D?

**Comment by ascriptmaster** [comment]
Probably Marty? Anyways, the idea is that after I finish this refactor, I can probably fix Foresight and Miracle Eye real easy as well by adding this code into the volatile instead of the `onModifyMove` handler:

    onModifyBoost: function (boost, pokemon, stat) {
        if (stat === 'evasion' && boost > 0) return 0;

**Comment by ascriptmaster** [comment]
TheImmortal was bugging me about Baton Pass with Simple, so I added that check. (I don't think it's neccessary though)

**Comment by Marty-D** [comment]
Ah nice work @ascriptmaster, this looks like a great change. Nice tests too! You've also reminded me I forgot to change the Foresight/Odor Sleuth/Miracle Eye descriptions in my update the other day.

**Comment by ascriptmaster** [comment]
Cool!

Hmmm, since I didn't set `inherit:true` on this, does that mean I can remove the `onBoost` empty function?

**Comment by ascriptmaster** [comment]
Removed the empty `onBoost` function.

**Comment by Zarel** [comment]
I think we should have a new rule to only use the event system if we have more than one event handler.

If it's only one, we might as well hardcode it as an exception.

**Comment by ascriptmaster** [comment]
It is going to have more than one event handler.

- It's being used for this, the implementation of Generation 4's Simple.
- It's going to be used for Foresight and Miracle Eye.
- Maybe we could use it in Unaware to improve the readability of our code.

**Comment by Zarel** [comment]
Okay, sounds good. Do you personally think this is ready for merging, or should I get someone else to look over it?

**Comment by TheImmortal** [comment]
What about when it Baton Passes to something without Simple?

**Comment by Zarel** [comment]
That case is definitely being handled correctly, although we might want to make a test to that end.

**Comment by Zarel** [comment]
Well, the "Baton Pass in" test should work the same way as "Baton Pass out". There's not a huge need to test both.

**Comment by Zarel** [comment]
I'm merging since it looks good to me and no one else has said anything.

**Pull request merged**
