### PR TITLE
Support highlights in Resource Monitor`s admin log

### PR DESCRIPTION
**Pull request by Slayer95**
Setting: `Config.adminloghighlights`

### CODE REVIEW

**Comment by Zarel** [comment]
Can't you just highlight on the text itself?

**Comment by Slayer95** [comment]
See http://logs.psim.us:8080/<super_secret_room>/2015-09/2015-09-29.html#20:46

**Comment by Zarel** [comment]
I mean, you can add the text in the monitorlog to your personal highlight list

**Comment by Slayer95** [comment]
That would allow false positives and false negatives for the notifications (consider that highlights' lists are global), but it's up to you.

**Comment by Zarel** [comment]
I would rather not have something like this in core. In theory, it should be easy enough to mod ResourceMonitor directly in Config if it's that big of a problem.

**Comment by Slayer95** [comment]
Hmmm yea... I suppose resmonitor's logging system is already specific enough.

I don't think it's very important to keep track of Config implementation, so I'm closing.

**Pull request closed without merging**
