### PR TITLE
Expand on non-Trace and Entrainment abilities

### PR DESCRIPTION
**Pull request by KrisOnPS**
Fixes https://github.com/Zarel/Pokemon-Showdown/issues/3230

### CODE REVIEW

**Comment by asgdf** [comment]
Note that things like Simple Beam, Worry Seed, Mummy, Power of Alchemy, etc. would most likely also fail on those abilities, as mentioned in the post linked in the issue. I clarified the issue title to include overwriting of abilities as well.

**Comment by KrisOnPS** [comment]
ill update more tomorrow after school, im tired and need sleep and dont want that to affect this

**Comment by urkerab** [comment]
Rather than repeating all of these abilities, would it be a good idea to update `setAbility` with the lists of abilities that can never be copied and/or overwritten?

**Comment by KrisOnPS** [comment]
That could work as well @urkerab , I'll update it in a bit when I get home.

**Comment by KrisOnPS** [comment]
oKay so i cant do this im too rusty with JS and too busy IRL

**Comment by Spandamn** [comment]
I can do that

**Pull request closed without merging**
