### PR TITLE
Shrink needlessly long prototype chains for battles

### PR DESCRIPTION
**Pull request by Slayer95**
Properties should now be searched in this order:
- Instance
- Scripts installed
- Battle.prototype properties
- <strike>Scripts installed (again)</strike>
- Tools properties
- Object properties

### CODE REVIEW

**Comment by Zarel** [comment]
Why do we search scripts installed twice?

**Comment by Slayer95** [comment]
That's a good question. Thought you would have the answer!

**Comment by Zarel** [comment]
I think it's a relic of something past. Feel free to only do it once. We have something resembling a test suite now, anyway. :P

**Comment by Slayer95** [comment]
Having the prototype chain set this way allows us to do stuff like:
`` Tools.hasMegaEvo(Tools.getTemplate('blaziken'))``, or
``Tools.checkAbilities(blah)`` (whatever this function is supposed to do).

I just learned this yesterday, so it's probably obscure enough not to be missed.

**Comment by Zarel** [comment]
Oh, I remember now. Yeah, drop that.

**Comment by Slayer95** [comment]
Updated

**Pull request merged**
