### PR TITLE
Server: Reorganize TypeScript globals

### PR DESCRIPTION
**Pull request by TheJetOU**
This commit keeps modules in `server/global.d.ts` and moves types to `globals.ts` (a la `sim/`'s structure).

### CODE REVIEW

**Comment by Zarel** [comment]
Why not merge the two completely? I don't see a strong reason for them to be separate.

**Comment by Zarel** [comment]
(I think the original reason they were separate was because of a limitation with TypeScripted jsdoc-`.js` files which no longer exist.)

**Comment by TheJetOU** [comment]
> Why not merge the two completely? I don't see a strong reason for them to be separate.

I think a good reason to seperate them is to avoid dumping all the global types, interfaces, namespaces, into the `declare global { ... }` block which locks a bit cluttered IMO.

**Comment by Zarel** [comment]
I don't think we'd necessarily need to?

**Comment by Zarel** [comment]
What lines are we drawing, and can we rename these files to match?

**Comment by TheJetOU** [comment]
> What lines are we drawing, and can we rename these files to match?

I'm not sure what you mean by that. Why would we rename the files? ``globals.ts`` matches the file's use, so does `global.d.ts`.

**Comment by Zarel** [comment]
It looks like it should be `global-variables.d.ts` and `global-types.ts`?

**Comment by TheJetOU** [comment]
> It looks like it should be `global-variables.d.ts` and `global-types.ts`?

That's fine by me. +1.

I suppose `sim/` should also follow suit.

**Comment by scheibo** [comment]
Oh man, no more having to remember when autocompleting which one requires an `'s'` or not. Lovely!

**Comment by Zarel** [comment]
Looks good! Thanks!

**Pull request merged**
