### PR TITLE
Add -ability tags to most ability activations

### PR DESCRIPTION
**Pull request by ascriptmaster**
I'm still unsure about a few of the abilities:

- When Immunity blocks Poison, when does a message show up?
- Does Overcoat show the ability box when it blocks Sandstorm/Hail?
- Does Lightning Rod show the ability box when it redirects moves?

Also very unsure about what to do with old-gens, since I don't know when messages show up in those cases.

### CODE REVIEW

**Comment by Zarel** [comment]
Why not just make `[from]` display it?

**Comment by Zarel** [comment]
Display the ability activation box, I mean.

**Comment by ascriptmaster** [comment]
I don't understand. Can you clarify what you mean by that?

**Comment by Zarel** [comment]
e.g. in client, change it so `-setboost ... [from] ability: Anger Point` displays the ability box.

**Comment by Marty-D** [comment]
> When Immunity blocks Poison, when does a message show up?

If you use say, Toxic on an Immunity Pokemon, it will activate and the message "POKEMON cannot be poisoned!" comes up. The other status immunity Abilities behave the same way.

> Does Overcoat show the ability box when it blocks Sandstorm/Hail?

Nope.

> Does Lightning Rod show the ability box when it redirects moves?

Yeah, I was actually going to add the "POKEMON took the attack!" message a while ago, but then ran into the problem that Lightning Rod and Storm Drain currently redirect to the wrong Pokemon when multiple instances are on the field, and never got around to fixing that. But yes, it shows up once to redirect (if it wasn't the original target) and again right after to absorb the attack.

For some of these activations, there probably also needs to be an additional check so that it doesn't visibly activate when the Ability isn't actually doing anything. Stuff like Cute Charm when already infatuated, Flame Body when already burned (etc), and all the weather Abilities when their weather is already active (the only exception is Gen 5; if the weather wasn't already permanent and the respective weather Ability comes into play, it does activate and makes it permanent).

**Comment by ascriptmaster** [comment]
Wait, if two Lightning Rod mons are on the field at the same time, which one does it redirect to? The faster one, or the slower one?

**Comment by Marty-D** [comment]
The faster one. If it's a Speed tie, the one that's been on the field longest. If that's also a tie, the leftmost one.

**Comment by ascriptmaster** [comment]
Really? That's a pain...

**Comment by ascriptmaster** [comment]
What about the left-most one on both sides with Lightning Rod, with the same speed and have been on the field an equal number of turns?

**Comment by Marty-D** [comment]
Good question; looking through my old tests from Gen 5, it doesn't seem like I ever tried having a Speed tie between Pokemon on opposite sides (that would have been a real pain considering I used wild Pokemon). Here are the tests for reference: http://hastebin.com/ziyepuvusa.txt

**Comment by ascriptmaster** [comment]
Curiously, Veekun reports that in speed ties it redirects to random mons. Are you sure you didn't just get lucky with your tests (like what happened with Pickup when I was refactoring items)?

**Comment by Marty-D** [comment]
Oh, it doesn't say there, but I was actually draining Thunder Wave's PP with each test, so that's ~10 trials for each line. For the final Tynamo test, I kept it going until they started using Tackle only (so at least 50 turns).

As for Veekun, "*If the move's intended target also has this ability, the move is not redirected.*" is clearly false (for Gen 5 and 6 at least), so the rest of the description is dubious at best.

**Comment by Zarel** [comment]
> The faster one. If it's a Speed tie, the one that's been on the field longest. If that's also a tie, the leftmost one.

Define "leftmost". What if they're on opposite sides?

**Comment by DanUgore** [comment]
Leftmost means the first one sent out by the owner's side, basically the earliest one you pick in team preview. Opposite sides are unknown/untested.

**Comment by Marty-D** [comment]
Yeah, I said leftmost because all I was thinking of was the Tynamo test. The second test I did in that list shows the opposing side's right Lightning Rod Pokemon taking all the attacks from the actual fastest Lightning Rod Pokemon while it's Speed tied with the Pokemon to its left, so it's not actually clear what leftmost means. Unless maybe in a wild battle the right Pokemon is considered the first on the field? (the left one from the player's perspective)

**Comment by DanUgore** [comment]
I would think it' first pokemon to appear on the field. In wild encounters it would be the opposite side, in trainer battles idk, the host's?

**Comment by ascriptmaster** [comment]
That would actually make sense... the first Pokemon to switch in with simultaneous switches would be the one that was on the field longest (even if it's only by 2 seconds). Can you check what happens with double switching normally into two Lightning Rod Pokemon with the same speed? That would prove/disprove the theory.

**Comment by ascriptmaster** [comment]
If my conjecture is correct, what we probably need for Lightning Rod redirection is a sort of queue that keeps track of the exact order that Pokemon switched in.

We might also need some sort of `priorityEvent` which, instead of aborting on falsey values, aborts on the first non-undefined value. We'd have to reverse the `RedirectTarget` priorities for the relevant effects, of course (Follow Me, Sky Drop)

**Comment by Zarel** [comment]
@ascriptmaster, I still don't understand why we need `-ability`.

e.g. Why not just make `|-damage|...|[from]ability: Aftermath` display the ability popup?

**Comment by TheImmortal** [comment]
@Zarel like this https://github.com/Zarel/Pokemon-Showdown-Client/commit/d19b4f952c72431b5d2a49177974bcd0c2b01143?

**Comment by TheImmortal** [comment]
Here's another! https://github.com/Zarel/Pokemon-Showdown-Client/commit/e1c03bf49ac8659d3a6109c8fd7cc01c49abe09f

**Comment by Zarel** [comment]
@TheImmortal, yes, but automatically instead of writing a separate one for each thing.

**Comment by ascriptmaster** [comment]
Between the merge conflicts and the fact that half of these are going to be client-side anyways, I'm going to shelve this.

We really have to figure out how to get Lighting Rod working properly. I'll raise an issue.

**Pull request closed without merging**
