### PR TITLE
Un-hardcode Rock Head in favor of an onDamage handler

### PR DESCRIPTION
**Pull request by ascriptmaster**
Instead of having a hardcode in scripts.js that people needed to
reference, it seemed more intuitive to take advantage of the Damage
event instead, and have Rock Head negate damage within the event.

Fixed a minor Gen-NEXT Rock Head bug that was basically the same
as our old Rock Head + Mummy bug.

Also, fixed up a Sheer Force test (the Sheer Force Pokemon didn't
have a Life Orb so the test checking for the negation of Life Orb recoil
would pass even if Sheer Force wasn't coded correctly.

---

This PR could also be titled "I'm bored at work"

I was planning to un-hardcode Sheer Force too but that one wasn't
being very cooperative.

### CODE REVIEW

**Comment by SolarisFox** [comment]
I know at one point we had it where Pokemon with Rock Head still took recoil damage when attacking substitutes. Was that a bug by us, or is that intentional behavior? (at one point Bulbapedia claimed that this is the actual game mechanic but looking back now it was changed to makes no mention of it!)

**Comment by ascriptmaster** [comment]
If the bug you speak of is the one I'm also thinking of, it was a result of our first Rock Head + Mummy fix, where we forgot that our Substitute code needs to handle recoil separately from the main function, and we had forgotten to add the hardcode check to that handler.

**Comment by SolarisFox** [comment]
Oh, so Bulbapedia mistakenly saw our bug and thought it was in-game behavior? That's pretty funny.

**Comment by ascriptmaster** [comment]
When did you hear about that bug? It was active for only a few days about 3 weeks ago.

**Comment by SolarisFox** [comment]
It was a few weeks ago when the bug was first discovered. Makes you wonder who actually writes the Bulbapedia entries. Clearly they don't fact check.

**Comment by Marty-D** [comment]
Heh, I seem to constantly forget NEXT exists. The Struggle check was for Gen 3, where Struggle actually uses `move.recoil` for recoil since it's half the damage dealt instead of a constant amount.

**Comment by ascriptmaster** [comment]
Ooh, that might be a problem. I could probably fix it by checking `battle.activeMove` though, right?

**Comment by Marty-D** [comment]
You could just override the function in Gen 3 Rock Head. That's what was being done before with `ModifyMove`, anyway. You also missed reverting the Gen 5 Substitute change!

**Comment by ascriptmaster** [comment]
Like this?

**Comment by Marty-D** [comment]
Oh, I misinterpreted what the `Damage` function was doing because I saw `move.id` instead of `effect.id` and just assumed you could check for Struggle there. So yes, something like `move.id === 'recoil' && this.activeMove.id !== 'struggle'` would work for Gen 3 there.

What you have right now also works since there are no effects that can change your Ability during an attack in Gen 3. I don't really have a preference; the hardcoded implementation was the closest to the way the games do it, but everything other than that is fine with me as long as it's mechanically accurate (and not terribly ugly). If anyone else wants to give their opinion, go right ahead.

**Comment by ascriptmaster** [comment]
Based on your comment, I changed `move` to `effect` in Rock Head's `onDamage` handler.

Maybe I should have written a Gen 3 test for struggle

**Comment by ascriptmaster** [comment]
poke

**Pull request merged**
