### PR TITLE
Random Battle: Refactor STAB Move Checks

### PR DESCRIPTION
**Pull request by ascriptmaster**
The current variables in place to check for STAB do not work as intended.
If a Pokemon has two STAB moves of the same type, and one of them is set
as a move that shouldn't be counted as STAB, the Pokemon will be counted
as not having STAB. Since nothing in the code checks for Pokemon having
STAB of a specific type, it is refactored to be a boolean instead.

In order to avoid a situation where a move like Infestation sets the STAB
variable to true when it doesn't count as a damaging move, these kinds of
moves no longer increment counters for abilities that boost damage, like
Adaptability.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
While we're on the subject of STAB move checks, *why is Aeroblast not counted as STAB in Doubles?*

**Comment by Slayer95** [comment]
Re: Aeroblast.
41c46e67 fixed that, but only for Singles.

**Comment by Zarel** [comment]
I'm still confused. Why isn't Aeroblast counted as STAB?

**Comment by Slayer95** [comment]
https://github.com/Zarel/Pokemon-Showdown/pull/260#issuecomment-20225171

**Comment by ascriptmaster** [comment]
The way the code is set up, Lugia has Aeroblast and Ice Beam equally... in Singles, since Ice Beam passes the check where your only damaging move is an Ice move on a Psychic-type. In Doubles, the check doesn't include Psychic types when there's only one damaging move, so maybe we should add that?

Actually, I just checked the code, and evidently, *Lugia doesn't have Ice Beam in Singles for some reason*. So that's a thing I'll have to fix too.

**Comment by TheImmortal** [comment]
Lugia isn't an offensive Pokemon and does run, or need, Ice Beam.

**Pull request merged**
