### PR TITLE
Random Battle: Update on AV

### PR DESCRIPTION
**Pull request by iceblinkluck**

### CODE REVIEW

**Comment by Zarel** [comment]
For the third time, please do not create a new pull request every time you make a change. This is what rebase is for.

Creating a new pull request clutters our repository and spams our watchers.

Many of our contributors would love to help you rebase if you can't figure out how to; you can ask in the Development room http://play.pokemonshowdown.com/development

**Comment by iceblinkluck** [comment]
Won't happen anymore

**Comment by TheImmortal** [comment]
You are aware this is changing doubles? It seems like this was thought to be singles here and in the previous requests, based on the comments. Well if it was singles, then Assault Vest is not hard coded so I reject this change. If it is meant for doubles then I'd ask @ascripmaster for an opinion as I do not play doubles.

**Comment by ascriptmaster** [comment]
Based on your comments in #1818, I would change the Life Orb check on Line 2926/2928 to not give it to Pokemon with **less than 55 base Speed.** This should give Escavalier the **Occa Berry**, and Azumarill the **Assault Vest**. Slowking most likely will get **Sitrus Berry** under these checks, but if you think it wants Assault Vest more, fix the check on Line 2942 to check that the Pokemon doesn't have Regenerator. This should create more general use-cases that work better for random doubles as a whole.

Actually, if you want, you could even have the speed cut-off for Life Orb be **58 base Speed**, which also includes Pangoro and Scrafty as Assault Vest candidates (allowing you to remove the hardcode entirely). Machamp would lose out on Life Orb but it's not particularly needed for it.

**Comment by iceblinkluck** [comment]
that is probably the best way to go yeah

**Comment by ascriptmaster** [comment]
If that's the best way to go, then go ahead and do it.

**Pull request closed without merging**
