### PR TITLE
Add Alias for Modnote

### PR DESCRIPTION
**Pull request by Aurolux**

### CODE REVIEW

**Comment by bumbadadabum** [comment]
Why?

**Comment by AustinXII** [comment]
“Note” implies a note to self not really a note for other moderators. I also don’t see how this is useful when /mn can be used with much more ease

**Comment by Aurolux** [comment]
Okay so here is why I thought this might be useful. A global driver once told me that they prefer spelling things out than doing short aliases than things like `/mn` so I thought `/note` would be shorter but couldn't be confused with `/m`. Also, "Note" being for one's self isn't necessarily true, but all of these changes I've made were out of preference. I don't see why this alias is useless even if its not a priority to PS code.

**Comment by Zarel** [comment]
You should definitely not pullreq things just because a gdriver said they'd prefer it. At least, not without asking the Dev room for opinions first. I personally am wary about this because it might conflict with future commands, so I'm going to deny this. `/mn` is fine.

**Comment by Aurolux** [comment]
Okay sounds good.

**Pull request closed without merging**
