### PR TITLE
README: Add Dex to Navigation section

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Slayer95** [comment]
You should shift the following ref indices [3] -> [4], etc

Though I am not a fan of linking the Dex repository here.
It's not like we are linking the Learnsets or the Battle Factory repos either, which are kind of satellital.

**Comment by Zarel** [comment]
Well, the difference is, the Dex repository _does_ have the same structure as the rest.

**Comment by Zarel** [comment]
In terms of what it's named, as well as in terms of its README links.

And the Dex is kind of more important than the Learnsets repo, which was useless as soon as 3DS encryption was cracked.

**Comment by panpawn** [comment]
>You should shift the following ref indices [3] -> [4], etc

...er...?? I'm not sure I understand what you mean, can you clarify?

>Though I am not a fan of linking the Dex repository here.

The main reason I did this was because I noticed the Dex README was setup very much like how the client/server one is, including Navigation - except the server/client was missing the Dex repo link.

**Comment by Zarel** [comment]
I'm still not sure whether or not we want to do this. It _is_ a nice dex, I guess...

**Pull request merged**
