### PR TITLE
Random Battle: Update item checks for Unburden and Quick Feet

### PR DESCRIPTION
**Pull request by ascriptmaster**
- Update Unburden's item check in Doubles to match Singles.
- Give Toxic Orb to Quick Feet users (affects Ursaring, which has a 1/3
  chance of getting it over Guts)
- Give Linoone Pickup instead of Quick Feet, since it always has Sitrus
  Berry and could obtain an extra item occasionally

### CODE REVIEW

**Comment by ascriptmaster** [comment]
The build failure isn't my fault!

**Comment by sirDonovan** [comment]
@ascriptmaster Fixed the failure, try pushing your commit again.

**Comment by TheImmortal** [comment]
I disagree with always giving Linoone Pickup. Quick Feet is just as useful due to paralysis and I have had that occurrence several times.

Your Quick Feet change doesn't work as well because all Pokemon with it get will get Toxic Orb. That's probably why it was never here in the first place.

**Comment by ascriptmaster** [comment]
Linoone has a 62% usage for Pickup in its tier, according to your bot. The rest of it is Gluttony, probably to apply Salac Berry. Quick Feet has 0.3% usage.

No other Pokemon with Quick Feet other than Ursaring (and Linoone, of course) will actually get it in the generator, since they all have abilities that don't get rejected and are ranked at least one point higher than Quick Feet in priority (when the cutoff is 0.6 points).

You have a good point though, and the Toxic Orb addition isn't really needed because Ursaring will get it from an earlier check due to it having Facade.

**Comment by TheImmortal** [comment]
There's also the point the Linoone doesn't always get Belly Drum.

**Comment by ascriptmaster** [comment]
`randomBattleMoves: ["bellydrum","extremespeed","seedbomb","shadowclaw"],`

It only does that for doubles, since there its movepool also has Protect. But I digress.

`if (template.species === 'linoone' && hasMove['bellydrum'])` ... nah, it's fine

**Comment by TheImmortal** [comment]
lol I guess I forgot I removed Substitute. Anyway, yeah I don't think it should be hardcoded to always have Pickup. It isn't necessary like some of the other hardcoded abilities.

**Pull request closed without merging**
