### PR TITLE
Add -center message type for Triples Automatic Center

### PR DESCRIPTION
**Pull request by ascriptmaster**
It's not a rule clause or part of a custom metagame,

### CODE REVIEW

**Comment by Slayer95** [comment]
This should be a major imo: <code>center</code> rather than <code>-center</code>.

**Comment by ascriptmaster** [comment]
OK I'll fix once I get off work

**Comment by Zarel** [comment]
What @Slayer95 said.

**Comment by ascriptmaster** [comment]
https://github.com/Zarel/Pokemon-Showdown-Client/pull/386 merged while listening to the minor message `-center`, so what should I do now?

**Comment by Zarel** [comment]
Oh, I said it should be a major because I thought it was where the actual relocation happened. If we still send `swap`, then `-center` should be a minor.

**Comment by Zarel** [comment]
But yeah, I'll leave this open for you to document it in `protocol-doc`.

**Comment by ascriptmaster** [comment]
Here's the documentation.

**Pull request merged**
