### PR TITLE
Fixing smogintro link

### PR DESCRIPTION
**Pull request by Bryan-0**
Fix the smogintro links.

### CODE REVIEW

**Comment by Bryan-0** [comment]
The others links are bad too, but I don't find them the correct link on smogon. I just found the correct for  "Introduce yourself to Smogon!".

**Comment by Rhythms88** [comment]
The mentorship program has been inactive for a while

**Comment by Bryan-0** [comment]
Ohh.

**Comment by xfix** [comment]
Thanks for fixing a link, but I think this commands needs a bigger improvement. Feel free to check http://www.smogon.com/forums/forums/smogon-info-intro-hub.264/ (Smogon Info / Intro Hub), which replaced old Smogon Mentorship to check what links may be useful.

Also, don't make links with thread titles. Just do https://www.smogon.com/forums/threads/3522706. It will still work, and it's the style used in the code. Make sure to also use HTTPS, despite Smogon not supporting HTTPS (eases maintenance when Smogon will finally support HTTPS).

**Comment by Bryan-0** [comment]
Ok thanks, i will fix and search for links.

**Comment by TheImmortal** [comment]
I think it should just be:

> Welcome to Smogon's official simulator!
> - Smogon Info / Intro Hub

There's no point in linking just one thread in that forum, and linking all the threads is too much. Just link the forum.

**Comment by Bryan-0** [comment]
I will wait @Joimer.

**Comment by Bryan-0** [comment]
@TheImmortal, I think that is good to link some specific threads, because with that user can have a better guide.

**Comment by TheImmortal** [comment]
I'd go with Useful Smogon Info and Tiering FAQ.

**Comment by Joimer** [comment]
Agreeing with @TheImmortal here, that would be neat for this update.

**Pull request merged**
