### PR TITLE
Update poll.js with lesss spam..

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by bumbadadabum** [comment]
Why are you putting it in ANOTHER div?

**Comment by Zarel** [comment]
I don't think there's consensus that the poll needs to take up less space.

**Comment by Lord-Haji** [comment]
if u do !poll show it would eventually make it a spam tho

**Comment by Zarel** [comment]
I don't currently see that as a substantial risk.

**Comment by kotarou3** [comment]
and if you do !roomhelp, it spams even more. Maybe fix that first?

**Pull request closed without merging**
