### PR TITLE
Refactor user.isAway to a getter function

### PR DESCRIPTION
**Pull request by TheJetOU**
It makes sense semantically. It's also a pure function (has not side effects).

### CODE REVIEW

**Comment by Zarel** [comment]
No, I actually already had this argument with Bumba.

Getters are just bad in general.

**Comment by Zarel** [comment]
There are a number of arguments here, but the main one is that variables should look like variables, and functions should look like functions. Having a function that looks like a variable is bad for readability.

**Comment by Zarel** [comment]
Unrelatedly, having a function that looks like a variable is also bad for performance. Like, 10x slower.

But also, it's just bad because it misleads you into thinking the way to set a user back is to use `.isAway = false`, but it's not.

I think it's important to be clear about what's state and what's computed.

**Comment by TheJetOU** [comment]
Fair enough.

**Pull request closed without merging**
