### PR TITLE
Random Battle: Reject more move combinations

### PR DESCRIPTION
**Pull request by ascriptmaster**
- Reject Toxic with Nuzzle.
- Remove Sleep+Talk from Primal Kyogre. Getting just Rest and not Sleep
  Talk can be a problem since it cannot hold a Chesto Berry.

### CODE REVIEW

**Comment by CrestfallPS** [comment]
Assuming the Toxic-Nuzzle change is for Dedenne, I don't see why it should be removed. Gives it a way to punish otherwise safe electric switch ins, apart from pivoting out.

**Comment by ascriptmaster** [comment]
If so, then why is Toxic rejected with Thunder Wave?

**Comment by TheImmortal** [comment]
Double status is mostly bad. Except if it is like Toxic + Scald. But, in this case, Dedenne has poor offensive stats and does more damage with status. And Nuzzle isn't exactly like Thunder Wave. It can't be Taunted and does some, albeit a very small amount of, damage.

As for the other change, I have a better idea.

**Comment by ascriptmaster** [comment]
Dedenne can get brutal once it hits Petaya because of its base 81 SpA for its level tier at +1, but you do have a good point. Not only that, Pachirisu (who also has both in its set) has practically zero offensive worth whatsoever.

For the other change, are you thinking of something like adding `if (!hasMove['sleeptalk'] && template.requiredItem)` to the Rest check? That would probably work.

**Comment by TheImmortal** [comment]
8c62c585109182d192096e21c28f34b5daf2de68

**Pull request closed without merging**
