### PR TITLE
Link rooms in Punishments#monitorRoomPunishments

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
This looks like an abuse of `/raw`.

I'm not sure if I'd recommend reimplementing `Monitor.log` or something...

**Comment by panpawn** [comment]
>This looks like an abuse of /raw.

I'm not sure I follow

**Comment by Zarel** [comment]
`/raw` is a hack for PMs and as a dumb hack to make chat plugins easier; I don't really want it to be used in cases like these.

**Comment by Zarel** [comment]
But I guess it's not a huge deal.

**Comment by panpawn** [comment]
Alternatively, we could link rooms with the <<roomid>> format here.

**Comment by Zarel** [comment]
That's what I suggested to Bumba, actually.

**Comment by panpawn** [comment]
Wait, why is it that this doesn't need to be rebased; this file was changed since this was opened...

???

**Comment by panpawn** [comment]
Just in case, I ended up rebasing it anyways (with the master branch)

**Comment by Zarel** [comment]
Manual rebasing only needs to be done if there's a merge conflict. If your changes are to a different part of the file than others changed, you don't need to rebase (although it's often still a good idea for testing purposes).

**Pull request merged**
