### PR TITLE
Add bold in /punishments

### PR DESCRIPTION
**Pull request by spekss**

### CODE REVIEW

**Comment by panpawn** [comment]
Off-topic: This reminds me, maybe we should standardize using either ``<b>`` or ``<strong>`` across the repo.

**Comment by Zarel** [comment]
Yeah, this should be `<strong>`.

**Comment by Zarel** [comment]
We don't need to standardize; we should just use the existing standards.

**Comment by panpawn** [comment]
Oh, I thought we were using ``<b>`` in some places, I guess I was mistaken

**Comment by Zarel** [comment]
It's possible we are, but only when it makes sense.

**Comment by Zarel** [comment]
Oh, grepping reveals a lot of situations we probably should be using `<strong>`. Yeah, we should fix those.

**Pull request merged**
