### PR TITLE
Add new aliases

### PR DESCRIPTION
**Pull request by ascriptmaster**
Added some aliases for mega evolutions, and also for Hoopa (its base forme is Hoopa-Confined)

(( I remembered that people mentioned missing aliases for megas, but I forgot what all of them were! ))

### CODE REVIEW

**Comment by RhythmsAreFromVibrations** [comment]
``Mega Beedrill:`` ``megadrill``
``Mega Lopunny:`` ``megabunny``
``Mega Gallade:`` ``megallade``
``Mega Houndoom:`` ``megadoom``
``Mega Latias:`` ``megatias``
``Mega Latios:`` ``megatios``

If I think of more, I'll edit this post.

**Comment by CrestfallPS** [comment]
I've never seen megallade said ever. The rest should be added.

Thx for adding what I asked ascript n_n

**Comment by ascriptmaster** [comment]
I never heard of megati@s before, either, but if crest says it's OK then I'll add it when I get home.

I should probably add mega kanga and mega amphy as aliases as well.

**Comment by CrestfallPS** [comment]
Well people say Megalati but there is no way to differentiate. So it's either add nothing or do what he suggested as unknown as it is. From past pulls zarel/ti lean towards just not adding at all if they aren't used. Besides megalati are both shit and barely brought up in serious conversation.

**Comment by ascriptmaster** [comment]
Added Megabunny, Megadrill, Megadoom, and Megakanga.

**Comment by ascriptmaster** [comment]
Anything else that people want added?

**Pull request merged**
