### PR TITLE
Ban Shaymin-Sky from Gen 6 Mix and Mega

### PR DESCRIPTION
**Pull request by KrisXV**
@TheImmortal or anyone this is urgent

### CODE REVIEW

**Comment by Zarel** [comment]
"Urgent" but no thread link? Can you provide one ASAP?

**Comment by KrisXV** [comment]
It was never allowed in gen 6...

**Comment by urkerab** [comment]
I don't know whether ROM is up-to-date because I don't watch the threads like a hawk but its Gen 6 banlist includes Darkrai, Cresselia, Genesect, Lucario, Manaphy and Shaymin-Sky while it doesn't include Deoxys-Speed.

**Comment by KrisXV** [comment]
@urkerab that seems correct

**Comment by urkerab** [comment]
Great then we're agreed thanks!

**Pull request merged**
