### PR TITLE
Add slowchat message upon joining a room

### PR DESCRIPTION
**Pull request by panpawn**
Much like we try to mirror the UI of modchat when it comes to slowchat, it should also be displayed upon joining a room, like modchat is.

### CODE REVIEW

**Comment by Zarel** [comment]
I don't think that's necessary...

**Comment by panpawn** [comment]
It's information that's relevant to user's joining the room, though, just like modchat imo

**Comment by Zarel** [comment]
It's not immediately relevant the way modchat is. It only matters if you want to talk a lot, at which point we'll tell you.

I think modchat is the only one that matters immediately.

**Comment by panpawn** [comment]
Modchat is only immediately relevant to people who come in the room to actually talk, if they aren't a rank where the modchat level will allow them to talk, it will also let them know.

I'm not sure I'm seeing the difference with this, or the logic of how one is more important to be alerted of upon joining a room than another.

**Comment by panpawn** [comment]
I believe just came across an instance where the room/global staff of a room forgot that slowchat was on, since it doesn't effect them or alert them upon joining the room.

**Comment by Zarel** [comment]
Okay, it should tell _staff_, but not regular users.

**Comment by panpawn** [comment]
>Okay, it should tell staff, but not regular users.

Okay, I'll update this shortly

**Comment by panpawn** [comment]
Updated

**Pull request merged**
