### PR TITLE
Refactor blacklist commands to a namespace command

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by bumbadadabum** [comment]
This was actually how I had the command planned initially but zarel told me to NOT do this.

**Comment by panpawn** [comment]
It definitely should be a namespace command

**Comment by Zarel** [comment]
None of the other punishment commands are namespaced.

I'm not super opposed to this, as long as you alias the old names, I guess.

**Comment by Zarel** [comment]
Oh, I remember, the main reason is that `/blacklist [username]` needs to work. As long as you still support that, lay it out however you want.

**Comment by panpawn** [comment]
Why does that still have to work?

**Comment by Zarel** [comment]
Because it's the most natural way to invoke the command.

You can refactor however you want, as long as you don't make the command harder to use.

**Comment by panpawn** [comment]
Yeah, I'm not sure how to make this a namespace command and keep that functionality

**Comment by Zarel** [comment]
Yeah, the problem is that something like `/bl add Bob` might be blacklisting "add Bob" or it might be blacklisting "Bob"

**Comment by Zarel** [comment]
For now, unless you have a better idea, I want `blacklist` to work the same way `ban` does.

**Pull request closed without merging**
