### PR TITLE
Add an auto start at player cap option for tours

### PR DESCRIPTION
**Pull request by Teremiare**
I personally really like the current auto start command but more often than not I feel like having it start when the player cap is reached would be more useful so having the option to do that would be nice, especially in bigger rooms. Not sure if this is the best way to do it though. (And not so sure about the name of it either.)

### CODE REVIEW

**Comment by Slayer95** [comment]
This should probably be an option for ``setautostart``

**Comment by sirDonovan** [comment]
I agree with @Slayer95. Maybe <code>/tour setautostart [on/cap]</code>?

**Comment by Zarel** [comment]
I'd probably have it enabled by default, incidentally.

**Comment by Teremiare** [comment]
You'd still get the current `"The tournament's automatic start timeout has been turned off."` message when setting it to `"off"` now. Would it be possible to change it to something more generic that would cover both options better?

**Comment by Zarel** [comment]
"Timeout" is mostly a programming term; not something I want to show users.

How about just "The tournament's automatic start is now OFF"?

**Comment by Teremiare** [comment]
Added the change to the off message in Zarel/Pokemon-Showdown-Client#582

**Comment by Zarel** [comment]
Why did you create a new pull request for it?

**Comment by Zarel** [comment]
Anyway, can you squash these commits?

**Comment by Zarel** [comment]
You can make "Change the tournament autostart messages" into its own commit, but the commits here are all one logical change and should be one commit.

**Comment by Slayer95** [comment]
@Zarel, that one is in the client...

**Comment by Zarel** [comment]
Ooooh, nevermind. My other comment re: commit summaries still apply.

**Comment by Zarel** [comment]
Can I get an MIT license from you?

Repeat after me:

> I, __, license all my contributions to the Pokémon Showdown project, past and future, under the MIT license.

**Comment by Teremiare** [comment]
I, Teremiare, license all my contributions to the Pokémon Showdown project, past and future, under the MIT license.

**Pull request merged**
