### PR TITLE
Change single quotes to double quotes in formats-data.js

### PR DESCRIPTION
**Pull request by ScottehMax**

### CODE REVIEW

**Comment by TheImmortal** [comment]
What about in mods

**Comment by Slayer95** [comment]
<code>'dreamball'</code> is not text intended to be read by humans. Therefore, it should be ok as it currently is according to our style convention.

**Comment by Zarel** [comment]
Single quotes is correct here.

**Comment by ScottehMax** [comment]
Note: There's a single line in Galvantula's randomDoubleBattleMoves that seems to be incorrect which was the initial reason this PR was made. I spoke to @sirDonovan to confirm that the rest could be changed, and was told it would be fine. My apologies.

**Pull request closed without merging**
