### PR TITLE
Markshared: Require a reason

### PR DESCRIPTION
**Pull request by HoeenCoder**

### CODE REVIEW

**Comment by panpawn** [comment]
Kind of unrelated, but I get annoyed with commands that require a reason and a staff just puts "." as the reason. Maybe we should have some kind of reason blacklist or something to stop that from happening?

**Comment by Zarel** [comment]
I'm not sure if this should necessarily be required.

**Comment by panpawn** [comment]
It should be definitely documented in the help command, though

**Comment by bumbadadabum** [comment]
I don't see why reasons would need to be required here.

**Comment by HoeenCoder** [comment]
This was brought up in the staff room yesterday.
`/ip` lists the ip as shared and why, if no reason is provided it shows "undefined". While another fix for this is to fix listing the reason as "undefined" in `punishments.js`, I went with this because having info on why an IP is shared is useful (and really not that much work to add).

**Comment by AustinXII** [comment]
I have to agree with Hoeen, there is merit in doing this and considering you shouldn’t be marking shared IP on non-public IPs, forcing people to explain why they are using the command can avoid confusion when people are alt checking and what not.  Also it isn’t even that much more work considering if you are going to use /markshared you “have to” look up the details of the IP anyways and a copy + paste isn’t that bad

**Comment by Zarel** [comment]
Superseded by #4475

**Pull request closed without merging**
