### PR TITLE
endlockdown: Better phrase declared message

### PR DESCRIPTION
**Pull request by panpawn**
Lockdowns are about server restarts, not server shutdowns

### CODE REVIEW

**Comment by Zarel** [comment]
No, they're not, they're about server shutdowns...

PS doesn't have any built-in ability to restart itself.

**Comment by Zarel** [comment]
On the other hand, I think lockdown does use the "restart" language.

We should probably find some way to unify this. We do use `/kill` because we want to convey that the command doesn't command with any built-in autorestart amenity.

We could start bundling `pm2` with PS or something...

**Comment by panpawn** [comment]
> On the other hand, I think lockdown does use the "restart" language.
Yea, that was kind if my reasoning

**Comment by Slayer95** [comment]
@Zarel, last time I checked pm2 didn't support Windows

**Comment by Zarel** [comment]
$&^!*&^@*^ I've stopped caring

**Pull request merged**
