### PR TITLE
Fix alphabetization in data/moves.js

### PR DESCRIPTION
**Pull request by ekmnoop**
Moves are listed alphabetically; this pull request corrects some apparent mistakes:

### CODE REVIEW

**Comment by ekmnoop** [comment]
Now it should be ready for review, @scheibo. Hopefully I didn't forget one.
There are 17 `isNonstandard` moves, only three were listed at the end of the file, therefore I alphabetized those as well.

**Comment by scheibo** [comment]
Thanks!

**Comment by Zarel** [comment]
All `isNonstandard` moves should be at the end of the file. There should also not be 17 `isNonstandard` moves...

**Comment by Zarel** [comment]
Oh, the others are LGPE moves. Only custom moves `isNonstandard: "Custom"` should be at the end of the file. They're placed correctly.

**Pull request merged**
