### PR TITLE
Digimon Showdown

### PR DESCRIPTION
**Pull request by AlphaWind**
Pokemon X Digimon mode has not been tested nor does it have a randomizer yet.

### CODE REVIEW

**Comment by Zarel** [comment]
I thought you wanted to pullreq the client changes...

**Comment by mathfreak231** [comment]
Just an update: Our team has resolved most of the TS errors on a local build simply by mimicking what the main server did. I've looked through the remaining TS errors, which are pasted [here](https://hastebin.com/pigefomequ.pas); my explanations and proposed solutions are [here](https://pastebin.com/qRVtad6n). I'd do these myself but I'm too occupied with other things and there are people with better resources than me.

**Comment by AshleyPikachu** [comment]
I see @Zarel I'm afraid this is what we have, only 1 person on our team knows how to use the client and the rest of us do not even know how to touch the client. I'm afraid we need help or we are stuck.

**Comment by AlphaWind** [comment]
Opened #5392

**Pull request closed without merging**
