### PR TITLE
Fix crash in hiding text of users with no object

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks!

**Comment by AustinXII** [comment]
I’m curious what was the crash?

**Comment by whalemer** [comment]
hidealtstext on a user with an expired user object, tries to access
properties of null and crashes (L2463, targetUser is null). the rest of it
is just cleaning old code that didn't effect anything, since we only have
one hidetype now.

**Comment by AustinXII** [comment]
Ah ty

**Pull request merged**
