### PR TITLE
Datasearch: Allow using "all" as only perameter

### PR DESCRIPTION
**Pull request by jumbowhales**
[17:59:51] +The(Who+Doctor)²: Is there a way to change the code for /ds to allow "/ds all" to continue working?
[18:29:26] @HoeenHero: oh it got blocked, as the only paramater, maybe thats what twid meant
[19:55:10] +The(Who+Doctor)²: Yeah that is what I meant Hoeen
[19:55:22] +The(Who+Doctor)²: Doing /ds all provides no result where it used to list all Pokemon

### CODE REVIEW

**Comment by Zarel** [comment]
@urkerab, why did you disable this in #3582?

**Comment by jumbowhales** [comment]
He didn't? It's been there since before that commit.

**Comment by CheeseMuffin** [comment]
I was the one that disabled this in #3580. I saw that the code was already there for it (like there as already a message that said "No search parameters other than 'all' were found. Try '/help dexsearch' for more information on this command."). This is consistent with movesearch, and I think its possible for people to do /ds all on accident and flood their screen. If they want to get around, they can still do things like /ds spe>0, all

**Comment by Zarel** [comment]
Okay, fair.

**Pull request closed without merging**
