### PR TITLE
Change Player rank from ★ to ☆

### PR DESCRIPTION
**Pull request by panpawn**
There is a client-side counterpart to this.

### CODE REVIEW

**Comment by panpawn** [comment]
https://github.com/Zarel/Pokemon-Showdown-Client/pull/847

**Comment by Spandamn** [comment]
By the way, OM Room's room star rank uses ☆

**Comment by panpawn** [comment]
I mean, that wouldn't particularly be a _problem_ - it should just say "Player" when they click on their name... unless that is a problem?

**Comment by Spandamn** [comment]
I think it would also allow stars to set modjoin, promote people to roomvoice, make the room hidden, etc which isn't normal.
Well, TI can change the star symbol to \u2605

**Comment by panpawn** [comment]
Well, the plan is to be giving that rank special powers, specifically for groupchats, so that symbol probably wouldn't work, either...

Idea: what about \u2729 (✩)

**Comment by Spandamn** [comment]
Well, that looks good

**Comment by Zarel** [comment]
Hm:

\u2729 ✩

\u2606 ☆

They actually both look pretty good, but the bigger question is browser/OS font support.

**Comment by Zarel** [comment]
Client's merged, server can be merged now.

**Pull request merged**
