### PR TITLE
Clear forcerename monitor names on namelock more completely

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
Okay, now this one I don't get. Is the entire list of usernames namelocked? Is that why you're doing this?

**Comment by whalemer** [comment]
Yes, (i think) that that list of names will namelock on login, so reporting isn't necessary

**Comment by Zarel** [comment]
I _still_ think it makes more sense not to report any names that are namelocked on login, rather than manually clearing them all here.

**Comment by whalemer** [comment]
I don't think that's possible without changing when the namefilter is checked, they're not namelocked at that point

**Comment by Zarel** [comment]
The simple solution is to move the reporting to outside of the namefilter check.

**Comment by Zarel** [comment]
And/or check namelocks before namefilter.

**Comment by whalemer** [comment]
Can I move it to a loginfilter?

**Comment by Zarel** [comment]
That's a possibility.

**Comment by whalemer** [comment]
bump?

**Pull request merged**
