### PR TITLE
Add Sky Drop tests and pending Sky Drop glitch tests (for Gen 5)

### PR DESCRIPTION
**Pull request by ascriptmaster**
@Marty-D can you verify the mechanics of how Pokemon can be freed from the Sky Drop glitch are indeed the ones that I mentioned? What happens when Power Herb is used with two-turn moves, or maybe if the two-turn move misses or is blocked by Protect?

### CODE REVIEW

**Comment by Marty-D** [comment]
Everything you have so far is accurate, nicely done! The completion of the second turn of any two-turn move is what frees the original target, which includes Power Herb, missing, and being blocked. Only if the second turn is actually prevented from executing due to confusion or paralysis or whatever does the target stay immobile.

Something else I forgot to mention before is that the user of Sky Drop also cannot be forced to switch out while the immobilizing effect is still active (a Red Card is still consumed as normal). Basically, it's like the user has a Suction Cups-like effect and the target has an Ingrain-like effect (but you covered the target already).

**Comment by ascriptmaster** [comment]
This Suction Cups effect you speak of is probably in the effect of Sky Drop to begin with, to prevent the user from being forced out via Lock On + Roar or the like. Can you check that behavior for Sky Drop in Gen 6?

**Comment by Marty-D** [comment]
Yeah, it is part of Sky Drop's effect; I was just comparing it to other stuff. Still works the same way in Gen 6.

**Comment by ascriptmaster** [comment]
Speaking of Sky Drop preventing Pokemon from being dragged out, that implementation was actually slightly off (the target wasn't prevented from being forced out).

Also, this makes me curious. I know that when you try to switch when your Pokemon is being held by an opposing Sky Drop, it will display "__ won't let __ go!" but does any message along those lines display when Sky Drop prevents dragging?

**Comment by Marty-D** [comment]
Roar/Whirlwind show "But it failed!" as expected, but other than that there are no messages. In fact, the "Sky Drop won't let POKEMON go!" message is never actually shown in the battle text, only to the player trying to click anything besides something in the Fight command.

**Comment by ascriptmaster** [comment]
Yeah I was just checking. The Sky Drop tests should be comprehensive now, but the Sky Drop glitch tests might have some holes.

**Comment by ascriptmaster** [comment]
@Marty-D can you double check that everything is good before it gets merged?

**Comment by Marty-D** [comment]
Looks good to me! :+1:

The only thing I noticed after skimming through it again is that Infiltrator Sky Drop should probably not fail against a substitute, but I can't test that in-game by myself. Testing No Guard Skill Swap on it during the second turn would also be a neat thing to check. That's a minor thing though; there's no need to wait for that to be tested before merging this.

**Pull request merged**
