### PR TITLE
Super Staff Bros.: Add %Kayo

### PR DESCRIPTION
**Pull request by RhythmsAreFromVibrations**
I also moved %Hugendugen's entry quote because it wasn't in the right
place and I changed the double quotes to single quotes.

### CODE REVIEW

**Comment by RhythmsAreFromVibrations** [comment]
and yes this is what he wanted, we talked on skype

**Comment by Zarel** [comment]
You didn't test this, so how do you know it does what you think it does?

**Comment by RhythmsAreFromVibrations** [comment]
I actually did test it, but this is when i used ``move.onHit = function (target, source, move)`` separately instead of realizing that i could put it into the secondary by doing ``onHit: function (target, source, move)``, but then when i tried to put the ``move.onHit =`` into the secondary, i only deleted the ``move.`` and didn't replace the ``=`` with ``:``.

**Comment by Zarel** [comment]
Yes, you made a change and didn't test to see if your change did what it was intended to do.

**Comment by RhythmsAreFromVibrations** [comment]
Yeah i just forget to do things sometimes. :/

**Comment by RhythmsAreFromVibrations** [comment]
I tested the stuff and it works like it was intended to

**Pull request merged**
