### PR TITLE
Add Reversed Command

### PR DESCRIPTION
**Pull request by Spandamn**
@TheImmortal

### CODE REVIEW

**Comment by Zarel** [comment]
at some point, we should maybe just add a parameter in `/data` for format.

**Comment by TheImmortal** [comment]
I don't see the point. It isn't new stats or some complex formula. You could just /data.

**Comment by KrisXV** [comment]
It’s not like people are unable to switch stats in their head

@zarel I was actually working on that

**Comment by bumbadadabum** [comment]
why

**Comment by Zarel** [comment]
Looks like consensus has spoken; we don't consider this worth a command.

**Pull request closed without merging**
