### PR TITLE
Make code style consistent between files

### PR DESCRIPTION
**Pull request by xfix**
This is it. 86,955 additions, 11,692 deletions. Crazy.

### CODE REVIEW

**Comment by Zarel** [comment]
We should probably have waited for a vote before adding trailing commas... it at least shouldn't be in a commit with everything else...

**Comment by Zarel** [comment]
Oh well, iirc Slayer95 supported them and there's no reason to strongly oppose.

**Comment by Marty-D** [comment]
The move Return got unquoted in learnsets.js, please fix!

**Comment by xfix** [comment]
@Marty-D: I don't think the client uses learnsets.js anymore, therefore ES3 compatibility is not a concern.

**Comment by Slayer95** [comment]
I only supported ``comma-dangle`` for data (and ``config/formats.js``)... But I don't <em>strongly</em> oppose the ``always-multiline`` setting. To clarify, I don't see anything wrong in having two (but only up to 2!) different code styles: one for scripting properly and the other for data.

Other than that, the line ending rules are relevant for Git-less code deploying.

**Comment by xfix** [comment]
Now trailing commas changes are in a separate commit, to make not applying them easier.

**Comment by Zarel** [comment]
> I only supported ``comma-dangle`` for data

Technically, any multiline literal is data, whether or not it's in the `data/` directory.

**Pull request merged**
