### PR TITLE
Rename Gen6 formats to have [Gen 6] in name

### PR DESCRIPTION
**Pull request by xfix**
Note that I intentionally split this into two commits to make it easier to revert the second one. The plan is to revert second commit once bots know about new format names (in particular I'm talking about @sirDonovan's Lady Monita here).

### CODE REVIEW

**Comment by Zarel** [comment]
The aliases shouldn't be removed so much as updated to gen 7, when the time comes.

**Comment by Zarel** [comment]
Well, actually, no, it should just be done in `getFormat`.

**Comment by Zarel** [comment]
Actually, this one might be best done in `getFormat`.

**Comment by xfix** [comment]
The plan is indeed to have Gen7 aliases, however I would prefer to have some time where there are no aliases at all for transition (people may already be used to no generation number meaning Gen6).

**Pull request merged**
