### PR TITLE
Added Many Gen 2 Random Battle Movesets

### PR DESCRIPTION
**Pull request by ClaudiuBancos**
I added Gen 2 Random Battle movesets for all fully-evolved Pokemon (plus Scyther), based on Smogon write-ups. This should seriously improve the quality of Gen 2 Random Battle mode, though of course it still needs some work.

Is "EssentialMove" a thing here the way it is for Gen 1 Random Battle? If so, I could go add essential moves for many Pokemon that could use them. If not, perhaps in the future I or someone else could look into programming it in. But that's for another day.

I hereby explicitly state that I agree to MIT license all of my submitted code.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Merge your commits

**Comment by Zarel** [comment]
Squashing commits isn't as important now that squashmerging exists. Bigger question is, someone should probably check to see if these lists are good. @TheImmortal?

**Comment by ClaudiuBancos** [comment]
I for one think the lists are a lot better than not having lists at all.
I'm totally in favor of people editing the lists to make them better though.

**Comment by TheImmortal** [comment]
idk gen 2

**Comment by Joimer** [comment]
The list is fine, also there's no essential move for gen 2 randbats. Thanks!

**Pull request merged**
