### PR TITLE
Remove some ability effects to improve compatibility with Instruct

### PR DESCRIPTION
**Pull request by urkerab**
Instruct means that a Pokémon is now capable of making more than one move in a given turn, and not even the same move at that (if the Instruct happens before the Pokémon's own move then the previous move gets repeated).

This means that several effects that used to be per-turn need to be replaced with per-move flags instead, otherwise they could end up affecting both moves.

This PR deals with abilities which used to use effects but should be using per-move flags. (The other effects set by abilities all already have multiple turn duration.)

Note that Dark Aura and Fairy Aura used to be effectively unbreakable because Mold Breaker doesn't ignore the TryPrimaryHit event, and the aura effect isn't affected by Mold Breaker of course.

### CODE REVIEW

**Comment by Zarel** [comment]
This is good, but I'm worried about namespace issues. Maybe stuff like `move.sheerforceFlag` instead of `move.sheerforce`?

**Comment by Zarel** [comment]
By the way: This is great, I like this new system a lot more than screwing around with volatiles.

**Comment by urkerab** [comment]
I went for `Boosted` for the -ates because we already have `pranksterBoosted` but for the other abilities I went for `hasAbility` as I find it slightly less meaningless than `abilityFlag`.

**Comment by Zarel** [comment]
Thanks!

**Comment by urkerab** [comment]
I had a look at moves that use volatiles:

- Beat Up is weird, particularly in Gen 4, where it has to modify the user's Atk and defender's Def.
- Fell Stinger and Relic Song don't need a volatile because moves already get the AfterMoveSecondarySelf event.
- Fling and Natural Gift look overly complicated and can probably do all their work in the TryMove event handler.
- Triple Kick looks deceptively simple.
- Assurance, Beak Blast, Counter, Focus Punch, Me First, Metal Burst, Mirror Coat and Shell Trap and many other moves need per-turn or multi-turn volatiles for various reasons.

**Comment by Zarel** [comment]
I think the first four bullets can all just store temporary data in the `MoveCopy` object.

**Comment by Zarel** [comment]
Except possibly Beat Up, but I think Beat Up is still implemented as one move overall.

**Pull request merged**
