### PR TITLE
Add ignoring Aurora Veil to Infiltrator's description

### PR DESCRIPTION
**Pull request by asgdf**
The shortdesc still fits the 480px limit, albeit barely.

### CODE REVIEW

**Comment by Marty-D** [comment]
It was almost at the limit before, it's definitely over now.

**Comment by asgdf** [comment]
Oh huh, are there differences between browsers? I thought font size, width and margins were all fixed?

**Comment by Marty-D** [comment]
Probably OS differences, although even in Chrome a few more pixels are cut off for me.

**Comment by asgdf** [comment]
Oh, yeah, I tested on Firefox/Mint which apparently defaults to Helvetica which is quite a bit more compact.

**Comment by Marty-D** [comment]
Ah I see, yeah Helvetica definitely looks way better, even for chat.

**Comment by Zarel** [comment]
Helvetica is narrower; Verdana is more readable at low resolutions.

**Pull request merged**
