### PR TITLE
Added an exception in IP check.

### PR DESCRIPTION
**Pull request by SilverTactic**
Added an exception in the ip check so that the original user isn't recognized as an alt.
http://prntscr.com/6eyje8

### CODE REVIEW

**Comment by codelegend** [comment]
you should give a better and shorter commit summary. like `wifi plugin: added exception in ip check`

**Comment by SilverTactic** [comment]
@codelegend Done.

**Comment by codelegend** [comment]
I meant the commit summary, not the pull req title.

**Comment by SilverTactic** [comment]
Hmm well okay.

**Comment by codelegend** [comment]
@Zarel , this can be merged.

**Comment by Zarel** [comment]
No it can't, the commit summary is wrong.

**Comment by Zarel** [comment]
I guess it can, but for future reference, prefix commit summaries with the mod/plugin name if there is one.

**Comment by Zarel** [comment]
You did not add any exceptions to PS's own IP checks.

**Comment by Zarel** [comment]
So the commit summary as it stands is sort of a lie.

**Comment by SilverTactic** [comment]
@Zarel Lmao, okay, I'll type it in correctly next time. >.<

**Pull request merged**
