### PR TITLE
Add "/veekun" to the command list

### PR DESCRIPTION
**Pull request by Aurolux**
When the command list is given, "/veekun" will be listed in the informatative commands

### CODE REVIEW

**Comment by Zarel** [comment]
I don't think it's useful enough to go there?

**Comment by Zarel** [comment]
The goal is definitely not to overwhelm the user with a huge list, but just to go over common ones people might want to use.

**Comment by Aurolux** [comment]
Okay sounds good. Want me to close PR?

**Comment by Zarel** [comment]
Yeah, detailed documentation does feel like it'd be useful, though. I'll think about where to put it.

**Comment by Aurolux** [comment]
@Zarel We could have a list for uncommon commands. Though that would be unnecessary, then the command is essentially useless without anyone knowing of it.

**Comment by Zarel** [comment]
I guess the `/help` command could make reference to `/morehelp` or something...

**Pull request closed without merging**
