### PR TITLE
Clarify how to set EVs in /statcalc

### PR DESCRIPTION
**Pull request by Teremiare**

### CODE REVIEW

**Comment by Zarel** [comment]
Does this need to be rebased?

**Comment by Teremiare** [comment]
Fixed

**Comment by Zarel** [comment]
I thought it was fixed to no longer need the `ev` part?

**Comment by Teremiare** [comment]
oh, no that was only for the + and -, you still need the ev or evs if you don't end it with that

**Comment by Zarel** [comment]
annoying

**Pull request merged**
