### PR TITLE
Fix Fly + Gale Wings Interaction

### PR DESCRIPTION
**Pull request by Pikachuun**
http://www.smogon.com/forums/posts/6180153

As per this post. Feel free to close if the mechanics listed here are incorrect.

### CODE REVIEW

**Comment by DanUgore** [comment]
Sounds like correct/expected behavior but I haven't tested it

**Comment by Marty-D** [comment]
Fly is a Flying-type move on both turns, so it has +1 priority both turns. It's not like Gen 5 Prankster Assist calling a two-turn move at all.

**Comment by DanUgore** [comment]
Alright. GF was really serious about not having Divecats return

**Comment by Pikachuun** [comment]
Understood.

**Pull request closed without merging**
