### PR TITLE
Add BD (Belly Drum), Tflame, and Smogon Bird

### PR DESCRIPTION
**Pull request by Zipzapadam**

### CODE REVIEW

**Comment by AustinXII** [comment]
you forgot the , after smogon bird

**Comment by ascriptmaster** [comment]
"tfalme"

**Comment by ascriptmaster** [comment]
Do you know how to squash your commits?

**Comment by Zipzapadam** [comment]
Squashed

**Comment by Zipzapadam** [comment]
Squashed @ascriptmaster

**Comment by ascriptmaster** [comment]
Oh right, forgot about this

**Pull request merged**
