### PR TITLE
Random Battle: Ability and STAB Changes

### PR DESCRIPTION
**Pull request by ascriptmaster**
Upgrade Flash Fire's rank to bypass Early Bird (for Houndoom).

Sucker Punch cannot be the only STAB move on Special attackers.

Fixed issues with incorrect setup.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Bump

**Comment by TheImmortal** [comment]
I'm not satisfied with either of those. The rating is fine, and Sucker Punch being outright rejected affects Cacturne/Honchkrow/etc. They want another STAB, sure, but they don't want this being removed.

**Comment by ascriptmaster** [comment]
Forgot to mention that I updated this.

**Comment by ascriptmaster** [comment]
Can someone look at these changes? If nobody comments on it by like Tuesday I'll merge it as-is.

**Comment by TheImmortal** [comment]
You didn't remove the rating change.

**Comment by ascriptmaster** [comment]
But how do we prevent early bird? Even when the opponent has sleep inducers, flash fire is still going to be the optimal ability.

**Comment by TheImmortal** [comment]
Not that necessary. Houndoom gets Early Bird 33% of the time and it gets Houndoomite 74% of the time.

**Comment by ascriptmaster** [comment]
Even for Mega Houndoom, being able to switch into a Fire move for free the first time is nice. Early Bird won't proc fast enough because you'll want to go mega ASAP.

And regular Houndoom still wants Flash Fire as the optimal ability

**Comment by Slayer95** [comment]
When did Randbats set maker design philosophy turned into cookie-cutter set optimization?

**Comment by ascriptmaster** [comment]
It didn't

But Flash Fire is still better

**Comment by TheImmortal** [comment]
>Early Bird won't proc fast enough because you'll want to go mega ASAP.

That's my point, the ability doesn't matter cause you're going Mega asap.

Remove that change.

**Comment by ascriptmaster** [comment]
> That's my point, the ability doesn't matter cause you're going Mega asap.

Except that's also my point. Having flash fire gives you the chance to switch in to one fire move for free before you go mega, even though you lose the boost when you do mega evolve, while early bird does nothing for it.

It's obvious you don't want to change the rating, so do you have another suggestion regarding this issue.

**Comment by TheImmortal** [comment]
No. I don't see it as an "issue" either.

**Comment by ascriptmaster** [comment]
It's obvious we're at an impasse regarding the issue/non-issue of Flash Fire Houndoom. That change is removed for now; we'll discuss it with the rest of staff later.

**Pull request merged**
