### PR TITLE
Seasonals: Delta Stream does not affect Color Moves

### PR DESCRIPTION
**Pull request by ascriptmaster**
Affects Seasonals.

### CODE REVIEW

**Comment by Zarel** [comment]
Can you clarify?

**Comment by Zarel** [comment]
What moves specifically are affected by this change?

**Comment by ascriptmaster** [comment]
The current Seasonals' moves. And that's it.

There might be a better option that I haven't thought of yet, probably involving sticking a volatile on the mon so that it can read the `runEvent` instead of the `singleEvent` that the move is checking.

Also if we keep this version, don't merge yet because @TheImmortal already suggested another change that I'd need to do first

**Comment by Zarel** [comment]
I don't believe it should be implemented here.

**Comment by ascriptmaster** [comment]
I think I figured it out now? Give me a second

**Comment by ascriptmaster** [comment]
This should do the thing

**Comment by Zarel** [comment]
okay

**Pull request merged**
