### PR TITLE
Remove aliases /kick and /k from /warn.

### PR DESCRIPTION
**Pull request by NotBlizzard**

### CODE REVIEW

**Comment by Rhythms88** [comment]
I don't agree with this because a lot of room and global auth use /k for an easier and faster way of warning users

**Comment by ascriptmaster** [comment]
Why do you want these removed?

**Comment by panpawn** [comment]
>I don't agree with this because a lot of room and global auth use /k for an easier and faster way of warning users

I agree with this statement.

**Comment by kotarou3** [comment]
I said that statement right before he sent the pull request too

**Pull request closed without merging**
