### PR TITLE
(Minor) Add a [still] tag to Sky Drop's preparation turn

### PR DESCRIPTION
**Pull request by ascriptmaster**
This will let me change Sky Drop's animation properly back to a flight-style animation when I introduce the next graphics patch.

### CODE REVIEW

**Comment by Zarel** [comment]
Isn't there a straight-up `[prepare]` tag or something?

**Comment by Zarel** [comment]
How are two-turn moves usually handled, and why can't Sky Drop be handled that way?

**Comment by ascriptmaster** [comment]
So it turns out that it's actually my fault that it's like this.

I thought the `isTwoTurnMove` flag did more things than just be a flag for giving two-turn moves a `[still]` tag on their first turn, so I removed it when I fixed the Sky Drop code last time.

**Comment by Zarel** [comment]
You might want to update your commit message, too.

**Comment by Zarel** [comment]
meh, good enough

**Pull request merged**
