### PR TITLE
Seasonal: Implement February Seasonal: Han vs Hun

### PR DESCRIPTION
**Pull request by ascriptmaster**
To be opened on February 5! Do not merge until then!

Please double check the code to make sure everything makes sense, though.

### CODE REVIEW

**Comment by Zarel** [comment]
Remember to comment to remind me when you actually want me to merge.

**Comment by kotarou3** [comment]
ascriptmaster = Joim confirmed

**Comment by Joimer** [comment]
You forgot to add the new Cancel Mod, can you add it before tomorrow? I can merge and update the server the fifth of February at GMT morning / OCN night, the least populated hour and when Seasonals are updated.

Also nice work, we can start talking about March already!

**Comment by ascriptmaster** [comment]
It is done. Cancel Mod is in.

**Pull request merged**
