### PR TITLE
September tier and format changes

### PR DESCRIPTION
**Pull request by KrisOnline**

### CODE REVIEW

**Comment by KrisOnline** [comment]
@TheImmortal

**Comment by Zarel** [comment]
Need sources for all of these...

**Comment by Zarel** [comment]
#3959 has the right idea.

**Comment by Zarel** [comment]
...nevermind, the link isn't right either...

**Comment by TheImmortal** [comment]
Please don't merge everything into one pull request. Suspect tests should definitely not be a part of this.

**Comment by Zarel** [comment]
To be fair, it _is_ possible to rebase-merge

**Pull request merged**
