### PR TITLE
Arena Trap Typo Fix

### PR DESCRIPTION
**Pull request by ascriptmaster**
What does `hasType('ironball')` mean anyways?

### CODE REVIEW

**Comment by TheImmortal** [comment]
Use `hasItem`.

**Comment by kotarou3** [comment]
Generally the rule is, whenever you fix a bug, add a test for it

**Comment by TheImmortal** [comment]
Probably if it was real bug and not just a typo. Clearly whoever added this mean `hasItem` instead of `hasType`.

**Comment by ascriptmaster** [comment]
Do we even need half of these checks? `runImmunity` covers most of them except Ingrain, I think

**Comment by Slayer95** [comment]
Actually, the offending line here is <i>mostly</i> <code>runImmunity('Ground')</code>. Almost everywhere that this function is called, we want to check whether a Pokémon is grounded or airborne, and not whether it's affected by Ground (this can be seen by their effect in Inverse Battle).
Being grounded/airborne has a lot of subtleties, however, which is why <code>BattlePokemon.prototype.isGrounded()</code> hasn't been coded yet.

**Pull request merged**
