### PR TITLE
List Feint Attack after Feint

### PR DESCRIPTION
**Pull request by ekmnoop**
List Feint Attack after Feint, instead of before Fairy Lock (ei is not ai), because moves are listed alphabetically.

### CODE REVIEW

**Comment by scheibo** [comment]
Hi - thanks for your contributions, but do you think you could bundle all of these alphabetization changes into a single PR?

**Comment by ekmnoop** [comment]
Yes, I could, but my previous PR was merged already before I could upload changes :)

**Comment by scheibo** [comment]
Usually you don't open a PR (or at least open in as a 'Draft') if its incomplete.

**Comment by ekmnoop** [comment]
Sorry, I'm not very familiar with github, I'm used to command-line `git`.
How can I make this a “Draft” then?

**Comment by ekmnoop** [comment]
Also, is there a reason why paleowave, shadowstrike, and magikarpsrevenge are listed at the end of the file (below z)?

**Comment by scheibo** [comment]
In the Github UI when you make a PR there's a dropdown which allows you to open up a Draft PR instead. There's unfortunately no way to go back to a draft once a PR has been opened.

As for paleowave, shadowstrike, and magikarpsrevenge - I assume because they're all non standard?

**Comment by ekmnoop** [comment]
Thanks, I'll close this one then and start a new pull request as a draft.
Shouldn't non-standard moves be in a mod?

**Pull request closed without merging**
