### PR TITLE
Add pi command

### PR DESCRIPTION
**Pull request by panpawn**
I accidentally typed /ip as /pi, and I thought this would be a pretty humorous response.

Yay for meme commands!

### CODE REVIEW

**Comment by CrestfallPS** [comment]
A /pi command should add 3.14 to a user's username tbh :^) If their name is 17-19 characters remove the extra hehe

**Comment by Slayer95** [comment]
Imo it should display PI using at least 4 different radixes, including golden.

Also we could move both /joim and /pi to a meme plugin?

**Comment by Zarel** [comment]
imo you should link to http://guangcongluo.com/mempi/

**Comment by panpawn** [comment]
>Imo it should display PI using at least 4 different radixes, including golden.

lol okay
>Also we could move both /joim and /pi to a meme plugin?

Woah, that's some pretty serious dedication to meme'ing - I'm not sure if PS is ready for that... yet...

>imo you should link to http://guangcongluo.com/mempi/

It's like you secretly planned for this.

**Comment by bumbadadabum** [comment]
Please no meme commands.

**Comment by panpawn** [comment]
> including golden

I might need some help on that one, actually...

**Comment by bumbadadabum** [comment]
Don't go through all the effort for a meme command and just stop.

**Comment by Slayer95** [comment]
https://oeis.org/A102243

``100.0100 1010 1001 0001..``

Which is equal to

``11.0100 1010 1001 0001...``

The reason is left as an exercise to the reader.
Bonus points if equality and the sentence above are included in the command.

**Comment by Slayer95** [comment]
> Woah, that's some pretty serious dedication to meme'ing - I'm not sure if PS is ready for that... yet...

Actually, it's quite the opposite. I definitely don't want meme commands in ``chat-commands.js``

**Comment by xfix** [comment]
>  A /pi command should add 3.14 to a user's username tbh :^) If their name is 17-19 characters remove the extra hehe

That would have to be client side, however adding joke commands to client is not that great of an idea, because server may want to create its own `pi` command, and it would be better if a joke command wouldn't override it.

**Comment by bumbadadabum** [comment]
Why is this PR still open?

**Comment by Slayer95** [comment]
@bumbadadabum , evidently you are the only one fully opposed to it.

Last time I checked, you aren't the Owner of the project, so stop your demands.

**Comment by bumbadadabum** [comment]
Sorry I thought the consensus was to not have this in chat-commands or
publicly on the repo at all.

**Comment by Zarel** [comment]
No one's really commented enough to build consensus. Slayer95 doesn't want it in chat-commands; no one's opposed to having it publicly on the repo in general.

`chat-plugins/info.js` may be the best place; I don't personally think we have enough memes to have a meme plugin. But I wouldn't oppose `chat-plugins/memes.js`

Speaking of, does anyone fully support this? I'm mostly neutral.

**Comment by xfix** [comment]
I'm fine with it, although I did put some joke commands in Usain Bot, so I may be biased (I like easter eggs myself).

It's not like it's the first, there is also stuff like `/joim`, DOGARS easter egg and secret avatars (and some more secret features ;)).

**Comment by bumbadadabum** [comment]
The thing is as well that /ip is usually a command that's used in serious
contexts (you generally want to know someone's IP for a reason), and is
probably not the best context for a stupid meme to appear either. If people
actually do mistype /ip as /pi a lot, why not make /pi an alias for /ip,
instead of displaying a stupid joke.

**Comment by AustinXII** [comment]
I have to agree with @bumbadadabum

**Comment by Zarel** [comment]
We could compromise and display a pi meme followed by the result of the `/ip` command

**Comment by AustinXII** [comment]
@Zarel I guess but I would find that annoying rather than funny honestly

**Comment by panpawn** [comment]
>Why is this PR still open?

Why not?

Anyways, I'll update this shortly to better accommodate the expressed concerns above as soon as I have time.

**Comment by Ridaz** [comment]
> Why not?
This is such a basic/non constructive answer.
If we can't have `/rub`, why should we have this? We got enough meme commands, and like @AustinXII said, it's not as funny as it should

**Comment by Slayer95** [comment]
For God's sake, what's wrong in showing pi if a user asks for pi?

This almost looks like a quest for who has the less fun

**Comment by bumbadadabum** [comment]
I just don't find this particular joke funny.

**Comment by Zarel** [comment]
The issue with `/rub` is that we don't want people to do it accidentally. `/ip` has no side effects.

**Comment by kotarou3** [comment]
`ls` is used in serious contexts. But reminder that `sl` exists

**Comment by kotarou3** [comment]
`ls` is used in serious contexts. But reminder that `sl` exists

**Comment by kotarou3** [comment]
`ls` is used in serious contexts. But reminder that `sl` exists

**Comment by Morfent** [comment]
I don't like the idea of having a command like this take the place of the usual command-not-found message as an exception for the sake of the joke. It comes across as more mocking in comparison to me.

**Comment by Zarel** [comment]
Someone else can pullreq a move to the correct file or to add an actual IP below the pi stuff, but I see now harm in merging this now.

**Pull request merged**
