### PR TITLE
eslint: Update to 4.x

### PR DESCRIPTION
**Pull request by panpawn**
This is the latest stable version of eslint, as per https://david-dm.org/zarel/Pokemon-Showdown?type=dev

### CODE REVIEW

**Comment by panpawn** [comment]
I'm dumb; there is a lot more to this :|

**Comment by panpawn** [comment]
Is this something that's actually wanted, though?

**Comment by Zarel** [comment]
We'd need to piecewise decide what to do about each error.

Personally, I think unnecessary escapes aid readability in regexes (because regexes are always stupid unreadable) but I can see both sides.

**Comment by Zarel** [comment]
Every other one I agree with `eslint` on.

**Comment by Zarel** [comment]
Overall, I think `no-useless-escape` is probably good, especially since it standardizes code.

**Comment by Zarel** [comment]
So yes, feel free to fix every one of these errors.

**Comment by xfix** [comment]
```
/home/travis/build/Zarel/Pokemon-Showdown/chat-plugins/datasearch.js
...
  1372:41  error  Unnecessary escape character: \-  no-useless-escape
```

```javascript
descWords = descWords.replace(/super[\-\s]effective/g, 'supereffective');
```

I mean, yes, it's unnecessary here, but I feel like ESLint makes a mistake complaining about it, as whether `-` needs to be escaped in character groups is pretty context sensitive. I sorta would prefer code to show it didn't want to use a range (is there a lint in ESLint for extremely weird ranges?).

That said, because the lint sounds useful, and I don't think code with `\-` in groups will be changed often, I think it's fine to "fix" those instances.

**Comment by panpawn** [comment]
>Personally, I think unnecessary escapes aid readability in regexes... Overall, I think no-useless-escape is probably good, especially since it standardizes code.

So, should I make an exception for regexes?

**Comment by Zarel** [comment]
No, I think regexes are good. I personally put `-` at the end of a `[...]` block and don't escape it. We may just standardize on that.

**Comment by Zarel** [comment]
Like, did you miss my comment where I said "Overall, I think `no-useless-escape` is probably good, especially since it standardizes code" and "So yes, feel free to fix every one of these errors"?

And xfix's comment where he said "That said, because the lint sounds useful, and I don't think code with `\-` in groups will be changed often, I think it's fine to 'fix' those instances"?

**Comment by panpawn** [comment]
No, I just misinterpreted it, sorry.

I'll work on this as soon as I have time.

**Comment by panpawn** [comment]
This has been superseded by https://github.com/Zarel/Pokemon-Showdown/pull/3657

**Pull request closed without merging**
