### PR TITLE
Revert to Sun/Moon Alola Pokedex for VGC 2017

### PR DESCRIPTION
**Pull request by urkerab**
For example, Tyranitar should not be legal.

### CODE REVIEW

**Comment by Marty-D** [comment]
Good catch!

**Comment by urkerab** [comment]
You can thank +darkintruder!

**Comment by Zarel** [comment]
...this is not the latest code for the Alola Dex.

We specifically stopped using `:1` objects because benchmarks showed it was slower than `[...].includes`, and it's always been less readable.

**Comment by Zarel** [comment]
Whoa, apparently it is? I thought I refactored this code already? Did it get reverted while I wasn't paying attention?

**Comment by Zarel** [comment]
Okay, so #4079 _did_ happen; whew. Why didn't it touch `rulesets.js`? That's freaky. Apparently the regexes I used weren't general enough.

**Comment by Zarel** [comment]
Oh, I see, I only removed `... in {...}`; anything that involved declaring a variable got missed.

**Pull request merged**
