### PR TITLE
Fix Stomping Tantrum interaction with spread moves and Protect

### PR DESCRIPTION
**Pull request by MacChaeger**
https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-435642464
When I implemented this originally, I'd seen someone say this worked the other way around, so to get it to match on sim I had to put in some hard-coded hacks. Fixing this was as simple as taking them out.

### CODE REVIEW

**Comment by mathfreak231** [comment]
The issue with this is now hitting Protect once again doubles Stomping Tantrum when it shouldn't. (The unit test is only passing because, wouldn't ya know, Manaphy is hitting a double Protect. If it's changed so that it uses a dummy move t2, the test properly fails.)

**Comment by MacChaeger** [comment]
I can think of only one way to fix this, and it's gonna be hack-y again. We'll need a special return flag for the `"TryHit"` event (I'm thinking `0`) that tells `tryMoveHit` to return `null` instead of `false`. I was thinking that `runMoveInner` always returns whatever the events it calls return to it, but `tryMoveHit` runs a bunch of events that use `null` and `false` to respectively mean "already used a custom failure message/no failure message" and "use a 'But it failed!' message" instead of "Stomping Tantrum isn't boosted by this" and "Stomping Tantrum is boosted by this". These don't totally match up, as Protect is the only case (that I know of) where a failed `"TryHit"` event _doesn't_ boost Stomping Tantrum, so in light of the spread moves case that led to this problem, I think Protect-likes just need a special return flag that means "already used a custom failure message" AND "Stomping Tantrum isn't _necessarily_ boosted by this", or, "don't say "But it failed!", but return `null` instead of `false`".

**Comment by Zarel** [comment]
This is a good use-case for `undefined`, I think.

**Comment by Zarel** [comment]
Although the code for correctly supporting "neither success nor failure" would be a lot harder than before.

**Comment by Zarel** [comment]
A sentinel `this.NOT_FAILURE = "NOT_FAILURE"` might be easier.

**Pull request merged**
