### PR TITLE
Fix crash in /dexsearch

### PR DESCRIPTION
**Pull request by asgdf**
This also hopefully makes /dexsearch a bit less messy: there's no more on-the-fly learnset modifiying and filtering through moves is not done in two locations anymore.

### CODE REVIEW

**Comment by Zarel** [comment]
Doesn't this have horrible performance?

**Comment by Zarel** [comment]
I guess it's not a main process anymore, but still... ick.

**Comment by asgdf** [comment]
In what way? As far as I can tell, performance actually got better (about 170ms -> less than 100ms on my machine). Not sure how well that scales up with more users, of course.
I didn't really add anything, the call to checkLearnset() was there before, I just moved it.

**Comment by Zarel** [comment]
Oh. Hm.

**Pull request merged**
