### PR TITLE
Make formatting of smogon links consistent

### PR DESCRIPTION
**Pull request by KrisOnline**

### CODE REVIEW

**Comment by Zarel** [comment]
If you're going to make formatting changes, can you change them all to `` ` `` quotes?

**Comment by KrisOnline** [comment]
like throughout the project or for all links?

**Comment by Zarel** [comment]
It eliminates the need for `\"` in links.

Do it for all links and surrounding text.

**Comment by KrisOnline** [comment]
@Zarel can you merge this for now, I'll do the update to quotes when I'm not in the middle of recovering from wisdom tooth surgery

**Comment by Zarel** [comment]
mmk

**Pull request merged**
