### PR TITLE
Stop status desyncing when joining rooms or renaming

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm... going to be too lazy to hotpatch this. It can wait until next restart.

**Comment by Zarel** [comment]
This is at least partly my fault for merging bumba's refactor so hastily.

**Comment by Zarel** [comment]
Also, `getIdentityWithStatus` can now just be `name` or `name + '@!'`, right?

**Comment by whalemer** [comment]
Given that (afaik) we only use the status message in the userdetails popup, yes. If we want to include them in join/leave messages then we'd need to keep it.

**Pull request merged**
