### PR TITLE
Add cooldown to re-enabling timer after disabling it

### PR DESCRIPTION
**Pull request by asgdf**
Each player has their own cooldown. The point is to prevent spamming timer on/off to timerstall indefinitely.
This is my attempt of a server-side approach to the same problem as https://github.com/Zarel/Pokemon-Showdown-Client/pull/910
Should I add a type annotation for the ``lastDisabled`` object? Like "Object<string, number>"?

### CODE REVIEW

**Comment by Zarel** [comment]
We only need to track one requester, I think.

**Comment by asgdf** [comment]
Ok. Only keeps track of the last time the timer was disabled now. Also the cooldown now doesn't prevent requesting the timer to be on when it was switched on by the other player already.

**Comment by Zarel** [comment]
Should probably just have `lastDisabledUser` and `lastDisabledTime` as separate fields.

**Comment by asgdf** [comment]
Ok. (I think "lastDisabledUser" sounds a bit unclear so I went with "lastDisabled**By**User").

**Comment by Zarel** [comment]
Yay, thanks!

**Pull request merged**
