### PR TITLE
Cache node modules while testing

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by Zarel** [comment]
I don't think the build failure is your problem. hrm.

**Comment by Slayer95** [comment]
This is likely a NPM bug regarding https://github.com/npm/npm/issues?q=milestone%3A%22first-class+git%22

**Comment by Slayer95** [comment]
Can you rebase / force-push with a different commit hash so that Travis builds again?

**Comment by kotarou3** [comment]
I think Zarel can trigger a manual rebuild from travis

**Comment by Marty-D** [comment]
Actually, any collaborator can request a rebuild. I've done so for all currently open pull requests that recently failed, and most have completed by now.

**Comment by Zarel** [comment]
What I don't understand is _why_ requesting a rebuild is enough... shouldn't we have to rebase on the new longer timeout? Or did jscs fix their performance regression or something?

**Comment by xfix** [comment]
@Zarel This is because Travis doesn't test if commit works fine, but rather if it works fine **after** merging (because that's what projects usually care about).

**Comment by Zarel** [comment]
Oh, that makes sense.

**Comment by Zarel** [comment]
Anyway, won't caching `node_modules` mean that Travis won't automatically update to new versions of jscs etc?

**Comment by xfix** [comment]
@Zarel All it means is that the testing will be slightly faster because it will only check if there are updates available.

**Comment by Zarel** [comment]
It'll still check if there are updates available? Is this documented somewhere?

**Comment by xfix** [comment]
@Zarel: It simple. It caches `node_modules` directory, but still calls `npm install`. `npm install` can also update modules.

**Comment by Zarel** [comment]
Hm, I wonder if we could cache differences only.

**Comment by Zarel** [comment]
By which I mean that there's a `gulp` thing so you only relint files that have changed since the last lint. I wonder if Travis supports that.

**Comment by xfix** [comment]
Will look into that right now.

**Pull request merged**
