### PR TITLE
Eslint Fix

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by DeathlyPlays** [comment]
?

**Comment by DeathlyPlays** [comment]
https://travis-ci.org/Zarel/Pokemon-Showdown/builds/309313508

**Comment by Zarel** [comment]
The reason the build is failing is because Gen 4 Healing Wish is broken, and that's much higher priority than a formatting error.

**Comment by DeathlyPlays** [comment]
My bad, I was just trying to help :v

**Pull request closed without merging**
