### PR TITLE
Z-Memento and Z-Parting Shot should not heal the replacement if they fail

### PR DESCRIPTION
**Pull request by urkerab**
(Client-side changes to follow.)

### CODE REVIEW

**Comment by Marty-D** [comment]
Since when are those effects using the Healing Wish effect??? They don't cure status conditions...

**Comment by Zarel** [comment]
um, because I implemented them.

They should probably be implemented as a different effect in `statuses.js` if they're not identical.

**Comment by urkerab** [comment]
I'm going to assume it's OK to call this effect `healreplacement` for consistency.

**Comment by Zarel** [comment]
Sure.

**Comment by urkerab** [comment]
Added the side condition as a `self` so that it only works if the move succeeds.

**Comment by urkerab** [comment]
Actually adding the side condition as a self was wrong; the cartridge always sets the side condition. If the move fails (e.g. due to Protect) but the user switches anyway (e.g. due to Eject Button) then the side condition still needs to take effect. I'll create a new PR for this.

**Pull request merged**
