### PR TITLE
lol KOTA you're so dumb you don't know what var or boolean is lol

### PR DESCRIPTION
**Pull request by EmmaKitty**

### CODE REVIEW

**Comment by ScottehMax** [comment]
Please run `npm test` before committing.

**Comment by EmmaKitty** [comment]
no

**Comment by EmmaKitty** [comment]
fuku

**Comment by EmmaKitty** [comment]
at least let me run npm test bitch

**Comment by HeavenlyKitten** [comment]
Emmakitty who r u even

**Pull request closed without merging**
