### PR TITLE
Some roomnames shouldn't be allowed

### PR DESCRIPTION
**Pull request by panpawn**
This prevents the server from being able to make rooms with ids of: battles, teambuilder, rooms, ladder

### CODE REVIEW

**Comment by panpawn** [comment]
Wait, I have more to add.

**Comment by Slayer95** [comment]
This looks like something that should be dealt with client-side.
Maybe by namespacing system rooms?

**Comment by Zarel** [comment]
No, if anything should be namespaced, it should be chatrooms.

But Twitter gets away with not namespacing usernames... I suspect we can do the same.

Hardcoding them is fine. But the hardcoding should probably be in `addChatRoom`, not here.

**Comment by panpawn** [comment]
Alright, will update PR soon.

**Comment by panpawn** [comment]
Updated

**Pull request merged**
