### PR TITLE
Add /man alias for /help

### PR DESCRIPTION
**Pull request by Morfent**
Since /help is PS' equivalent to `man` and I keep doing this by accident all the time

### CODE REVIEW

**Comment by Zarel** [comment]
...my main worry is that `man` is actually an English word and this could confuse people...

**Comment by Zarel** [comment]
Vote, I guess.

**Comment by panpawn** [comment]
What platform(s) use this alias? I've literally never used or heard of this alias myself, but I'm also not against it.

**Comment by Morfent** [comment]
> What platform(s) use this alias? I've literally never used or heard of this alias myself, but I'm also not against it.
Every POSIX-compliant OS (Linux, BSD, Solaris, etc.)

**Comment by Zarel** [comment]
(Including macOS, for the record. Basically every common OS except Windows.)

**Comment by bumbadadabum** [comment]
I'm against joke commands tbh but if you're legitmately doing this wrong all the time I guess it's fine. Not feeling strongly about this

**Comment by bumbadadabum** [comment]
I guess this really doesn't cause any harm anyway

**Comment by panpawn** [comment]
I don't follow how this is a "joke command," but yeah, in that case, I think this is a good idea.

**Comment by AustinXII** [comment]
Yeah I don't see how man would be a joke command, It seems like it's a shortened way to say "manual"

**Comment by Zarel** [comment]
Looks like consensus is mostly in favor.

**Pull request merged**
