### PR TITLE
Make Leftovers/Black Sludge recovery happen during Grassy Terrain recovery

### PR DESCRIPTION
**Pull request by urkerab**
If you know a better way to avoid the duplication then I'm all ears.

### CODE REVIEW

**Comment by Zarel** [comment]
...let's just refactor the residual system?

**Comment by urkerab** [comment]
I looked into that but unfortunately I couldn't find a solution that would handle both the case of Grassy Terrain recovery happening on its last turn but Hail/Sandstorm damage doesn't.

**Comment by Zarel** [comment]
No, I mean, like, really refactor. We should make residual events way more like normal events.

**Comment by Zarel** [comment]
Crazy hack, but really refactoring residuals will happen probably never. :/

**Pull request merged**
