### PR TITLE
Remove a note about talking during moderated chat from /groups

### PR DESCRIPTION
**Pull request by xfix**
Modchat can be set for any rank, voice isn't anyhow special.

### CODE REVIEW

**Comment by Zarel** [comment]
On the other hand, modchat/modjoin _is_ a major use of the voice rank...

**Comment by Zarel** [comment]
Voice in particular has a special exception to the modjoin rules.

**Comment by xfix** [comment]
Frankly, most of the time when modchat+ is enabled, voices that weren't intended to talk shouldn't talk.

**Comment by Zarel** [comment]
Yes, but modjoin! Voices are always intended to be the exception to modjoin.

**Comment by Zarel** [comment]
After all, there's no reason to promote someone if you don't want them in the room at all.

**Pull request merged**
