### PR TITLE
Fix Leppa Berry

### PR DESCRIPTION
**Pull request by mathfreak231**
This fixes https://github.com/Zarel/Pokemon-Showdown/issues/2367#issuecomment-443505854

If I understand correctly, the Leppa Berry is normally eaten when any move is at 0 PP, and restores 10 PP to the first move with 0 PP. If the Leppa Berry is forcibly eaten through means such as Fling, it restores PP to the first move that has any PP missing. If all moves have full PP, nothing happens.

Thank @SadisticMystic for the research

### CODE REVIEW

**Comment by Zarel** [comment]
Is the `leppaberry` volatile necessary? My theory is that it's "first move with 0 PP if there's at least one move with 0 PP, otherwise first move with any PP missing".

**Comment by mathfreak231** [comment]
I can't say for sure, you'll have to ask someone who can research it

**Comment by Zarel** [comment]
@SadisticMystic?

**Comment by SadisticMystic** [comment]
In case of Fling/Bug Bite/Pluck, 0 PP does take precedence over an earlier move with some but not all PP missing.

**Comment by Zarel** [comment]
AS I SUSPECTED

**Comment by Zarel** [comment]
image

This is what I like to see.

**Pull request merged**
