### PR TITLE
Update dependencies and JSCS rules

### PR DESCRIPTION
**Pull request by Slayer95**
- All dependencies are optional except for `sockjs` and `sugar`.
- Fixes global variable leaks in `cloud-env` and `node-static`.
- JSCS: various rule additions regarding spacing; also yoda conditions banned.

### CODE REVIEW

**Comment by Zarel** [comment]
Do we need `sugar` anymore? Does ES6 do most of what we need now?

**Comment by Slayer95** [comment]
Hence "optional"!

It's needed only if PS is run in Node 0.10-0.12.

**Comment by Zarel** [comment]
Should we just implement them ourselves in-house (in `tools.js`)? We could also do them better, since Sugar is dumb and doesn't want to optimize.

**Comment by Zarel** [comment]
Why do we use `Number.prototype` methods? Blah, those are honestly the least intuitive APIs; they're like BDD in that they're just gimmicky to read like real English instead of actually making sense code-wise.

**Comment by Slayer95** [comment]
We should be able to easily replace most of sugar features except for date-related functions. Quinella suggested we use [https://github.com/Zarel/Pokemon-Showdown/pull/2033](moment.js) for them instead, which seems to be actively maintained.

Also, I haven't gotten around to write up a proper rationale for it, but #2033 should make ``Tools`` flexible enough to be required from any spawned node child process without adding any important load time from `data` and `mods`.

**Comment by Zarel** [comment]
What date-related functions do we even use? Like, in the repo, not in server config.

**Pull request merged**
