### PR TITLE
Configure Mocha to use the Nyan reporter

### PR DESCRIPTION
**Pull request by ascriptmaster**
It takes up less space now that we have so many tests.

Also it amused me.

### CODE REVIEW

**Comment by MJB47** [comment]
+

**Comment by xfix** [comment]
:+1:

**Comment by ascriptmaster** [comment]
Actually I stand corrected. While it does take up less space on your home console, it takes up SO MUCH SPACE on Travis.

**Comment by xfix** [comment]
Yeah, apparently Travis doesn't support \r escape sequence, so, yes, dots still better. Oh well.

**Comment by xfix** [comment]
That said, https://asciinema.org/a/255ag8f3luy5g8r8k2pdpjhz9 is still cute, so :+1:. Perhaps it would be feasible to disable Nyan for Travis CI?

**Comment by Zarel** [comment]
Dots also point out slow tests, which I like...

**Comment by ascriptmaster** [comment]
Nyan does too, by stopping when a test runs. But I guess you should be able to see slow tests after they're all done running.

But on the flip side, good luck figuring out which tests specifically are the slow ones.

**Comment by Zarel** [comment]
Still, I like dots for like three other reasons.

**Pull request closed without merging**
