### PR TITLE
Display healed pokémon on Aromatherapy/Heal Bell

### PR DESCRIPTION
**Pull request by Slayer95**
Reliant on https://github.com/Zarel/Pokemon-Showdown-Client/pull/258

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Um, Slayer... why are the time constraint commits in a pullreq about Aromatherapy

**Comment by Zarel** [comment]
Have we tested this and made sure there aren't graphical glitches?

**Comment by Zarel** [comment]
Right now I think most things like `-curestatus` assume that the thing passed to it is active.

**Comment by Zarel** [comment]
We might want to do something like `p1i:` for inactive pokemonids?

**Comment by Zarel** [comment]
This wasn't actually a problem, because we do Natural Cure before we actually switch, anyway.

**Comment by Zarel** [comment]
Okay, so, in theory, everything's good now?

**Comment by Zarel** [comment]
I mean, everything this pullreq depends on.

**Comment by Zarel** [comment]
@Marty-D, which generations does Aromatherapy/Heal Bell give a list of all pokemon healed?

**Comment by Marty-D** [comment]
@Zarel, just Gen 5 and 6.

**Comment by Marty-D** [comment]
Forgot this existed; fixed in https://github.com/Zarel/Pokemon-Showdown/commit/d8e4fe8486452a4bb31b4b5428f1869f4049aba0!

**Pull request closed without merging**
