### PR TITLE
Synchronize should trigger activations of other Abilities again

### PR DESCRIPTION
**Pull request by urkerab**
Reported [here](https://www.smogon.com/forums/posts/7877947). Regression from 82c792f.

### CODE REVIEW

**Comment by Zarel** [comment]
Actually forget my other comment, answer here. What exactly is this doing?

**Comment by urkerab** [comment]
Abilities suppress secondary effects silently. For instance, Limber makes you immune to the paralysis effect of Nuzzle, Stoked Sparksurfer and Zap Cannon, but silently, as if the secondary didn't exist.

On the other hand, if you use Glare or Thunder Wave, Limber visibly activates showing you that the target is immune to the effect.

Now consider the case of a Limber user trying to Nuzzle a Synchronize user. Synchronize actives and tries to paralyse the Limber user. This is now the primary effect of Synchronize (despite it being a secondary effect of Nuzzle) so Limber needs to visibly active to block the effect of Synchronize, in much the same way as Clear Body or Hyper Cutter visibly blocks the effect of Intimidate.

Effects where the status is primary have the relevant status property. Abilities use this to determine whether they should active the effect visibly or suppress the effect silently. Thus Synchronize has to provide an effect with the relevant status so that the Limber ability knows it needs to activate visibly.

**Comment by Zarel** [comment]
Okay, that makes sense. But something weird is going on with what makes an effect primary or secondary. How does this know that it's primary?

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/14c87afd6f7aa037e20369665e64ebf12a851b54/data/abilities.js#L1713-L1718

Looks like the detection is `!effect || !effect.status`.

I understand now; if `effect.status` exists, we assume the effect is primary, but if it doesn't, we assume it's because it's somewhere in `effect.secondary` and is a secondary effect.

That's certainly an elegant check, but it does cause an ugly hack here. Maybe we should flag secondariness in a different way.

**Comment by urkerab** [comment]
Would you prefer something along the lines of `Object.assign({status: status.id}, this.effect)`?

**Comment by Zarel** [comment]
No, I intentionally avoided that sort of code, it's just as hacky and worse for performance.

**Pull request merged**
