### PR TITLE
Tournaments: Implement reportjoins command

### PR DESCRIPTION
**Pull request by panpawn**
This allows for users running tournaments to make it so that when users join/leave the tournament during signup phase, it won't be reported to the room.  This is especially helpful for rooms with larger user counts such as the Lobby that might not want to be spammed with every single user who joins/leaves the tournament during signup phase.

It should be noted that it will still show the list of users who have joined the tournament where the bracket goes as it normally does, if this feature is used.

### CODE REVIEW

**Comment by Zarel** [comment]
Why is Lobby even running tournaments in the first place? o_o

**Comment by panpawn** [comment]
I'm not sure, but this command could still be helpful for other rooms as well as users attempting to join/leave spam a tournament wouldn't get reported to the room, if this command is used.

**Comment by panpawn** [comment]
@Zarel - I would like to note that the Lobby is still running tournaments fairly regularly, and this command could definitely be beneficial to other rooms running large tournaments as well.

**Comment by Zarel** [comment]
My proposed solution is still to create rooms for tournaments.

**Comment by Zarel** [comment]
This is also kind of weird as a server-side setting. We already have client-side tournament stuff...

**Comment by panpawn** [comment]
>This is also kind of weird as a server-side setting. We already have client-side tournament stuff...

The only client-side setting for tournaments user's have the option for is to either ignore tournaments or not to ignore tournaments.

The rest of the tournament settings are primarily done server-side.  Based on the current settings for tournaments that are toggle-able server-side, I feel like this kind of a change makes more sense primarily done server-side rather than client-side, imo

**Comment by Zarel** [comment]
I've talked to Lobby staff and they seem to intentionally use tournaments to distract people.

**Comment by Zarel** [comment]
@sirDonovan?

**Comment by sirDonovan** [comment]
I agree with this being a client-side setting. I'm considering other tournament/plugin settings to add and this can be one of them.

**Pull request closed without merging**
