### PR TITLE
Add /adduhtml

### PR DESCRIPTION
**Pull request by sirDonovan**

### CODE REVIEW

**Comment by Zarel** [comment]
?

**Comment by sirDonovan** [comment]
The main purpose is to allow bots that run scripted chat games or events to use HTML boxes without spamming.

**Comment by Zarel** [comment]
I'm not sure we need to blacklist existing uhtml patterns? I kind of dislike `PatternTester` in general.

**Comment by sirDonovan** [comment]
I'm fine with removing that.

**Pull request merged**
