### PR TITLE
Add Truant unit tests

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Requesting @Marty-D for review, specifically for the Truant+Sleep interaction.

Bulbapedia claims that "Truant is reset by sleep and a Pokémon with Truant will always be able to attack on the turn they wake up." However, what does this imply if a Slaking uses Sleep Talk or Snore while asleep? I don't have a copy of ORAS on hand, so I was unable to obtain the appropriate Pokemon for testing.

If Sleep Talk/Snore is blocked by Truant the turn after it uses a move and then falls asleep (either by its own effect such as Rest, or by an opponent's move), then the removeVolatile call needs to be moved to the end of the sleep block (instead of the beginning, as it is now)

**Comment by ascriptmaster** [comment]
Also, depending on what Marty confirms, I will write a unit test to ensure the correct behavior with Sleep Talk.

**Comment by Marty-D** [comment]
Bulbapedia is lying through its teeth as usual. Like I mentioned in https://www.smogon.com/forums/posts/7783715, Truant's BeforeMove check comes after sleep/freeze *because* they don't consume Truant "turns". That's part of the reason I removed the effect duration, which shouldn't have been there even when Truant wasn't fully understood.

**Comment by Zarel** [comment]
Can you edit Bulbapedia? In my experience they at least don't revert changes if you fix things.

**Comment by ascriptmaster** [comment]
Fixed unit test for current gen. Is the sleep stuff still true in past gens? Just making sure

**Comment by Marty-D** [comment]
They would always revert V4's changes, even with proof, so I stopped caring. I don't have an account and am not particularly interested in making one because of that.

Re: past gens, this is at least how it works starting from Gen 5, but I haven't found time to set up tests in Gen 3 or 4 yet. Also technically your wake up turn can be non-loafing, if your last action before falling asleep was loafing.

**Comment by Marty-D** [comment]
Thanks! 👍

**Pull request merged**
