### PR TITLE
Random Battle: Support Light Clay Aurora Veil

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Is there any reason why this shouldn't be put in, or whatever?

**Comment by Zarel** [comment]
Yeah, I can just accept it, I just usually just punt these things at TI. Did something happen to him?

**Comment by TheImmortal** [comment]
I was waiting for usage stats to see if Ninetails used this

**Comment by KrisOnline** [comment]
Yes this is its main set in OU and UU

**Comment by ascriptmaster** [comment]
80% usage in UU, 76% in OU. It's a pretty big deal

**Pull request merged**
