### PR TITLE
Tournaments: allow validation against tour banlists

### PR DESCRIPTION
**Pull request by sirDonovan**

### CODE REVIEW

**Comment by Zarel** [comment]
This is adding more and more complication to PS...

Custom formats would be a lot easier than this mess.

Can you just do that? Support custom formats specified with an ID like `customgame-ROOMID-tourNUMBER`?

**Comment by Zarel** [comment]
So that way, instead of complicating every bit of code dealing with formats, you'd just complicate `getFormat`.

**Comment by sirDonovan** [comment]
I can start working on custom formats, but this command will be useful either way and doesn't add anything new to the banlist code.

**Comment by Zarel** [comment]
That's fair. We can merge this for now.

**Pull request merged**
