### PR TITLE
Random Battle: Slightly tweak Hoopa, fix chance of Hoopa forme appearing

### PR DESCRIPTION
**Pull request by ascriptmaster**
Replaced Psyshock with Hyperspace Hole in Singles.

Reject Psychic with Hyperspace Hole in Doubles.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Other ideas based on usage stats:

- Give Hoopa Trick Room in Doubles (41%) and maybe even Singles (14.5%)
- Give Hoopa-Unbound Fire Punch in Singles (23%)
- Give Hoopa Unbound Gunk Shot (58% Singles, 36% Doubles)

**Comment by TheImmortal** [comment]
Psyshock is better is singles imo. It's too fast for Trick Room.

As for Unbound, add Gunk Shot and Substitute. Psychic is also good because it's better than Psyshock on mixed sets.

**Comment by ascriptmaster** [comment]
I'd say Psyshock and Hyperspace Hole are both good, since Hyperspace pierces subs (but subs are less common in randbats so maybe it isn't as useful). I understand that its low usage makes it hard to tell what moves work well on it, though.

Gardevoir and Gallade have Trick Room in Randdubs, and they're base 80. Hoopa is base 70. I'm not saying it should get TR in singles at all, honestly.

You haven't responded to my question about removing Nasty Plot from Unbound. Is it worth removing? (Probably not but I need your opinion anyways)

**Comment by TheImmortal** [comment]
And Protect is rare in singles.

Oh doubles, if faster Pokemon have it then fine.

Nah. Nasty Plot is quite viable.

**Comment by ascriptmaster** [comment]
What about Fire Punch Unbound? It has twice the usage as Ice Punch on him

**Comment by ascriptmaster** [comment]
I did the thing.

**Comment by TheImmortal** [comment]
I meant keep Psyshock on Unbound, but add Psychic as well.

Fire Punch only really hits Scizor/Forretress/Escavalier/Mawile. Ice Punch hits a lot more, Gliscor/Gligar/Dragonite/Salamence/Rayquaza/Landorus-I/Landorus-T/Mandibuzz/Togekiss/Hawlucha. And those are just what I remember.

In addition, we don't have Hoopa-U analyses yet on Smogon so we can only go by the thread in OU, which I'm pretty sure lists Ice Punch a lot more than Fire Punch.

**Comment by ascriptmaster** [comment]
A thing.

**Pull request merged**
