### PR TITLE
Commands: prevent unintentionally adding/removing aliases to the wrong room

### PR DESCRIPTION
**Pull request by Morfent**
Also added help entries.

### CODE REVIEW

**Comment by Zarel** [comment]
Why?

**Comment by Morfent** [comment]
Just had a case where a leader accidentally added `digidigimon` and `digimondigi` to staff trying to add `digi` as an alias to the Digimon room. I don't think staff having to be in the room they're adding an alias to is entirely necessary

**Comment by Zarel** [comment]
We can just give an error message if `,` is sent.

**Comment by Morfent** [comment]
Why would that be more preferable? I can do that, just I'm not sure why it's necessary to be in the room you're adding an alias to

**Comment by Zarel** [comment]
Slightly less typo risk.

**Comment by Zarel** [comment]
Commands that change the room in some sense should be made in the room, especially if they're rarely-used commands.

**Comment by Morfent** [comment]
Fair enough

**Pull request merged**
