### PR TITLE
Fix Fusion Bolt and Fusion Flare's interaction with each other

### PR DESCRIPTION
**Pull request by jmclemo6**
This should fix https://github.com/Zarel/Pokemon-Showdown/projects/3#card-18662639

### CODE REVIEW

**Comment by Marty-D** [comment]
`moveThisTurn` isn't necessarily the last move used by any Pokemon that turn. In Triples for example, up to 4 Pokemon could have used a different move in between, in which case the next Fusion move shouldn't be doubled.

**Comment by jmclemo6** [comment]
RIP. I'll take a more intensive crack at this later.

**Comment by jmclemo6** [comment]
@Marty-D does this look alright now?

**Comment by Marty-D** [comment]
Looks good to me, thanks! 👍

**Pull request merged**
