### PR TITLE
Discussion: user disposal and plugins

### PR DESCRIPTION
**Pull request by Slayer95**
We now keep track of tournaments in which users currently are

### CODE REVIEW

**Comment by Zarel** [comment]
It seems like we should use some sort of more-general model for this...

**Comment by Slayer95** [comment]
That was not the sort of comment I was expecting but you are right.
We should then think of an API to expose to plugins so that they also get rid of inactive users.

**Comment by Zarel** [comment]
I've actually been thinking of a general model for this.

Really just two-way tracking between users and rooms in which they're participating in things.

For battle rooms, that'd be rooms they're battling in. For chat rooms, that'd be tournaments or room script games (limit 1 at a time).

**Comment by Slayer95** [comment]
Yea. They need to be standardized though.
- <code>user</code> -> plugin map would be the easiest I think. A plugin would just call methods like <code>user.onJoinEvent(plugin_id, event_id)</code> or <code>user.onLeaveEvent(plugin_id, event_id)</code>, and we set/clear everything at <code>users.js</code> side.
- <code>plugin</code> -> <code>user</code> map is gonna be an issue. We may call <code>plugin.onDestroyUser(plugin_id, event_id)</code>... but we need to set up such a method for <i>every</i> plugin in which is relevant <_> Anything simpler than that is not viable, as there are plugins that store users in plain objects, others in maps, or sets, and some even in multiple places at the same time. The last one is the case of tournaments actually, and I am not satisfied enough with just disqualifying them :|

Won't have time for this for a while. Definitively not this week...
(Why can't PRs just be transformed into issues with a click? :|)

**Comment by Zarel** [comment]
I mean, I said two-way map. Every user has a `roomid` -> `holdtype` mapping, every room has a `userid` -> `holdtype` mapping.

I say "hold" because if a user has any holds, they should be prevented from changing their name. The battle puts a "hold" on their username.

`holdtype` can be `battle`, `tournament`, or the name of a plugin (maybe namespaced, so it'd be like `#scavengers` so plugins wouldn't conflict with possible future official hold types)

**Comment by Zarel** [comment]
Actually, new idea: instead of the concept of "hold", we have the concept of "player".

`room.players` works like `room.users` except only tracking stuff.

And users would have `roomPlayerCount` in addition to `roomCount` for the reverse mapping.

We don't need `holdtype`, rather, we specifically have `room.game` specify exactly what type of player the room has. I don't think there's a need for a room to simultaneously run a tournament and a scripted plugin-game, anyway.

**Comment by Slayer95** [comment]
<code>they should be prevented from changing their name</code>
What about unrated battles? Also tournaments are specifically coded to support player renames...

<code>I don't think there's a need for a room to simultaneously run a tournament and a scripted plugin-game, anyway.</code>

Sure, there isn't a need. But making it impossible to hold both a tournament and a short game, or even a trivia doesn't sound reasonable; after all, some people may attend the tournament and other people may play the alternate game. Also, there is the issue that it's planned (tagging @kotarou3 to confirm) to support multiple tournaments in the same room -specifically the Tournaments room.

--

Also, I am not convinced that we should pledge to linking plugins to rooms. What about chat games running across multiple rooms? (I think that was the original idea of Scavengers?)

**Comment by kotarou3** [comment]
Re: Multiple tournaments in a single room

I talked with Zarel about it a while back, and he basically said scrap the idea of multiple tournaments per room.
(This doesn't mean the code can't be easily modified to support multiple tournaments per room. In fact, it was designed with that in mind, and only the glue between room and tournaments need to be changed)

**Comment by Zarel** [comment]
> But making it impossible to hold both a tournament and a short game, or even a trivia doesn't sound reasonable; after all, some people may attend the tournament and other people may play the alternate game.

Why? The Staff room has a "don't interrupt serious dicussion" rule precisely because multiple things going on in the same room is really annoying to follow for everyone involved. What we should probably do instead is have something like having scripted games create their own room for the game, like how battles work.

**Comment by Slayer95** [comment]
```The Staff room has a "don't interrupt serious dicussion" rule precisely because multiple things going on in the same room is really annoying to follow for everyone involved```

I thought it was to avoid trivialization of relevant matters? If it were otherwise, it could just be "discuss one thing at a time".

```have something like having scripted games create their own room for the game```
Sounds very overkill but it's an interesting alternative.

**Comment by Zarel** [comment]
@Slayer95, use `>` to quote, like in e-mail...

**Comment by Zarel** [comment]
> If it were just to avoid multiple things at a time, why not just make it read "discuss one thing at a time"? :|

Well, it's usually unnecessary to be that harsh, but yes, it _is_ annoying when people discuss multiple important things at a time, and people get confused a lot when that happens.

It's the same when it's serious talk and when it's games. Especially since scripted games/tournaments fill the chat log with lots of messages... It seriously doesn't make sense to have more than one going on at a time. Imagine more than one battle going on in a battle room, each battle adding its own "POKEMON lost 26% of its health" messages.

**Comment by Slayer95** [comment]
Ok. I have slept over it, and while I am not yet fully comfortable with the idea, I now agree due to scalability.

**Comment by Slayer95** [comment]
The proposal doesn't handle the possibility of plugins running across multiple or no rooms hmm....

**Comment by Zarel** [comment]
Multiple rooms: One of the rooms should be designated as the main room.

No rooms: ...why?

**Comment by Slayer95** [comment]
I guess it makes more sense as "no specific room" = "server-wide".

Stick it to global room? o_o

**Comment by Zarel** [comment]
What kind of game would be server-wide?

**Comment by Slayer95** [comment]
Some sort of hunt? It doesn't need to be a "game" though.

In general, I can imagine chat-enhancing plugins (say instant-messaging-client-like features) that may hold references to users, and need to get rid of them when the ``User`` instances are destroyed.

**Comment by Zarel** [comment]
I'm not sure a server-wide game would use this game API. Is there any reason it needs to?

In any case, no one should hold references to users. That just leads to bugs.

**Comment by Zarel** [comment]
Alternatively: You can just create a new room for a server-wide game. It's not like a single additional room is all that problematic.

**Comment by Slayer95** [comment]
Fiiine.

**Pull request closed without merging**
