### PR TITLE
Targets of the wrong type are immune to Synchronoise

### PR DESCRIPTION
**Pull request by urkerab**
PS! currently displays "But it failed!" in this case, which is wrong according to a YouTube video I watched recently (sorry I've mislaid it but I'll comment if I find it again.)

### CODE REVIEW

**Comment by Zarel** [comment]
Should we implement this in `onImmunity` or however we screw with immunity?

**Comment by Zarel** [comment]
It may affect mechanics.

**Comment by urkerab** [comment]
Ah, right, you need to know whether the move can miss. (`onImmunity` is only for status immunity).

**Comment by urkerab** [comment]
Meritt kindly researched for me that it can only miss semi-invulnerable targets, otherwise targets of the wrong type are simply immune as if they were Dark type.

Unfortunately the sim as currently implemented doesn't let the move itself check for immunity between the semi-invulnerable check and the accuracy check; the `TryHit` event that Abilities use does happen in between, but the `TryHit` that the move itself sees happens after accuracy. On the other hand, the problem with the `Try` event is that it happens before the semi-invulnerable check. Currently my best idea is to disable the accuracy check for immune targets in the `Try` event, so that the semi-invulnerable check will process as normal before the `TryHit` event flags up the immunity.

**Pull request merged**
