### PR TITLE
Adding /jeopardy to "Driver Commands".

### PR DESCRIPTION
**Pull request by Bryan-0**
Adding the /jeopardy command to "Driver Commands", because on 'config.js' the Drivers (%) can do /jeopardy.

### CODE REVIEW

**Comment by AustinXII** [comment]
isnt this pointless since if you do /help jeopardy or w/e the help command is for jeopardy it will tell you what ranks can do what? If jeopardy doesn't have this then maybe its a better idea to add that to the jeopardy commands

**Comment by Bryan-0** [comment]
@AustinXII, 2 things: 

First: /help jeopardy doesn't exist, is /jeopardy help.

Second: I'm adding /jeopardy on _Driver Commands_ because if you see "config.js" in this part: http://hastebin.com/netulidati.sm 'Drivers' can do /jeopardy, so i think that it will be good to add it on help too.

**Comment by AustinXII** [comment]
yes I see that now, I did edit my comment earlier though

**Comment by Zarel** [comment]
Jeopardy is an unofficial chat plugin; it should not be documented in the official help.

**Comment by Zarel** [comment]
I'm open to other ways to document, perhaps even in the main `/help` command, but I don't think sticking it among a bunch of moderation commands is the right approach.

**Comment by Bryan-0** [comment]
Ok.

**Pull request closed without merging**
