### PR TITLE
Standardize formatting of OM restrictions

### PR DESCRIPTION
**Pull request by KrisOnline**
Since I've already started adding and changing all of the OM banlists to allow them to be viewable though `/om`, I figured that I'd take the final step and standardize all OM banlists and restrictions. It's understandable if you want things like 1v1's banlist and ruleset to remain the same as before; I'll happily revert that part.

### CODE REVIEW

**Comment by KrisOnline** [comment]
I also didn't touch BH's banlist because it isn't based off of any metagame.

**Comment by MacChaeger** [comment]
I like the use of the unbanlist feature. Be sure to update the /mixandmega command’s check for Pokémon that aren’t allowed to mega, while you’re at it.

**Comment by TheImmortal** [comment]
1v1 isn’t directly based on OU; OU bans don’t/shouldn’t automatically be 1v1 bans. Revert it.

**Comment by MacChaeger** [comment]
Oh yeah, I was wondering why we weren’t already using unbanlists. Now that you mention it, doesn’t the same go for every OM that allows a few Ubers?

P.S. Oh, and you already updated the command... I shouldn’t try commenting on code at 2 AM.

**Comment by KrisOnline** [comment]
done @TheImmortal

**Comment by KrisOnline** [comment]
@theimmortal ?

**Pull request merged**
