### PR TITLE
Added a note to README for use on Ubuntu

### PR DESCRIPTION
**Pull request by th174**

### CODE REVIEW

**Comment by panpawn** [comment]
>(If you're not on Windows, we recommend doing `./pokemon-showdown` instead.)

... Doesn't this say that if you're using Ubuntu, to use ``./pokemon-showdown``?

**Comment by th174** [comment]
It doesn't work if you use ./pokemon-showdown because the shebang line is `/usr/bin/env node`

In order to run on Ubuntu, you need to use `nodejs` not `node`.

**Comment by xfix** [comment]
@th174 

Or you can just install `nodejs-legacy`. Also, in Ubuntu 17.10 installing nodejs-legacy won't be even necessary to be able to use `node` as a binary name.

**Comment by xfix** [comment]
It's probably easier to install nodejs-legacy I feel like which provides `node` to `nodejs` symlink. Also, in Ubuntu 17.10 it won't be necessary to install nodejs-legacy.

**Pull request closed without merging**
