### PR TITLE
Gen 1: Full paralysis chance is 63/256

### PR DESCRIPTION
**Pull request by Guernouille**
https://github.com/iimarckus/pokered/blob/master/engine/battle/core.asm#L3504

### CODE REVIEW

**Comment by Irraquated** [comment]
Why are there two pull requests for this?

**Comment by xfix** [comment]
@Irraquated: Separate mods, would say it's fine.

**Comment by Irraquated** [comment]
Ah, fair enough.

**Comment by Guernouille** [comment]
Yeah, I thought it would be better to commit one for each mod, but I was not sure about it. If changing both files in a single commit would be better next time, please tell me =)

**Comment by Irraquated** [comment]
@Guernouille it would make reviewing the pull request easier, in this case I guess it's fine because it's just changing a number.

**Comment by Zarel** [comment]
Yes, both in a single commit would be preferred.

**Pull request merged**
