### PR TITLE
CONTRIBUTING.md: Clarify template string usage

### PR DESCRIPTION
**Pull request by panpawn**
Based on discussion in the Development room

### CODE REVIEW

**Comment by Zarel** [comment]
I may have to write more template string code so people have a better idea of what I mean :/

**Comment by bumbadadabum** [comment]
I wouldn't make it a blanket thing like this.

**Comment by panpawn** [comment]
>I wouldn't make it a blanket thing like this.

Most things in CONTRIBUTING.md are kind of a blanket; it's supposed to be a guide when contributing.

**Comment by bumbadadabum** [comment]
Then don't put it in there. The thing about multiline strings is fine, but "serious string processing like ternary operators" is both wrong and vague

**Comment by panpawn** [comment]
>Then don't put it in there. The thing about multiline strings is fine, but "serious string processing like ternary operators" is both wrong and vague
Do you suggest a better way of phrasing it?

**Pull request closed without merging**
