### PR TITLE
Convert `data` and `mods` to modern standards

### PR DESCRIPTION
**Pull request by Rhythms88**

### CODE REVIEW

**Comment by Rhythms88** [comment]
Zarel asked the Dev room if anyone wanted to this, so I said sure

**Comment by Rhythms88** [comment]
so apparently trailing whitespace is required after commas now?

**Comment by kotarou3** [comment]
Shouldn't reverting https://github.com/Zarel/Pokemon-Showdown/pull/2316 be mostly what you need?

**Comment by Zarel** [comment]
Don't you have `npm test`? I thought you did.......

**Comment by Zarel** [comment]
Superseded by #2350

**Comment by Rhythms88** [comment]
Sorry for the late reply, but yes, I do have `npm test`, but these errors didn't show up when i did this. So sorry!

**Pull request closed without merging**
