### PR TITLE
Remove unused Tier Shift mod

### PR DESCRIPTION
**Pull request by Spandamn**
[12:59:21] Spandan: please tell me
[12:59:28] Spandan: whether Tier shift is gonna return
[12:59:40] Spandan: either as a challenge only or as a ladder
[13:00:24] +Ransei: probably not

### CODE REVIEW

**Comment by urkerab** [comment]
I'm trying to work on a way of implementing Tier Shift without using a mod anyway, just in case.

**Comment by Zarel** [comment]
@TheImmortal?

**Comment by TheImmortal** [comment]
If you're asking me, I left it on purpose because Tier Shift will come back when we have tiers. If you don't care about unused mods then keep it.

**Comment by Spandamn** [comment]
Like urkerab said, its possible to implement it without a mod:
https://gist.github.com/Spandamn/4f7826f1a47fbaf902032d73c1d6356a
Something like that (might have a couple of errors)

**Comment by Zarel** [comment]
@Spandamn, that wouldn't preserve through forme changes.

Maybe a base-stat-change event would be necessary for that.

**Comment by Spandamn** [comment]
well, the sample was just to show it was possible :)
ill update it in a while

**Comment by urkerab** [comment]
In case you're wondering, I implemented it on ROM using an `onBeforeFormeChange` callback (unsurprisingly, called near the beginning of `formeChange`). This gets called automatically by `new BattlePokemon` via `clearVolatile`, so it handles the starting case as well as forme changes. I had problems with the HP though; currently I get `formeChange` to recalculate the HP (doing some of the work of Power Construct too).

**Comment by Zarel** [comment]
Forme changes generally don't affect HP or max HP... Power Construct is explicitly an exception.

**Comment by urkerab** [comment]
Then again, Power Construct is the first forme change that changes base HP. (Since no other forme changes change base HP, recalculating the HP makes no difference there.)

**Comment by Zarel** [comment]
#3228 is good and will be merged in eventually, which means that the old Tier Shift mod is no longer necessary.

**Comment by Zarel** [comment]
Thanks, Spandan!

**Pull request merged**
