### PR TITLE
PMs: Prevent sending messages to self

### PR DESCRIPTION
**Pull request by ShadesOfBlack**
How to replicate:
   - Imagine your name is "user123"

Type in chat "/msg user123, content" and it will send a PM to yourself.

### CODE REVIEW

**Comment by Spandamn** [comment]
I don't think this is required; Sending pns to self can be used for various purposes like lag testing, testing formatting, etc

**Comment by AustinXII** [comment]
Agreeing with @Spandamn

**Comment by ShadesOfBlack** [comment]
Perhaps send a response back instead of actually sending the message then?

**Comment by HoeenCoder** [comment]
Sending PMs to yourself can be useful for testing things (lag tests, formatting tests, i used it to test a bug with spoilers yesterday too), and even for notes-to-yourself (i do that occasianlly). I dont think this is a good idea.

**Comment by Zarel** [comment]
We have a lot of code for specifically handling sending PMs to yourself without doubling. This is intentional behavior.

**Pull request closed without merging**
