### PR TITLE
Add /staffintro to /roomhelp

### PR DESCRIPTION
**Pull request by panpawn**
Room moderators now gain a new command (/staffintro), so we can list it in /roomhelp along with the others.

### CODE REVIEW

**Comment by Zarel** [comment]
Why isn't it same level as roomintro, anyway?

@sirDonovan, can we just change it to be RO+ like roomintro?

**Comment by panpawn** [comment]
I was actually thinking about this command a lot on how spammy it is, and yet how useful it is to new users.

I was thinking about a new way to make it be just as effective as it is currently but also be more efficient.  I was thinking of doing something along the lines of:


Once you click a button, it will then send that user a popup with the respected information.  This way, users are not forced to look at information that does not pertain to what they are looking for, but yet remains effective in aiding them in what they need help with.

**Comment by Slayer95** [comment]
I wouldn't call one extra click more efficient.

But we could hide each section until they are hovered over.

**Comment by panpawn** [comment]
I'm not sure how much harder it is to click a button than to hover over something o_o?

**Comment by Zarel** [comment]
I don't like either way.

roomhelp isn't meant to be broadcasted except once on room creation, really. Let's just increase its broadcast requirement or something.

**Comment by Zarel** [comment]
IOW, roomhelp is exactly the right size for what it's meant to be.

**Comment by panpawn** [comment]
Alright.  Also, I'll update this PR when we can determine what rank /staffintro is actually going to be for long term.

**Comment by sirDonovan** [comment]
@Zarel It wouldn't be a huge deal to make it RO+, but it would be helpful for most rooms if mods could keep access. They usually help manage topics in the off-site locations that /staffintro is meant to replicate, like Skype groups.

**Comment by Zarel** [comment]
Fine for now, I guess. We'll see how it goes.

**Pull request merged**
