### PR TITLE
Add "Pokémon" in simulator-doc.txt

### PR DESCRIPTION
**Pull request by Bryan-0**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Oh, while you're here, could you possibly look over the rest of the document to make sure it's accurate? The only obvious thing that comes to mind is the fact that `InterruptMove` does not exist (any more) and is still mentioned in the doc.

**Comment by Bryan-0** [comment]
Ok.

**Comment by Bryan-0** [comment]
So, you want that I remove the complete line of 'Interrupt Move'? (Line: 58)@ascriptmaster

**Comment by ascriptmaster** [comment]
Yeah. And figure out if anything else needs changing too if you have time.

**Comment by Bryan-0** [comment]
Ok.

**Comment by Bryan-0** [comment]
Updated.

**Pull request merged**
