### PR TITLE
Add vkun as an alias to the veekun command

### PR DESCRIPTION
**Pull request by Ridaz**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Who requested this? I don't know if the alias will be used by anyone...

**Comment by Ridaz** [comment]
[09:13:05] +Ridaz: xfix, how does vkun and/or vk sound as aliases for the veekun command
[09:13:31] &xfix: I don't know, really.
[09:14:48] +Ridaz: I mean, people use !dex and !dt
[09:14:59] +Ridaz: which is easier than typing !veekun
[09:15:06] &xfix: I don't see why not(...)
[09:15:35] &xfix: Either way, vk is not happening.
[09:17:07] +Ridaz: vkun then
[09:20:17] &xfix: DuckDuckGo only has !veekun, but I may consider vkun here.

**Comment by xfix** [comment]
I actually asked Ridaz to send a pull request if he wants `vkun`. I'm neutral towards it (`vk` is no, because @Zarel doesn't two letter commands to be taken without a really good reason).

**Comment by Zarel** [comment]
Is `/veekun` used so commonly as to need an alias? o_O

**Comment by Rhythms88** [comment]
I don't think it's been hotpatched yet ._.

**Comment by Joimer** [comment]
I don't think the /veekun commands needs an alias.

**Comment by xfix** [comment]
As far I'm concerned, nobody thinks this is a good idea (I'm neutral myself on this), so might as well close it, because I don't see it being merged.

**Pull request closed without merging**
