### PR TITLE
Add Eternal Floette Random Battle Movesets and Aliases

### PR DESCRIPTION
**Pull request by ascriptmaster**
Mostly just for Seasonals purposes, really.

Made "Eternal Floette" and "Floette-Eternal" aliases for
Floette-Eternal-Flower, which is a mouthful.

(Do we need to add "Eternal Flower Floette" as well? Unsure)

### CODE REVIEW

**Comment by Marty-D** [comment]
Oh, why is it called Floette-Eternal-Flower? The "Flower" part is the forme type that appears in most other forme names, which we drop with no exceptions as far as I know.
Wormadam Trash Cloak is just Wormadam-Trash, Basculin Blue-Striped Form is just Basculin-Blue-Striped, Tornadus Therian Forme is just Tornadus-Therian, etc. (and Gastrodon East Sea would just be Gastrodon-East when implemented I presume)

Opinions?

**Comment by ascriptmaster** [comment]
It's Floette (Eternal Flower forme), like how Basculin (Blue-Striped) is Basculin-Blue-Striped, not Basculin-Blue.

Although, Smogon refers to it as Floette-Eternal.

**Comment by Marty-D** [comment]
I'm saying the game actually refers to them as "Eternal Flower" and "Blue-Striped Form". There are plenty more examples here: http://pastebin.com/t1Krxt5t

Also, the 20 character limit on PS isn't even long enough for Basculin-Blue-Striped let alone Floette-Eternal-Flower.

**Comment by ascriptmaster** [comment]
> Also, the 20 character limit on PS isn't even long enough for Basculin-Blue-Striped let alone Floette-Eternal-Flower.

lol

I guess this is an issue we have to talk to @Zarel about. Zarel, should we shorten the names of these super-long forme names? We can always alias the old names back.

**Comment by ascriptmaster** [comment]
Also, due to Floette's offensive nature, maybe I should add more attack options like HP-Fire or Energy Ball.

**Comment by Marty-D** [comment]
A lot of this seemed very familiar, and it looks like I've had this conversation before:
```
2014-03-01
20:08:18: <Layell> some places are calling it eternal flower but I went with floette-az to be nice and short
20:09:08: <TheImmortal> it's eternal flower in the pokedex, apparently
20:10:40: <TheImmortal> Floette-Eternal-Flower :D
20:10:47: <TheImmortal> nice and... long?
20:12:36: <Layell> I'll let someone else have the honour of changing that
20:13:43: <Marty> oh god that's even longer than Basculin Blue-Striped :/
20:13:50: <TheImmortal> lol
20:13:59: <TheImmortal> also hi Marty
20:14:01: <Marty> plus it'll be truncated to Floette Eternal-Flow
20:14:04: <Marty> hey TheImmortal :)
20:14:52: <Joim> hi marty
20:15:22: <Marty> hey Joim
20:15:35: <Marty> up the character limit on nicknames to 22 imo
20:16:09: <Joim> I'm sure zarel wouldn't like that xD
20:16:38: <Marty> Basculin Blue-Striped already doesn't fit
20:17:41: <Joim> lol
20:19:18: <Zhorken> why not just Floette-Eternal?
20:19:30: <Zhorken> aren't the others Floette-Red etc?
20:20:22: <TheImmortal> the others are Red Flower and such in the pokedex too
20:20:28: <TheImmortal> they're not on PS
20:20:51: <TheImmortal> i guess we could drop the flower
20:20:53: <Zhorken> oh, yeah, I guess they wouldn't be
20:21:10: <Zhorken> but yeah "Flower" is Floette's version of "Form" as far as I'm concerned
```

**Comment by Slayer95** [comment]
Why not say that <code>Striped</code> is Basculin's form equivalent, say that normal Basculin is Basculin-Red and the other one is Basculin-Blue, and call it a day?

**Comment by Zarel** [comment]
I'd say Floette-Eternal and Basculin-Blue.

**Pull request merged**
