### PR TITLE
Cheek pouch fix

### PR DESCRIPTION
**Pull request by alex-taxiera**
Changed `EatItem` to `TryEatItem` and adjusted calls in items.js
Cheek Pouch now triggers on the new `EatItem` event after `Eat`
Added the new `EatItem` event to Bug Bite, Pluck, and Fling so that Cheek Pouch will trigger

I agree to the MIT license.

### CODE REVIEW

**Comment by Marty-D** [comment]
Nicely done! Only thing missing seems to be renaming Unnerve's use of `EatItem`.

**Comment by alex-taxiera** [comment]
@Marty-D Whoops you're right. Want me to fix that for the pull?

**Comment by ascriptmaster** [comment]
yes please do

**Comment by alex-taxiera** [comment]
That should fix it for this patch.

**Comment by Marty-D** [comment]
:+1:

**Pull request merged**
