### PR TITLE
Random Battle: Enforce coverage for dual-Normal Pokemon

### PR DESCRIPTION
**Pull request by ascriptmaster**
Prevents issues with the Pokemon being walled by Ghost Pokemon.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
I think there's probably a better policy to help Normal mons, but I'm really not sure what the right policy should be. Are there any suggestions?

**Comment by TheImmortal** [comment]
This seems like an odd condition. I think we should rather make those types necessary, than doing this. Most STABs are already required except STAB. We could add something for Grass with exceptions.

**Comment by ascriptmaster** [comment]
Maybe. the main things that come to mind that might not need Grass STAB are Ferrothorn, Shiinotic, Whimsicott, and maybe some Grass/Poisons. Whimsicott and Shiinotic don't even have Grass STAB in their pool! Unfortunately Whimsicott's frailty means we can't do a defensive stat check for this, but checking for Fairy/Poison/Steel as the exception might work. (Tapu Bulu gets caught up in this as well, but it has no Fairy STAB so it'll always have a Grass STAB anyways.)

Again, I'm not very familiar with the entire Grass pool so I'm not sure what "needs" or "doesn't need" a Grass STAB.

**Comment by TheImmortal** [comment]
Would also fix non-Seed Flare Shaymin-Sky. I'll probably do it in my next update.

**Comment by ascriptmaster** [comment]
Ok. I'll close this now then. Just keep in mind the exceptions I mentioned.

**Pull request closed without merging**
