### PR TITLE
Add short forme aliases for Gourgeist

### PR DESCRIPTION
**Pull request by xfix**
I quite often see Gourgeist formes referred to Gourgeist-S and Gourgeist-XL. Because that naming is quite popular, I decided to add those aliases to the Showdown source code.

While I didn't really see Gourgeist-L (because it's not really viable), I decided to add it as well for consistency with two other aliases.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Gourgeist-M tho

**Comment by xfix** [comment]
I don't see any references to Gourgeist-M, usually that forme is referred just by Gourgeist, as confusing as it is.

Although I guess could be Gourgeist-H for Gourgeist-Super.

**Comment by Zarel** [comment]
Yeah, those are fine to add.

**Comment by ascriptmaster** [comment]
@xfix can you add the aliases you mentioned so it can be merged?

**Pull request closed without merging**
