### PR TITLE
Add UU Suspect Test

### PR DESCRIPTION
**Pull request by KrisXV**
http://www.smogon.com/forums/threads/3627043/

PLEASE DO NOT MERGE THIS UNTIL 10 PM EST (GMT -5) ON JANUARY 26, AND PLEASE HOTPATCH FORMATS AFTER MERGING THIS WHEN IT IS MERGED

### CODE REVIEW

**Comment by KrisXV** [comment]
ill say it again just in case

PLEASE DO NOT MERGE THIS UNTIL 10 PM EST (GMT -5) ON JANUARY 26, AND PLEASE HOTPATCH FORMATS AFTER MERGING THIS WHEN IT IS MERGED

**Comment by Zarel** [comment]
Do you not have access to labels?

**Comment by AustinXII** [comment]
That’s only for collaborators iirc

**Comment by KrisXV** [comment]
^

**Pull request merged**
