### PR TITLE
Fixed up the TCG search functions

### PR DESCRIPTION
**Pull request by bumbadadabum**
It took a while, but it should be better now.

### CODE REVIEW

**Comment by Slayer95** [comment]
Every command function gets passed the command name as the fourth parameter...
And you <i>still</i> aren't wrapping <code>JSON.parse</code> in a try/catch block :|

**Comment by bumbadadabum** [comment]
Ah right yeah I should try/catch the JSON.parse. What do you mean with the first thing though, the command name is used to get the url of the wiki.

**Comment by Slayer95** [comment]
```javascript
yugioh: function (target, room, user, cmd) {
[...]
var host = (cmd === 'yugioh' || cmd === 'ygo') ? 'yugioh.wikia.com' : 'mtg.wikia.com';
[...]
}
```

**Comment by bumbadadabum** [comment]
ah right that is very well possible, thank you.

**Comment by bumbadadabum** [comment]
For the try/catch, do I just need to catch the SyntaxError or anything else as well?

**Comment by Zarel** [comment]
Just catch anything that comes up. It's not like JavaScript makes it very easy to selectively catch.

**Pull request merged**
