### PR TITLE
Uno: wild cards default to the color of the top card when DQd

### PR DESCRIPTION
**Pull request by jumbowhales**
Previously, if a player was DQd during the color selection of a wild card, players would only be able to play black or wild cards. Uno has no proper rules handling disqualifications.

### CODE REVIEW

**Comment by sparkychildcharlie** [comment]
This would change the colour of the previous card (since the ``this.topCard`` object is directly linked to the last wild card which would create unplayable cards possibly). You probably have to apply this to ``this.changedColor``.   There's also the issue of several wild cards in a row on the top of the discard pile...

**Comment by jumbowhales** [comment]
What if we made `changedColor` a property of the wild card itself?

**Comment by jumbowhales** [comment]
@sparkychildcharlie bump, like that

**Comment by Zarel** [comment]
@sparkychildcharlie?

**Comment by sparkychildcharlie** [comment]
It looks good

**Pull request merged**
