### PR TITLE
Seasonal: Balance Update

### PR DESCRIPTION
**Pull request by cadaeic**
- Remove all instances of `setType(type, true)`
- Update to reflect awu name change
- Nerf biggie, Jack Higgins, Kid Wizard
- Buff sparktrain

### CODE REVIEW

**Comment by Slayer95** [comment]
Question: are those effects really <em>designed</em> to override Arceus' typing? O_o

**Comment by cadaeic** [comment]
If you are referring to why I chose to use `setType(type, true)` in this Seasonal, then I guess it was only precautionary, as there is no typed Arceus in the format anyway. If you're asking why the function might accept a second argument in the first place; I'd like to know too, since I have no idea as well.

**Comment by Zarel** [comment]
Yeah, a lot of these should just replace `setType(...)` instead of `setType(..., true)`

Only use manual type overriding if you have a need to override typechange resistance (which is practically never).

**Comment by cadaeic** [comment]
I don't think it's possible to use `setType(...)` to set a dual typing, so manual overriding had to be used in many effects anyway.

**Comment by Zarel** [comment]
A lot of your uses of `types =` aren't dual-type sets, anyway.

I wouldn't be opposed to supporting arrays passed to `setType`, if it came to that.

**Comment by cadaeic** [comment]
For the instance in statuses.js, I would argue that since the Pokemon is supposed to function as an Electric-type, it would be justified to override typechange resistance.
For the instances in moves.js, it was to maintain consistency with the dual-type sets within the same move effect. In addition, it is probably not problematic to override the resistance in this seasonal.

**Comment by Zarel** [comment]
The instance in statuses.js, yes, that's the correct implementation (it matches the Arceus implementation of typechanges).

The other ones should be changed to `setType`

**Comment by Zarel** [comment]
34200753c

Here you go. Pass an array to `setType`.

**Comment by cadaeic** [comment]
Corrected for this effect as well as other similar instances in moves.js.

**Pull request merged**
