### PR TITLE
Stop evalbattle from broadcasting by default

### PR DESCRIPTION
**Pull request by urkerab**
I left the old code in so that `!evalbattle` still broadcasts.

### CODE REVIEW

**Comment by Zarel** [comment]
tbh I kind of like that by default it shows up in the battle, makes it harder for admins to cheat

**Comment by Zarel** [comment]
(obviously not impossible because you have a console, but still)

**Comment by Slayer95** [comment]
Maybe have a single "This battle is being manipulated by the Server Operators" message?

**Comment by Zarel** [comment]
:|

**Comment by Zarel** [comment]
I mean it makes it harder for admins to cheat because anyone can see their code...

**Comment by Slayer95** [comment]
Though that also makes ``/editbattle`` for replaying battles very unfriendly...
At any rate, it's probably fair to assume that, unless there are clear reasons to do so, any battle in which the "manipulated" warning is shown is indeed one in which an admin is cheating.

**Comment by Zarel** [comment]
I still don't see the use-case...

**Comment by Slayer95** [comment]
I'd say aesthetical, @Zarel

**Comment by Zarel** [comment]
I'm leaning "no" but I'm open to further persuasion.

**Comment by Zarel** [comment]
I have not been further persuaded. I think the aesthetic argument is minor.

**Pull request closed without merging**
