### PR TITLE
Matchmaker: fix  crash in spawning tournaments

### PR DESCRIPTION
**Pull request by Morfent**

### CODE REVIEW

**Comment by Zarel** [comment]
Why is the matchmaker starting battles????

**Comment by Morfent** [comment]
Because of the search cleanup needed before starting battles, but that 
should be a separate method in the future
The battle logging that got glommed on as a side effect desperately 
needs to be refactored out, just not back to the global room
Maybe they should be static methods of Rooms for now, since some 
logging's already done there?
After some  other tweaks Rooms.createBattleRoom could be what starts 
battles instead

**Comment by Zarel** [comment]
Also why don't you `git grep` for function names before removing them from PS? :|

**Comment by Morfent** [comment]
E-mails showed up in pullreqs? Weird

I already do use git grep. Sadly it doesn't prevent accidents like this

**Pull request merged**
