### PR TITLE
Reword htmlbox help

### PR DESCRIPTION
**Pull request by InactiveUser**
I think the way it was before kind of confusing, especially with the not rank part, hopefully this helps?

### CODE REVIEW

**Comment by InactiveUser** [comment]
*not rank

**Comment by Zarel** [comment]
I would possibly leave `*` off entirely. iirc bots have a separate undocumented command for boxes.

**Comment by Zarel** [comment]
(But otherwise this is good)

**Comment by InactiveUser** [comment]
Thanks @Zarel

**Pull request merged**
