### PR TITLE
Random Battle: Ability and Move Updates

### PR DESCRIPTION
**Pull request by ascriptmaster**
Affects Charizard.

---

A point of discussion that came up was whether or not we can increase Sheer Force's rating or lower Mold Breaker's such that Rampardos won't get Mold Breaker. Alternatively, we could hardcode it onto Rampardos.

### CODE REVIEW

**Comment by TheImmortal** [comment]
The ratings are fine. Also, Mold Breaker isn't that bad if it doesn't have Rock Polish and it has Head Smash.

**Comment by ascriptmaster** [comment]
`if (template.id === 'rampardos' && !hasMove['headsmash']) ability = 'Sheer Force';`

Sound good?

**Comment by TheImmortal** [comment]
Fine.

**Comment by ascriptmaster** [comment]
Done, and now with a new thing dealing with setup type.

The idea is that if you have Physical setup but no Physical moves (and also some Special moves) you shouldn't change `setupType` so that the setup move will be rejected first. The same would go for Special setup. Trickster had reported a set of `Calm Mind / Substitute / Drain Punch / Return` on Slurpuff, which would be caused if the moves were generated in the following order:

    Dazzling Gleam, Flamethrower, Surf, Belly Drum, Play Rough, Draining Kiss, Calm Mind, Substitute, Drain Punch, Return

This probably isn't the best idea for dealing with our problems with mixed sets with varying setup moves, though. I'm not sure what the best solution is, though.

**Comment by TheImmortal** [comment]
That would reduce the chances of getting setup sets, which is bad.

**Comment by TheImmortal** [comment]
Also, what's the point of `if (!counter.setupType) ` in the original if statement?

**Comment by ascriptmaster** [comment]
It was mostly there for consistency with the other check.

You have a  point regarding setup becoming less common, but there's always a sacrifice to make with these things. How about we don't put a setup if there are none of that type and 2 or more of the other one?

**Comment by ascriptmaster** [comment]
I changed it to reject setup if there are 2+ of the opposite attack type now. Is this acceptable?

**Comment by TheImmortal** [comment]
Are you sure it does that? It looks to me like you're accepting the setup type if it has less than 2 moves of that type...

**Comment by ascriptmaster** [comment]
Whoops, nice catch! I was checking on the wrong counter for each of them.

**Pull request merged**
