### PR TITLE
Update Battle Factory OU, UU, and NU

### PR DESCRIPTION
**Pull request by KrisXV**
OU: https://pastebin.com/4X5VRnzN
UU: https://pastebin.com/E3ApHPKu
NU: https://pastebin.com/nNmgAV6t

### CODE REVIEW

**Comment by Slayer95** [comment]
> AssertionError [ERR_ASSERTION]: miscapitalized move "Power-Up  Punch" of lopunny

The error isn't clear, but it implies that there is too much whitespace in the name.

**Comment by KrisXV** [comment]
(i would test this locally but whenever i try to it runs too long and fails)

**Comment by KrisXV** [comment]
ok everything should be good

**Comment by Zarel** [comment]
I am _so_ glad I added a validator to Battle Factory; your typoes would be causing _so_ many problems if not for it.

I hope you can at least make sure the learnsets are correct; my tests don't cover that yet I don't think.

Also, point of order: I don't see the "Verified" so it doesn't look like you're editing on GitHub. Do you not have access to `npm test` in whatever you do use?

**Comment by erlandfauzan** [comment]
hmm...

**Comment by TheImmortal** [comment]
> 
> 
> I am _so_ glad I added a validator to Battle Factory; your typoes would be causing _so_ many problems if not for it.
> 
> I hope you can at least make sure the learnsets are correct; my tests don't cover that yet I don't think.
> 
> Also, point of order: I don't see the "Verified" so it doesn't look like you're editing on GitHub. Do you not have access to `npm test` in whatever you do use?

Nice. You could check Natures for typos and EVs for 510 and then it'd be perfect.

**Comment by KrisXV** [comment]
I can add those tests when I get home in another PR. All of the learnsets are correct.

@zarel I use VS code, but whenever I run npm test it says it exceeds the timer and fails.

**Comment by Zarel** [comment]
Can you show me the error message for exceeding the timer?

**Comment by KrisXV** [comment]
@zarel sorry for taking so long, i forgot

```
1) Factory sets
       should have valid sets in bss-factory-sets.json:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\kris\Desktop\Pokemon-Showdown\test\simulator\misc\random-teams.js)
      at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by Zarel** [comment]
Can you give your output for the test suite as a whole?

**Comment by Zarel** [comment]
Also: apparently `mocha --no-timeouts` will let you get around the timeout.

**Comment by KrisXV** [comment]
@Zarel sorry for the delay

```
NEW GLOBAL: global
NEW CHATROOM: lobby
NEW CHATROOM: staff

  .........................................................................,................,...............
  ..........................................................................................................
  ..........................................................................................................
  .............................................................,............................................
  ......................................................,................,..................................
  ..........!!..............................................................................................
  ..........................................................................................................
  ..........................................................................................................
  ................................................,................,,,,,....................................
  ....................................................................,,,,,,,,,,,,,,........................
  ...................................................

  1084 passing (3m)
  25 pending
  2 failing

  1) Factory sets
       should have valid sets in bss-factory-sets.json:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\feeds\Desktop\Pokemon-Showdown\test\simulator\misc\random-teams.js)
      at process.topLevelDomainCallback (domain.js:121:23)

  2) Factory sets
       should have valid sets in factory-sets.json:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\feeds\Desktop\Pokemon-Showdown\test\simulator\misc\random-teams.js)
      at process.topLevelDomainCallback (domain.js:121:23)



npm ERR! Test failed.  See above for more details.
```

**Comment by Zarel** [comment]
Man, it's a week later and I don't even remember why I wanted the full output anymore.

Anyway, just use `mocha --no-timeouts`

**Comment by KrisXV** [comment]
I need to update some of the sets because of tier shifts, then this will be ready

**Comment by KrisXV** [comment]
after a ton of local issues later, this is ready for merge @TheImmortal

**Pull request merged**
