### PR TITLE
Timer: log messages to the chat

### PR DESCRIPTION
**Pull request by HoeenCoder**
Requested by staff to help with timerstalling reports.

Tested and works though i'm wondering why https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/battle.js#L6367 is not causing a double post.

### CODE REVIEW

**Comment by Zarel** [comment]
`.log` means "add it to the roomlog but not to the room itself".

**Comment by Zarel** [comment]
like, it'll appear double in `/roomlog`, so you should remove that line if you're actually using `.add`

**Comment by HoeenCoder** [comment]
After testing the client changes you requested @Zarel, without `.log` timer messages don't show up in chat at all. Now that i think more about it, since its a different protocal `|inactive|`, if were going to log we need to tell it to (which we are already). So atm i didn't make any changes. If im not getting something feel free to PM me on the sim.

**Comment by Zarel** [comment]
I told you they appear in `/roomlog`. i.e. they appear in `logs/chat/` when chat logging is turned on. Those are the logs you don't want doubled.

**Comment by Zarel** [comment]
Wait, never mind, you're talking about a client `.log` call.

**Pull request merged**
