### PR TITLE
Add a full ability description for Contrary + Simple

### PR DESCRIPTION
**Pull request by Alumn2000**
https://www.smogon.com/forums/threads/add-a-full-ability-description-for-contrary.3652011/

@Marty-D , if you want add something or change, say it.

https://bulbapedia.bulbagarden.net/wiki/Contrary_(Ability)

### CODE REVIEW

**Comment by DaWoblefet** [comment]
I think it would be simpler to for the second sentence to read something like "Stat stage increases caused by the Z-Power effects of status Z-Moves are not inverted by Contrary, except for Extreme Evoboost".

**Comment by Alumn2000** [comment]
I agree. Added

**Comment by Marty-D** [comment]
If you clarify it like that then you're implying Extreme Evoboost has a Z-Power effect that somehow doesn't apply here. It doesn't; Extreme Evoboost is like Swords Dance, the stat stage increases are what the move does. Copying Bulbapedia is bad!

I was just going to add something like "This Ability does not affect the stat stages received from Z-Power effects." to both Contrary and Simple. You also have to override the description in the Gen 6 mod to remove Gen 7-specific stuff.

**Comment by Alumn2000** [comment]
I would be glad if someone could check that I didn't crashed something.

**Comment by Zarel** [comment]
I would probably still clarify like `(boosting Z-moves like Extreme Evoboost are not Z-power effects)` or something.

**Comment by Zarel** [comment]
> I would be glad if someone could check that I didn't crashed something.

It's a wording change; unless the checks fail (this thing), there's basically no way you could mess it up.

image

**Comment by Alumn2000** [comment]
ok. Thanks Zarel.

**Comment by Alumn2000** [comment]
@Marty-D , say if it's ok. If not, then just put the sentence in the comment and I will just c/c.

**Comment by Marty-D** [comment]
Thanks!

**Pull request merged**
