### PR TITLE
dexsearch: 'text' parameter suppresses icons

### PR DESCRIPTION
**Pull request by jumbowhales**
tried this once before the refactor, but it's still something that gets brought up as a suggestion

### CODE REVIEW

**Comment by Zarel** [comment]
why?

**Comment by CheeseMuffin** [comment]
I find it harder to read with the icons, and it also takes a while to load them all if they `ds` is large

**Comment by Zarel** [comment]
I'm not sure if a commandline argument has the right ergonomics for that case.

**Comment by jumbowhales** [comment]
What about a different command for it, something like ``/textds``?

**Comment by Zarel** [comment]
I don't think this is popular enough to go into the official client...

**Comment by Zarel** [comment]
If you have a much better parser for dexsearch queries, in which the code would be less messy, maybe I'd consider it.

**Comment by Zarel** [comment]
But this is an annoying maintenance burden for I'd guess like three people who actually want it.

**Comment by Zarel** [comment]
That's probably also too much maintenance burden.

**Comment by jumbowhales** [comment]
> If you have a much better parser for dexsearch queries, in which the code would be less messy
is it worthwhile in general to rewrite the parser?

**Comment by Zarel** [comment]
Possibly? I personally think I have a great script in the Dex, and that's the one that should probably be modified to a generalized dexsearch.

**Comment by Zarel** [comment]
Feel free to rewrite the parser, but as it stands, this pullreq is not going to be accepted.

**Pull request closed without merging**
