### PR TITLE
Implement /transferauthority

### PR DESCRIPTION
**Pull request by panpawn**
This lets an administrator or leader transfer a user's authority now with one command, instead of having to manually do it each time.

### CODE REVIEW

**Comment by panpawn** [comment]
Idea: have it modnote in each room it affects explaining the promotion?

**Comment by Zarel** [comment]
For me, it's intentional that we don't use it automatically.

**Comment by panpawn** [comment]
Why is that? To me, it makes a lot more sense for there to be one central command for it, assuming it's well documented (modnoted).

**Comment by panpawn** [comment]
I could make it so that the user using the command has to confirm it, before it's actually executed (kind of like forcepromote), if you'd like.

**Comment by Morfent** [comment]
Why an IEFF over promises for this? Closures can be nasty for leaking objects in their scope while being difficult to properly fix if you're not careful.

**Comment by Zarel** [comment]
No, that's not the problem. The problem is that ROs should not suddenly get new auth with no idea who they are. Making sure an RO repromotes the user in every room makes sure the ROs are aware of the name change.

**Comment by panpawn** [comment]
Well, like I said, we could have it modnote automatically in each room it affects...

**Comment by Zarel** [comment]
I still don't like nonconsensually promoting a new user in a room. Promotions need consent from roomauth.

**Pull request closed without merging**
