### PR TITLE
Inheritance: Add Donor Display and Fix Uber Mega Stones

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by Spandamn** [comment]
I hope modifying the battle-engine is allowed

**Comment by KrisOnPS** [comment]
just posting this here for prosperity

[00:37] Kris: the nickname function was fixed Spandan
[00:37] Kris: mega stones were as well i believe
[00:37] %Spandan: Mega Stones werent
[00:37] Kris: still
[00:37] %Spandan: and what nickname function?
[00:38] Kris: the donor display
[00:38] %Spandan: hmmm
[00:38] Kris: how it nicknames the pokemon the name of what they inherited from
[00:38] Kris: it was fixed to find the firsr available pokemon in the dex with all moves and abilities
[00:38] Kris: and then set to the prevo if there was one available
[00:39] %Spandan: hmm okay
[00:39] %Spandan: So there's no need for a "better" donor display?
[00:39] Kris: not really
[00:39] Kris: this is also just going to be on here for one month so editing the battle engine is less than necessary
[00:39] %Spandan: I'll still wait on TI :P
[00:39] %Spandan: well thats true

**Comment by TheImmortal** [comment]
I like using nicknames tbh. Allows you to see who is what without scrolling up in the battle log or remembering.

**Comment by KrisOnPS** [comment]
While I agree with you TI, and while this might not specifically be a programming issue, doesn't this essentially turn Inheritance into a nickname meta and therefore not eligible for OMotM? Or am I missing something?

**Comment by TheImmortal** [comment]
Nah, the script changes the nickname. What you put as the nickname is irrelevant.

**Comment by TheImmortal** [comment]
Also, best to ban the Mega Stones directly because Inheritance might ban or unban in the future.

**Comment by KrisOnPS** [comment]
Oh ok, thanks for clarifying.

**Pull request closed without merging**
