### PR TITLE
Add roomauth faq

### PR DESCRIPTION
**Pull request by AustinXII**

### CODE REVIEW

**Comment by TheImmortal** [comment]
I assume this is to help roomauth, and not random users, in which case this is already linked in ``/roomhelp``.

**Comment by AustinXII** [comment]
@TheImmortal Well its an easier way to link a random user who is wondering how to get roomauth (which is commonly asked) and we won't have to directly link them or make them do /roomhelp then scroll to the bottom

**Comment by kotarou3** [comment]
It wouldn't work since each room as their own rules regarding room promotions

**Comment by AustinXII** [comment]
its the basics of how to get promoted in a room, obviously rooms may have a different view on how promotions work but it states that in the smogon page @kotarou3

**Comment by AustinXII** [comment]
I don't see how that would be a problem, if its not a good promotion guide, than why do we use it in /roomhelp @kotarou3

**Comment by Slayer95** [comment]
Do we really want people who know tricks to get promoted?

**Comment by AustinXII** [comment]
@Slayer95 (can't tell if joking or not) well /faq staff does the exact same thing, but has tricks on how to get global rank instead of room rank. Regardless the smogon page is viewable to everyone meaning anyone can find that resource.

**Comment by TheImmortal** [comment]
Anyway, it doesn't tell you how to get promoted in a room. It's literally an extended ``/roomhelp``. It tells you your responsibilities as a certain rank, not how to get it.

**Comment by AustinXII** [comment]
@TheImmortal But it does tell you how to get the rank. " Room Voice is awarded to users who display a positive presence in the room." "Room Driver is given to users who are trusted to keep room discussions on topic and handle users who are breaking rules on the chat." " this position requires a potentially-promoted Room Driver to be trustworthy and mature, as well as having the judgment and responsibility required to handle any situation that may arise from the room." etc

**Comment by AustinXII** [comment]
@TheImmortal @Slayer95 Maybe a better solution would to just replace /roomhelp with this?

**Pull request closed without merging**
