### PR TITLE
Change PS version 0.10.2 -> 0.10.3

### PR DESCRIPTION
**Pull request by panpawn**
The last time this was changed was about ~a year ago, and it was when the ladder refactor was introduced.

I think that from the time between then and now, that there have been many major refactors and additions and otherwise changes that would warrant what PS is today to be considered a different "version" of that what PS was a year ago.

### CODE REVIEW

**Comment by Slayer95** [comment]
If anything, ``0.11``... Though semver leaves freedom about pre-release versions (i.e.  < 1)

**Comment by Morfent** [comment]
What kind of versioning system do we follow, anyways?

**Comment by panpawn** [comment]
>What kind of versioning system do we follow, anyways?

That's the problem I've talked about before in Dev... we don't.

**Comment by panpawn** [comment]
I propose we create a standard for this, including on when to update it.  

This PR can/should be used as a discussion on what that standard should be imo

**Comment by panpawn** [comment]
Personally, I think we should update it maybe every ~3 months (and keep it as semver form)

**Comment by Slayer95** [comment]
What problem would that solve?

**Comment by Morfent** [comment]
Time isn't an appropriate measure of version changes, I don't think, since that's independent of what changes have actually been made over whatever period of time would be used for them. I don't feel comfortable proposing a decent versioning system though since I have no experience dealing with that.

**Comment by panpawn** [comment]
>What problem would that solve?

It wouldn't, I realize now.  Subjecting it on time wouldn't accomplish anything.

I think I'm changing my mind about this - I think whenever there's a larger refactor, or a new feature added that's expected to be used by many users, that's when the version should change.

**Comment by Slayer95** [comment]
I mean, what problem would having a versioning standard solve?

**Comment by Zarel** [comment]
We haven't really had a breaking change...

**Comment by Zarel** [comment]
We don't really bother messing with the version number very often... @_@

We've had a lot of improvements since then...

**Comment by Zarel** [comment]
Well, you still need to update the version number client-side...

**Comment by panpawn** [comment]
https://github.com/Zarel/Pokemon-Showdown-Client/pull/799

**Comment by Lord-Haji** [comment]
This idea seems fine @panpawn

**Comment by Lord-Haji** [comment]
I don't think this is the version naming system.
Coz there were a lot of major updates
and it just increased from 0.10.2 -> 0.10.3

**Comment by Lord-Haji** [comment]
in my opinion it should be 1.0.2 ? ?

**Comment by Slayer95** [comment]
@Lord-Haji , I don't think you are aware about how versions work at all :|

**Comment by Lord-Haji** [comment]
Yeah i don't  know bout that all stuff But shouldn't it be alpha with so much commits since the last version change ? @Slayer95 below isn't below 0 a pre alpha ?

**Comment by kotarou3** [comment]
Our versioning is pretty arbitrary

**Comment by Zarel** [comment]
Well, Z-moves is worth a bump to 0.11.0 imo

**Comment by Zarel** [comment]
Closing, we're bumping to 0.11.0 soon

**Pull request closed without merging**
