### PR TITLE
Belch cannot be selected if the Pokemon has not eaten a berry

### PR DESCRIPTION
**Pull request by ascriptmaster**
https://www.youtube.com/watch?v=paMtFIVWRkQ&t=6m33s

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Should I remove Belch's `TryHit` handler? It shouldn't ever be called now since the move can't be selected normally, and it can't be called by Metronome or Assist.

**Comment by Marty-D** [comment]
Yeah, the `TryHit` bit is unnecessary now. This is a lot better than the ugly hardcoded way I was going to fix it last year (in `BattlePokemon#update`)! :+1:

**Comment by ascriptmaster** [comment]
Well, I can't think of any hardcode way that would even be different from what I'm doing now, it'd just be the same thing but near the `ModifyPokemon` event, right? After all, disabling moves used to be handled there before I refactored it.

**Comment by ascriptmaster** [comment]
At any rate, this is basically ready to merge, yes?

**Comment by ascriptmaster** [comment]
la la la

**Pull request merged**
