### PR TITLE
Past Custom Game "canUseRandomTeam", Level 9999/24 Pokemon

### PR DESCRIPTION
**Pull request by Tmi489**
Using future stuff in past game custom game still doesn't work so copied the exact same ruleset (gen6's) for all CGs other than Gen7

### CODE REVIEW

**Comment by Zarel** [comment]
None of those control using future stuff in past gens.

**Comment by Zarel** [comment]
I can take a look at what's going on here, but I'm swamped and probably won't get to this for a long time...

**Comment by scheibo** [comment]
Probably an `exists` check?

**Comment by Zarel** [comment]
Future Pokémon in past gens should still have `exists = true`

**Comment by Tmi489** [comment]
i still want level 9999 and 24 mons though

**Comment by Zarel** [comment]
That's fair.

**Pull request merged**
