### PR TITLE
Battle ban: Handle users already in tournaments

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by panpawn** [comment]
@panpawn: I think those typescript errors are because tournaments aren't typescripted :|

**Comment by CheeseMuffin** [comment]
if you have a typescript error that can't be fixed for now you can `// @ts-ignore` it.

**Comment by panpawn** [comment]
I guess I'll do that when I get access to a computer unless someone comes up with a better idea

**Comment by AustinXII** [comment]
Ohhhh yeah I never did PR this, whoops being busy all the time sucks but ty for fixing :+1

**Comment by Zarel** [comment]
That's quite a lot of ts-ignore but I'm accepting in lieu of a better implementation

**Comment by Zarel** [comment]
A better implementation would probably involve notifying all gamerooms?

**Comment by panpawn** [comment]
>A better implementation would probably involve notifying all gamerooms?

Well, the only game rooms that relate to battle bans are ones that involve battling (tournaments). Also, it's worth noting that some room staff leave tournaments to run themselves, this is why I think this is a better behavior rather than only notifying the rooms.

**Comment by Zarel** [comment]
> Well, the only game rooms that relate to battle bans are ones that involve battling (tournaments). Also, it's worth noting that some room staff leave tournaments to run themselves, this is why I think this is a better behavior rather than only notifying the rooms.

By "notify" I mean, like, call an `onBattleBan` function, not like a browser notification.

> I think Cheese had said he's working on typescripting tournaments, so theoretically they should be able to be gone when that happens.

Just type `room#tour` to `any` and we won't have this problem tbh, no need to actually TS them.

**Pull request merged**
