### PR TITLE
Hide text when users join a room

### PR DESCRIPTION
**Pull request by HoeenCoder**
This enforces text being hidden.

### CODE REVIEW

**Comment by kotarou3** [comment]
What is this meant to do? As far as I can see, all this code does is send extra `|unlink|`s on room join. Why is that needed? What are you trying to fix?

**Comment by HoeenCoder** [comment]
It's for **Fixes to text hiding** in Issue #2444. It works by looping through the last 100 lines of the room log (which is what is visible to a user when they join a room) and looking for `|unlink|hide|`. If it finds that it  sends the same command to the user who just joined. The  `room.log[i].substring(13)` is the userid that refers to the messages we want to hide.

**Comment by Zarel** [comment]
There's a better implementation sitting in Pull Requests somewhere...

**Comment by Zarel** [comment]
Ah, yes, #2645 is the right approach. This pull request is the wrong approach.

We really need to do something about _that_ pull request, though.

**Pull request closed without merging**
