### PR TITLE
Set prevUsers properly when merging

### PR DESCRIPTION
**Pull request by whalemer**
As far as I can tell this isn't intended behaviour.

### CODE REVIEW

**Comment by Slayer95** [comment]
LGTM :+1:

**Comment by Slayer95** [comment]
Hmm.... Actually, ``merge``'s API should probably be ``(fromUser, intoUser)``, matching the API of ``Object.assign`` and the like.

**Comment by whalemer** [comment]
>...(fromUser, intoUser), matching the API of Object.assign and the like.

Isn't `Object.assign` (destination, source)?

**Comment by Slayer95** [comment]
Uhm... Yea, that's what I mean, ``(intoUser, fromUser)`` :sweat_smile:

**Comment by Zarel** [comment]
Why is there a function just called `merge` here, anyway?

**Comment by Zarel** [comment]
I think `destination` and `source` are just not very clear names. They're better than `1` and `2` but I'd rather think of better names.

Maybe `toRemain`, `toDestroy`?

**Comment by whalemer** [comment]
>Why is there a function just called merge here, anyway?

```
// Low-level functions for manipulating Users.users and Users.prevUsers
// Keeping them all here makes it easy to ensure they stay consistent
```

formerly assigned as Users.merge but typescript doesn't like that

**Pull request merged**
