### PR TITLE
Updating "Pokemon" to "Pokémon"

### PR DESCRIPTION
**Pull request by Bryan-0**
Updating "Pokemon" to "Pokémon" in info.js file.

### CODE REVIEW

**Comment by Zarel** [comment]
no

**Comment by Zarel** [comment]
For now, I'd like to keep Unicode out of source files.

**Comment by Bryan-0** [comment]
Ok.

**Comment by Zarel** [comment]
For future reference, commit summaries should be in imperative case; i.e. `Update` instead of `Updating`.

**Comment by Bryan-0** [comment]
Understood.

**Pull request closed without merging**
