### PR TITLE
ban evasion from Doubles Ubers

### PR DESCRIPTION
**Pull request by Arcticblast**
#Arcticblast: do you definitely want evasion moves and abilities banned from DUbers?
@KyleCole: idc, but if you're running a tour with it and want it banned then im down

no longer allowed in singles Ubers iirc so why allow it here?

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Shouldn't this go through a Doubles council first?

**Comment by AustinXII** [comment]
@ascriptmaster  both Arcticblast (arcticblast being one of the leaders) and KyleCole are part of the doubles council

**Comment by Slayer95** [comment]
Needs more posts in media outlets.

**Comment by Joimer** [comment]
Doubles Ubers is an OM, basically, currently maintained by Kyle Cole. The community is currently playing with manual Evasion clause, so let's go.

**Pull request merged**
