### PR TITLE
Add aliases to deregisterchatroom and makechatroom

### PR DESCRIPTION
**Pull request by AustinXII**
This makes it less confusing for people who are just starting a server

### CODE REVIEW

**Comment by Zarel** [comment]
deregisterchatroom doesn't delete a chatroom, though...

**Comment by AustinXII** [comment]
@Zarel it does as of the next restart though, after the command goes through it even says ""It will be deleted as of the next server restart."

**Comment by Zarel** [comment]
It doesn't immediately, though.

**Comment by AustinXII** [comment]
@Zarel  yes but the message that comes after imputing the command warns them about it not instantly deleting the room. But it does delete it eventually

**Comment by Slayer95** [comment]
What would you name a command that deletes the chatroom immediately then, @AustinXII ?

**Comment by AustinXII** [comment]
@Slayer95 well if there is plans to add a command like that then feel free to close this PR, It seems weird to have a /makechatroom command and no a /deletechatroom command to go with it.

**Comment by Zarel** [comment]
I have nothing against a command that deletes a chatroom. The only reason why I haven't made one yet is that I haven't had the time to figure out if it would be safe to do without crashing the server.

The last time TI tried to delete a chatroom, it crashed the server, so presumably there's something we need to watch out for.

**Comment by AustinXII** [comment]
hmm well in that case I guess this should be closed for now

**Pull request closed without merging**
