### PR TITLE
BF: Multiple Bugfixes and Major UU Update

### PR DESCRIPTION
**Pull request by LegoFigure11**
Fixes include:
Multiple Megas on one team
Numerous typos in sets as outlined here: https://www.smogon.com/forums/threads/3629542/
UU Updates as described here: https://hastebin.com/raw/uyohifacux

### CODE REVIEW

**Comment by Zarel** [comment]
"Houndoomite" is still spelled wrong.

Can you write a validator so this doesn't happen?

`Dex.getItem(...).exists`, `Dex.getMove(...).exists`, etc

**Comment by Zarel** [comment]
Also your JSON isn't even valid. Did you test this?

**Comment by LegoFigure11** [comment]
Oh, shoot, I wasn't editing the version of the file that I was testing. So sorry! I'll amend that ASAP

**Comment by LegoFigure11** [comment]
Not gonna lie, I'm not really sure how I'd go about writing a validator (as useful as it would be, I'm not sure I have the knowledge to make it work)...
 I feel like an idiot right now, but this commit fixes Houndoominite and is a valid JSON. I'll try making a validator, but as I said I'm not sure I'll be able to.

**Comment by Zarel** [comment]
I'll write the validator myself:

AssertionError [ERR_ASSERTION]: invalid ability "Weakness Policy" of aegislash in bss-factory-sets.json

AssertionError [ERR_ASSERTION]: invalid ability "Red Orb" of groudon in factory-sets.json

AssertionError [ERR_ASSERTION]: invalid ability "Leftovers" of klefki in gen-6-factory-sets.json

AssertionError [ERR_ASSERTION]: invalid item "Fightinium" of togekiss in factory-sets.json

**Comment by Zarel** [comment]
This is the kind of validator I was asking for: fae71749123d22d3d2

**Comment by Marty-D** [comment]
You put too many `megaOnly` flags here. `megaOnly` means every single set for that Pokemon in that tier is a Mega set, so that the generator will not pick that Pokemon at all after it already has a Mega on the team. It should be possible to generate a team with Mega Scizor and a Banded Tyranitar, for example.

**Comment by Marty-D** [comment]
I also generated some teams just now and got this:
>Staraptor||leftovers||bravebird,roost,defog,uturn|Impish|248,,252,,8,|M||||]Celesteela||leftovers||heavyslam,flamethrower,leechseed,protect|Relaxed|252,,104,,152,|||||]Honchkrow||lifeorb|H|suckerpunch,bravebird,superpower,darkpulse|Naive|,252,,4,,252|F||||]Altaria||altarianite||dragondance,return,roost,refresh|Jolly|248,,8,,,252|F||||]Landorus||lifeorb|H|earthpower,sludgewave,rockslide,stealthrock|Timid|,,4,252,,252|||||]Vivillon||focussash|1|sleeppowder,quiverdance,hurricane,bugbuzz|Modest|,,4,252,,252|M||||

which looks like a Monotype Flying team, but there's a Mega Altaria on it.

**Pull request merged**
