### PR TITLE
Validator: support supplementary banlists

### PR DESCRIPTION
**Pull request by sirDonovan**
To be used in a new tournament feature and potentially in challenges.

### CODE REVIEW

**Comment by Zarel** [comment]
It seems like it should be passed next to the formatid, rather than next to the team?

**Comment by sirDonovan** [comment]
Updated.

**Comment by Zarel** [comment]
...by which I mean instead of

    TeamValidator(formatid).prepTeam(this.team, this.locked || this.namelocked, supplementaryBanlist)

it should be

    TeamValidator(formatid, supplementaryBanlist).prepTeam(this.team, this.locked || this.namelocked)

**Comment by Zarel** [comment]
(I didn't mean to imply I cared about crossprocess protocol; I mostly care about things like API)

**Comment by sirDonovan** [comment]
Oh I see, sorry for the confusion. Updated again.

**Pull request merged**
