### PR TITLE
Ban Altarianite from Monotype

### PR DESCRIPTION
**Pull request by scpinion**
http://www.smogon.com/forums/threads/oras-monotype.3544507/page-15#post-6382417

### CODE REVIEW

**Comment by TheImmortal** [comment]
That placement. Also missing space. I'll just do it myself...

**Comment by kotarou3** [comment]
...why didn't Travis catch that?
@Slayer95

**Comment by ascriptmaster** [comment]
We don't have Travis check that. Look at `formats-data.js`, we have no spaces there

**Comment by Slayer95** [comment]
@kotarou3, it's a regression introduced in JSCS new major version: https://github.com/jscs-dev/node-jscs/commit/9fc861494156a44b20616b710a5e9ffc5b328749

@ascriptmaster, data files have their own style settings.

**Pull request closed without merging**
