### PR TITLE
Dependencies: Add Husky githook

### PR DESCRIPTION
**Pull request by supersoniko**
**What?**
[Husky](https://www.npmjs.com/package/husky) is a dependency that makes githooks easy. It allows you to hook into commits, pushes & etc.

**Why?**
Prevent bad commits. Make pull request look more clear by preventing commits like 'Fix Travis'. This makes it easier to focus on the problem a PR is trying to solve.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks interesting, but I don't see a commit message check?

**Comment by Zarel** [comment]
I also don't understand what the Husky dependency adds? Aren't commit hooks built into Git?

**Comment by xfix** [comment]
@Zarel 

Essentially what Husky does is that when it gets installed, it installs its git hook. git clone doesn't install any git hooks for security reasons, so something like that is needed for this to work.

**Comment by supersoniko** [comment]
@Zarel Do you mean linting of the commit message itself?

**Comment by Zarel** [comment]
@xfix Oh, that makes sense. I think that's a good idea.

@supersoniko Yes.

**Comment by Zarel** [comment]
I guess there's not that much we can do, because every rule has exceptions. I'd say nevermind on linting commit message formatting.

**Comment by supersoniko** [comment]
We don't lint commit message formatting for the same reason at my work. Husky really helps us keep code reviews & the commit history clean.

**Comment by Zarel** [comment]
I suppose I have no objection.

**Pull request merged**
