### PR TITLE
invite: promote to higher ranks if modjoin is set

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
So the question is: Are the higher required ranks temporary? Or...?

**Comment by Zarel** [comment]
Should roomvoice just _always_ override modjoin settings?

**Comment by Zarel** [comment]
If the higher required ranks are permanent – for instance, it's a staff subroom of a public room, and you only want drivers to be able to join, then the right thing is to just allow all room ranks to join, and just roomvoice people to invite them.

If the higher required ranks are temporary – for instance, to temporarily deal with a spam problem, you would want /invite to fail with an error message – you don't want to accidentally promote someone to driver.

**Comment by Zarel** [comment]
So the question is: Which is the actual use-case for modjoin settings above `+`? Will that change, once subrooms are implemented?

**Comment by Zarel** [comment]
...anyone?

**Comment by HoeenCoder** [comment]
Modjoin settings above voice have only been used for staff rooms (with hidden status) afaik, the reason for needing it set to driver is so that global staff (and room ranked users) can join the room but not global voices. Meanwhile voice has been used as a kind of whitelist setting in secret rooms, where only users who have a room rank can join, and more can be easily added with /invite. Generally subrooms are rooms that have a public room as its "parent", they usually don't have modjoin afaik.

This seems to be mostly a convenience addition, and for the sake of security in the rooms with higher levels of modjoin (and to prevent accidently using `/invite` int eh wrong room), I feel `/invite` should only work with modjoin set to voice as it is now.

**Comment by Zarel** [comment]
There's some complication, but overall this is not how I or anyone else think is the right way to fix to the invite command.

**Pull request closed without merging**
