### PR TITLE
Made EV and IV distributions less redundant

### PR DESCRIPTION
**Pull request by AntonXue**
My first pull request please be gentle :^)

### CODE REVIEW

**Comment by ascriptmaster** [comment]
squash

**Comment by TheImmortal** [comment]
It's on purpose though...

@Zarel

**Comment by Zarel** [comment]
No, the random battle spreads are intentionally that way. If we wanted competitive spreads we'd just copy the EV suggester from the client. :|

**Comment by Zarel** [comment]
> It's on purpose though...

We accept fix commits if the commits fix a problem in master.

We do _not_ accept fix commits if the commits fix a problem in your own pullreq; you _must_ squash those.

**Comment by TheImmortal** [comment]
I was talking about the EVs...

**Comment by Zarel** [comment]
Oh, lol. Be clearer. :P

**Pull request closed without merging**
