### PR TITLE
Change FU pokemon from "PU" to "(PU)"

### PR DESCRIPTION
**Pull request by Teremiare**
Changed everything with 3.4% or lower usage according to these usage stats: http://www.smogon.com/stats/2015-12/pu-1630.txt

### CODE REVIEW

**Comment by TheImmortal** [comment]
I don't really know why this was accepted @Zarel. PU is the lowest tier. The only Pokemon that shouldn't listed as PU are NFE, if they don't have enough usage.

**Comment by TheImmortal** [comment]
Please revert.

**Comment by Zarel** [comment]
I asked for someone to do it in Dev; he did it.

`(OU)` means "OU but with less than 3.4% usage", and `(PU)` means the same thing for PU. I figure it's useful for PU players to see what the common threats are.

**Comment by TheImmortal** [comment]
Alright. It's not a problem if someone is going to maintain it every month. If it goes two months without being updated, I hope you don't oppose me removing it.

**Comment by Zarel** [comment]
Is there any reason you wouldn't want to maintain it yourself? I was going to ask you to do this but you were on leave, which is why I asked the Dev room and Teremiare volunteered.

**Comment by TheImmortal** [comment]
I have enough things to maintain and this is far from important or necessary imo

**Comment by Zarel** [comment]
Works.

**Comment by Rhythms88** [comment]
I'd be willing to help with this along with @Teremiare if you guys wouldn't mind.

**Comment by TheImmortal** [comment]
I think this should be reverted rather than maintained. There's several people who don't agree with this, most importantly the PU leader.

**Comment by Zarel** [comment]
I'd consent to reverting it.

We should possibly see if we can do something about usage stats being _that_ bad, though.

**Pull request merged**
