### PR TITLE
Boost time limit for JSHint.

### PR DESCRIPTION
**Pull request by xfix**
This fixes tests on Travis, because Travis is so slow.

### CODE REVIEW

**Comment by xfix** [comment]
And it still doesn't work, yay.

**Comment by xfix** [comment]
Okay, works now (failure is unrelated issue)

**Comment by Zarel** [comment]
What changed? o_O

**Comment by xfix** [comment]
From what I see, Travis got slower. @TheImmortal says that the first build that failed was https://github.com/Zarel/Pokemon-Showdown/commit/2051f5f117afec037ffa345fec2b337919601e14, which obviously shouldn't fail because of a timeout.

**Comment by Zarel** [comment]
Wait, how did we get that error there if `npm test` passes locally?

**Comment by Zarel** [comment]
Something weird is still going on...

**Comment by TheImmortal** [comment]
Well, that was an assumption xfix because the pull request before that passed.

**Comment by ascriptmaster** [comment]
Is it possible to run the test again? This one is failing because of supposed style changes that shouldn't be there

**Comment by Slayer95** [comment]
Thanks! Landed at https://github.com/Zarel/Pokemon-Showdown/commit/5059523cabce83708eb95308cd23f61319828ac5

**Comment by Zarel** [comment]
I have a feeling that once we get to the point where we're increasing the time limit to – what is this, ten times to default? – once we get to that point, we might want to look into ways to increase performance...

**Comment by xfix** [comment]
@Zarel: Well, this pull request boosts it 10 times, however @Slayer95 in 5059523 decided to boost it more, 15 times to default.

**Comment by Zarel** [comment]
> 7 minutes 30 seconds

Man, has it really come to this? :/

**Comment by kotarou3** [comment]
It might just be because travis is usually under pretty high load. `npm test` on my computer usually only takes about a minute

**Comment by TheImmortal** [comment]
It used to take 30 seconds for me but today it took over 4 minutes... I assume this is because of one of the recent changes.

**Comment by kotarou3** [comment]
Nevermind, after updating dependencies, it's taking a lot longer

**Pull request closed without merging**
