### PR TITLE
Implement Mix and Mega

### PR DESCRIPTION
**Pull request by Pikachuun**
Self-explanatory, this includes the Shadow Tag ban that was recently decided on.

C H O O N S C O D E B O Y S

### CODE REVIEW

**Comment by TheImmortal** [comment]
If we wanted that, we could have added that. @Slayer95 is re-doing it.

**Comment by Pikachuun** [comment]
Ah, I wasn't aware of him re-doing it. My mistake for making the request.

**Comment by Slayer95** [comment]
Done in abed3f8. I probably should have told you I was redoing it.

Thanks for the reference implementation, @Pikachuun !

**Comment by Pikachuun** [comment]
No problem, glad I could help somewhat :P

**Pull request closed without merging**
