### PR TITLE
Gen 3 Randbat updates

### PR DESCRIPTION
**Pull request by Honko**
* Prioritize high-value STABs and other important moves
* Clean up STAB enforcement and allow certain Pokemon to be STABless
* Optimize Hidden Power selection
* Add a few missing Pokemon
* Remove illegal moves from movepools
* Lots of other minor movepool and move selection improvements

### CODE REVIEW

**Comment by Honko** [comment]
@HoeenCoder 

I tested this pretty thoroughly and the overall set quality seems much better. Please take a look and let me know if you see any issues.

**Comment by TheTiksiBranch** [comment]
having helped hoeen with a lot of the sets i thought id take a look
overall seems like a lot of good stuff but i have a few comments & concerns. This is the Gen1 mons, I'll do the other gens when i next have time

super fang has been helpful on raticate more than once to bust down bulky things for teammates or to scratch to death. maybe return and increased fighting move chance will ameliorate this somewhat? but maybe not enough for it to lose helpfulness

disagree with axing physclef, that good stab off solid bulk is great. belly drum has won me games, but even without it, that bludgeon counterpart to your special assortment has seen the light plenty. meteor mash maybe can go but yeah

could you explain roar ninetails it doesnt seem that impressive especially with hypno

disagree with removing toxic on vileplume, great sync with a lot of your other moves and the typing/special fatness is solid

why no body slam for machamp? the para is great and the relative spammability can be helpful especially after boost. Somewhat similar case for victreebel, except that it now only has 2 physical attacks for SD, and that it benefits from Normal coverage less.

really disagree with removing perish trap on gar, unexpected that thing is straight lethal, unless its a can't-get-both-reliably issue. shadow punch sounds terrible but the neutral coverage and tolerable power of STAB has made it useful on occasion - again not life or death though

sub doesnt feel worth it on mime, if taunt isnt either thats fair but at least it stops roar

twave gyarados doesnt seem problematic but if u want it to do better things ok

i wouldnt say jolt bp is worth it without agility, even with sub, based on subpass experience here

bringing in your special wall on mewtwo and having it bulk up in your face is literal hell. please keep.

**Comment by Honko** [comment]
Hey, thanks for taking a look! I got through the Gen 1 comments so far, I'll respond to the Gen 2/3 ones in a day or two.

* Good points on Super Fang Raticate, physical Clef, and Toxic Vileplume. I'll add those back. (Tested them and didn't see any issues.)

* Ninetales' movepool had to change because it doesn't actually learn Solar Beam. Swagger also seemed out of place since it seems like Randbats generally tries to avoid the RNG-heavy moves in most cases. Removing those left it with a constant set of STAB / HP Grass / Hypnosis / WoW, and I wanted to give it a 5th move to mix that up. Roar seemed like the best option since Ninetales has decent bulk, but we could go with something like Substitute or Sunny Day or Confuse Ray instead. I'm open to suggestions.

* I removed Body Slam on Machamp because it blocks important coverage too often. You end up with lots of sets like Rest/Talk/CC/Body Slam, or Bulk Up/CC/EQ/Body Slam, where you're completely walled by stuff that you could have smashed if you got Rock Slide or HP Ghost instead of Body Slam.

* Same deal for Victreebel but to a greater extent because it has so many good moves. I'd always rather get Sleep Powder or Synthesis or Hidden Power. Body Slam is also especially bad filler to get on Sunny Day sets.

* Perish Trap Gengar needs Substitute as well, and any set that needs 3 specific moves out of such a large movepool is basically never gonna happen. I just tried generating 100+ Gengar sets with Mean Look and Perish Song back in its movepool and it didn't get picked once. That doesn't seem worth leaving in. Gengar has plenty of other cool things to do.

* Agree with adding Shadow Ball back on Gengar though, it's good enough against low Def Ghosts/Psychics.

* Mr. Mime is immune to Roar because of Soundproof, so Taunt is less useful than normal. Sub goes nicely with Encore and Hypnosis in addition to being BPable.

* As you suggested, T-Wave on Gyarados gets in the way of DD and CB sets which are its best options imo.

* If Jolteon had a bigger movepool I'd agree with getting rid of BP, but really its 4th move is filler and BP is not a bad filler at all.

* Bulk Up Mewtwo is great when you get the right set, but having it in the movepool also results in a lot of bad sets that make it not worth it imo. For every time you get a decent one (Bulk Up / Shadow Ball / EQ or BB / anything), you also get a really bad one (Bulk Up / Brick Break / Thunderbolt / Taunt). The physical moves are also inferior when they show up on non-Bulk Up sets where you'd basically always prefer Ice Beam or Flamethrower. I'd rather have Mewtwo be consistently threatening with good CM and all-out attacker sets than introduce crappy sets for the sake of the occasional awesome Bulk Up sweep.

**Comment by TheTiksiBranch** [comment]
Ah, that mostly makes sense. Thanks for going through. Not a whole lot to say, just that Confuse Ray and Sub both sound pretty strong for Tales. Even without sub there's a surprising lot Gengar can trap and eliminate, but taking two moveslots still probably isn't worth it, I see where you're coming from.

**Comment by HoeenCoder** [comment]
Ill take a good look at this after you guys talk it over, I havent had enough time to play randbats so im not completely aware of the state of the ladder

**Comment by Honko** [comment]
Gen 1:
* I'll go with Substitute over Roar on Ninetales.
* I tried adding Protect on Gengar, still didn't get Perish Trap even once in 200+ generated sets. Its just has too much other good stuff in its movepool for a specific set like that to get picked.

Gen 2:
* I removed Sleep Talk on Quagsire because it was getting a lot of Rest/Talk/Curse/EQ which seemed bad to me. I guess I could remove Curse (and HP Rock) instead, or if you think mono-EQ isn't that bad I can leave Sleep Talk there. Otherwise ChestoRest seemed like a good compromise.
* I'll re-add Perish Trap Murkrow. I'm not really a fan since most of its defensive switch-ins can still 2HKO to break the trap, but I guess it's a nice surprise for Skarmory/Forretress/Registeel.
* Good point on Sub being unhelpful filler on Qwilfish. I'll remove it.
* Belly Drum and Tail Glow unfortunately will never get picked on Smeargle unless it has a damaging move to go with them (which would be counterproductive over something like Spore) due to the universal checks for set-up moves. I'm hesitant to touch those checks since they make perfect sense for every other Pokemon. I guess I could add an exception specifically for Smeargle, but that feels a little dirty. How important is it for Smeargle to have DrumPass?
* Psychic + Thunderbolt gives better neutral coverage for Lugia's CM sets than Psychic + Ice Beam since Thunderbolt hits Steels.
* Physical Celebi has the same problem as physical Mewtwo: it results in lots of bad sets. Most notably you get sets like [SD / HP Grass / Reflect / BP]. I'd rather stick with the better consistency of special-only.

**Comment by TheTiksiBranch** [comment]
That pretty much makes sense. I mean i'd say drumpass is definitely worth keeping if there's a good solution, but it does feel dirty to do that as you say and its not life or death, so do whatever you think is best

**Comment by TheImmortal** [comment]
So, we gucci?

**Comment by Honko** [comment]
Not yet, I still have to go through Tiksi's Gen 3 comments and then actually make the changes we agreed on (which I should get to today), and then I think HoeenCoder wanted to take a look as well once that's done.

**Comment by Honko** [comment]
I played around with Smeargle a bit but was not able to get Belly Drum and Tail Glow to work without getting lots of bad sets. There's too much code that assumes a Pokemon with a set-up move will also have an attacking move.

Gen 3:
* I agree with most of your comments. I'll re-add Double-Edge on Masquerain, Counter on Aggron, Return (as well as adding Brick Break) on Crawdaunt, Toxic on Latias, and Water Spout on Kyogre.
* I'll remove Substitute from Volbeat to ensure it always gets TG+BP. I do think special > physical for Volbeat. It's not really gonna do any damage on its own either way, but TG-Pass has a lot more potential to win games than TrickBand imo.
* Registeel pretty much has to choose between Curse and Seismic Toss, otherwise it gets lots of bad sets for reasons I can't quite trace. I ran into this problem in Gen 4 Randbats as well. Since it sounds like you think Seismic Toss is the better choice here, I'll go with that and remove Curse along with all the other physical moves.
* I don't really buy Rest Deo-D as an unkillable wincon. It has to deal with being low-leveled as an Uber, its bad HP stat that it can't fully invest in, and the lack of Leftovers due to Rest without Sleep Talk. Relatively unimpressive stuff like Surf Vaporeon 3HKOes it, and obviously anything with CB or a set-up move is gonna power through it easily. For comparison, Jirachi is actually bulkier and could theoretically run a Rest stall set as well, but it has better things to do, and I think Deo-D does too. I think it's better off sticking with Recover + Lefties and focusing on Toxic-stalling and setting up Spikes. I will re-add CounterCoat though.

I'll make the agreed-upon changes soon.

**Comment by Honko** [comment]
Updated. @HoeenCoder I think this is ready for you to review. @TheTiksiBranch feel free to take another look as well, and thanks for your help so far.

**Comment by HoeenCoder** [comment]
Looks good to me @Honko

**Pull request merged**
