### PR TITLE
Implement Ultra Sun/Moon's Wide guard Z-move bug

### PR DESCRIPTION
**Pull request by urkerab**
Should the bug get patched all that needs to be done is to switch the two conditions around. This will keep the necessary Clangorous Soulblaze mechanics. (Currently PS grants Wide Guard full protection against it.)

### CODE REVIEW

**Comment by KrisOnline** [comment]
Can you also add the SM code for this into the `vgc17` Mod?

**Comment by Marty-D** [comment]
Nice, thanks!

**Comment by Zarel** [comment]
Can we consistently use USUM? :/

**Comment by MacChaeger** [comment]
If you leave it as USM in the format list, people will keep calling it that.

**Comment by Zarel** [comment]
Everyone's voting for USUM. I'd rather change BW2 to B2W2 than this.

**Comment by Marty-D** [comment]
Just for the record, I only left it as "USM" here because it's in a comment that will likely be gone within a few weeks. If it were part of the commit title I would have changed it during squash-merge. I also call it B2W2, because that's what it is: Black 2 and White 2.

**Pull request merged**
