### PR TITLE
Make help commands more consistent with one another.

### PR DESCRIPTION
**Pull request by uzelbot**

### CODE REVIEW

**Comment by panpawn** [comment]
As discussed in Dev, this is intentional

**Comment by panpawn** [comment]
In terms of adding bot commands to help commands, I'm not sure if they  should be added for consistency or removed for consistency.

@Zarel thoughts?

**Comment by panpawn** [comment]
What do you mean by "alias checker"? As it stands currently, you can do an alias to see something is an alias of a command or not

**Comment by Zarel** [comment]
Bots should mostly refer to `@` for bot privileges – `*` really only needs to be mentioned in the exceptions (`/addhtml` etc).

**Comment by Zarel** [comment]
Yes, I'd prefer it this way, thanks!

Leaving up for a few days, in case anyone has strong opinions otherwise.

**Comment by Zarel** [comment]
Fortunately, GitHub has a Squash option, so I no longer mind messy commit histories.

Tell me when you're done!

**Pull request merged**
