### PR TITLE
Tours: Use meansYes and meansNo

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Zarel** [comment]
That's not how to use `meansYes` and `meansNo`, as indicated by the Travis error.

**Comment by DeathlyPlays** [comment]
My bad

**Comment by DeathlyPlays** [comment]
Question: Should we add allow, etc into meansYes and disallow, stop, etc into meansNo

**Comment by DeathlyPlays** [comment]
Then we can clean this up even more

**Pull request merged**
