### PR TITLE
Don't parse emoticons as commands

### PR DESCRIPTION
**Pull request by Slayer95**
Two lines, <strike>I have dishonored my family</strike>.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Why these two characters, specifically?

**Comment by ascriptmaster** [comment]
For example: `!-!` or `!~!` exist

**Comment by Rhythms88** [comment]
!_!

**Comment by ascriptmaster** [comment]
Don't be silly Rhythms, !_! is already included as an exception.

Perhaps the best thing to do is allow any symbol character that isn't a letter (and maybe numbers if we ever decide to support that, `!3!` isn't that important)

**Comment by Slayer95** [comment]
https://github.com/Zarel/Pokemon-Showdown/commit/bed5a46ff37023e1ba52fe5db7165629e3dd7575

**Pull request closed without merging**
