### PR TITLE
Implement /moddeclare for ROs+

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by panpawn** [comment]
Screencap:

**Comment by TheImmortal** [comment]
Modnote kinda does the same thing. If the purpose is to gain attention, you could make modnote trigger a notification. I don't see the point of both.

**Comment by panpawn** [comment]
Modnotes are sometimes hard to see/notice in a fast moving chat, which was my thoughts of "how can we make this more noticeable in case something is urgently important in a fast-moving chat, and this was the first idea that came to mind.

> you could make modnote trigger a notification

I could, but not all modnotes are very important, so that would defeat the purpose of gaining attention if every modnote was treated with that same notification.

**Comment by Zarel** [comment]
Did a mod ask for it?

**Comment by panpawn** [comment]
Not "a mod" specifically, but I did ask Trickster earlier and he thought it might be useful in some situations.

**Comment by TheImmortal** [comment]
If there isn't demand for it then there's no reason to add it.

**Comment by Zarel** [comment]
There are reasons to do things even in the face of lack of demand, but I don't personally think this is necessary.

**Pull request closed without merging**
