### PR TITLE
Add autoconfirmed user metadata to /cmd userdetails

### PR DESCRIPTION
**Pull request by Kaiepi**

### CODE REVIEW

**Comment by Zarel** [comment]
Wait... do we actually want this info being made public??? On second thought, we really don't, do we?

**Comment by Slayer95** [comment]
It's sent as a boolean. Why not? In any case, it would make sense to make it available in the ``/whois`` for room auth.

**Comment by Zarel** [comment]
I'm fine with showing roomauth who's autoconfirmed, but I don't think we want regular users with that information.

**Comment by Zarel** [comment]
I guess it _is_ public, though. Based on reg date and battle wins, both of which are public.

**Pull request merged**
