### PR TITLE
Poll updates

### PR DESCRIPTION
**Pull request by bumbadadabum**

### CODE REVIEW

**Comment by Zarel** [comment]
Second commit summary goes past max length.

**Comment by Zarel** [comment]
Also feel free to add a "results" button to the vote screen so people don't have to use the command.

**Comment by bumbadadabum** [comment]
I might, kinda busy and lazy now.

**Comment by bumbadadabum** [comment]
shortened the commit message.

**Comment by panpawn** [comment]
The timer can be set to negative minutes, was that intentional, or should there be a check for that?

**Comment by bumbadadabum** [comment]
there should be a check for that.

**Comment by bumbadadabum** [comment]
Did that and some other things.

**Pull request merged**
