### PR TITLE
Remove github-specific code from /htmlbox

### PR DESCRIPTION
**Pull request by kotarou3**
Instead, add it to your local command overrides - it doesn't need to be in the public repository

### CODE REVIEW

**Comment by Zarel** [comment]
If we're doing this, I'd prefer to use a different local command, so we'd need @xfix to update his bot before I could accept this.

**Comment by xfix** [comment]
I'm fine with whatever command you like, just please implement it first, so I could update to it.

**Comment by kotarou3** [comment]
bump

**Comment by SolarisFox** [comment]
Instead of having github specific code, perhaps Leaders could have the ability to instate htmlbox permission to users. This could make htmlbox more accessible to bots and would justify how github works while still having it available in the public code.

**Comment by Zarel** [comment]
I'm starting to like the idea of a Bot rank with htmlbox permissions.

Everyone, please provide symbol ideas.

**Comment by kotarou3** [comment]
🤖

**Comment by panpawn** [comment]
☯

**Comment by Zarel** [comment]
Could probably be either.

I'm opposing all symbols that are emoji, and would prefer (but not require) ASCII

**Comment by SolarisFox** [comment]
I think `«` (as in console output) would look nice as a bot rank. Perhaps also `ƒ` (as in function). I also find it unlikely either of those symbols are used as ranks currently on other servers.

**Comment by Zarel** [comment]
I kind of like `>` (as a common console input character)

**Comment by SolarisFox** [comment]
That sounds fine to me. The only "problem" with `>` is that users may say the bot name (with rank symbol) at the start of a chat line and accidentally greentext. I still think it would look nice regardless.

**Comment by Zarel** [comment]
yeah, or maybe `*` or `^`?

**Comment by ascriptmaster** [comment]
If it must be for ASCII, I want to say `?`, but `*` might work. From the rest of the (non-emoji) character set, I'm a fan of U+2301 "electric arrow" `⌁`, but either of SolarisFox's suggestions might work too.

**Comment by SolarisFox** [comment]
For some reason `?` seems like an odd choice to me (maybe too close to lock?). `^` and `*` seem like they would work, though they are fairly small characters. `Σ` seems like it might be fairly nice. To clarify, for this discussion do you consider extended-ascii part of ascii?

**Comment by Zarel** [comment]
extended-ASCII is acceptable

**Comment by panpawn** [comment]
``?`` is too close to the locked symbol

**Comment by panpawn** [comment]
Oh, didn't mean to spam this PR...

Anyways, this can probably be closed now.

**Pull request closed without merging**
