### PR TITLE
Update hotpatch to use switch case.

### PR DESCRIPTION
**Pull request by NotBlizzard**

### CODE REVIEW

**Comment by VBlizzard** [comment]
I have no idea why or how this failed, when it works when I tested it locally.

**Comment by sirDonovan** [comment]
@VBlizzard Please do not repeatedly open/close pull requests, as it sends a notification to all who are subscribed to this repository each time you do so. Similarly, you shouldn't open a new pull request simply to fix a Travis CI build error. Instead, you can push to the same branch and squash your commits into one. To avoid the need for this in the future, you should run <code>npm test</code> in your branch's directory (the same place where you would run <code>node app.js</code>) before opening a pull request as it will show you any errors that you may have in your code.

In this case, the errors are coming from the <code>return</code> on line 1320 which is not needed due to the <code>break;</code> on the following line and from trailing whitespace on lines 1296, 1301, 1336, and 1348.

**Comment by VBlizzard** [comment]
Sorry, sirDonovan.

**Comment by codelegend** [comment]
@NotBlizzard , please either fix the build errors, or just close the pull req.

**Comment by Zarel** [comment]
I'm going to close. Reopen if you can actually fix the issues.

**Pull request closed without merging**
