### PR TITLE
Prohibit Multiple Pikachu-Starter & Eevee-Starter

### PR DESCRIPTION
**Pull request by tmagicturtle**

### CODE REVIEW

**Comment by Zarel** [comment]
This is actually overridden by the rule in `mods/letsgo/rulesets`

**Comment by Zarel** [comment]
Otherwise a good fix!

**Comment by KrisXV** [comment]
@Zarel there is still more than one starter usable per team, when there shouldnt be.

**Comment by Zarel** [comment]
@KrisXV Yes, that's because no one has fixed it. Feel free to. :|

**Comment by Zarel** [comment]
Oh, that code's already in `rulesets`. I see what you're saying. Yeah, that's a bug somewhere.

**Pull request closed without merging**
