### PR TITLE
Fix Avalanche and Revenge

### PR DESCRIPTION
**Pull request by ascriptmaster**
Similar to Focus Punch, if these Pokemon are hit by another Pokemon after
they are hit by their target, it might not activate properly.

Next on my list: Assurance! It might be a bit tougher depending on behavior with repeated U-turns, though?

### CODE REVIEW

**Comment by Zarel** [comment]
Do these really need volatiles, or should we just fix `lastAttackedBy` in some way? @Marty-D?

**Comment by ascriptmaster** [comment]
`lastAttackedBy`, as implied by its name, only keeps track of the last mon to attack it. Avalanche/Revenge double their power iff they were hit and damaged by the Pokemon they're attacking, which might not be the last Pokemon to attack them.

**Comment by Marty-D** [comment]
I let the Focus Punch fix slide since the way that was broken was far more important to fix as soon as possible than this is. ``lastAttackedBy`` should just be replaced with ``hurtBy`` going forward, which would be somewhat similar to your ``damagedBy`` implementation here (and would presumably also lead to a simpler Focus Punch implementation). See https://github.com/Zarel/Pokemon-Showdown/commit/d71d3737bdb89ddaad4f013622e0b7177a5afbd3#commitcomment-10422057 and the link there for specifics.

**Comment by Zarel** [comment]
Okay, I was right. We should implement `hurtBy`.

**Comment by ascriptmaster** [comment]
I also remember Marty mentioning that if a mon U-turns out, then another mon allows it back in with another U-turn, and you happened to target where the mon now is with Revenge, it doubles damage. A simple keeping track of slots as mentioned in the other probably won't work out, because of that reason...

**Comment by ascriptmaster** [comment]
I've left this on the backburner for far too long. Someone else deal with this if they want.

**Pull request closed without merging**
