### PR TITLE
Random Doubles: Preliminary Overhaul

### PR DESCRIPTION
**Pull request by ascriptmaster**
Most ability checks are up to date with Random Singles, as are some of the
item checks.

### CODE REVIEW

**Comment by Zarel** [comment]
I assume you notice the failed build.

**Comment by ascriptmaster** [comment]
@ god why you gotta do me like dis

**Comment by TheImmortal** [comment]
What if... doubles used ``randomSet``? Does it really need its own if its going to be almost the same? Whatever cases apply to doubles can probably be added to singles without affecting singles.

**Comment by ascriptmaster** [comment]
That might be a good idea, we just have to figure out how to consolidate things. The main difference with Doubles is a lot of items tend to be different (Choice items are not as useful, Leftovers is usually way too slow especially when you can get double teamed), and then some move choices, specifically the favoring of spread moves, like Stone Edge being rejected with Rock Slide instead of the other way around. Also, level scaling is based on base stats instead of tiers because doubles tiers are wack and singles tiers aren't indicative of a Pokemon's potential in doubles.

It's probably going to be complicated but if we can get it merged that would be wonderful

**Comment by TheImmortal** [comment]
I see. Guess this will do.

**Pull request merged**
