### PR TITLE
Delete deprecated command

### PR DESCRIPTION
**Pull request by Bryan-0**
- Delete /potd command from Pokémon Showdown.

We all know that this command is not used in Pokémon Showdown, practically this command is dead.

@Zarel

### CODE REVIEW

**Comment by AustinXII** [comment]
The command is still used on secondary servers though, it could still serve some purpose on main eventually. Is there any real reason to delete it?

**Comment by AustinXII** [comment]
@Bryan-0 If this does go through you should also remove the various POTD checks for random battles and other things

**Comment by Bryan-0** [comment]
Yes, I'm on it. 

Also, even secondaries servers doens't use it, it's really weird to see one server that use this command.

**Comment by TheImmortal** [comment]
There's nothing wrong with this command. Sure we don't use it, but we can. I don't think you have been on every server to check whether they have used it or not so you can't make that statement. I often use it when testing Random Battle stuff myself.

**Comment by Bryan-0** [comment]
Welp, if you say it.

**Comment by Zarel** [comment]
Yeah, PotD is really nice for testing random battle. We're probably too big to have it in Main anymore, but I could still see it being nice in some contexts.

Does the `/potd` command specifically still do anything, though? I remember it broke when we split off simulator processes and I don't know if we ever fixed that.

**Comment by Slayer95** [comment]
Cathy fixed it.

**Comment by panpawn** [comment]
From my experience, I often times will see this used on secondary servers @Bryan-0

**Pull request closed without merging**
