### PR TITLE
Implement custom JSCS rules to enforce code style

### PR DESCRIPTION
**Pull request by Slayer95**

### CODE REVIEW

**Comment by Slayer95** [comment]
Should we allow (any of) these?

```
if (Math.random) Math.random();
else Number.isFinite();

if (Math.random) Math.random();
else if (Number.isFinite) Number.isFinite();

if (Math.random) Math.random();
else if (Number.isFinite) Number.isFinite();
else Number.isInteger();

if (Math.random) Math.random(); else Number.isFinite();
```

**Comment by Zarel** [comment]
No, I don't like any of those.

**Comment by Slayer95** [comment]
Ok, banned them.

**Comment by Zarel** [comment]
On second thought, I'm not _that_ strongly against them. We should have a poll. What does everyone else think?

**Comment by TheImmortal** [comment]
I never liked those.

**Comment by kotarou3** [comment]
I never liked those either.

Though I prefer `case`s indented inside a `switch` block

**Comment by Marty-D** [comment]
The first three are okay I guess, but if we do allow any of these I personally wouldn't use them. I've never actually seen the last one used anywhere; that has the potential to be really unreadable.

**Comment by Zarel** [comment]
Consensus is "no" to all four.

**Pull request merged**
