### PR TITLE
Random Battle: Prevent Sucker Punch as only STAB

### PR DESCRIPTION
**Pull request by ascriptmaster**
Also sorted the no-STAB list.

@TheImmortal when you get back I'd appreciate if you could discuss this. However, from my glance at the list of Dark mons that have the move, I don't think any of them really appreciate it being their only STAB, not even Honchkrow.

### CODE REVIEW

**Comment by TheImmortal** [comment]
I sorted it as Physical/Special. Also, this is a bad idea. I agree they wouldn't want it as their ONLY STAB, but they don't want to lose this. Ideally they want both. Definitely not going to accept this.

**Comment by TheImmortal** [comment]
Also, pretty sure I prevented it as only STAB. Check the Adaptability/etc section.

**Comment by ascriptmaster** [comment]
if ( ...
        (hasType['Dark'] && hasMove['suckerpunch'] && counter.stab < template.types.length) ||
        ... )

This check works for dual-typed Pokemon like Honchkrow, but not pure Dark-types.

The pure Dark-types with it are Absol, Mightyena, Liepard, and Zoroark. I'm not sure about the first three (especially not Liepard, which has Prankster to annoy you to death) but Zoroark definitely doesn't want it as its only STAB because it's item-locked into Choice Scarf.

**Comment by ascriptmaster** [comment]
Still waiting for an answer on this. I think that all Dark-type Pokemon with Sucker Punch should get a secondary STAB, which simply means changing the line mentioned in the last comment from `template.types.length` to a flat `2`.

**Comment by TheImmortal** [comment]
Does this affect anything other than Zoroark

**Comment by Zarel** [comment]
Do Pokémon really often carry two STABs when one is Sucker Punch? I was under the impression that coverage was more important than more reliability (same reason why no one runs both Flamethrower and Fire Blast).

**Comment by ascriptmaster** [comment]
Hmmm, maybe you're right. Although Mega Absol might care too since Knock Off is fun.

**Comment by TheImmortal** [comment]
Zarel is right. I looked back at the post regarding this and the issue is Scarf Sucker Punch, not lack of second Dark move. Fixed in 7b2c60c53606684b68f6d1683c28a25e40114c18.

**Pull request closed without merging**
