### PR TITLE
Fix Encore + Pledge moves interaction

### PR DESCRIPTION
**Pull request by jmclemo6**
I believe this fixes https://github.com/Zarel/Pokemon-Showdown/projects/3#card-24204988.

I added a test for this, but there are probably better ways to check what I was checking. If so, let me know and I can fix them up.

### CODE REVIEW

**Comment by Slayer95** [comment]
It would probably be better to fix this in the ``OverrideAction`` [implementation](https://github.com/Zarel/Pokemon-Showdown/blob/5fb57e6cfc33031cd66cc15a09644ec4a6b47907/data/scripts.js#L23).

It would also make sense to test whether a prioritized Round can be overriden into an encored move. cc @DaWoblefet

**Comment by DaWoblefet** [comment]
Round still maintains the "you move next" property of double Round, but it won't gain a boosted BP or override the move with Round.

To give an illustration:
Previous turn Meloetta uses Return.
This turn, faster Smeargle and Meloetta select Round. The opposing Whimsicott Encores Meloetta into Round. Smeargle uses Round, then Meloetta uses Return before the opponent's Pokemon which was faster than Meloetta.

**Comment by Slayer95** [comment]
Thanks! So Round has the same glitch.

Then it would go something like this... 
```js
if (!zMove && baseMove.id !== 'struggle' && (!sourceEffect || ['round', 'firepledge', 'waterpledge', 'grasspledge'].includes(baseMove.id))) {
}
```

At which point we must consider whether ``!sourceEffect`` makes sense at all? It seems it'd only be relevant for Instruct and Pursuit...

So, if A uses Instruct and then the foe uses Encore on A....??? I guess Encore would actually fail?

**Comment by Marty-D** [comment]
Sorry about the radio silence; to Slayer95's point above I've been meaning to test the Pursuit interaction without checking for sourceEffects here but haven't had time yet.

How does Dancer react in this situation? While Encored into something it should attempt to copy dance moves and then fail unless it's the Encored move (just like Choice locking), but I don't think that's happening right now?

**Comment by jmclemo6** [comment]
Dancer has never checked for that on PS as far as I know. At the very least that bug is also on main right now as I just tested it there.

**Comment by Marty-D** [comment]
Okay it turns out Pursuit doesn't even pass a `sourceEffect`, so nothing that actually passes one wants to avoid having the move overridden by Encore. Except technically Dancer, but that's a special case. We can implement that later though.

This means the line can just be `if (baseMove.id !== 'struggle' && !zMove && !externalMove) {` for now, and then deal with Dancer separately.

**Comment by jmclemo6** [comment]
Done @Marty-D. :D

**Comment by DaWoblefet** [comment]
Research completed on oldgens @Slayer95;  this has occurred since the moves were introduced in Generation 5.

**Comment by Slayer95** [comment]
Thanks!

**Pull request merged**
