### PR TITLE
Datacenters: Add a new range

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
```
zarel@Adenosine ~> host 185.20.99.0
0.99.20.185.in-addr.arpa domain name pointer h185-20-99-0.host.redstation.co.uk.
```

**Comment by Zarel** [comment]
The datacenters table is a host lookup table for IPs without host entries. Redstation has a host entry, you can just ban `redstation.co.uk`

**Comment by Zarel** [comment]
I've been meaning to open-source Main's banlist for this sort of thing...

**Comment by panpawn** [comment]
Yeah, I was going to say I'm not sure how to do that currently

**Comment by panpawn** [comment]
I have a thing on my server that does that kind of a thing but I'm sure Main's is different than mine

**Comment by Zarel** [comment]
Let's leave this open; I'll get around to that tomorrow.

**Comment by scheibo** [comment]
> ...I should probably open-source more of hostfilter so it's clearer how to do that.

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/commit/0ca08068ae7ca8fba45c24de49619cd7182ed1d1#r32544970_

> I've been meaning to open-source Main's banlist for this sort of thing...
> Let's leave this open; I'll get around to that tomorrow.

_**Narrator**: He didn't._

**Pull request closed without merging**
