### PR TITLE
Use <strong> instead of <b>

### PR DESCRIPTION
**Pull request by DeathlyPlays**
Bold was deprecated

### CODE REVIEW

**Comment by AustinXII** [comment]
Where was this deprecated?

**Comment by DeathlyPlays** [comment]
I was told that it was not always preferred awhile back, but as this [article](https://www.w3.org/International/questions/qa-b-and-i-tags) says it isn't always bold.

**Comment by AustinXII** [comment]
There has been a huge discussion about this afaik @Zarel didn’t you say you didn’t care which one people used?

**Comment by DeathlyPlays** [comment]
I'll leave it to Zarel to decide ig

**Comment by AustinXII** [comment]
Well you could also look at the older PRs and see the discussion, it was pretty recent

**Comment by Zarel** [comment]
It's complicated. If we were to standardize at all, we should standardize to `<b>` rather than `<strong>` because using a style hint is less bad than using the wrong semantic hint.

It's like, which is worse: no braille, or braille that says "it's safe to walk here" even when it's not safe?

**Comment by Zarel** [comment]
That's the problem with your change here: You're using `<strong>` even in places where you shouldn't be.

If we do these conversions at all, it should be after we discuss exactly where we draw the line, what should be CSS, what should be `<strong>`, what should be `<b>`.

**Comment by DeathlyPlays** [comment]
👍

**Pull request closed without merging**
