### PR TITLE
Update optionalDependencies

### PR DESCRIPTION
**Pull request by AlainDuhHero**

### CODE REVIEW

**Comment by Zarel** [comment]
@Slayer95? I don't really know much about dependency management in general.

**Comment by thecutestlittleoniichan** [comment]
yo lordhaji arent you gitbanned?
https://patch-diff.githubusercontent.com/raw/Zarel/Pokemon-Showdown/pull/3396.patch
From: AlainDuhHero <lordhajisinbox@outlook.com>

**Comment by AlainDuhHero** [comment]
@thecutestlittleoniichan this even directs to @Spandamn

**Comment by XpRienzo** [comment]
Excuse me, what? This isn't related to development discussion anyways, so I'd refrain from commenting further.

**Comment by Zarel** [comment]
(I deleted some irrelevant memeing)

**Comment by Morfent** [comment]
I'd check for any breaking changes in updates for these dependencies, particularly `http-proxy` and `node-mailer`. If there are any, you'll need to check sockets.js and crashlogger.js to see if any changes are necessary.

**Pull request closed without merging**
