### PR TITLE
Create quick-tour.js

### PR DESCRIPTION
**Pull request by megas4ever**

### CODE REVIEW

**Comment by sirDonovan** [comment]
These could be combined into one command and don't need to be separated from <code>tournaments/index.js</code>. Also, make sure you run <code>npm test</code> to check for errors before opening and updating a pull request.

**Comment by TheImmortal** [comment]
Formats should not be hardcoded.

**Comment by megas4ever** [comment]
Yeah, I tested this on a local server and it worked fine so I didn't feel it necessary to npm test.

**Comment by megas4ever** [comment]
I still think PS should have these, though. Maybe rewrite them?

**Comment by kotarou3** [comment]
If typing out `elimination` is too much, the proper way would be to add aliases or prefix matching to the original tour code

**Comment by megas4ever** [comment]
Oh... true. What about randtour?

**Comment by bumbadadabum** [comment]
I feel like that's better suited to being a bot feature than a tours feature.

**Comment by bumbadadabum** [comment]
Also, npm test isn't about your code WORKING, it's about your code following the styleguide for PS.

**Pull request closed without merging**
