### PR TITLE
Scotteh is a Leader not a Global Mod

### PR DESCRIPTION
**Pull request by Soku-Hi**

### CODE REVIEW

**Comment by Soku-Hi** [comment]
I also updated Zebraiken as he also never had the Leader symbol beside his name.

**Comment by Soku-Hi** [comment]
Will be updating everyone's now on this Pull Req.

**Comment by panpawn** [comment]
Remember to squash and make a more informative commit name

**Comment by Soku-Hi** [comment]
@panpawn Thanks I'm new to most of this stuff. :)

**Pull request merged**
