### PR TITLE
Creating usergroups.csv

### PR DESCRIPTION
**Pull request by HaunterGhost**
Creating usergroups.csv where there will be the Staff.

### CODE REVIEW

**Comment by TheImmortal** [comment]
No.

**Comment by kotarou3** [comment]
It doesn't even do what the description claims it does

**Comment by Morfent** [comment]
If you're going to make a pull request, make sure it only includes the one commit with your changes in it, ahd not 7 153 unrelated ones.

**Comment by HaunterGhost** [comment]
I can't do anything to that... -_-

**Comment by Morfent** [comment]
Yes you can, with ``git rebase -i``.
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Zarel** [comment]
@Morfent, this is a guy who is trying to create a server and misinterpreted the readme, not someone who actually wants to pullreq. It happens all the time.

**Comment by Zarel** [comment]
@HaunterGhost, you've been blocked from pullreqqing this repository. If you ever want to contribute code, feel free to e-mail us at `staff@pokemonshowdown.com`.

**Comment by Morfent** [comment]
Oh, that makes this make sense now

**Pull request closed without merging**
