### PR TITLE
BW2 Doubles: Ban Swagger

### PR DESCRIPTION
**Pull request by n10sit**

### CODE REVIEW

**Comment by Zarel** [comment]
Can you link to the announcement thread on Smogon?

**Comment by xfix** [comment]
http://www.smogon.com/forums/threads/bw-doubles.3606719/#post-7448645

**Comment by urkerab** [comment]
Why not use the Swagger Clause?

**Comment by Zarel** [comment]
Swagger Clause is probably the right solution here, yes.

**Pull request merged**
