### PR TITLE
Add /hidejoins and /showjoins into /help

### PR DESCRIPTION
**Pull request by AustinXII**
I see people ask what the command is to show when a person joins/leaves is quite frequently this should help.

### CODE REVIEW

**Comment by Bryan-0** [comment]
I think that /showbattles and /hidebattles can be a good idea too.

**Comment by ascriptmaster** [comment]
Travis failure is not your fault. Hang tight, it'll be fixed in a bit.

**Comment by Zarel** [comment]
I'm not sure this should be documented here...

**Comment by Zarel** [comment]
Some features we really don't want users to use unless they're advanced users.

Especially `/showbattles`; that doesn't even do anything anymore.

**Comment by AustinXII** [comment]
The only reason I added /showjoins and /hidejoins was because it is very commonly asked in help, this could stop that from being spammed/frequently asked in that room. It is your decision though.

**Pull request closed without merging**
