### PR TITLE
Fix Disable/Encore interaction with Healing Wish/Lunar Dance/Baton Pass/U-turn in Gen IV

### PR DESCRIPTION
**Pull request by Andi-Wang**

### CODE REVIEW

**Comment by Andi-Wang** [comment]
Mentioned in #2367 

Thought I'd try my hand at contributing to a project. I think I've followed all the procedures, but it's more than possible I've missed or broken something.

**Comment by Slayer95** [comment]
This would also change the behavior of Conversion 2, Mimic, Mirror Move, Sketch, Spite, Torment, and I am not sure if also anything else. Idk if that would be a conformant change.

**Comment by Andi-Wang** [comment]
Yeah. I'm going to go digging around some research threads to see if I can find testing results for anything that relies on last move interactions. I initially assumed that they would be treated the same.

Like you said, if anyone can clarify off the top of their head, that'd be great.

**Comment by Marty-D** [comment]
Here's a fairly detailed breakdown: http://upcarchive.playker.info/0/upokecenter/content/pokemon-diamond-version-pearl-version-and-platinum-version-last-move-used.html
PS simulates the last game(s) released during the generation, in this case HGSS. I'm not aware of any new or fixed bugs between Platinum and HGSS battle mechanics, though.

**Comment by Slayer95** [comment]
From the chart, it seems that all "last move" cases are equivalent after Healing Wish / Lunar Dance / U-Turn  :smile:

**Comment by Andi-Wang** [comment]
Seems like a useful resource, thanks! If I'm reading the chart properly, it seems like any changes to interactions with other moves and those 4 switching moves should be correct.

A full explanation is probably unnecessary, but just for clarity's sake: 

The main thing I was worried about with different games is that Platinum fixes a bug where U-turning into a Choiced Pokemon that also has U-turn would no longer lock the second Pokemon into U-turn (whereas it did in DP). If we're going off HGSS, then the in-game bug shouldn't exist here.

I haven't looked at how Choice items are coded, but it's possible that my changes break that interaction and reintroduce the in-game bug. I'll take another look at it when I have time today to check.

**Comment by Marty-D** [comment]
You actually just need a `noCopy: true` in the `choicelock` volatile in statuses.js to accomplish that. Much like this: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/statuses.js#L224

**Comment by Andi-Wang** [comment]
Ah, cool. I'll remove the previous change and do that, then.

**Comment by Slayer95** [comment]
For us, it's fine to rebase when each review cycle is done. However, nowadays Github supports automatically rebasing when we finally merge your PR, so the rebase guide for PS can be considered obsolete now, and you shouldn't normally worry about it .... unless there are conflicts.

Unfortunately, your Git manipulation seems to have generated conflicts where there used to be none, so you'll have to fix them :/

**Comment by Andi-Wang** [comment]
Okay, fair enough. So in the future, I just leave it during PR?

In any case, I'll go fix the conflict.

**Comment by Slayer95** [comment]
I fixed it myself, @Andi-Wang .

And I shall correct myself: there was indeed a conflict with another PR just merged.

> So in the future, I just leave it during PR?

Yup

**Comment by Andi-Wang** [comment]
Cool. Thanks for the help, @Slayer95 .

**Comment by Zarel** [comment]
I _think_ this is ready? Not sure, though.

I'll let @Marty-D merge this.

**Comment by Marty-D** [comment]
Yep, looks great. Nice work, thanks very much @Andi-Wang!

**Pull request merged**
