### PR TITLE
Randoms: Allow Mono-Attack Setup with BP, change Venomoth movepool

### PR DESCRIPTION
**Pull request by SolarisFox**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
This only works for Mothim... so you don't need the `hasAbility` since that tracks all possible abilities a Pokemon can have. Also update the comment to match

**Comment by ascriptmaster** [comment]
I've already discussed a better solution with SolarisFox than this, so he/she will be committing it shortly.

**Comment by ascriptmaster** [comment]
If you can be bothered you could probably use better capitalization on your first commit message, but it's not that important

**Comment by TheImmortal** [comment]
Remove Roost. It is neither recommended by Smogon nor is it used on the ladder. I don't see any benefit to having Roost myself.

**Comment by TheImmortal** [comment]
You can add Substitute if you want to it to have another option. I don't mind either way.

**Comment by SolarisFox** [comment]
Roost showed up on Venomoth occasionally during the short time it was in NU, and I've had a few occasions where I was using Venomoth in randoms and really wished I had Roost to outlast some bulkier mons. If I'm alone in thinking Roost would be useful I'll settle for Substitute though.

**Pull request merged**
