### PR TITLE
Proper credits

### PR DESCRIPTION
**Pull request by LordRichardAdams**
I, Richard Adams created Pokemon Showdown not Zarel therefore my name should be on this file.

### CODE REVIEW

**Comment by bumbadadabum** [comment]
This is a remarkable amount of effort for such an unfunny joke

**Comment by Morfent** [comment]
You also edited the completely wrong files to make yourself the PS creator.

**Comment by trixiemiller** [comment]
Also how did you even break travis with this

**Comment by ScottehMax** [comment]
Echoing what @trixiemiller said. You have trailing whitespace on one of the lines. Please run `npm test` before committing in future.

**Comment by aakash-singh** [comment]
guys that guy @LordRichardAdams is making shit of my name every where. I am the original richard adams .
i know that guy is @Lord-Haji who is doing this on every popular servers..
he dont abled to hack into my account so this what he is trying to do now..
I truely say i dont own any part of this pr
I am not that stupid to make such pr's

Thank you

**Pull request closed without merging**
