### PR TITLE
Random Battle Gen 3 and 4: Fix Togetic

### PR DESCRIPTION
**Pull request by ascriptmaster**
It does not get Super Luck in this generation, so it should always get
Serene Grace, but it keeps getting rejected.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Uh, instead of hardcoding, shouldn't Hustle be rejected as well? Then it selects the highest rated ability gets picked (doesn't look like I copied that over from future gens but I should) which is Serene Grace.

**Comment by ascriptmaster** [comment]
Ability selection is mostly the same as the current gen, where it selects the highest rated ability (33% chance of choosing the second highest if it's within a 0.5 point difference), then takes the second choice if the first choice is rejected. 

Serene Grace is rated 3, and Hustle is 2, so it will always choose Serene Grace first, and thus the check needs to be in Serene Grace, and not Hustle.

**Comment by TheImmortal** [comment]
No it used to be like this. Look at future gen ability selection. I updated it some time ago. If all the abilities are rejected, it defaults to the highest rated.

**Comment by TheImmortal** [comment]
bfa0394e938190e756c9111e6df38ff73d847e74

So you can just reject Hustle now, in gen 4 at least.

**Comment by ascriptmaster** [comment]
What about gen 3? That's where the bug was originally reported.

**Comment by TheImmortal** [comment]
Gen 3 had these weird lines: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/mods/gen3/random-teams.js#L443

I wanted to look into it and see if it's necessary.

**Comment by ascriptmaster** [comment]
I can fix the gen 3 issues. Give me a second.

**Comment by ascriptmaster** [comment]
Done. Hustle would've actually been rejected on Togetic with the current system anyways, since Seismic Toss doesn't increment the Hustle counter, so the only thing that needed to be done was the ability update.

**Comment by ascriptmaster** [comment]
never mind i broke something with that change, somehow

**Comment by ascriptmaster** [comment]
ah I forgot the else statement at the end of the ability selection code

**Comment by ascriptmaster** [comment]
Apparently removing the gen 3 ability check breaks the set generation by giving mons abilities they didn't have in that gen, so whatever.

**Pull request merged**
