### PR TITLE
Fix some errors in commands on info.js file

### PR DESCRIPTION
**Pull request by Bryan-0**

### CODE REVIEW

**Comment by AustinXII** [comment]
global rules seems kind of pointless, when you think of rules dont you think of the entire server? I understand there are room rules aswell but still seems strange to me.

**Comment by Bryan-0** [comment]
mmm, well I don't know. I will wait what Zarel says.

**Comment by SolarisFox** [comment]
This would make the command somewhat misleading because `/rules` has different functionality in rooms, wherein it pulls up the room rules as well. If we were to use this alias it should probably not pull up the room rules, but at that point you're making a command that has less functionality and I just don't see a reason for it.

**Comment by Bryan-0** [comment]
I think you are right.

**Comment by Bryan-0** [comment]
Updated.

**Pull request merged**
