### PR TITLE
Type: Null is PU

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by Zarel** [comment]
Could really use links to sources here...

**Comment by KrisXV** [comment]
Not really because antar doesnt ever mention when NFEs change tiers unless they're already in said tier

**Comment by KrisXV** [comment]
but here

https://www.smogon.com/forums/threads/usage-based-tier-update-for-october-2018.3642391/#post-7926268

 | 49   | Type: Null         |  3.439% |

**Comment by Zarel** [comment]
Yeah, that kind of link is enough.

**Pull request merged**
