### PR TITLE
Weather modifies baseDamage instead of basePower

### PR DESCRIPTION
**Pull request by sobolews**
Closing this TODO: http://git.io/vZKZ5

This PR also contains a small refactoring for damage randomization, to allow more resilient testing of damage calculations.

### CODE REVIEW

**Comment by Marty-D** [comment]
Fantastic, thanks! The randomizer refactor will surely help later with moves that don't do damage variation at all (such as Spit Up in Gen 3 and 4). :+1:

**Comment by DanUgore** [comment]
Oh awesome this is finally done.

**Comment by ascriptmaster** [comment]
I'd structure the tests a little differently but I'll deal with those myself. Great work, though :+1:

**Comment by Zarel** [comment]
@sobolews, can I get a license from you?

Repeat after me:

> I, ____, hereby license all my contributions to the Pokémon Showdown project, past and future, under the MIT license, as described in https://github.com/Zarel/Pokemon-Showdown/blob/ee65f8a72c713fa4e9408c884056a9ee0d631d00/LICENSE

**Comment by sobolews** [comment]
Oh, sure thing :)
I, Carl Sobolewski, hereby license all my contributions to the Pokémon Showdown project, past and future, under the MIT license, reproduced at https://opensource.org/licenses/MIT

**Pull request merged**
