### PR TITLE
Fix Air Lock and Cloud Nine

### PR DESCRIPTION
**Pull request by Rhythms88**
Moved them from AnyModifyPokemon to AnySwitchIn based on information in
https://github.com/Zarel/Pokemon-Showdown/issues/1789 from @gamut-was-taken

### CODE REVIEW

**Comment by Rhythms88** [comment]
lol i forgot to test i suck

**Comment by xfix** [comment]
> Always run `npm test` before submitting Pull Requests.

**Comment by Rhythms88** [comment]
I know, I can't believe I forgot to do that myself...lol

**Comment by ascriptmaster** [comment]
And the regressions I put in place immediately come in handy

I think I see the problem now. The fix also needs to be added within the `Battle#singleEvent` function in the correct place (somewhere around line 2031?) as well.

**Comment by Rhythms88** [comment]
Fixed all of the errors

**Comment by Zarel** [comment]
Why are we still setting `.ignore` if the point was to stop using `.ignore`?

**Comment by ascriptmaster** [comment]
There was a time when we were trying to set the `ignore` flag in ways that weren't in `ModifyPokemon` but the idea was eventually scrapped. We just forgot to remove that part once we implemented the new system

**Comment by Rhythms88** [comment]
Removed them

**Comment by Zarel** [comment]
@ascriptmaster, so is this good for merge?

**Comment by TheImmortal** [comment]
Obligatory @Marty-D tag.

**Comment by Marty-D** [comment]
I briefly tested with several weather effects and they all worked as expected. It'll be nice to see one of the longest-standing bugs go away. Looks good! :+1:

**Pull request merged**
