### PR TITLE
Add Mega Ampharos Alias

### PR DESCRIPTION
**Pull request by Yoshizilla315**
I don't know why this isn't an alias yet so I added it.

### CODE REVIEW

**Comment by Zarel** [comment]
The word you are looking for is `add`, not `update`

**Comment by Yoshizilla315** [comment]
You're right haha, I'm just so used to using Update in my proposals. Thanks.

**Comment by Zarel** [comment]
Also, commit summaries should probably not have jokes in them; will make history annoying.

**Comment by Zarel** [comment]
But also I need to hear other people say whether or not this alias is actually good; I've literally never heard it.

**Comment by AustinXII** [comment]
This is a very common Alias, being more popularized by YouTubers such as Pokeaim

**Comment by AustinXII** [comment]
For what it's worth this has been an alias for mAmphy since it was revealed/released

**Comment by Yoshizilla315** [comment]
Uh yeah probably shouldn't have the word obvious in there haha, but uh yeah it was popularized by pokeaim and has been used since release so I thought it was kind of weird that it wasn't in there. Next time I'll be sure to provide an explanation.

**Pull request merged**
