### PR TITLE
Fix Perish Song + Soundproof

### PR DESCRIPTION
**Pull request by MacChaeger**
Perish Song doesn't do this automatically any more as of #3483. http://replay.pokemonshowdown.com/gen7customgame-567963603

### CODE REVIEW

**Comment by Zarel** [comment]
Does this apply to all past gens?

**Comment by Zarel** [comment]
(Your change, the way it's currently written, would apply to all past gens)

**Comment by MacChaeger** [comment]
Well, the Perish Song change applies to all past gens, and neither Perish Song nor Soundproof are modified in any way that would conflict with either of these changes in past gens, so yes, this should be good as-is.

**Comment by Zarel** [comment]
@Marty-D

**Comment by Marty-D** [comment]
I can only assume this was here for Heal Bell in Gen 5. Heal Bell itself has been refactored multiple times since then and this was probably forgotten. Worth checking if it still works properly there, but otherwise this seems regressionless.

**Comment by Zarel** [comment]
Can you write a test for Heal Bell?

**Comment by MacChaeger** [comment]
Me?

**Comment by Zarel** [comment]
or Marty? I could too if someone described the thing

**Comment by MacChaeger** [comment]
OK I don't think I understand how Heal Bell is programmed, but would the test just be "Heal Bell should cure Soundproof users of the move in gen 5"?

**Comment by Zarel** [comment]
idk, Marty is most likely to know

**Comment by Marty-D** [comment]
Turns out Heal Bell is hardcoded in every gen, so it will never interact with changes to Soundproof here.

**Pull request merged**
