### PR TITLE
Random Battle: Update Tauros

### PR DESCRIPTION
**Pull request by ascriptmaster**
Single Battle: Replace Rock Climb with Return if Tauros does not have
Sheer Force (1/3 chance of getting Intimidate)

Double Battle: Remove Rock Climb for Return and add Stone Edge, since
Tauros always has Intimidate in Random Double Battles

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Alternatively, we could trade Rock Climb for the slightly less powerful Body Slam (weaker by 5 BP but perfect accuracy) so it still has utility with Intimidate sets

**Comment by TheImmortal** [comment]
Replace it with Double Edge, not Return. And there's no need to change `hasMove`.

**Comment by ascriptmaster** [comment]
Tauros can already roll Double Edge, but it can't roll Return as it is now.

I still think using Body Slam is a good idea because of the whole "randbats doesn't care about ability/move combination illegalities"

**Comment by TheImmortal** [comment]
4949d4a4763474f73913941ab9c329a5160bcfd9. No to Body Slam. Double-Edge is the preferred move but Rock Climb is a suitable alternative without recoil as it only a slightly weaker. Do what I said above.

**Comment by ascriptmaster** [comment]
Body Slam hits for 110.5 BP after Sheer Force, and Rock Climb is 117 BP.  Is the 6.5 BP difference really worth the 15% less accuracy?

**Comment by TheImmortal** [comment]
No. However, that isn't the actual case here. Body Slam means you're willing to give up 9.5 BP to run it instead of Double-Edge. That is not worth it. Rock Climb is giving up 3 BP and some accuracy for no recoil, which is more worth it.

**Pull request merged**
