### PR TITLE
/formathelp: Fix near matches

### PR DESCRIPTION
**Pull request by MacChaeger**
https://github.com/Zarel/Pokemon-Showdown/pull/3914#pullrequestreview-61672679

### CODE REVIEW

**Comment by Zarel** [comment]
@urkerab is this what you wanted? I can't actually read this

**Comment by urkerab** [comment]
Not quite; line 1397 should have been moved, not copied.

**Comment by Zarel** [comment]
Now?

**Comment by urkerab** [comment]
LGTM.

**Pull request merged**
