### PR TITLE
Enhance process management via PM API

### PR DESCRIPTION
**Pull request by Slayer95**
- Creating multiprocess tasks easier than ever.
- ``Tools.dexsearchProcess`` mess cleaned.
- Processes for signed messages verification and dexsearch are now fully optional.

### CODE REVIEW

**Comment by Zarel** [comment]
`process.send` is no longer a good way to detect whether you're a child process, because PS itself might be running in a child process.

The new way is `module === process.mainModule`

**Comment by Zarel** [comment]
I'm not sure `onMessageUpstream` and `onMessageDownstream` are the best names here. Maybe `onParentMessage` and `onChildMessage`.

**Comment by Slayer95** [comment]
I am checking those together everywhere relevant. Note that leaving the ``process.send`` check out altogether would break ``node team-validator.js`` (which is actually useful to track down some syntax errors due to a bug in stack traces in Node v4-5).

Regarding naming, do your proposals convey the directionality semantics properly? I am not sure of that, but I'd prefer those names had I had that guarantee.

**Comment by Zarel** [comment]
I haven't forgotten about this but I don't have time to go over it in detail until probably Monday.

**Comment by Zarel** [comment]
I don't think "upstream" conveys directionality very well, either. `onParentReceive` conveys perfectly, though.

**Comment by Zarel** [comment]
Worth merging. I don't like all of it, but it's mostly good so I'd rather merge and commit on top of it than trying to iterate here.

**Pull request merged**
