### PR TITLE
Add Create Your Formats Battle (Suspect Test)

### PR DESCRIPTION
**Pull request by Kiribartlett**
Today i'm testing Create your Formats Battle (CYF). So I has to add first and then I test the format. If is working, then I will test. If is not, then I will fix or/and add something.

### CODE REVIEW

**Comment by Marty-D** [comment]
That's not how contributing works; you should test your changes first and then submit a pull request, not the other way around. Either way, this isn't something the main server wants.

**Comment by Kiribartlett** [comment]
Yeah. But I wonder what is it?

**Comment by HoeenCoder** [comment]
Test your changes locally first, fix any issues, then PR. It also helps (alot) to discus your changes with the developers first before doing the work, so you don't waste anytime on something that would get rejected.

**Comment by Zarel** [comment]
What are you trying to ask? Marty's comment seems clear enough to me.

**Pull request closed without merging**
