### PR TITLE
Random Battle: Reject Disable without Substitute

### PR DESCRIPTION
**Pull request by ascriptmaster**
Affects Gengar formes since SubDisable is the only viable set with
Disable.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Nope. I don't agree with this; Gengar do run Disable without Sub, sometimes.

More importantly, Mega Gengar doesn't even have Substitute in its moves so you're essentially rejecting Disable every time.

**Comment by ascriptmaster** [comment]
Since when was Disable w/o Substitute viable? I guess Mega Gengar can use Protect in its place so something could be done there, but that's all I can think of.

**Comment by TheImmortal** [comment]
It's viable on Prankster Pokemon or Pokemon with high speed. Sub benefits you if you're slow and sub on the switch.

**Comment by ascriptmaster** [comment]
When is it viable on high speed Pokemon without Sub or Protect? Don't you Sub or Protect to block an attack, then disable it the next turn? Isn't that the whole premise of SubProtect? Why would being slow even work in a SubDisable scenario?

**Comment by TheImmortal** [comment]
>Why would being slow even work in a SubDisable scenario?

They attack you with the super effective move, breaking your sub, and then you disable it.

>When is it viable on high speed Pokemon without Sub or Protect?

When you come in after your teammate is killed with the move that they would use on you as well.

**Comment by ascriptmaster** [comment]
But when are these strategies viable in random battle? There's a reason we only put it on Gengar

**Comment by ascriptmaster** [comment]
At any rate, perhaps we should examine the original complaint: a Pokemon with pain split, wisp, disable, and shadow ball. I'm pretty sure disable isn't going to be useful in such a set

**Comment by ascriptmaster** [comment]
No suggestions? At any rate, Disable without Substitute and/or a second attacking move to use is probably not a good idea

**Pull request closed without merging**
