### PR TITLE
Allow Leaders to block pms

### PR DESCRIPTION
**Pull request by HoeenCoder**
Talked about in upper staff a few days ago, no objections, supported.

### CODE REVIEW

**Comment by Zarel** [comment]
...

**Comment by Zarel** [comment]
Blah fine, it's not like I have individual PM blocking working yet...

**Comment by AustinXII** [comment]
I feel like at this point there is no reason to prevent staff from blocking pms :-/

**Comment by HoeenCoder** [comment]
Once help tickets are farther along (and we can direct all appeals to them via the button without spamming the staff room) Id be open to that.

**Comment by AustinXII** [comment]
Convincing @Zarel is the biggest concern. He didn’t seem to pleased to add this and iirc he’s expressed his distaste in staff blocking pms as it defeats the purpose of being on a staff account or something like that

**Comment by Zarel** [comment]
Oh yeah, I did it before because it was before help tickets were a thing.

Yeah, a staff block should show a link to Help tickets, but as long as that's a thing, I don't have a problem with staff blocking PMs.

**Comment by HoeenCoder** [comment]
Ill add this to my help tickets PR then.

**Pull request merged**
