### PR TITLE
Fix confusion problem with unaware

### PR DESCRIPTION
**Pull request by Tigerball890**
Actually works this time (last time build failed)

### CODE REVIEW

**Comment by Tigerball890** [comment]
I literally have no idea why this fails. "262 === 66" is error message.

**Comment by Zarel** [comment]
I told you why this fails in the previous pull request. Why did you ignore me?

**Comment by Zarel** [comment]
The relevant line from the error message is:

`1) Battle simulation Abilities Unaware should ignore attack stage changes when Pokemon with it are attacked`

**Comment by Tigerball890** [comment]
OK. At the time, I was asleep.

**Pull request closed without merging**
