### PR TITLE
Random Battle: Reject Aurorus Snow Warning with Hyper Voice

### PR DESCRIPTION
**Pull request by ascriptmaster**
Added a counter that tracks Normal damaging moves for purposes of -ate
Abilities, in case it becomes important later. This counter also
future-proofs Aurorus in case it receives other viable Normal attacks
later.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Or maybe we should have the -ate ability have higher priority than Snow Warning, then reject that instead based on Normal attacks?

Actually, that's a great idea and I'll probably implement it later today since I have to sleep

It'll also let you have things like Cute Charm Sylveon if it's missing Hyper Voice, to truly mess people up. Surprise, your mon is hit by Attract now!

**Comment by TheImmortal** [comment]
1efd11466f9f570f257e3e62df2308dcffe11d16 buffs -ate abilities. I think you should change this now so that it rejects -ate abilities without normal moves.

**Comment by ascriptmaster** [comment]
That was already my plan since I wanted -ate to have higher priority than Snow Warning, so the check would need to be rejecting that anyways. I'll get to it in a few hours.

**Comment by TheImmortal** [comment]
@Zarel why did you merge this already...

**Pull request merged**
