### PR TITLE
Fix Last Will Crash

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by Zarel** [comment]
...this is a bug in Last Will, not in Rock Head. The Rock Head code is working correctly. Don't mess with it.

**Comment by Zarel** [comment]
Please tell me you haven't screwed up any other good code this way, trying to fix Last Will...............

**Comment by Spandamn** [comment]
No, I havent... 
I felt that this would be better instead of adding a mod, and I dont think it breaks anything

**Comment by Nixola** [comment]
It literally just checks if ``effects`` exists instead of letting it cause an error in case it doesn't. While it's true only Last Will brought this up so far, it kind of can be considered a Rock Head bug.

**Comment by Zarel** [comment]
@Nixola, I don't think you understand.

`effect` not existing is a bug, that should be fixed by not passing a nonexistent effect into the Damage event, not by checking for `effect` literally everywhere it's used, which would make the code a whole lot messier/slower.

**Comment by Zarel** [comment]
In other words, the `Damage` handler signature is `(damage: number, target: Pokemon, source: Pokemon, effect: Effect) => (damage: number | undefined | null | false)`

`effect` should always be an `Effect`, not `Effect | undefined`. Passing an incorrect value into the event is a bug in the thing that passed it in, not the handler function.

**Comment by asgdf** [comment]
This is the wrong approach because the crash isn't due to ``effect`` being null, it's due to ``activeMove`` being null.
This is because Last Will kind of causes a nested move execution, it does a new move while not being done executing the old one - recoil being an example of something that'd be done after the last will. If the last will move fails, then it sets activeMove to null.
What might work would be storing ``activeMove`` before the last will and re-setting it afterwards?

**Comment by Zarel** [comment]
The correct solution seems to be doing the Last Will `onAfterMove`?

**Comment by asgdf** [comment]
Wouldn't `onAfterMove` be called after the fainting, meaning the last will wouldn't have a valid source? There's also the issue of fainting for reasons not related to moves - weather, status, hazards, whatever. I think that limits it to `onBeforeFaint`?

**Comment by Zarel** [comment]
All work. The last will already doesn't have a valid source, which is why we wrap the entire thing in a `try` block.

**Comment by asgdf** [comment]
Hm, maybe on `onAfterMove` to cover moves, and then `onAfterDamage` for all non-move effects that might have fainted something.

**Comment by asgdf** [comment]
Ok just tested, that works, @Spandamn do you want to it or should I make a PR?

**Comment by Zarel** [comment]
@asgdf, make a PR.

**Comment by urkerab** [comment]
Heh, so it turns out that by chance http://www.smogon.com/forums/posts/7333466 was right all along... I would never have guessed that `activeMove` was the problem though.

**Comment by Zarel** [comment]
Me neither; I'm pretty sure PS supports nested moves because we do use it for move calling iirc.

**Comment by Zarel** [comment]
Oh, it's because it's `runMove` and not `useMove`. Yes, you can't call `runMove` when an active move already exists; PS doesn't support that.

**Comment by Zarel** [comment]
@Spandamn, so yeah, I hope you understand the problem now?

**Comment by urkerab** [comment]
> you can't call runMove when an active move already exists; PS doesn't support that.

Looks like Dancerability got lucky then?

**Comment by Zarel** [comment]
Dancer calls `runMove` after the active move has resolved, it's written very carefully to work properly.

**Comment by urkerab** [comment]
Dancer itself does, but Dancerability, the OM, doesn't, thus it got lucky.

**Comment by Zarel** [comment]
Oh, yeah, probably.

**Pull request closed without merging**
