### PR TITLE
Locale aware time in /roomevents

### PR DESCRIPTION
**Pull request by xfix**
Depends on Zarel/Pokemon-Showdown-Client#950, but won't cause problems without it.

### CODE REVIEW

**Comment by bumbadadabum** [comment]
How would this work for dates like "every Sunday at 9"?

**Comment by xfix** [comment]
@bumbadadabum: Simply leave it unchanged, locale aware time leaves unrecognized time formats unchanged.

**Comment by xfix** [comment]
That said, it would be sorta cool to have ranges, but even this basic functionality should be fine. I will look into ranges later.

**Comment by bumbadadabum** [comment]
I think this is fine, great addition!

**Pull request merged**
