### PR TITLE
Run effectiveness events even for string type

### PR DESCRIPTION
**Pull request by urkerab**
Reported [here](https://www.smogon.com/forums/posts/8066734/).

This is a regression from commit 13614b9 which among other things stopped `onEffectiveness` events from being sent when running type effectiveness for a string rather than an `ActiveMove`, so to handle these I picked an innocuous move and manually set its type.

### CODE REVIEW

**Comment by Zarel** [comment]
I don't really like the idea of running it on a fake Judgment, but I guess I have no better ideas.

**Comment by Zarel** [comment]
Can you add a test?

**Comment by urkerab** [comment]
I just took the existing type effectiveness test from Stealth Rock, copied it to the Inverse Battle test, and switched the order of the Pokémon so that they are in descending damage order again.

**Comment by Zarel** [comment]
Looks good, thanks!

**Pull request merged**
