### PR TITLE
Reject Magnet Pull on non-Earth Power Probopass

### PR DESCRIPTION
**Pull request by ascriptmaster**
Without Earth Power, there isn't anything Probopass can actually do to hurt the Steels that it traps, so it might as well get Sturdy in those situations.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Hmm. Should we look at Golem-Alola as well?

**Comment by ascriptmaster** [comment]
I personally feel like Alolan Golem has the Attack to hit hard with Thunder Punch, and Alolan Golem should always have it based on the code, as long as it doesn't have Return (in which case it has Galvanize). This is why I was focusing on Probopass, because it has weak Special Attack and both STABs are resisted by Steel. I'll leave it to your judgment, though.

Also, if Magnet Pull is rejected on Golem, it will get Galvanize, which is not good for it without Return.

**Comment by TheImmortal** [comment]
Fair. Btw, forgot to change gen 6.

**Comment by ascriptmaster** [comment]
ok

**Pull request merged**
