### PR TITLE
Gen-NEXT: Fix Intrinsic Levitate

### PR DESCRIPTION
**Pull request by ascriptmaster**
An examination of the commit history seems to indicate that it was
intended to be bypassed by Mold Breaker variants, and not be affected
by Gastro Acid.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
@Zarel because this affects Gen-NEXT exclusively. The old code before my refactor had `pokemon.ignore['Ability'] !== 'A'`, which means intrinsics are negated by Mold Breaker variants. However, when I refactored I accidentally set it to negate it by Gastro Acid, and NOT Mold Breaker variants.

Is it supposed to be bypassed by Mold Breaker only, or by both Mold Breaker and Gastro Acid?

**Comment by Zarel** [comment]
Mold Breaker: bypasses

Gastro Acid: whichever's easier to code; prefer no bypass

**Comment by Zarel** [comment]
Most of NEXT mechanics are "whichever's easier to code" if they don't have a very big effect on balance.

**Comment by ascriptmaster** [comment]
Gastro Acid is really easy to code now that we have `ignoringAbility`. It was even easier pre-refactor: checking `ignore['Ability']` for truthiness covered both automatically.

Speaking of Mold Breaker, I should probably rename `suppressAttackEvents` to `suppressingAttackEvents` to be in line with the two `ignoring` functions.

**Comment by Zarel** [comment]
You can choose whichever, then.

**Pull request merged**
