### PR TITLE
Fix uploading replays

### PR DESCRIPTION
**Pull request by HoeenCoder**
`join('\n')` is done in `room.getLog()` now.

### CODE REVIEW

**Comment by Zarel** [comment]
This is not hotpatchable...

**Comment by Zarel** [comment]
Also let's rename `logidx` to `channel` and move the search/replace inside it.

**Comment by HoeenCoder** [comment]
Yeah it isn't. Should I remind you to merge this before you restart / shortly after if i'm not on before it?

**Comment by Zarel** [comment]
Probably, yeah.

**Comment by Zarel** [comment]
c74fefa2c7479c508a55a

**Pull request merged**
