### PR TITLE
Return if /accept has no userid given

### PR DESCRIPTION
**Pull request by Morfent**

### CODE REVIEW

**Comment by Zarel** [comment]
Why? In the old code it'd still be O(1)-ish and still give an error message. This one even skips an error message. Is that desirable?

**Comment by Morfent** [comment]
It helps when the command's entered manually instead of through clicking accept on the challenge box. An error message would be a better idea than skipping it though.

**Comment by Zarel** [comment]
That, or return documentation. Although I guess it's undocumented.

**Comment by Zarel** [comment]
We might want to detect if there's only one challenge and if so, accept that one? Maybe make sure it's a format that doesn't require teams like randbat.

**Comment by Morfent** [comment]
Documentation would probably be more helpful. Accepting the only challenge if no userid's given sounds good.

**Comment by Morfent** [comment]
Needing the format to use random teams if no userid's given doesn't seem reasonable to me if it's not needed at all with a userid. Would adding an extra parameter to ``user.acceptChallengeFrom`` to detect whether or not the command was sent from the accept button be reasonable, if it should still check if the format requires teams when the command's not sent from it?

**Comment by Morfent** [comment]
While I'm at it, I'll add the same functionality to /reject

**Comment by Zarel** [comment]
You're doing a lot of work to a pullreq that can't be reopened fsr... Maybe make a new pullreq?

How would you send the teams? You'd have to make a client-side commit to use your first compatible team when sending `/accept`.

**Comment by Morfent** [comment]
Oh, now I see why you suggested this working only with random team formats. I'll remake this pullreq and get started on the client-side part.

**Pull request closed without merging**
