### PR TITLE
Add SM Triples 

### PR DESCRIPTION
**Pull request by Lord-Haji**
SM Triples format (Beta)

### CODE REVIEW

**Comment by Zarel** [comment]
...have you tested this? Why did you rename `beta` to `ß`?

In all, I don't see a need for this.

**Comment by Lord-Haji** [comment]
@zarel what's wrong in it?

**Comment by Zarel** [comment]
Other than your rename of "beta"? If we wanted to add SM Triples, we would've added it ourselves. We don't, which is why we haven't.

**Comment by Zarel** [comment]
There is zero need to make pullreqs like these, ever. It spams the repo.

**Comment by KrisOnPS** [comment]
also there isn't triples in Sun and Moon

**Pull request closed without merging**
