### PR TITLE
Helptickets: Lower the amount of helptickets that shared IPs can have

### PR DESCRIPTION
**Pull request by AustinXII**

### CODE REVIEW

**Comment by AustinXII** [comment]
@HoeenCoder

**Comment by Zarel** [comment]
I support this, for the record.

**Comment by HoeenCoder** [comment]
20/hour is fine with me

**Comment by AustinXII** [comment]
This should be good to merge then

**Comment by Zarel** [comment]
Honestly, 20/hour still seems really high.

**Comment by AustinXII** [comment]
I would have compromised with 10 without a doubt, I didn’t think you would be ok with something that low

**Pull request merged**
