### PR TITLE
Fix tournament auto disqualify error

### PR DESCRIPTION
**Pull request by ascriptmaster**
The function requires an "output" argument.

### CODE REVIEW

**Comment by Slayer95** [comment]
@ascripmaster, care explaining why you tagged this with ``do-not-merge``? :|

Also, in the future please remove the label before actually merging @Zarel

**Comment by Zarel** [comment]
I don't read labels... :| Really, if it shouldn't be merged, make a note of why in the pullreq summary or a comment.

**Comment by Slayer95** [comment]
... you should

**Comment by Zarel** [comment]
no objection

**Pull request merged**
