### PR TITLE
Rooms: fix memory leak in safe file writer functions

### PR DESCRIPTION
**Pull request by Morfent**
The writer functions held circular references to themselves due to their
finishWriting closure. Because the bug that required making an exception
for how files are written on Windows was fixed 4 years ago now (https://github.com/nodejs/node-v0.x-archive/commit/41f2725639dd10378cb0a5a57fe29157d7b926e9), it's perfectly safe to remove the closure and break the reference.

### CODE REVIEW

**Comment by Morfent** [comment]
If it's alright to, removing the regex from `GlobalRoom#writeChatRoomData` would stop the stringified `GlobalRoom#chatRoomData` from getting allocated to the heap, which would save much more memory than this already does. There isn't much else I'd be able to do about it since it's due to [a bug in v8's string slicing code](https://bugs.chromium.org/p/v8/issues/detail?id=2869)

**Comment by Zarel** [comment]
Why "never to be GCed"? It should be GCed once the write finishes, shouldn't it?

**Comment by Morfent** [comment]
I was mistaken. I' was taking heapdumps too quickly after calling the function, since the string does get GCed fairly quickly afterwards, but I didn't have the foresight to check that. The regex methods were probably just making the function take longer to finish or get GCed instead.

**Comment by Zarel** [comment]
I'm glad we pinned down another leak and simplified some code, but I actually don't think this is the main source of our problems right now.

**Comment by Zarel** [comment]
I'm still suspecting our map-like Objects to be the problem here.

**Comment by Morfent** [comment]
I doubted this would be the source, considering it didn't leak anywhere near enough memory to cause the crashes, but I think the leak's a combination of several problems, not just objects in dictionary mode, judging from what I could read in the coredumps. I suspect ProcessManager, Tools, and how timers are used throughout the code mainly.

**Comment by Zarel** [comment]
Yeah, closures always make me vaguely uncomfortable... Tell me more about Tools? It uses a lot of memory but I'm pretty sure its memory use is pretty constant...

**Pull request merged**
