### PR TITLE
Simplify high load game number checks

### PR DESCRIPTION
**Pull request by panpawn**
Sparked from https://github.com/Zarel/Pokemon-Showdown/commit/d105beeacdb719f7093b23dca2191bbd9016fe7b discussion.

### CODE REVIEW

**Comment by Zarel** [comment]
This just makes the check take more RAM, it only makes it more readable.

**Comment by Zarel** [comment]
We would previously have used `Object.size` but unfortunately that doesn't currently exist...

**Comment by panpawn** [comment]
So, is there nothing _to change_ with this then?

**Comment by Zarel** [comment]
Honestly, `Object.keys(...).length` might not be that bad. Do @Slayer95 and @kotarou3 have opinions?

**Comment by bumbadadabum** [comment]
Idk how much the RAM matters. This feels like you're putting too much
emphasis on something that matters very little.

**Comment by panpawn** [comment]
I believe kota had suggested it on the mentioned commit comments

**Comment by Zarel** [comment]
> Idk how much the RAM matters.

We're crashing multiple times a day because of a RAM issue. To be fair, I think it's way subtler than just "using too much RAM" but still...

**Comment by panpawn** [comment]
RAM has been the most of a resource that PS demands, so generally speaking, I wouldn't say that it "doesn't matter."

**Pull request merged**
