### PR TITLE
Remove depreciated EndAbility event

### PR DESCRIPTION
**Pull request by ascriptmaster**
The 'EndAbility' event was initially introduced for the implementation of
new weathers in ORAS, like Desolate Land, but has since been depreciated
in favor of an 'End' singleEvent.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
Updated since I missed one of the events.

**Comment by Zarel** [comment]
It's spelled "deprecated".

"Deprecated" means "we think it's bad"

"Depreciated" means "it lost value because time has passed"

**Comment by ascriptmaster** [comment]
bleh what is english

**Comment by Zarel** [comment]
A good rule of thumb is that "depreciate" is only used when money is directly involved.

**Pull request merged**
