### PR TITLE
Replace all s.substr(x, 1) with s.charAt(x)

### PR DESCRIPTION
**Pull request by Morfent**

### CODE REVIEW

**Comment by kotarou3** [comment]
Why not just `[0]`?

**Comment by Morfent** [comment]
Is there any difference in performance between the two? I used ``charAt`` to keep this consistent with the rest of the code

**Comment by Slayer95** [comment]
<code>charAt</code> is slightly better in Node 0.10 - 0.11.
<code>[0]</code> is slightly better in Node 0.12, io.js.

But I still believe that <code>charAt</code> is by spec better than </code>[0]</code> as the first one maps <code>String -> String</code> -throwing for other inputs-, while the later is too catch-all and may even return <code>undefined</code>.

**Comment by Zarel** [comment]
I like `charAt` because it makes it clearer that it's a string and not an array.,

**Pull request merged**
