### PR TITLE
Trivia: add all-time leaderboard

### PR DESCRIPTION
**Pull request by CheeseMuffin**

### CODE REVIEW

**Comment by Zarel** [comment]
Who handles Trivia? @Morfent?

**Comment by CheeseMuffin** [comment]
Should be morfent yeah

**Comment by Morfent** [comment]
Sorry I've been busy for the past week

I'm not sure it's a good idea to build on the ladder system when the original implementation of it I wrote is pretty bad. `triviaData.leaderboard` isn't much better than a glorified cache of `triviaData.ladder`, and the sorting algorithm from `Trivia#win`/`sortLadder` is not a very optimal way of handling that cache in the first place. I think it'd be a better idea to modify the schema of `triviaData.ladder` to handle all time rank vs. current rank and remove `triviaData.leaderboard` in lieu of an in-memory cache of the sorted ladder created when first loading the plugin, but before then the sorting algorithm needs to be fixed

**Comment by Morfent** [comment]
The all-time leaderboard would need a separate cache from the regular one, but it should be possible to do without needing to handle most of the sorting needed for the ladder twice

**Pull request closed without merging**
