### PR TITLE
Implement Triple Kick multiple accuracy checks

### PR DESCRIPTION
**Pull request by cadaeic**
Any multi-strike move with the `multiaccuracy` property set to `true` will now check for accuracy before each hit.

I have no knowledge, however, of whether Triple Kick actually uses its accuracy for hits 2 & 3 (instead of hard-coded 90% chance of connecting the hit), and if it does, whether it uses the same accuracy for each hit instead of adjusting to current accuracy/evasion modifiers which may change between hits.

The latter concern also extends to other multi-strike moves. If the user of a contact-making multi-strike move was damaged by Rocky Helmet or other similar sources to the point where it ate its Lansat Berry, the critical bonus, which is applied in `onModifyMove`, will not apply to the remaining hits. I suspect that this is not the case on cartridge. There may be also other similar cases. If these concerns turn out to be real, it might be necessary to look into whether more events need to be placed inside the multi-strike loop.

### CODE REVIEW

**Comment by Marty-D** [comment]
Yeah, Triple Kick rolls accuracy for each hit independently from the others. Skill Link is an exception to this since it overrides the check for the other hits, letting all three hit if the first one succeeds.

Your other concern is also valid since in the exact situation you described, any remaining hits will take into account the increased crit rate (just like any other stat modifier besides accuracy).

**Comment by cadaeic** [comment]
Correcting the interaction between critical rates and multi-strike moves would probably require moving critical stages to the `Pokemon` object.

Could you clarify as to what you mean by "just like any other stat modifier besides accuracy"? Does this mean that a No Guard Hitmontop using Triple Kick on a Mummy Pokemon will never miss the 2nd and 3rd hits anyway?

**Comment by ascriptmaster** [comment]
I can deal with the Lansat Berry issue.

"just like any other stat modifier" means that if the stat chances mid-attack, it affects later hits.

"...besides accuracy" just means that for most other multi-hit moves, the accuracy check already rolled once, and as such accuracy mods mid-attack normally won't affect it. Triple Kick is the obvious exception, though.

**Comment by Marty-D** [comment]
Yeah what @ascriptmaster said; my second point was about multi-hit moves that aren't Triple Kick.

As for the other question, losing No Guard mid attack would subject Triple Kick to the possibility of missing, but if it were Skill Link, the three hits would connect if the first did (even if Mummy is obtained after the first hit). It's the same behaviour as other multi-hit moves in that way.

**Pull request merged**
