### PR TITLE
BF: Update Marshadow

### PR DESCRIPTION
**Pull request by LegoFigure11**
Prevents fully Physical Marshadow from getting a Mixed Nature

### CODE REVIEW

**Comment by Zarel** [comment]
Didn't Kris PR a BF update? It hasn't even been merged yet, has it?

**Comment by Zarel** [comment]
#5351, still open. Will those conflict?

**Comment by LegoFigure11** [comment]
He didn't touch Ubers so assuming I understand how conflicts work it shouldn't. If you want to just edit this into that PR though go right ahead and I'll close this one.

**Comment by KrisXV** [comment]
The worst it’ll make me do if anything will just be a quick rebase, nothing severe

**Pull request merged**
