### PR TITLE
Remove config option for the crash guard

### PR DESCRIPTION
**Pull request by kotarou3**
Cut down a useless config option

### CODE REVIEW

**Comment by Slayer95** [comment]
Dupe of #865? I don't think anything has changed since then...

**Comment by kotarou3** [comment]
I forgot about that pull req!

Main rationale is: Do you turn it off? Do you expect anyone to turn it off?
My answer to both is "no", which is why I think it's worth removing

**Comment by Slayer95** [comment]
It's turned off in the test suite. Certainly not via ``Config.crashguard``, but I'd say not using the config option there is a mistake.

**Comment by kotarou3** [comment]
Then maybe the test suite should explicitly use `Config.crashguard` then (rather than `removeListener`ing)? Then there's sufficient reason to keep the config imo

**Comment by Slayer95** [comment]
Yea

**Comment by kotarou3** [comment]
Done

**Pull request merged**
