### PR TITLE
Full Potential: Update banlist

### PR DESCRIPTION
**Pull request by KrisOnline**
Alolan Raichu and Speed-doubling abilities have been banned: http://www.smogon.com/forums/threads/full-potential-om-of-the-month.3596777/page-7#post-7273360

### CODE REVIEW

**Comment by KrisOnline** [comment]
@The Immortal

**Comment by KrisOnline** [comment]
@TheImmortal

**Comment by KrisOnline** [comment]
Can you please wait until the checks of pullreqs that you edit have gone through before merging? It's not a big issue but it's really annoying.

**Comment by panpawn** [comment]
For what it's worth, it looks like Travis failing was completely unrelated to TI's commit, and instead was from the current working master branch at the time.

**Pull request merged**
