### PR TITLE
Update possibly shiny gen 3 events

### PR DESCRIPTION
**Pull request by TheMantyke**
Updated Gen 3 eggs to be legally shiny. Fixed an issue with Plusle and Minun having each others event moves

### CODE REVIEW

**Comment by Zarel** [comment]
@TheImmortal, should we have some way of marking "possible shiny" like `shiny: 1,` or something?

**Comment by TheImmortal** [comment]
Yes, I was just doing that.

**Comment by Zarel** [comment]
I'll let you handle this, then.

**Comment by TheImmortal** [comment]
@TheMantyke 0a5dfd649e6a06ef5164ab3a707d4775521511a5

Can you update this? Also, you need to modify the events in the gen 5, gen 4, and gen 3 mods.

**Comment by Joimer** [comment]
If only we inherited upwards instead of downwards :p

**Comment by Zarel** [comment]
> If only we inherited upwards instead of downwards :p

What does that have to do with anything? If we actually inherited downwards, we wouldn't need to modify gen 3-5 at all.

Why do we have to modify gen 3-5 events anyway?

**Comment by TheImmortal** [comment]
>Why do we have to modify gen 3-5 events anyway?

Because past gens don't inherit event data. I didn't make it, it's always been like this. If you want to fix it so that we only need _one_ event database, that would be great.

**Comment by TheMantyke** [comment]
To start, forgive any strange mistakes I've made submitting these changes. I haven't previously used Github before.

I parsed the code I submitted earlier and set all shiny values to `"shiny": 1,` For all Egg events and a few 4th gen wild encounters.

**Comment by Zarel** [comment]
@TheImmortal, you've never fixed it yourself or asked me to fix it......

**Comment by Zarel** [comment]
@TheImmortal, have you tried just replacing `eventPokemon: ...` with `inherit: true,`?

**Comment by TheImmortal** [comment]
I've never had an issue with it, so no. It's up to you how you want the events to be @Zarel.

**Comment by TheImmortal** [comment]
I did this myself in 7e33b0a855e9268d5789b7d4f003ada8f1491126 @TheMantyke.

**Pull request closed without merging**
