### PR TITLE
Update scripts.js

### PR DESCRIPTION
**Pull request by sparktrain**
Give Dirpz an even HP number so that Sitrus Berry can activate after Belly Drum.

### CODE REVIEW

**Comment by Zarel** [comment]
Please refer to CONTRIBUTING.md for commit naming rules:

https://github.com/Zarel/Pokemon-Showdown/blob/master/CONTRIBUTING.md

**Comment by Joimer** [comment]
The proper name could be:
Seasonal: Change EVs on on Dirpz
Then what you put in the PR as the description. Can you amend and squash?

**Comment by Zarel** [comment]
I assume you mean "amend _or_ squash"

**Comment by Joimer** [comment]
Yes, was on phone. And I forgot we squashmerge now, lol

**Pull request merged**
