### PR TITLE
Random Battle: Allow Belly Drum Gluttony

### PR DESCRIPTION
**Pull request by ascriptmaster**
Affects Linoone. Gluttony currently has a rating far too low to be chosen.

### CODE REVIEW

**Comment by TheImmortal** [comment]
We could make it 1.5 but what could we use to reject Quick Feet?

**Comment by ascriptmaster** [comment]
Should I keep the chance factor? 

I also need to check all other gluttony users to ensure that the rating change won't negatively affect any of them

**Comment by MacChaeger** [comment]
This would be nice in Doubles, too.

**Comment by ascriptmaster** [comment]
Updated

**Pull request merged**
