### PR TITLE
Use most recent version of Node for tests.

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by Zarel** [comment]
Do we need both? Should we just test Node 0.12?

**Comment by kotarou3** [comment]
We should just switch to Node 0.12 completely, and switch to some available ES6 features (See: http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12)

**Comment by DanUgore** [comment]
I'm liking those features

**Comment by Zarel** [comment]
Yeah, let's just move over to Node 0.12.

**Comment by xfix** [comment]
I'm not sure about switching right now. Most server owners I assume use Node.js from their operating system repository. Most of these are 0.10 (only Arch Linux has 0.12 right now).

(although I will say that `for (var i of array)` by itself looks quite intriguing)

**Comment by Zarel** [comment]
`Array#forEach` wasn't syntactic sugar. It was noticeably slower than a regular for-loop, and it required a ton of boilerplate unless you have arrow functions (which, incidentally, Node 0.12 still doesn't).

**Comment by ascriptmaster** [comment]
Bump!

**Comment by Zarel** [comment]
Done in 90681760d8.

**Pull request closed without merging**
