### PR TITLE
Don't pass the id of a format to Tools.mod

### PR DESCRIPTION
**Pull request by urkerab**
The other callers pass a Format object, which has different behaviour, in particular, it uses the format's actual `mod` instead of guessing that it's the same as the format.

I'm wondering whether the `battleProtoCache` should be keyed off `mod` rather than `format` but I'm not going to touch it with all of those prototypes flying around. (Or maybe I should convert it to a Map?)

### CODE REVIEW

**Comment by Zarel** [comment]
It was originally designed to be keyed off `mod`, but I suppose in practice it's been used differently.

**Comment by urkerab** [comment]
I took the plunge and rewrote the caching code; it hasn't broken my server yet.

**Comment by Zarel** [comment]
I'm confused, what does this change?

**Comment by Zarel** [comment]
It looks like you replaced an Object with a Map (which is good) and also refactored out an IIFE... but is that all?

**Comment by urkerab** [comment]
No, the important bit is that we now pass the `mod` to `Tools.mod` rather than the `formatarg`, which is neither the name of a mod nor a `Format` object (which is an acceptable alternative).

**Comment by Zarel** [comment]
Okay...

**Pull request merged**
