### PR TITLE
Update pokedex colors

### PR DESCRIPTION
**Pull request by HoeenCoder**
Really minor change prompted by a bug report post. [colors changed](http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_color#Changes)
(let me know if I shouldn't use bulbapedia for proofs anymore)

I didn't touch shellos/gastrodon because the east formes didn't have seperate data entries.

### CODE REVIEW

**Comment by urkerab** [comment]
Strictly speaking, should the Gen 6 colours be changed back, so to speak?

**Comment by HoeenCoder** [comment]
I only edited the gen 7 data, the gen 6 color data is unchanged, unless im wrong. Ill check it out in a little while.

**Comment by HoeenCoder** [comment]
Yeah looks like it would be needed, @Marty-D should I update the colors for gen 6 that or is it not important?

**Comment by Marty-D** [comment]
I guess if old OMs used that data, sure.

**Comment by urkerab** [comment]
I did find one OM that used that data, and that was Palette Pals.

**Pull request merged**
