### PR TITLE
Rooms: move matchmaking logic to ladders-matchmaker.js

### PR DESCRIPTION
**Pull request by Morfent**
This abstracts matchmaking logic from the global room away to its own
module, allowing the two to be decoupled from each other entirely with
some refactoring.

Related to #3361

### CODE REVIEW

**Comment by Zarel** [comment]
Honestly. `ladders.js` already exists; we might not want to create an entirely new file...

**Comment by Morfent** [comment]
...yeah, the ladder related stuff in `Matchmaker` should've been a giveaway. I'll refactor it

**Comment by Morfent** [comment]
Moved everything over

**Comment by Zarel** [comment]
Unfortunately, `ladders-remote.js` also exists...

**Comment by Morfent** [comment]
`Ladders` is two entirely different modules depending on config...? I feel like it'd make sense to merge them and export instances of `Ladder` based off what the config settings currently are in case `Config.remoteLadder` changes while PS is running. Putting the matchmaker in one file for the other to import and export already makes the two aware of each other, so it seems to defeat the purpose of having them be separate modules. Maybe I'm completely misunderstanding something

**Comment by Zarel** [comment]
Define "merge them and export instances"? They're two files with the same API because that lets them support different database backends.

**Comment by Morfent** [comment]
Take a `RemoteLadder` class from `ladder-remote.js` and a `Ladder` one from `ladder.js`. `Ladders`/`getLadder` could return an instance of either class depending on what `Config.remoteladder` is set to. Same deal with the other `Ladders` properties. I wouldn't be asking about this if they didn't have a similar API.

**Comment by Zarel** [comment]
Works, I guess.

We might want to have a `Matchmaker` base class that `Ladder` extends?

**Comment by Zarel** [comment]
Nah, needs to be the other way around, actually. Maybe they should be separate objects... Kind of wish they were the same, though.

**Comment by Morfent** [comment]
Matchmaker that keeps a cache of ladders?

**Comment by Zarel** [comment]
Sounds weird. For now we can just call it `LadderMatchmaker` and keep them separate; I'll figure out how to best combine them later.

**Comment by Morfent** [comment]
Ok

**Comment by Morfent** [comment]
Merged the files. Code's kinda ugly though

**Comment by Zarel** [comment]
In what world does "keep them separate" mean "merge the files" to you? o_o

**Comment by Morfent** [comment]
I missed this comment:

**Comment by Zarel** [comment]
`ladders.js` `ladders-remote.js` `ladders-matchmaker.js`

**Comment by Morfent** [comment]
Ohhh. I was confused what you meant by `LadderMatchmaker` and assumed you wanted them in the same file, but still kept separate classes from each other. So more along the lines of what I had before?

**Comment by Zarel** [comment]
Yeah.

**Comment by Morfent** [comment]
Done

**Comment by Zarel** [comment]
Are you aware you removed your socket tests? Those should be in a different commit if that was intentional.

**Comment by Morfent** [comment]
I wasn't. I probably moved it while fixing async tests and forgot to move it back

**Comment by Zarel** [comment]
Yay!

**Pull request merged**
