### PR TITLE
Add more doubles tier support

### PR DESCRIPTION
**Pull request by KrisXV**
This is the server-side change for adding support for Doubles NU in the teambuilder. While Doubles NU does not have a format, there is already server support for it in the teambuilder, and I got approval from MajorBowman about adding a "DNU" section despite there not being a DNU format. This would have the same functionality as "NU" does for GSC; there isn't an actual GSC NU ladder, but it's still a format in the teambuilder to separate UU from NU.

[23:32:46] +Kris: hi i have 1 more question for doubles teambuilder stuff
[23:32:55] @MajorBowman: what's up
[23:33:24] +Kris: so ik DNU isn't rly a supported meta anymore but would u be okay with me implementing the DNU made from usage to separate "viable" and "unviable" duu mons?
[23:34:09] @MajorBowman: DNU isn't really a thing at all, i don't know if i want it showing up in the teambuilder
[23:34:27] +Kris: it would be kind of the same idea as Untiered in the smogon pokedex
[23:34:28] @MajorBowman: if it's like a silent sorting kinda thing that's fine but i don't really know if DNU showing up as a 'tier' is a good idea
[23:34:47] +Kris: it wont show up as a tier/ladderable format/ teambuilding format etc
[23:35:01] +Kris: its just like the "NFEs not in a higher tier"
[23:35:04] +Kris: or like
[23:35:13] @MajorBowman: can you give me an example of what it would be used for just so i have a better understanding
[23:36:00] +Kris: just to split up the pokemon that are DUU by usage so people can have a better idea of whats common while building
[23:36:27] @MajorBowman: oh so if they're building a team and duu is the selected tier only the duu by usage mons show up as suggestions?
[23:36:32] +Kris: its kind of like how Untiered was added to the smogdex to separate unviable PU mons from the viable ones
[23:36:34] +Kris: yea
[23:36:40] @MajorBowman: yeah that's fine then
[23:36:46] +Kris: it'd still look like if you were building for ou
[23:36:52] +Kris: how the uu mons and stuff would show up under
[23:36:57] +Kris: but they'd be divided
[23:37:30] @MajorBowman: gotcha

### CODE REVIEW

**Comment by KrisXV** [comment]
Gen 6 stats: https://www.smogon.com/forums/threads/smogon-usage-based-tier-update-november-2016.3586573/
Gen 7 stats: https://www.smogon.com/forums/threads/usage-based-tier-update-for-jan-2019.3645743/

**Comment by Zarel** [comment]
I personally would have gone with "(DUU)" for "Doubles UU but not popular in the tier", but I mean Smogon went a different direction by introducing "Untiered" as a tier.

That might be the right keyword to use here.

**Comment by TheImmortal** [comment]
Agree. Doubles NU literally isn’t a thing. I’d go with Untiered.

**Comment by KrisXV** [comment]
Alright. What should I do about the Megas that are currently duu by technicality?

**Comment by Zarel** [comment]
`(DUU)`?

**Comment by KrisXV** [comment]
Oh, I misinterpreted something. Never mind.

**Comment by KrisXV** [comment]
bump

**Comment by Zarel** [comment]
I don't _like_ this but ok :/

**Pull request merged**
