### PR TITLE
Datacenters: Add a range

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
...you should probably make your committer/author match.

**Comment by panpawn** [comment]
I thought I already did, not sure what has changed :|

**Comment by Zarel** [comment]
Hm, I don't see anything weird in the Git log. Are you sure you're using the same name and email address everywhere?

**Comment by panpawn** [comment]
Well, I recently added my actual name to my GitHub profile, could that have anything to do with it?

**Comment by Zarel** [comment]
Maybe? Make sure it matches your name in your Git config.

**Pull request merged**
