### PR TITLE
Friend list

### PR DESCRIPTION
**Pull request by ghost**
DO NOT ACCEPT THIS PULL REQUEST BEFORE ACCEPTING THE CLIENT ONE!
We don't want any trouble after all.

### CODE REVIEW

**Comment by ReklessZombie** [comment]
@Zarel how're things looking on this? It would be nice to have

**Comment by Zarel** [comment]
See my comment on the client commit.

**Comment by TheImmortal** [comment]
@Zarel can we close this (and the client pr) because it can't be merged anyway and Quinella's account is deleted...

**Comment by Zarel** [comment]
Well, it should be an issue. We might as well make an issue for a friend list if we're closing this.

**Pull request closed without merging**
