### PR TITLE
Partners in Crime: Fix Skill Swap

### PR DESCRIPTION
**Pull request by MacChaeger**
This fixes the new ability's `onStart` function not being called for the ally of the target/user of Skill Swap.

### CODE REVIEW

**Comment by MacChaeger** [comment]
Rip didn’t save after fixing that.

Also, 
>[11:37:47] @macch aeger: Of course now it occurs to me that this could be way simplified if setAbility had a parameter that told it not to start the abilities

**Comment by urkerab** [comment]
Just a general point: you've obviously needed to adapt code from `pokemon.js` where you have to refer to the battle object as `this.battle`, but in `moves.js` the battle is simply `this`.

**Comment by MacChaeger** [comment]
I just made everything match the way Skill Swap already did it.

**Comment by urkerab** [comment]
Fair enough; I fixed several versions of Skill Swap in PR #4221.

**Pull request merged**
