### PR TITLE
Move simulator harness to sim/tools

### PR DESCRIPTION
**Pull request by scheibo**
- move `build.js` logic back into build and remove 'full' option
- `dev-tools/simulate` logic moves into `sim/tools`
- `sim/examples-random-player-ai.ts` moved into sim/tools where its used and `sim/battle-stream-example.ts` deleted as `sim/tools` give plenty of examples of its use.

---

I still needed a place for `simulate.js` - moving it (and its documentation) to the top level seemed somewhat undesirable as it might be confused with `./pokemon-showdown simulate-battle`? moving it under `test/` is also an option, but I didn't think that was necessarily obvious either, which is why I settled on `'tools/'` (though thats really just a rebranded `dev-tools/`...)

I also don't have a better name than `'Runner'` (et al), except maybe adding a `'Battle'` prefix to be explicit (ie.  `'BattleRunner'`)? I wouldn't mind that, but I imagine its the 'runner' description you don't like, not that its too generic?  I don't like `'BattleExecutor'` because `Executor` means a pretty specific thing in my Java background, nor do I think `'Automator'` is any better. If only I could turn 'playout' or 'rollout'  (the terms used in MCTS) into an adjective...

### CODE REVIEW

**Comment by Zarel** [comment]
This pull request **introduces 1 alert** when merging 2213a96b7bc35ef4bf64dad0dcdb5e0ed59f4743 into f123adf560e6adaca22dcdb2b1a52bc1b5ce821f - [view on LGTM.com](https://lgtm.com/projects/g/Zarel/Pokemon-Showdown/rev/pr-e98abe3cf86f8bc7c17b6c59ea63f45ffa10abdf)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Zarel** [comment]
Are the examples particularly readable though?

**Comment by Zarel** [comment]
(It doesn't seem particularly readable to me but I'm also running on a lot of sleep-dep...)

**Comment by scheibo** [comment]
> Are the examples particularly readable though?

I've added it back, but `sim/examples/battle-stream-example.ts` is effectively `Runner#runGame` from `sim/tools/runner.ts`. `battle-stream-example.ts` also looks simple because it hides all the actual logic in `sim/tools/random-player-ai.ts`, which is signficantly more involved than the original `RandomPlayerAI` which was pulled out the of `battle-stream-example.ts` because it now actually works.

**Comment by Zarel** [comment]
This pull request **introduces 1 alert** when merging 1217bcfa149810442c8f39affefddfae941dc98b into f123adf560e6adaca22dcdb2b1a52bc1b5ce821f - [view on LGTM.com](https://lgtm.com/projects/g/Zarel/Pokemon-Showdown/rev/pr-6d6ff59fc8adfc9ecf23df0da8f4c550e4040c8a)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Zarel** [comment]
This pull request **introduces 1 alert** when merging 0d404b8f80a692a3893eb5dfcb40c3aa5fe49185 into f123adf560e6adaca22dcdb2b1a52bc1b5ce821f - [view on LGTM.com](https://lgtm.com/projects/g/Zarel/Pokemon-Showdown/rev/pr-757d5e7f5435e9499a73d9883eb4246605a70c82)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
