### PR TITLE
Gen 2 Random Battle: Fix Move Rejection Phase

### PR DESCRIPTION
**Pull request by ascriptmaster**
hasMove was not tracking moves properly, instead keeping all moves ever
added in the object even if they were rejected. Also, there was a line of
code that caused all moves to be flagged as rejected.

### CODE REVIEW

**Comment by Zarel** [comment]
`hasMove` is reset in line 969, which is where we loop back up to after a move has been rejected. In theory, this change does nothing.

**Comment by ascriptmaster** [comment]
Line 1015 was rejecting absolutely every move, and I think that was a lot of the problem. But you do have a good point about the other part.

**Comment by Zarel** [comment]
Let's try not to cargo-cult program too much. Do we know what the problem is and why these changes fix them? _Do_ these changes fix them?

**Comment by ascriptmaster** [comment]
Problem number 1: This code on line 1015:

    if (hasMove[moveid]) rejected = true;

This line should be true for every move in a Pokemon's moveset (bar Hidden Power), so it instantly rejects every non-Hidden-Power move, and thus the last four moves to get picked ever are usually the ones that go on the moveset, regardless of synergy between them. This is the most important problem.

Problem number 2: Only moves being added in that cycle are being placed in the `hasMove` object, meaning that if Rest was placed in the previous cycle and Sleep Talk in the next, Sleep Talk can't see Rest and thus gets rejected. The rest of the code queries the moves into `hasMove` properly (it now uses the randbats methods of doing that)

**Comment by Zarel** [comment]
Oh, I understand now. How is this implemented in regular randbat?

**Comment by ascriptmaster** [comment]
Regular randbats loops through all the current moves and puts them in `hasMove` (with Hidden Power filling in `hasMove['hiddenpower']` instead of their respective typed variants). Then it adds moves from its random battle movepool, skipping over Hidden Power if it's already on the moveset, and adds them to `hasMove` as well. It then goes through the rejection phase where it rejects moves under certain conditions, and then loops back around if a move was rejected.

**Comment by Zarel** [comment]
Okay, good, now this matches the usual randbat algorithm.

**Pull request merged**
