### PR TITLE
/details: gen information

### PR DESCRIPTION
**Pull request by SolarisFox**
With more and more people playing older gen formats I've seen a few people request this lately.
Gen information for Pokemon, moves, and items

### CODE REVIEW

**Comment by Slayer95** [comment]
<code>I'm still of the opinion that gen for Pokemon is implied with dex number</code>

Disagreed. I, for one, cannot tell at a glance which Pokémon are from DPP, and which from BW just from the number.

**Comment by SolarisFox** [comment]
Do you need to be able to tell at a glance? I don't personally play older meta format so I don't know how much of an issue it is for people trying to teambuild for it.

**Comment by Zarel** [comment]
I think it's fine to add gen in addition to the number.

**Comment by SolarisFox** [comment]
Alright sense I seem to be in the minority updated so that it returns gen information for Pokemon, moves, and items.

**Pull request merged**
