### PR TITLE
Escape é in /forums command

### PR DESCRIPTION
**Pull request by Bryan-0**

### CODE REVIEW

**Comment by acz13** [comment]
Why exactly? I like the acute better, it's correct. No need to leave it out.

**Comment by Bryan-0** [comment]
I like the acute too, but for now Zarel don't want it on the source files.

**Comment by Bryan-0** [comment]
I was forgetting about, what Zarel told me. (About the title)

**Comment by Slayer95** [comment]
Not the title, the <i>commit message</i>.

**Comment by Bryan-0** [comment]
Ohh, damn I'm a bad reader. Lol

**Comment by Zarel** [comment]
Well, we don't really have rules for PR titles, but it might as well be both.

**Comment by Zarel** [comment]
Anyway, fixing a commit message is just `git commit --amend`

**Comment by Zarel** [comment]
Anyway, you can use `&eacute;` or `\u00e9` here.

**Pull request merged**
