### PR TITLE
Markshared: Require a reason

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by HoeenCoder** [comment]
Actually, now that you mention it, i have one of these open already #4394

**Comment by panpawn** [comment]
... I completely forgot about that, how embarrassing

**Comment by Zarel** [comment]
The real question is still whether or not we want it. I like this implementation more, and the bump was useful to me.

**Comment by Zarel** [comment]
I think yes, we should require the reason, but we should also be clear that "reason" here is just a description of who owns the shared IP (school, etc)

**Comment by panpawn** [comment]
Updated

**Pull request merged**
