### PR TITLE
2v2 doubles: Ban Final Gambit

### PR DESCRIPTION
**Pull request by TheMezStrikes**

### CODE REVIEW

**Comment by TheMezStrikes** [comment]
https://www.smogon.com/forums/threads/2v2-doubles-om-of-the-month.3606989/post-7721063

**Comment by KrisXV** [comment]
I was asked by Rumplestiltskin to not do this

**Comment by KrisXV** [comment]
ok

**Comment by TheMezStrikes** [comment]
There was little to no controversy when it comes to the Final Gambit ban, and I was informed those discussions only concern the Z Move part of the bans

**Comment by TheImmortal** [comment]
I was asked by motogp to do this.

**Pull request merged**
