### PR TITLE
Gen 1 Randbats: Minor moveset updates

### PR DESCRIPTION
**Pull request by xCrystal**
Reverts #3592 (not a bug), and also I took the opportunity to tweak Beedrill's moveset.

### CODE REVIEW

**Comment by Zarel** [comment]
Should comment it.

**Comment by xCrystal** [comment]
This is the case for almost half the movesets though, and even more so in gen 2 with the last update. The only reason the Exeggcute one in particlar went noticed is because I recently updated it to fix an incompatible move. Maybe I should make an introductory comment at the top of the page that repeated moves are not a bug?

**Comment by Zarel** [comment]
Oh, okay.

**Comment by Zarel** [comment]
That's fine, then.

**Pull request merged**
