### PR TITLE
Random Battle: Add possibility for Fly-Z or Bounce-Z

### PR DESCRIPTION
**Pull request by ascriptmaster**
This involves adding Fly to some Flying Pokemon without a good Flying
STAB. (This also makes sure Fly is not their only STAB.)

### CODE REVIEW

**Comment by ascriptmaster** [comment]
```
[22:37] %Ascriptmaster: .usage salamence items
[22:37] *TIBot: Flyinium Z 56.936% | Leftovers 7.419% | Life Orb 7.091% | Choice Scarf 7.011% | Lum Berry 5.359% | Dragonium Z 3.904% | Focus Sash 2.838% | Firium Z 1.060% | Assault Vest 1.007% | Choice Specs 0.881% | Choice Band 0.848% | Sitrus Berry 0.654% | Other 4.993%
[23:30] %Ascriptmaster: .usage gyarados items
[23:30] *TIBot: Flyinium Z 49.732% | Leftovers 23.478% | Lum Berry 5.767% | Waterium Z 3.964% | Life Orb 3.312% | Focus Sash 2.284% | Choice Scarf 1.564% | Rocky Helmet 1.560% | Sitrus Berry 1.207% | Normalium Z 1.189% | Assault Vest 0.620% | Wacan Berry 0.487% | Other 4.836%
[23:31] %Ascriptmaster: .usage dragonite items
[23:31] *TIBot: Weakness Policy 31.288% | Lum Berry 18.326% | Leftovers 11.540% | Flyinium Z 10.976% | Choice Band 8.043% | Electrium Z 4.548% | Life Orb 2.506% | Dragonium Z 2.264% | Assault Vest 1.894% | Sitrus Berry 1.206% | Firium Z 0.984% | Focus Sash 0.715% | Choice Scarf 0.689% | Rocky ...
[23:31] %Ascriptmaster: .usage landorust items
[23:31] *TIBot: Rocky Helmet 48.200% | Choice Scarf 15.787% | Rockium Z 9.717% | Leftovers 8.074% | Flyinium Z 7.921% | Life Orb 2.406% | Yache Berry 1.503% | Earth Plate 1.418% | Other 4.974%
```

Although Landorus-T has a very low usage for Flyinium-Z, the wallbreaker set that uses it is considered one of the best in OU. Might not be the best because randbats move scrambling? IMO, the only one that is questionable is Dragonite, because of Weakness Policy and Lum Berry being so useful for it.

Alternatively, Fly should also only be used with setup sets?

**Comment by TheImmortal** [comment]
I'd definitely give it to Lando because it often has bad sets due to only one STAB in the movepool. Non-Mega Salamence is probably fine. Dragonite is questionable.

Yes, allow it with setup only.

**Comment by ascriptmaster** [comment]
I removed Fly from Dragonite. Non-Mega Mence/Gyara definitely appreciate the Z-Fly and Z-Bounce respectively.

Should I enforce Bounce with setup the same way I'm enforcing Fly with setup? Or does Gyara need it on more sets?

**Comment by ascriptmaster** [comment]
still waiting for a response

**Comment by TheImmortal** [comment]
My bad. Hmm, no, don't reject it. But, only give it Flyinium **if** it has setup.

**Pull request merged**
