### PR TITLE
Random Doubles Updates

### PR DESCRIPTION
**Pull request by ascriptmaster**
- Fix Guts Dynamic Punch Machamp.
- Mega Heracross with Protect doesn't need Guts in its base form.
- Give Kingler Liquidation for its Sheer Force.

### CODE REVIEW

**Comment by TheImmortal** [comment]
I'd argue Guts Heracross is useful. Also no need for the gen 6 change because the gen 6 file doesn't have any doubles stuff anyway.

**Comment by ascriptmaster** [comment]
The Guts check line doesn't prevent it from being Guts, it just prevents it from ALWAYS being Guts. Based on its ability ratings this will give it a 2/3 chance of being Moxie and 1/3 Guts, as per usual. I guess adding the exception isn't particularly necessary though? It just seemed silly to me

**Comment by TheImmortal** [comment]
Can we just change it to ``hasMove['protect']  && !isDoubles``

**Comment by ascriptmaster** [comment]
You know what? Yes that's a good idea

**Pull request merged**
