### PR TITLE
Randbats: update Poliwrath

### PR DESCRIPTION
**Pull request by MacChaeger**
85 SpA Poliwrath Ice Beam vs. 85 HP / 85 SpD Celebi: 90-106 (32 - 37.7%) -- 0.1% chance to 3HKO after Leftovers recovery
85 Atk Poliwrath Ice Punch vs. 85 HP / 85 Def Celebi: 94-112 (33.4 - 39.8%) -- 22.6% chance to 3HKO after Leftovers recovery

### CODE REVIEW

**Comment by TheImmortal** [comment]
I mean if you're implying that Ice Punch is better in general, then you should remove Ice Beam. I guess the question is, if you take all the Ice weak Pokemon that resist STABs into account, which does more damage on average?

**Comment by MacChaeger** [comment]
I left Ice Beam on for the Choice Specs set.

**Comment by TheImmortal** [comment]
Thoughts @ascriptmaster

**Comment by ascriptmaster** [comment]
What Choice Specs set? It only gets Specs if it has Ice Beam/Focus Blast/Scald/Hydro Pump, which is very uncommon because it's double STAB.

**Comment by TheImmortal** [comment]
I guess this is good since it can hit both sides now.

**Pull request merged**
