### PR TITLE
Replace lol with rof

### PR DESCRIPTION
**Pull request by RofNaniMan**
rof

### CODE REVIEW

**Comment by TheImmortal** [comment]
rof

**Comment by xfix** [comment]
rof

**Comment by NaniMan** [comment]
rof

**Comment by DragonBean** [comment]
rof

**Comment by kotarou3** [comment]
rof

**Comment by Rhythms88** [comment]
rof

**Comment by Slayer95** [comment]
replace lol with hots imo

**Comment by MJB47** [comment]
need more dota in this pr

**Comment by Morfent** [comment]
rof

**Comment by Zarel** [comment]
no fun allowed >:(

**Pull request closed without merging**
