### PR TITLE
Add Morfent and SolarisFox's names to credits

### PR DESCRIPTION
**Pull request by Morfent**

### CODE REVIEW

**Comment by SolarisFox** [comment]
Oh I'm in there too? I didn't even know. Could you add my name here as well, or should I do it as a separate pullreq?

**Comment by Morfent** [comment]
I can do it in the same pullreq. Do you want to be on the credits though?

**Comment by SolarisFox** [comment]
Yes, I'm honored to even be considered relevant enough. My name is Jacob Zimmer.

Also the names seem to be in alphabetical order, so your name is currently in the wrong position.

**Comment by Morfent** [comment]
Added and fixed.

**Pull request merged**
