### PR TITLE
Fix canHTML() for certain cases

### PR DESCRIPTION
**Pull request by kotarou3**

### CODE REVIEW

**Comment by Zarel** [comment]
> Only require one of width and height on images

This defeats the purpose of the requirement, which is to embed the exact dimensions of the image before the image is downloaded.

The other changes are good, though.

**Comment by kotarou3** [comment]
What would be the point of having the exact dimensions, when one can be inferred from the other as soon as the image headers are downloaded?

**Comment by xfix** [comment]
@kotarou3: Being able to determine the size of htmlbox before making any request.

**Comment by Zarel** [comment]
> What would be the point of having the exact dimensions, when one can be inferred from the other as soon as the image headers are downloaded?

Because we need to calculate the size of the HTML box before the image headers are downloaded, for scrolling purposes.

**Comment by kotarou3** [comment]
Isn't that automatic by the browser?

**Comment by Zarel** [comment]
Turns out, no, it's not.

Specifically, it's automatic on Firefox but not Chrome.

**Comment by kotarou3** [comment]
Wouldn't it then be better to just require a height instead?

**Comment by Zarel** [comment]
Width can cause inline images to push text to wrap, causing height changes. If you want to write a complicated parser to detect block-level images and allow height-only in that case, feel free, but in the meantime can you just drop that change so I can merge the other two?

**Comment by kotarou3** [comment]
The problem is the huge regex for detecting width/height in styles will double in size...

Also, is it worth detecting obsolete tags and attributes (looking at `<font>`) and blocking those?

**Comment by Zarel** [comment]
Ugh, just require width and height like a normal person. :| It's not that much more work.

**Comment by ascriptmaster** [comment]
@kotarou3 how is the progress on this?

**Comment by Zarel** [comment]
The only relevant commit was re-fixed because @kotarou3 was taking too long to remove the other changes. :|

**Pull request closed without merging**
