### PR TITLE
Fix mega pokemon being able to use Z-Moves

### PR DESCRIPTION
**Pull request by Spindlyskit**

### CODE REVIEW

**Comment by Ridaz** [comment]
Why though? Custom Games and Hackmons are a thing

**Comment by Zarel** [comment]
Is this a mechanics issue? Is Rayquaza able to do it?

**Comment by Spindlyskit** [comment]
because hackmons is everything possible on cart and this doesn't work

**Comment by Zarel** [comment]
Do you have a YouTube video of it not working on cart?

**Comment by Spindlyskit** [comment]
no I don't but it's on the known mechanical bugs issue

**Comment by Zarel** [comment]
You missed the word "Transformed". As in with the move Transform or the ability Imposter.

**Comment by Zarel** [comment]
@Marty-D, could you advise on mechanics?

**Comment by Spindlyskit** [comment]
welp guess I should learn to read :p

**Comment by Marty-D** [comment]
This reminded me to check Transforming into Primals for the same behaviour, will fix in a bit.

**Pull request closed without merging**
