### PR TITLE
Random Battle: Enforce Bug Buzz on Bug/Flying Pokemon except Vivillon

### PR DESCRIPTION
**Pull request by ascriptmaster**
@TheImmortal

### CODE REVIEW

**Comment by Zarel** [comment]
Isn't Hurricane also better on CompoundEyes Butterfree?

**Comment by ascriptmaster** [comment]
It doesn't have anything to do with this PR because it checks for Hurricane instead of a species hardcode. Also more importantly:
Butterfree cannot learn Hurricane

**Comment by ascriptmaster** [comment]
@TheImmortal still waiting on your input

**Comment by TheImmortal** [comment]
I'm thinking. This works as intended but I'm wondering if it should be expanded to more Bug types.

**Comment by ascriptmaster** [comment]
In terms of dual-typed Bug-type Pokemon that aren't covered by this current check:

- Beedrill can have either one of its STABs.
- Parasect can have either STAB.
- Same with Venomoth.
- Scyther both are fine.
- Mega Pinsir vastly prefers its Normal moves because of Aerialate.
- Ledian only has U-Turn as its STAB anyways.
- Ariados prefers Megahorn.
- Forretress only has Gyro Ball as its STAB.
- Scizor and its Mega both prefer Bullet Punch.
- Heracross likes both STABs.
- Dustox is basically a worse Venomoth. Either.
- Ninjask only has X-Scissor as STAB.
- Shedinja is weird. IDK.
- Armaldo prefers Stone Edge a bit more.
- Wormadam-Grassy is fine with either Giga Drain or Signal Beam.
- Wormadam-Sandy only has EQ as STAB.
- Wormadam-Trash only has 4 moves.
- Vespiquen only has Attack Order as STAB.
- Leavanny is fine with either STAB.
- Scolipede likes Megahorn.
- Crustle likes its Rock STAB.
- Escavalier likes Megahorn.
- Galvantula loves its Electric STAB, which is enforced.
- Durant is fine with either.
- Volcarona loves its Fire STAB, which is enforced.
- Genesect is fine with either.

I specifically chose Special Bug/Flying because they tend to have Air Cutter (sucks) and Air Slash as their Flying STAB, and Bug Buzz is definitely better for the damage. The exception, of course, is Vivillon, because Hurricane is nice.

**Comment by ascriptmaster** [comment]
Based on the above I can't really think of any hard and fast rules for anything else regarding Bug STAB... do you have any suggestions?

**Comment by ascriptmaster** [comment]
bumpity @TheImmortal

**Comment by TheImmortal** [comment]
I came up with this:

```
(hasType['Bug'] && !hasMove['batonpass'] && (movePool.includes('megahorn') || movePool.includes('pinmissile') || (hasType['Flying'] && !hasMove['hurricane'] && movePool.includes('bugbuzz'))))
```

I believe it targets the important Pokemon like Heracross, Escavalier and Scolipede, without touching the weaker stuff like X-Scissor.

**Comment by ascriptmaster** [comment]
The only possible edge case that might not be desirable would be BP/QD/Roost/Air Slash Masquerain. What are you opinions on this?

I understand the Baton Pass thing is for Scolipede, yes

**Comment by ascriptmaster** [comment]
Changed the clause based on my last comment.

**Comment by TheImmortal** [comment]
That set is fine in my opinion. It has Air Slash to attack with but it's main goal is to pass boosts and Roost helps it get as many boosts as possible.

**Pull request closed without merging**
