### PR TITLE
Update bot rank permissions to reflect changes

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by panpawn** [comment]
Not done, going to update the help commands in this PR that the bot is now able to use.

**Comment by panpawn** [comment]
How does this look?

**Comment by Zarel** [comment]
On second thought, let's remove * from all the informational commands.

It's not like we _want_ bots to be using them, and any bot writer should know anyway.

**Comment by Zarel** [comment]
Since we've already said everywhere that bots have @ permissions.

**Comment by panpawn** [comment]
Okay, I'll do this when I have time

**Pull request merged**
