### PR TITLE
Update info.js

### PR DESCRIPTION
**Pull request by rambo199**
created the heading bold in /roomhelp

### CODE REVIEW

**Comment by Lord-Haji** [comment]
lol
good joke PR

**Comment by kotarou3** [comment]
@Lord-Haji 
When you comment, can you actually say something constructive?
Almost all your comments recently have been completely useless and unneeded (like this one).

**Comment by rambo199** [comment]
Lol correct

**Comment by Zarel** [comment]
@Lord-Haji, this is your last warning. You will be blocked the next time you say something unconstructive.

**Pull request closed without merging**
