### PR TITLE
Dexsearch: add "weak" parameter

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by SkiAmplitude** [comment]
i removed the whitespaces also daily "remove travisbuddy" message

**Comment by Zarel** [comment]
daily "maybe you should actually test your code before pushing if you don't want someone to tell you you did it wrong" message

**Comment by Zarel** [comment]
Like, if it weren't TravisBuddy, it'd be me telling you to test your code. :|

**Comment by KrisXV** [comment]
daily "i do test my code on separate branches and then redo them on a new branch" message

**Comment by AustinXII** [comment]
Thats a .. weird practice. You do only have your self to blame if you prefer testing on a “unfinished branch” over the actual branch you want. If you’re only going to do it once why not wait until you’re actually finished?

**Comment by Zarel** [comment]
Why would you redo them on a new branch? Git branches are just named commits. Instead of redoing them on a new branch, why not just... rename the old branch? Or make a copy of the old branch, and give it a new name?

Not to mention: If you redo them on a new branch, why not test them again? It doesn't matter what you do, just test right before pushing.

**Pull request merged**
