### PR TITLE
[Minor] Fix typo in short description of Purify

### PR DESCRIPTION
**Pull request by Ghoulean**

### CODE REVIEW

**Comment by Zarel** [comment]
Most likely, this is written like this because the space doesn't fit. @Marty-D?

**Comment by sparkychildcharlie** [comment]
This was already rejected in https://github.com/Zarel/Pokemon-Showdown/pull/3196, having to do with size limitations.

**Comment by Marty-D** [comment]
If a third PR happens for this I guess I'll have to seriously consider adding a comment to that line!

**Comment by Ghoulean** [comment]
"Cures target's status; heals user 1/2 max HP if so." → "Cures target's status; heals user 50% HP if so."

Consistent with Roost wording.

**Pull request closed without merging**
