### PR TITLE
Fix code style of Gen-NEXT Genesect Pokedex.

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by Zarel** [comment]
Um, please revert this.

This is the exact same code style as `data/pokedex.js`

`pokedex.js` shouldn't be subject to style checks in the first place.

**Comment by TheImmortal** [comment]
What's wrong with this style, it's far more readable :|

**Comment by ascriptmaster** [comment]
Considering Gen4 Rotom is written in the exact same way, I don't see why NEXT Genesect can't be written like this.

**Comment by Zarel** [comment]
It's not supposed to be readable; it's supposed to be dense. -_-

**Comment by ascriptmaster** [comment]
If this one needs to be dense, then we need to densify the `pokedex.js` in gen 4 and gen 5 mod folders as well, then. If those are allowed then why isn't this?

**Comment by Zarel** [comment]
Those shouldn't be allowed, either; the engine was never designed to support `inherit` in `pokedex.js`.

I guess if they've been working fine without bugs it's not a huge deal, but it definitely makes me very uncomfortable.

**Comment by Marty-D** [comment]
[But you started the trend](https://github.com/Zarel/Pokemon-Showdown/commit/4c5d44462f095efbb5a1636459b25c7ae93dd651)!

**Comment by Zarel** [comment]
I probably forgot about it when I wrote that.

**Pull request merged**
