### PR TITLE
Sorting roomauth correctly

### PR DESCRIPTION
**Pull request by sparkychild**
Sort alphabetically

### CODE REVIEW

**Comment by kotarou3** [comment]
Can you reword your commit to remove the extra description unrelated to the commit itself (do with `git commit --amend`)

**Comment by Zarel** [comment]
Is this necessary?

**Comment by Zarel** [comment]
Do we really need to compare IDs?

**Comment by Zarel** [comment]
It may be better to sort before testing for onlineness.

**Comment by Zarel** [comment]
Squash?

**Comment by Zarel** [comment]
Well, `fixup`, to be specific

**Comment by sparkychild** [comment]
Done.  I did the bolding after the sorting.

**Pull request merged**
