### PR TITLE
Database changes for Items & Old-gen teambuilding

### PR DESCRIPTION
**Pull request by Enigami**
Added viability for items.
Added Hidden Power IVs for Gen 1/2.
Added type category (Physical/Special) for Gen 1/2/3

### CODE REVIEW

**Comment by Slayer95** [comment]
What does "conditional" viability mean?

**Comment by Enigami** [comment]
"Conditional" is part of some smart code on the Client. If it detects 'isViable' is a boolean or absent, it simply pushes the item as Usable Item or just Item. If its not (such as a string like "Conditional"), it goes into more detail to see whether to put it into Usable Item or not.

These items include super-effective damage reducing berries (only those that actually would work for the Pokemon are usable), Mega Stones (only usable if they mega-evolve the Pokemon in question), and Pokemon-specific boosting items.

**Comment by TheImmortal** [comment]
First of all, there has been tons of complaints about the "usable moves" section as it determined generally rather than Pokemon specific. This is as bad if not worse. If we're adding a section for viable/usable items, then it should be the best of the best items only. You list pretty bad items as viable, such as Black Belt. If we're adding said section, it should display items such as (most) Mega Stones, Life Orb, Leftovers, Expert Belt, Assault Vest, Air Balloon, etc. And then you should check if these items are actually viable, like if it is not weak to Ground then hide Balloon, if it has a Status move then hide Vest, etc.

As it is I am totally against this.

**Comment by Enigami** [comment]
Well, your problem seems to just be which items are tagged as 'viable'. It would take just a second to change them, so what changes would you want?

**Comment by TheImmortal** [comment]
Practically everything that I didn't list.

And almost all of the stuff that are not Mega Stones should be "Conditional". Assault Vest isn't viable on something with a Status moves. Air Balloon isn't viable on something that isn't weak to Ground. Choice Band/Specs isn't viable on something without an attack of that type. I could go on and on.

**Comment by Enigami** [comment]
Uh, items are the first thing after the Pokemon listed. The idea with 'Usable Items' is to reduce clutter, i.e. instead of sifting through a gigantic spread of items you've got usable items right at the top of the list. I really don't see how that would be anything but a good thing. Some of the things like Air Balloon is a fair point, but Assault Vest/Choice items etc. is getting really nitpicky.

**Comment by TheImmortal** [comment]
Fair point. In which case I don't agree with accepting this change at all.

>I really don't see how that would be anything but a good thing.

Because you're saying a certain item is useful, or worse VIABLE, on a certain Pokemon. Choice items are not viable on majority of Pokemon. Do you want me to list them all?

**Comment by Enigami** [comment]
Making some revisions, closing temporarily.

**Comment by Zarel** [comment]
This is for Zarel/Pokemon-Showdown-Client#555

**Comment by Zarel** [comment]
Fixed by a number of recent client commits, such as 4ffd1034e0c1ab5

**Pull request closed without merging**
