### PR TITLE
Run Caja sanitizer on canHTML

### PR DESCRIPTION
**Pull request by Slayer95**
Pass HTML input through a sanitizer

This prevents some user input from deforming the site layout and/or
phishing with scripted buttons.
It also fixes some edge cases of our HTML validator, and obsoletes part of it.

### CODE REVIEW

**Comment by Zarel** [comment]
We already run Caja clientside. Why do we need to run it here?

**Comment by Slayer95** [comment]
Ok, I'll try my best to list all the reasons here

- There is some HTML content that the server may want to send to the user via scripts, but its users shouldn't be trusted to send less they may be confused with official messages.

E.g. most instances of ``<button name="send">``, and ``<button name="receive">``.
The server currently has some legit uses of the former, such as buttons that PM bots, but also some disagreeable uses of it. I cannot see any valid possible uses for the second action type, and it's often used in private rooms to simulate a well-known user or staff-member saying something there.

- Client usage of selector searches both with ``jQuery`` and ``CSS`` is such that it may match some elements that are in the chat log simply due to their ``class``.
This PR bans most of the critical classes such as ``ps-room`` due their high impact.

- There is some HTML content that, after some dubious validation at ``canHTML``, we wrap in more HTML and send it in various plugins, such as ``poll.js``. Despite that half of the function currently intends to check for mismatched tags, it fails to do so in some cases, and will likely still fail unless the HTML code it checks is standardized.
This allows users to break out of the intended DOM structure and possibly trick users.

- The ``canHTML`` method is currently coded to handle HTML that follows a very specific style. It will fail, for example, to understand that ```` (perfectly valid HTML code) has specified both its width and height.
HTML code styled differently will therefore work around it. Calling ``caja`` sanitizer before doing our own checks will allow us to write simpler code on standardized input with better results.
While ``caja`` does its job, it could also in the future find ``width`` and ``height`` data defined in ``style`` attributes and make them attributes.

**Comment by Zarel** [comment]
I would probably prefer my manual pre-sanitizing to having a big ugly library as a dependency...

**Comment by Slayer95** [comment]
Certainly. If only HTML parsing would be so easy to handcraft reliable code for it...

**Comment by Zarel** [comment]
This pullreq adds _lots_ of lines and lots of files, probably more code than it would take to just fix `canHTML` to fit your needs, even excluding Caja's own code.

**Comment by Slayer95** [comment]
It's possible. For the things described we only need a parser and a stringifier. I guess that would be two dependencies...

But isn't it ridiculous that [https://play.pokemonshowdown.com/smogondoubles](some of our official rooms) send ``body`` tags in their room intros? Those would also be cleared up when editting them, and staff will finally know why their code doesn't work.

This PR makes extensive use of the Caja API, and it can use it even more. For example, we can use the URI Rewriter to shorten Smogon thread links (this is actually a tip I just read in the Dubs room intro).

**Comment by Zarel** [comment]
I've been aware for a while now that we have very different opinions about external dependencies.........

**Comment by scheibo** [comment]
We should probably have done this...

**Pull request closed without merging**
