### PR TITLE
Update various help commands to include player rank

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by panpawn** [comment]
apparently, there's other commands that should have the player rank documented in their help command - I'm going to add them to this PR soon

**Comment by JetOU777** [comment]
**Modchat**: update help command with player rank
**roompromote**: update help command with player rank
Add player rank in the **Informational Commands** in **/help** command
Add player rank in **/help calc / help analysis /help learn /help intro /help faq /help groups /help data**.
in the ![command] with + % @ * # & ~

**Comment by panpawn** [comment]
Thanks!

**Comment by AustinXII** [comment]
Speaking of ``/help calc``, doesn't "show everyone the link to the damage calculator" sound better than "show everyone a link to a damage calculator

**Comment by panpawn** [comment]
I mean, there are _other_ damage calculators out there... "the damage calculator" implies that that's the only one, doesn't it?

**Comment by Zarel** [comment]
"The damage calculator" is fine; it's the PS damage calculator and they're on PS. "A damage calculator" makes it sound unaffiliated with us.

**Comment by AustinXII** [comment]
^ those were my exact thoughts

**Comment by Zarel** [comment]
Outdated. If there's still something that should be done here, please tell me.

**Pull request closed without merging**
