### PR TITLE
Allow for viewing only punishment-related actions in the modlog

### PR DESCRIPTION
**Pull request by scheibo**
**Context:** [An option to split modlog into punishments and non punishments](https://www.smogon.com/forums/threads/an-option-to-split-modlog-into-punishments-and-non-punishments.3651100/) (3rd most popular)

- I'm not wedded to the idea of a `'/punishlog'` command vs. implementing some sort of flag (`'scope=punishments'`?) the way `maxLines` works, but this was the easiest approach and its relatively simple to change
- I may be missing or including actions which are or are not 'punishment related'. Something like `'NOTE'` is not necessarily 'punishment-related', but it often provides additional context for punishments so I figured it was useful to include. Ditto some others I've added. On the main server we may wish to add to `PUNISHMENTS` with actions from private code, potentially meaning the list should be defined in `config/` somewhere instead of here.
- Taking a step back - would it instead make sense to have the non-punishment actions show up in different log files entirely? The approach I've taken here relies on the existing design, but I'm not positive trivia actions belong in the same place as global bans to begin with, even if both require auth.

### CODE REVIEW

**Comment by scheibo** [comment]
@panpawn has brought up the fact that this depends on modlogs being uniformly formatted, @Zarel can you confirm that you've run @sparkychildcharlie's [script](https://pastebin.com/0UfyDmVu) from https://github.com/Zarel/Pokemon-Showdown/pull/3972?

**Comment by sparkychildcharlie** [comment]
pretty sure it hasnt been run

**Comment by Zarel** [comment]
I'm worried about how it'll work while the server is actively running...

**Comment by AustinXII** [comment]
The script is missing battleban btw. Also perhaps try it on smogtours first?

**Comment by sparkychildcharlie** [comment]
Im pretty sure at the time i wrote it battleban didnt exist on the server... sooo it wouldnt been in sentence form

**Comment by AustinXII** [comment]
@sparkychildcharlie yeah you did, I was just pointing it out incase zarel were to run it right now since no one has mentioned it to him

**Comment by panpawn** [comment]
Shouldn't matter, since the script's purpose is to only convert entries before the standard formatting was changed, and it only targets ones that need to be converted

**Comment by scheibo** [comment]
@Zarel - are you OK with this approach? I think this change can still land without the script having been run, it just will be more accurate/effective once that is run as well.

**Comment by Zarel** [comment]
It's fine I guess.

**Pull request merged**
