### PR TITLE
Improve room punishments

### PR DESCRIPTION
**Pull request by Slayer95**
1) Only display popups to users who are currently in the room. This prevents abuse.
2) Allow warns to be used in private rooms with own authorities.
3) Display a button to list room staff in the roomban popup.

Requires https://github.com/Zarel/Pokemon-Showdown-Client/pull/419 for (3)

### CODE REVIEW

**Comment by Zarel** [comment]
Poke this is a few days.

**Comment by Slayer95** [comment]
Client seems to be updated now.

Also, added
> - Hour-mutes now display "1 hour" rather than "60 minutes".

**Comment by Zarel** [comment]
I don't know if there's a restart since the last client update, so I can't guarantee that everyone's on the new client code.

**Comment by AustinXII** [comment]
I think it would also be a good idea to add something that will break the link of an alt when warned. this helps if someone post a link on an alt then switches over to another account but the thing they posted isn't really mute or ban worthy. something similar to how bans work with this.add('|unlink|' + toId(alts[i]));

**Pull request merged**
