### PR TITLE
add weakcoasta to randbats

### PR DESCRIPTION
**Pull request by SolarisFox**
Add the "weakcoasta" set to randbats. These abilities give Carracoasta the potential to tank a super effective hit and be a dangerous +4 sweeper in just one turn.

### CODE REVIEW

**Comment by SolarisFox** [comment]
I don't really know much about this file, so if @ascriptmaster could double check I did this right I would appreciate it.

**Comment by ascriptmaster** [comment]
The code itself is solid. As for whether or not it should actually be used, ask @TheImmortal

**Comment by CrestfallPS** [comment]
Not TI so I can't decide, but if there's a way to implement weakcosta always getting ajet then I'd think it's a welcome change. A big issue of costa is generally even at +2 there are things (at neutral!) that can revenge.

**Comment by ascriptmaster** [comment]
`if ((ability === 'Solid Rock' && ability === 'Sturdy') && counter['priority'])`

**Comment by TheImmortal** [comment]
Well I'm not sold on this change completely. Sturdy requires team support (which would be possible to check after #1822) in the form of hazard removal. For now, I'd accept just Solid Rock.

**Comment by TheImmortal** [comment]
I'd also be more comfortable with checking priority to lower the rate of Weakness Policy. So, ascripmaster's change minus Sturdy.

**Comment by SolarisFox** [comment]
In that case should we remove the coin flip to decide on the item sense it's dependent on the priority move anyways?

**Comment by ascriptmaster** [comment]
yes basically

**Comment by SolarisFox** [comment]
Alright updated.

**Pull request merged**
