### PR TITLE
Remove user from a tournament when room banned

### PR DESCRIPTION
**Pull request by Nineage**
Not sure if this is the most efficient check, I couldn't find another check similar to this to use as reference.

### CODE REVIEW

**Comment by Zarel** [comment]
idk who handles tours these days

**Comment by kotarou3** [comment]
This is not the correct way to do this.

Firstly, use `Tournaments.get()`.
Next, don't access generator properties directly - there's no guarantee they'll be there or be what you think they are. Use `generator.getUsers()` if you need a list of users.
Putting this in `commands.js` also doesn't sound good to me.

**Comment by Nineage** [comment]
Where else would I put this? I could put a check somewhere in tournaments code to see if the user is banned from the room but honestly removing the user from the tournament as the ban happens seems like the best way.

**Comment by Zarel** [comment]
I've been meaning to abstract a lot of the tournament and battle-room code into a generic "game" system.

Either way, this should be handled in the roomban handler in `rooms.js`. Possibly just calling a function in tours, so the actual code would mostly be in `tournaments/`.

**Comment by Nineage** [comment]
@kotarou3 @Zarel Made the changes suggested. 

One issue I noticed with this method is that because the roomban popup occurs before the function is called, a user is informed that they have been dq'ed from the tournament instead of getting a roomban popup. Not quite sure how to fix this except for rearranging the order in the command itself.
If the removeBannedUser function is OK, I should probably add it for global bans as well.

**Comment by Zarel** [comment]
We could suppress the popup, I suppose.

**Comment by Nineage** [comment]
@Zarel Is there a particular way you would recommend doing that? I thought about calling the generator dq function which doesn't notify the user, but it seems less safe than calling the one in Tournaments.

**Comment by Zarel** [comment]
Add a parameter to `disqualifyUser`, or overload the `reason` parameter`

**Comment by Nineage** [comment]
@Zarel done. As far as I can tell it doesn't matter what I put for the second or third parameter, so I put the safest options I could think of just in case.

**Comment by Zarel** [comment]
I'd probably be better to overload `reason`. You could make it so `reason === null` means "suppress popup". We use `null` to mean "suppress message" all over the place in PS, anyway.

**Comment by Nineage** [comment]
Thanks, it's way more efficient this way @Zarel 
Sorry this has taken so many revisions!

**Comment by Slayer95** [comment]
Just a nit: ``removeBannedUser`` is not a name indicative of what the ``Tournament`` method proper does. I suggest ``forceRemoveUser``

**Comment by Slayer95** [comment]
Blah... I'll refactor it later, I guess...

**Comment by Zarel** [comment]
Heh, I practically never get around to refactoring the things I say "I'll refactor it later" about...

**Comment by Zarel** [comment]
> Sorry this has taken so many revisions!

btw, @Nineage, don't worry, this is a completely normal number of revisions. We're perfectionists and more than anything, we're happy you're taking the time to do these fixes for us!

**Comment by kotarou3** [comment]
To add to Zarel, this is less revisions that typical of a open source project

**Pull request merged**
