### PR TITLE
Gen IV: Accuracy should be checked before Ability immunities

### PR DESCRIPTION
**Pull request by JordanLow**
Known Mechanics Bugs #2367

Gen IV, Accuracy of a move is checked before Immunities granted via Abilities such as Dry Skin and Flash Fire

### CODE REVIEW

**Comment by Zarel** [comment]
Are ability immunities actually implemented in the `Immunity` event? It was my understanding that it's done in `TryHit`.

**Comment by JordanLow** [comment]
It _is_ done in TryHit. That's why I put the TryHit event after the accuracy check if this.gen is 4.

**Comment by Zarel** [comment]
Oh, I see. Yeah, that looks like it should work. @Marty-D?

**Comment by Marty-D** [comment]
This particular mechanic also exists in Gen 3, but it's slightly different.
* Gen 3: natural immunity -> accuracy -> Ability immunity *even if natural immunity would have otherwise stopped the attack*
* Gen 4: natural immunity -> accuracy -> Ability immunity
* Gen 5-6: natural immunity -> Ability immunity -> accuracy
* Gen 7: Ability immunity -> natural immunity -> accuracy

However, it becomes less and less obvious what's going on in the current gen's scripts file as past gen exceptions are added. I think it's worth doing this in the Gen 3 & 4 mods for scripts, especially since there are a dozen other things that still need tweaking between gens. I'm also wary of changing past gens during SPL, since bugs are unlikely to be caught on the main server before they potentially ruin a tournament match.

**Comment by JordanLow** [comment]
I think that should be it. @Marty-D ?

**Comment by Marty-D** [comment]
For Gen 3, the natural immunity message is shown even if the move would miss. It's only when the Pokemon is both naturally immune and immune by Ability that it can show either the immunity message (if it missed) or the Ability activation (if it hit).

Also feel free to drop useless stuff that doesn't exist in Gens 3 and 4, like the powder or stealsBoosts checks.

**Comment by JordanLow** [comment]
I think this works

**Comment by Zarel** [comment]
Have you considered learning how to use Git and how to run `npm test`? That would save a lot of commit clutter here.

**Comment by JordanLow** [comment]
I know how to use Git, but it never crossed my mind to use `npm test`. I'll do that next time.

**Comment by JordanLow** [comment]
Well I am using the GitHub online editor to do this PR. I'll use Git for future commits.

**Comment by JordanLow** [comment]
As for the current situation, are the changes fine?

**Comment by Zarel** [comment]
I'll let Marty assess that.

**Comment by JordanLow** [comment]
@Marty-D ?

**Comment by Marty-D** [comment]
Not going to review this until SPL is over.

**Comment by Marty-D** [comment]
Did you test your latest changes? You're getting two immunity messages _and_ a failure message when you "hit" an immunity in Gen 3.

**Pull request closed without merging**
