### PR TITLE
Add randmove command

### PR DESCRIPTION
**Pull request by CheeseMuffin**
Works essentially the same way as /randpoke

### CODE REVIEW

**Comment by Zarel** [comment]
:|

**Comment by CheeseMuffin** [comment]
:|

**Comment by Zarel** [comment]
I'll leave it to @Slayer95 @sirDonovan @urkerab @asgdf to decide whether this belongs in PS.

**Comment by CheeseMuffin** [comment]
I've seen people be confused by why this doesn't exist in help that was the main reason I added it. I'm not entirely sure what uses people would have for it though but I think it would be nice to exist

**Comment by CheeseMuffin** [comment]
This also makes it so that if you do /ms and it comes up with a single result, it gives you the dt of the result instead just the name (e.g.
image
vs
image )
This would also be potentially used in Game Corner for games, and maybe other game rooms

**Comment by asgdf** [comment]
Wouldn't most game rooms use their resident bot to run such games anyway?

**Comment by CheeseMuffin** [comment]
Lady Monita currently can do .move, to get a random move, but can't do it with any parameters

**Comment by Zarel** [comment]
Seems useful enough.

**Pull request merged**
