### PR TITLE
Random Battle: Enable Stomping Tantrum Raticate

### PR DESCRIPTION
**Pull request by ascriptmaster**
It's more powerful than Flame Wheel and hits both Rock and Steel super
effectively, unlike Flame Wheel only being super effective on Steel.

### CODE REVIEW

**Comment by Zarel** [comment]
I promise I'll go back and re-review all of these after I fix the Travis failure from the TypeScript update.

**Comment by TheImmortal** [comment]
Does it double in power if Sucker Punch failed? If so, I'm sold.

**Comment by KrisXV** [comment]
Yes

**Comment by Zarel** [comment]
TI says he's sold, he can revert if he didn't actually mean that.

**Pull request merged**
