### PR TITLE
Add a new alias in formats

### PR DESCRIPTION
**Pull request by Bryan-0**

### CODE REVIEW

**Comment by TheImmortal** [comment]
Who even uses those Pokemon aliases

**Comment by Bryan-0** [comment]
mm, Well I use it, but you probably are right.  

What about the format alias?

**Comment by TheImmortal** [comment]
The format alias is fine.

**Comment by Bryan-0** [comment]
So, just the format alias?

**Comment by TheImmortal** [comment]
Yes.

**Comment by Bryan-0** [comment]
Updated. @TheImmortal

**Pull request merged**
