### PR TITLE
Added link to another chatbot implementation

### PR DESCRIPTION
**Pull request by Nixola**
I added a link to my chatbot in protocol.md. I just started commenting the code, so it isn't well documented yet, and I still have to clean some stuff up, but it can still serve as a guide or a base for anyone who wishes to create their bot, learn with an actual example how PS works, and more. Since it's written in Lua, which none of the examples yet use, I thought it could be a nice addition to the list. I plan on making battles available in the future, but I'm afraid that's a feature worth of a summer.

### CODE REVIEW

**Comment by Zarel** [comment]
Does your chat bot power anything important?

**Comment by Nixola** [comment]
It doesn't, but it's still an example and can serve as a base, in a different language than the example projects provided; I just thought it might be useful, since not everyone knows JS and/or ruby.

**Comment by Zarel** [comment]
True. My main worry is that the quality of the code can't really be vouched for...

**Comment by Zarel** [comment]
Oh, well, it's not like there are other Lua implementations.

**Pull request merged**
