### PR TITLE
Implement chatroom log search plugin

### PR DESCRIPTION
**Pull request by panpawn**
This allows staff to search a room's roomlogs for specific text.

### CODE REVIEW

**Comment by bumbadadabum** [comment]
This should be implemented into the log viewer itself.

**Comment by panpawn** [comment]
[The open source code for the log viewer](https://github.com/zarel/pokemon-showdown-client/tree/log-viewer) is highly unmaintained.  It's hard to submit changes to something that you can't really test - that's why I did it this way on the server.

**Comment by panpawn** [comment]
I could also make this link to the actual roomlog, that might make this slightly more useful (still under the assumption that this is being considered for the server until told otherwise for certain)

**Comment by Zarel** [comment]
I mean, this is in a private chat plugin right now because roomlogs aren't really open-source these days... I guess I could open-source it but open-sourcing PHP seems to lead to bad things; I definitely underestimated how hard PHP is to secure...

**Comment by Morfent** [comment]
I could learn PHP and get acquainted with how to write it securely to help out. There are already changes I want to be able to make to the parts that are public anyways

**Comment by panpawn** [comment]
So, should I close this then @Zarel ?

**Comment by Zarel** [comment]
Security by obscurity is a bad idea; I might just publish it anyway. Will work on that.

**Pull request closed without merging**
