### PR TITLE
Add a new alias for /help.

### PR DESCRIPTION
**Pull request by Bryan-0**
cmds = commands.

### CODE REVIEW

**Comment by Slayer95** [comment]
`/cmds` is too close to `/cmd` imo

**Comment by Bryan-0** [comment]
Yeah i know that, but there will be no error.

**Comment by AustinXII** [comment]
well the problem is that people may start putting in /cmds instead of /cmd by accident and not even realizing it

**Comment by Bryan-0** [comment]
I don't think that people can have problems with that, because of that they need to see first what they are going to send.

**Comment by codelegend** [comment]
the most important question is: Is this alias necessary?
People can just use /help or /h. I don't think anyone would prefer /cmds over /help.

**Comment by Zarel** [comment]
Unless you can show me some other software with >100 users that uses this to get a command list, I'm not going to accept this.

**Comment by xfix** [comment]
(inb4 proposing /man as alias for /help... and then /info...)

**Comment by Zarel** [comment]
zarel@Lysine ~> man
    What manual page do you want?

Technically not a command list. :P

**Comment by Bryan-0** [comment]
@Zarel i know a place where they use this, is on a game named "samp" (San Andreas Multiplayer), there are like *20,000* users on that game, they have different servers and on that servers they use: "/cmds, /commands, /help".

**Comment by Bryan-0** [comment]
Here is the page of the game: https://www.sa-mp.com/ <---- and here are the forums: http://forum.sa-mp.com/

**Comment by Zarel** [comment]
Hm. Well, it's probably about time to rename `cmd` to something else, anyway.

**Comment by Bryan-0** [comment]
mm Ok.

**Comment by Bryan-0** [comment]
@Zarel, can you re-open this? for a reminder of the command.

**Comment by Zarel** [comment]
No, I don't consider it that important.

**Comment by Bryan-0** [comment]
Alright.

**Pull request closed without merging**
