### PR TITLE
Random Battle: Add new Oricorio sets

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by ascriptmaster** [comment]
@TheImmortal 

Maybe they should just have copy-pasted sets because Hidden Power is kind of meh off a 98 base SpA, until it drops to NU/PU as predicted. At any rate, for those, I chose Ground instead of Ice for Pom-Pom because Electric resists both Elec/Flying STAB, and Fighting for Pa'u because Steel resists both Psychic/Flying STAB.

**Comment by TheImmortal** [comment]
Yeah, that's way too weak for coverage moves, let alone Hidden Power.

**Comment by ascriptmaster** [comment]
They are all now the same set because I legit can't find anything else to give the others.

**Comment by TheImmortal** [comment]
We can always update it later when they're in NU and with usage stats.

**Pull request merged**
