### PR TITLE
Random Battle: Update Armaldo, A-Dugtrio

### PR DESCRIPTION
**Pull request by ascriptmaster**
Armaldo is far too slow to utilize Swords Dance well, and only works on
dedicated Rain teams (which are very uncommon in Randoms).

Updated the item selection for when Substitute and Reversal are on the same set.

### CODE REVIEW

**Comment by TheImmortal** [comment]
This only has the second change.

**Comment by ascriptmaster** [comment]
Huh, so it does. The first change is in now.

**Comment by TheImmortal** [comment]
Maybe we shouldn't give Leftovers then?

**Comment by ascriptmaster** [comment]
Leftovers interferes with Reversal's damage output: at 1 HP, a single turn of Leftovers drops the BP from 200 to 150, and then 100, removing the whole point of Reversal. Focus Sash (current item) is counterintuitive with Substitute. Finally, stat berries like Leichi definitely don't want to wait until you've hit 1 HP with Substitutes before activating. Basically, I can't think of any item that would work very well with the combination, so I'd rather go on the safe side and never have both together.

**Comment by ascriptmaster** [comment]
I've given my explanations for why I'm coding things this way; still waiting on feedback.

**Comment by TheImmortal** [comment]
>Basically, I can't think of any item that would work very well with the combination, so I'd rather go on the safe side and never have both together.

Expert Belt? Fighting Plate? Z-Crystal!?

**Comment by ascriptmaster** [comment]
So you're suggesting Fightinium-Z? A one-time 160BP move doesn't sound too bad.

As for situations where a Z-Crystal was already chosen, Expert Belt I guess is the best choice.

Updated accordingly.

**Comment by TheImmortal** [comment]
I was thinking reject Reversal with Substitute and if the team already has a Z-Move.

**Comment by ascriptmaster** [comment]
I made the change.

**Pull request merged**
