### PR TITLE
Random Battle: Remove all other setup moves if a setup type is chosen

### PR DESCRIPTION
**Pull request by ascriptmaster**
Affects any Pokemon with both Physical and Special setup. Mixed setup is
not removed because it's always a higher priority than the others.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Have you tried this out on Infernape, Lucario, Virizion etc? What are the results like? How common is setup?

**Comment by ascriptmaster** [comment]
I used the following test suite file: http://pastebin.com/zs5ctUVd

Before my changes:

	----------
	Testing sets for Infernape
	6825 setup sets found among 10000
	108 double-setup sets found among 10000
	----------
	Testing sets for Virizion
	7874 setup sets found among 10000
	80 double-setup sets found among 10000
	----------
	Testing sets for Lucario
	8019 setup sets found among 10000
	113 double-setup sets found among 10000

After my changes:

	----------
	Testing sets for Infernape
	6854 setup sets found among 10000
	0 double-setup sets found among 10000
	----------
	Testing sets for Virizion
	7912 setup sets found among 10000
	0 double-setup sets found among 10000
	----------
	Testing sets for Lucario
	8089 setup sets found among 10000
	0 double-setup sets found among 10000

**Comment by TheImmortal** [comment]
What about setup sets with moves from the other category?

**Comment by TheImmortal** [comment]
Add Slurpuff too

**Comment by ascriptmaster** [comment]
Before:

    ----------
    Testing sets for Slurpuff
    4750 setup sets found among 10000
    0 double-setup sets found among 10000

After:

    Testing sets for Slurpuff
    4429 setup sets found among 10000
    0 double-setup sets found among 10000

**Comment by ascriptmaster** [comment]
New script: http://pastebin.com/AHBw6Be3

More iterations because I have way too much time on my hands, and I discovered that once I started checking unique sets, 10k actually leaves out some minor edge case sets. It takes like 2-3 minutes to finish the script on each run.

Before:

	Using 100000 iterations
	----------
	Testing Infernape
	259 unique sets found
	68182 setup sets found
	1151 double setup sets found
	16677 conflicting setup sets found
	----------
	Testing Virizion
	46 unique sets found
	79258 setup sets found
	809 double setup sets found
	5934 conflicting setup sets found
	----------
	Testing Lucario
	47 unique sets found
	80966 setup sets found
	1042 double setup sets found
	2601 conflicting setup sets found
	----------
	Testing Lucario-Mega
	48 unique sets found
	80761 setup sets found
	992 double setup sets found
	2608 conflicting setup sets found
	----------
	Testing Slurpuff
	50 unique sets found
	47595 setup sets found
	0 double setup sets found
	121 conflicting setup sets found

After:

	Using 100000 iterations
	----------
	Testing Infernape
	180 unique sets found
	68023 setup sets found
	0 double setup sets found
	16664 conflicting setup sets found
	----------
	Testing Virizion
	31 unique sets found
	79099 setup sets found
	0 double setup sets found
	5140 conflicting setup sets found
	----------
	Testing Lucario
	28 unique sets found
	80959 setup sets found
	0 double setup sets found
	2982 conflicting setup sets found
	----------
	Testing Lucario-Mega
	28 unique sets found
	80913 setup sets found
	0 double setup sets found
	3006 conflicting setup sets found
	----------
	Testing Slurpuff
	38 unique sets found
	45309 setup sets found
	0 double setup sets found
	253 conflicting setup sets found

For most of the mons, overall setup decreased slightly, and the mons that get more conflicting setup sets gain more than the ones that lose conflicting setup sets.

**Comment by TheImmortal** [comment]
I figured conflicting sets would be an issue. I'm not comfortable with accepting this based on those results. You need to find a way to reduce, not increase, conflicting sets if you want this.

**Comment by ascriptmaster** [comment]
I decided to test the rest of the double-setup mons that I found (Steel, Ghost and Dragon Arceus) just for completion's sake. While both Lucarios gained around 320 conflicting sets each, Ghost Arceus lost around 2000 of them, lol

I will do more investigation on how to curb Lucario's increased frequency of conflicting sets, though.

    ----------                         ----------
    Testing Infernape                  Testing Infernape
    259 unique sets found              180 unique sets found
    68182 setup sets found             68023 setup sets found
    1151 double setup sets found       0 double setup sets found
    16677 conflicting setup sets found 16664 conflicting setup sets found
    ----------                         ----------
    Testing Virizion                   Testing Virizion
    46 unique sets found               31 unique sets found
    79258 setup sets found             79099 setup sets found
    809 double setup sets found        0 double setup sets found
    5934 conflicting setup sets found  5140 conflicting setup sets found
    ----------                         ----------
    Testing Lucario                    Testing Lucario
    49 unique sets found               28 unique sets found
    80687 setup sets found             80695 setup sets found
    1086 double setup sets found       0 double setup sets found
    2687 conflicting setup sets found  3016 conflicting setup sets found
    ----------                         ----------
    Testing Lucario-Mega               Testing Lucario-Mega
    49 unique sets found               28 unique sets found
    80932 setup sets found             80760 setup sets found
    1082 double setup sets found       0 double setup sets found
    2668 conflicting setup sets found  3050 conflicting setup sets found
    ----------                         ----------
    Testing Slurpuff                   Testing Slurpuff
    51 unique sets found               38 unique sets found
    47760 setup sets found             45347 setup sets found
    0 double setup sets found          0 double setup sets found
    113 conflicting setup sets found   232 conflicting setup sets found
    ----------                         ----------
    Testing Arceus-Dragon              Testing Arceus-Dragon
    68 unique sets found               40 unique sets found
    80482 setup sets found             80467 setup sets found
    395 double setup sets found        0 double setup sets found
    6732 conflicting setup sets found  6824 conflicting setup sets found
    ----------                         ----------
    Testing Arceus-Ghost               Testing Arceus-Ghost
    54 unique sets found               52 unique sets found
    69936 setup sets found             69861 setup sets found
    3027 double setup sets found       0 double setup sets found
    8056 conflicting setup sets found  6193 conflicting setup sets found
    ----------                         ----------
    Testing Arceus-Steel               Testing Arceus-Steel
    39 unique sets found               27 unique sets found
    75694 setup sets found             75948 setup sets found
    0 double setup sets found          0 double setup sets found
    54 conflicting setup sets found    0 conflicting setup sets found

**Comment by ascriptmaster** [comment]
I'm having a new theoretical idea that I wanted to run by you, @TheImmortal 

The idea would be that each move in the movepool has a bias such that certain moves have a greater chance of being chosen over other moves, like STAB having a higher chance or conflicting setups having a lower chance. That way, we don't excessively prune the move pool in setup scenarios and the like, and increase the chances of better sets.

I'm not exactly sure on the details but basically it'd run every time it's time to choose a new move, but that'll compound the number of calls to `queryMove` we have to run, and because that function now checks the movepool when determining the setup type our algorithm is already O(N^2).

The other issue is I have no idea how I want to weight the biases.

**Pull request closed without merging**
