### PR TITLE
Ash Greninja and Zygarde 10% and Complete should be Gen 7

### PR DESCRIPTION
**Pull request by urkerab**

### CODE REVIEW

**Comment by TheImmortal** [comment]
If it's battle only then the gen shouldn't matter

**Comment by urkerab** [comment]
While that prevents Greninja-Ash from validating, because you can't have it without Battle Bond, which is a Gen 7 Ability, it still shows the wrong gen when you use `/details`.

**Comment by urkerab** [comment]
Also, Greninja-Ash currently validates for Gen 6 BH.

**Comment by TheImmortal** [comment]
Unacceptable!

**Comment by urkerab** [comment]
Oh, and this stops it from being chosen for Gen 6 Challenge Cup too.

**Pull request merged**
