### PR TITLE
UNO: Improve colored text readability

### PR DESCRIPTION
**Pull request by Teremiare**
Makes the black text visible in dark mode.
Makes yellow easier to read in bright mode (second line is old, first line is new):

Makes blue easier to read in dark mode:

### CODE REVIEW

**Comment by HoeenCoder** [comment]
If your doing this, could you fix black (wild & wild +4) in dark mode?

**Comment by Teremiare** [comment]
If you mean them still being black in dark mode the initial commit does fix that

**Comment by Zarel** [comment]
Can you resolve the merge conflict?

**Comment by Teremiare** [comment]
Resolved the conflict

**Comment by Zarel** [comment]
Also in the future please never use `_` in variables.

**Pull request merged**
