### PR TITLE
Help: Add scrollbar for long replies

### PR DESCRIPTION
**Pull request by panpawn**
This adds a scrollbar to help commands that are longer than 15 lines

### CODE REVIEW

**Comment by panpawn** [comment]
Note: Bondie had suggested using ``<summary>`` and ``<details>`` tags for individual help commands and splitting them into sections as opposed to this solution.

**Comment by Articuno-I** [comment]
My understanding of Bondie's request is that it would mostly be editing the larger help commands individually and largely subjectively, and that this piece of code itself wouldn't need to be changed for that to be implemented. Is that correct?

If so, I think it makes most sense for this pr to be merged and then coders with more free time but who don't know what to do on PS (such as myself) could update the help commands, where the only real difficulty would be the subjectivity in how to separate the help commands into sections.

**Comment by panpawn** [comment]
>Is that correct?

Yes

**Comment by panpawn** [comment]
Anyways, I went ahead and made a PR to split specifically Trivia's help command up into sections https://github.com/Zarel/Pokemon-Showdown/pull/3897 as well

**Comment by Zarel** [comment]
There's zero reason to add a scrollbar for long replies. Either you want to read the response or you don't. If you use the command, it implies you do want to read the response, so you should not intentionally make the response hard to read.

The only valid use of `infobox-limited` is to limit roomintro size, so rooms can't make them too big.

**Comment by panpawn** [comment]
That doesn't consider someone spamming it in battles or PMs to be malicious though - just because the command is used, doesn't mean that anyone actually wants to see it

**Comment by Articuno-I** [comment]
IDK about PMs but surely the solution to broadcasted commands being spammed in battles is to hide them when broadcast by a hidden opponent / spectator somehow?

**Comment by bumbadadabum** [comment]
If people are spamming them that's a problem with the users.

**Comment by Zarel** [comment]
If there's reason to split it into sections, you can make the sections autohide by default.

**Comment by panpawn** [comment]
Closing this as it seems this would really only affect a few help commands - and those specific ones should probably be what changes, not a general change such as this.

**Pull request closed without merging**
