### PR TITLE
Poll: Fix display

### PR DESCRIPTION
**Pull request by sparkychildcharlie**
- make all poll options align left

### CODE REVIEW

**Comment by Zarel** [comment]
Screenshot before/after?

**Comment by sparkychildcharlie** [comment]
Before:
Dank memes 1

After:
Dank memes 2

**Comment by Zarel** [comment]
Thanks.

PS: true things can be memes

**Comment by AustinXII** [comment]
@sparkychildcharlie absolutely __disgusting__

**Pull request merged**
