### PR TITLE
Random Battle: Various Moveset Fixes

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by TheImmortal** [comment]
Reasoning for each change?

**Comment by ascriptmaster** [comment]
- Lumineon always wants Scald and that has same BP as Waterfall anyways. Especially since Seaking and probably other physical attackers caused Scald to reject with Waterfall in our scripts.
- Mega Audino only has its STABs for damage. Fire Blast helps it hit Steel.
- Liquidation is stronger than Waterfall, and Carracosta is so slow it hardly gets flinches off Waterfall even after a Shell Smash.
- Seed Bomb hits Rock and Ground and Drain Punch hits Rock and Steel. All of these resist Garbodor's STAB. Rock Blast doesn't help as much with coverage, and kinda sucks. Also it's in its ORAS analysis on Smogon, both have higher than 20% usage (Seed Bomb 34%, Drain Punch 22%), and Rock Blast only has 5% usage now
- Zoroark appreciates the Fairy coverage
- Skill Link Toucannon. It has no good Sheer Force moves anyways so best to cater to its other ability
- Shiinotic's other STAB and minor recovery
- U-Turn is very popular on Scarfed Passimian (which is the only set it can have with its 4 moves anyways) with 87% usage
- Consistent Bug STAB for Goliscopod because sometimes you're already switched in and still want to punch a Slowking in the face
- Consistent STABs for Turtonator because SpA drops for its only reliable STAB sucks. If you still want Overheat then Draco Meteor can be cut

**Comment by ascriptmaster** [comment]
Feedback on the changes would probably be nice.

**Comment by TheImmortal** [comment]
Garbodor: I don't think Seed Bomb and Drain Punch are good options. Garbodor isn't an offensive Pokemon and would prefer its support moves. If you want to add a second attack, I think it should be Explosion.

Toucannon: We don't need to cater to its ability if it doesn't improve the Pokemon. What do those moves hit that its STAB and Brick Break don't hit?

Shiinotic: Does Giga Drain actually help it? The Pokemon that resist Moonblast also resist Giga Drain. It would prefer its support moves.

Turtonator: Remove Dragon Pulse imo.

**Comment by ascriptmaster** [comment]
Garbodor's Smogon set is both sets of spikes, Gunk Shot, and coverage (Seed Bomb or Drain Punch). Between the two, if one could stay only, I'd choose Drain Punch for minor recovery and the fact that Steel is immune to Poison while Ground only resists it. Explosion could still be an option.

Brick Break is very weak against non-Steel, non-Rock Pokemon. Looking at the coverage charts and usage, it seems that Rock Blast is most popular for the toucan because it practically doubles the number of Pokemon it is super effective against and is still a solid raw damage move against Electric and Rock, which both resist Flying. Meanwhile, Bullet Seed hits Rock and Water really hard, and both of those types typically carry super-effective moves against Toucannon (Rock especially because it resists and has its own STAB be super-effective, while Water commonly carries Ice Beam). Brick Break is very rare on its usage stats, but I guess so is Swords Dance and that's still a good move.

    [15:18] %Ascriptmaster: .usage toucannon moves uu
    [15:18] *TIBot: Rock Blast 83.291% | Bullet Seed 79.836% | Beak Blast 62.874% | Brave Bird 32.354% | U-turn 25.091% | Roost 23.135% | Flame Charge 19.315% | Return 12.610% | Brick Break 9.885% | Overheat 8.961% | Swords Dance 8.489% | Tailwind 6.242% | Boomburst 4.295% | Substitute 4.234% | Ot...

Shiinotic doesn't really need Giga Drain, but the idea was that it's nice secondary recovery for a support mon. I guess it doesn't *really* need it.

**Comment by TheImmortal** [comment]
Fine, I'll accept the Toucannon. If I get complaints or have a bad experience myself with it then I'll change it.

**Pull request merged**
