### PR TITLE
Fix multiple places in SSB leaking Illusion

### PR DESCRIPTION
**Pull request by Lusamine**
Lava Terrain leaks Illusion; this fix shows the Illusion mon's name if it's in effect.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Speaking of Lava Terrain, is it intentional that it doesn't override other Terrains @HoeenCoder ?

**Comment by Torracat** [comment]
@TheImmortal it does override terrains. There is a visual bug that makes it look like terrains are stacking on top of each other

**Comment by HoeenCoder** [comment]
Its a visual bug yeah, I'm going to do a client PR for that / patch setTerrain again soon(tm)

**Comment by HoeenCoder** [comment]
Looks like scripted terrain has this issue too, can you patch that and check the rest just in case?

**Pull request merged**
