### PR TITLE
Add Dark Void alias

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by Zarel** [comment]
Is this actually used? @TheImmortal?

**Comment by Spandamn** [comment]
I thought it would be 
I've seen people trying to broadcast !dt dv

**Comment by AustinXII** [comment]
Seeing how it's a special move only being used by 2 Pokemon I feel this is un-needed

**Comment by Spandamn** [comment]
Hmm okay, I agree with that
Oh and its heavily used in BH Doubles

**Comment by TheImmortal** [comment]
I honestly don't know if it's used in Ubers and/or Doubles but it is used in OM.

**Comment by TheImmortal** [comment]
Apparently it is used outside OM

**Comment by Zarel** [comment]
This will also move Dark Void above Disarming Voice in a "dv" search in the teambuilder/dex.

**Comment by Spandamn** [comment]
Great

**Pull request merged**
