### PR TITLE
Blacklist: Specify "room" ban in errorReply

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
We're moving to using "ban" instead of "roomban" for roombans.

**Comment by panpawn** [comment]
Would "just ban the user from the room" be better?

"ban" has always implied global ban, and I understand that we're moving to using just "ban", but perhaps we could make this more specific.

**Comment by Zarel** [comment]
I don't think that's necessary.

"Ban" hasn't implied global ban except to global mods and above, which most users aren't.

**Comment by Zarel** [comment]
And for the people who are global mods, they've gotten the message.

**Comment by panpawn** [comment]
I've literally never seen room staff refer to room bans as just "ban" before, from my observations, at least.

Maybe I just haven't been paying enough attention, who knows.

**Comment by Zarel** [comment]
Weird. Lately, I've only ever seen "ban" to mean "roomban".

**Comment by panpawn** [comment]
>Lately, I've only ever seen "ban" to mean "roomban".

I interpret this as people referring to global bans as "global bans" then, which I also haven't seen... :|

**Comment by panpawn** [comment]
I actually really think what this is, is me just disagreeing with the renaming of "room bans" to "bans".

It seems really inconsistent to me.  I understand renaming "ban" to global ban, that matches other commands such as globalpromote.

But room bans stray from that trend.  There's lots of room-specific terms that use "room" before them: roomintro, room staff, roomvoice, etc, that it just makes more sense to me to use "room ban" in the UI than just "ban".  (And those also use "room" in their UI iirc)

I guess I just don't really understand what makes "bans" different than any other room-specific thing, UI wise.

**Comment by Zarel** [comment]
As PS has gotten bigger, I've been moving slowly towards having "room" be the default rather than "global".

Back when PS had one lobby chatroom, room[anything] and global[anything] were essentially the same thing. 

Nowadays, room staff outnumber global staff, and even the global staff are used to thinking in terms of the rooms they staff rather than PS as a whole. Some commands specify "room" to be clear, but many don't, such as modchat/modjoin.

You noticed that I renamed `roommod/mod` to `roommod/globalmod`, after quite a few incidents of various upper staff accidentally global modding a user they meant to roommod. I'd actually considered renaming it to `mod/globalmod` eventually, but promotion is the sort of thing that happens rarely enough that you might as well require some more typing and make absolutely sure what the user intended to do.

Banning, on the other hand, happens often enough that I really am planning on renaming the commands from `roomban/ban` to `roomban/globalban` and eventually to `ban/globalban`. It's just as clear that way, and probably more natural. PS has always been inspired by IRC, and in IRC, "ban" means to be banned from a chatroom; they call server bans "gline" or something.

**Pull request closed without merging**
