### PR TITLE
Parting Shot only switches if the stat drops succeeded

### PR DESCRIPTION
**Pull request by QuiteQuiet**
This was listed in the Smogon SM research thread [here](http://www.smogon.com/forums/threads/pokemon-sun-moon-battle-mechanics-research.3586701/page-71#post-7470273) and nothing I've been able to find contradicts this claim, though the information regarding this is admittedly very limited.

### CODE REVIEW

**Comment by Zarel** [comment]
@DaWoblefet?

**Comment by Zarel** [comment]
@Marty-D?

**Comment by Marty-D** [comment]
Yeah, has been known since someone [reported it as a bug](http://www.smogon.com/forums/posts/7339180). This doesn't seem to cover the case where the stats don't change because they're at -6 (or +6 with Contrary), which shouldn't cause a switch either.

**Comment by QuiteQuiet** [comment]
Okay, it should only cause a switch if the boost was != 0 now, including Contrary and probably cases like Hyper Cutter + -6 SpA as well.

As a side note, I was looking at Adrenaline Orb (because it was the only other thing that use `onAfterBoost`), and according to Bulbapedia (not reliable source) it is only consumed if the item will boost the stat (so not at +6 speed). Is that actually the case?

**Comment by DaWoblefet** [comment]
Confirming what Marty said with [3DS footage](https://youtu.be/E6v2qvJGVtU). That is, any time Parting Shot cannot lower both Attack and Special Attack, it won't switch the user out (I tested Clear Body, Mist, Hyper Cutter & -6 Sp. Atk, -6 Atk & -6 Sp. Atk, Contrary at +6 each).

> As a side note, I was looking at Adrenaline Orb (because it was the only other thing that use onAfterBoost), and according to Bulbapedia (not reliable source) it is only consumed if the item will boost the stat (so not at +6 speed). Is that actually the case?

Bulbapedia's description is correct (Adrenaline Orb is not consumed at +6 Speed). I show it off near the end of the video.

**Comment by urkerab** [comment]
If the Adrenaline Orb is the only thing that used `AfterBoost` then I would have said the easiest fix would be to change it to use `AfterEachBoost` instead, as that only runs after a successful boost.

As for Parting Shot, I would have written it like this, although it might be too subtle:

    onHit: function () {
        return this.boost({atk: -1, spa: -1});
    },
    selfSwitch: true,

For Gen 6 the `return` would be removed, causing the `selfSwitch` to always happen.

**Comment by QuiteQuiet** [comment]
>If the Adrenaline Orb is the only thing that used AfterBoost then I would have said the easiest fix would be to change it to use AfterEachBoost instead, as that only runs after a successful boost.

This is actually not correct from what I've gathered. Adrenaline Orb triggers on the activation of Intimidate, even if Intimidate doesn't result in a lowered stat.

**Comment by urkerab** [comment]
Sorry, I misread the previous comment. (The lack of activation at +6 speed is something I already have code for. Thanks for reminding me to test and PR it.)

**Comment by Marty-D** [comment]
Done in #4105

**Pull request closed without merging**
