### PR TITLE
Chat: make the broadcast cooldown actually work

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
There's a repetition cooldown in `canTalk` though.

**Comment by Zarel** [comment]
What exactly does this actually fix?

**Comment by whalemer** [comment]
It lets the check at l715 work, in the current code ``this.broadcastMessage`` isn't defined by that point.

**Comment by whalemer** [comment]
The cooldown here exists in every room, stopping you from broadcasting the same message as the last message broadcast within 20 seconds.

**Comment by Zarel** [comment]
Okay but can you not move the location of the `canTalk` check? I'm afraid that's going to break other things.

**Comment by whalemer** [comment]
I don't see what that'd break unless you had some very strange chatfilters, but sure, updated

**Comment by Zarel** [comment]
Anyone can make whatever chatfilter they want, so those "very strange chatfilters" may very well actually exist.

(I'm pretty sure they do actually exist, too.)

**Comment by Zarel** [comment]
Chatfilters are supposed to be supported as message logging: If a chatfilter doesn't return `false`, the message is guaranteed to be output to the room.

**Comment by whalemer** [comment]
Fair enough

**Comment by Zarel** [comment]
Looks like a lot of users are annoyed by this affected `!roll` etc.

**Comment by Zarel** [comment]
We should maybe add an exception or something.

**Comment by whalemer** [comment]
Agreed, I tried at #4594

**Pull request merged**
