### PR TITLE
Use void in promises to appease TSLint

### PR DESCRIPTION
**Pull request by TheJetOU**
We obviously don't care about floating promises if we're disabling them.

The server checks checks for `unhandledRejection`s anyway.

### CODE REVIEW

**Comment by Zarel** [comment]
We had this discussion when it was first turned on.

@scheibo's idea was that floating promises should be explicit. It's kind of like `// falls through` in switch-cases: it's not about "we shouldn't do it", but "we shouldn't do it accidentally".

**Comment by scheibo** [comment]
I gave up on my mission to civilize.

**Comment by Zarel** [comment]
What's wrong with my `void` idea, anyway?

**Comment by scheibo** [comment]
The point is to propagate the future up to the correct level and handle it there (or `// tslint:disable`) it and then probably half of these ignores would go away, but I gave up trying to tell people to fix the chain in `server/`.

**Comment by scheibo** [comment]
If you want to use `void`, do what you want. I will continue to fix the chains in the code I need and disregard everything in `server/` anyway

**Pull request merged**
