### PR TITLE
Random Battle: Remove Shell Smash from Magcargo

### PR DESCRIPTION
**Pull request by ascriptmaster**
Its speed is not high enough to take advantage of it and therefore could
die easily before it can get an attack off.

---

Just something that was mentioned yesterday in PS Staff chat.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Then remove HP Grass because that is weak unboosted.

**Comment by AustinXII** [comment]
well people still use it fairly often, although the speed doesn't really matter the rise in SPA does. I think it is still viable.

**Comment by ascriptmaster** [comment]
Went back to PS Staff and people didn't seem to mind any more.

**Comment by SolarisFox** [comment]
Just to pitch in my two cents: Magcargo's potential to have Shell Smash makes it a bit less predictable which indirectly helps all other sets it can have.

**Pull request closed without merging**
