### PR TITLE
Gen 1 Random Battles: Improve movesets and balance

### PR DESCRIPTION
**Pull request by xCrystal**
Even though randbats aims to be as close to competitive as possible, it still leaves a lot to be desired. Some of the possible movesets and move combinations are very suboptimal, to the point that some Pokemon such as Fire-types or Water-types often come without a STAB move, and a few Pokemon may even come with no damaging move other than Explosion/Selfdestruct. A lot of Pokemon may also come with moves that have no use whatsoever even though there are far more useful options in their movepool. This PR mainly aims to improve the efficiency of the movesets while still keeping some variety in Pokemon that can successfully use different kind of sets. There were also a couple of cases of incompatible moves that were fixed.

In addition to movesets, levels are also balanced in this PR. Instead of being based off just the tier, each Pokemon now gets a level based on its overall strength in a metagame where all 151 Pokemon may show up. The tiers are accurate when the player is given the choice to select 6 Pokemon, but when Pokemon are assigned randomly, other factors such as BST should be taken into account. Based on my knowledge of this tier, as well as RBY OU, I've tried my best to estimate each Pokemon's strength when assigning the levels.

This level balance also opened the possibility of making OUs not so blatantly common as they where. Fully evolved Pokemon are still favored over NFEs and LCs though.

I set up my own server on localhost and tested all the changes by generating multiple battles to make sure everything's working as expected.

I noticed that Wartortle was tagged as UU when it showed up with the wrong level, even though it's listed as NFE in Smogon and has no business being in UU. I assumed it was a typo so I fixed it. If it's there for a reason, I can change it back.

### CODE REVIEW

**Comment by Zarel** [comment]
I like this in general, but why are the custom levels so important?

**Comment by ascriptmaster** [comment]
Yeah the custom levels are too much. Custom levels are supposed to only be rarely handed out. There is way too much holistic judgment on these scales.

If you think it's still too imbalanced, then I suggest you look at the modern `randomDoublesSet` level scaling; it determines all levels purely using base stats, but tweak the formula a little to better suit your needs. For example, tweaking the formula slightly to `60 + Math.floor(((600 - this.clampIntRange(bst, 200, 600)) / 10.34))` gives you a Level 98 Weedle/Magikarp, Level 60 Mewtwo, and Level 69 Dragonite, so *most* other things should fall into place. Maybe you'll just have to tweak Mew to a slightly lower level since it'll also be Level 69 with this formula.

**Comment by xCrystal** [comment]
I think a universal BST-based formula to determine the level of all Pokemon wouldn't be accurate in RBY for the following reasons:
- There's a huge difference in movepools, contrary to the newer generations where all Pokemon are gifted with versatile options. In RBY, there are Pokemon that get very effective movepools that include a strong STAB move, plenty of coverage options, and/or extremely useful moves like Amnesia or Recover. On the other hand, other Pokemon are only able to barely use normal-type moves or very weak STAB attacks.
- Some types are significantly better than the rest, both defensively and offensively, specifically Psychic and Normal, and Water to an extent.
- The Special stat should be weighed more than the other stats since in RBY it's both Special Attack and Special Defense. I guess thid would have an easy solution, but I just don't think a simple BST-based formula would lead to accurate results due to the peculiarities and lack of balance in Gen 1.

I agree that a lot of decisions were arbitrary and if someone else was given the task to balance out the levels, they'd probably choose slightly higher or lower levels in some cases, probably up to a 4-level difference. What I tried in regards to LC and NFE Pokemon was to make them balanced to their fully evolved counterparts, so that the LC/NFE Pokemon have slightly lower resulting stats, but the difference is just enough to be compensated in the level factor of the attack formula. Obviously, the shitmons are still significantly weaker than the rest, but you can't help those unless you lower the other ones to around level 30-40.

**Comment by xCrystal** [comment]
By the way, let me know if you'd rather I rebase and force push the last two commits, or all three commits, into a single one. The last commit was to amend an oversight/typo that I randomly noticed now, but everything else should be fine (unless the level changes are reworked/reverted).

**Comment by Zarel** [comment]
No, your commits are great and don't need to be rebased.

I still don't think custom levels are necessary. Randbat has always been balanced so that OU Pokémon retain their relative speed tiers; i.e. if you have two OU Pokémon, the faster one will always be faster. I'd rather not break that without a good reason.

**Comment by xCrystal** [comment]
I've opened a thread/poll in the Ruins of Alph subforum of Smogon to gather opinions on this matter: http://www.smogon.com/forums/threads/ps-random-battles-level-balancing.3595079/

**Comment by xCrystal** [comment]
Alright, so I opened a poll in both Smogon and the Ruins of Alph PS room and the results have been approximately 1/3 for keeping levels consistent within tiers and 2/3 for balancing the levels. 
http://i.imgur.com/95t28CL.png
Still, nobody really bothered to give their opinion on my proposed levels or to suggest their own. The moveset changes were mostly agreed upon, and the few people that commented on them were happy about the improvements. I'd at least would like to see the moveset uprades going through, so feel free to let me know if I should revert the level changes (or only adjust the levels given to each tier), if I should keep the OU Pokemon at the same level, or if it's fine to leave them as I suggested.

**Comment by TheImmortal** [comment]
I agree that we shouldn't assign arbitrary levels to each and every Pokemon. We already have tiers that balance out the levels. However, if you balance the OU Pokemon, there is already a scale available to us - viability rankings. Set Uber to 70, then OU Pokemon according to their rank. S rank 72, A rank 73, B 74, C 75, D 76, and E 77. UU to 79, NFE to 81, and LC to 83. Problem solved?

**Comment by xCrystal** [comment]
I don't think levels should be based on rank because those are mostly an indicator of how the Pokemon performs in a OU environment, but not in a tier where all 151 are supposed to have similar strength. I actually would rather leave all OUs with the same level then.

Still, I was think that the level scale between LC Pokemon up to OU and Ubers should be wider. If I were to revert the custom levels, I was thinking to keep the default levels I assigned for each tier (except OUs would probably be 60 and LC Pokemon would average at 78). I think a level diffenence of 13 at such higher levels is not enough to compensate the difference in strength of first stage evolutions and strong full evolutions.

Another option is maybe I could divide each tier into two subgroups, and assign each subgroup a different level (say, a 3 or 4 level difference between the subgroup), depending on how strong the Pokemon is compared to the rest of the tier. This would still allow for an accurate balance of most Pokemon while not feeling quite as arbitrary.

**Comment by Zarel** [comment]
Once again, if we interpret randbat as a way to learn a generation's tiers' speed tiers, every tier should have the same level.

A poll is interesting information, but it doesn't answer my main question of why?

**Comment by xCrystal** [comment]
Well, different interpretations then, I guess. I never saw randbats as a way to learn the generation's speed tiers, just a different kind of metagame where maybe a different kind of skill is needed. Apart from being familiar with the generation's mechanics and Pokemon, there's usually some other skill involved, such as being able to identify your opponent's biggest threats, analyzing on the fly how important each Pokemon is given the current state of the battle to act accordingly, being able to choose the best action accounting for the characteristics of the hidden Pokemon that your opponent may have, and in the late game, there's often a lot of knowing how to play by the numbers. I never really saw randbats as a way to get used to the generation, although I see there's a point on it.

**Comment by Zarel** [comment]
Let's discuss here?

https://www.smogon.com/forums/threads/ps-random-battles-level-balancing.3595079/#post-7227157

**Comment by xCrystal** [comment]
Any news on this?

**Comment by Zarel** [comment]
It seems like there aren't particularly many people posting opinions, so I'd say revert the custom levels and keep everything else.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
