### PR TITLE
Random Battle: Diversify Xerneas' Moveset

### PR DESCRIPTION
**Pull request by ascriptmaster**
~~Xerneas has no business running Thunder in a non-Ubers format since Drizzle is rather uncommon.~~

~~NO I'M NOT MAD THAT I NEARLY LOST A RANDBATS GAME DUE TO XERNEAS MISSING THUNDER TWICE IN A ROW AND LETTING THE OPPONENT SET UP, WHY DO YOU ASK~~

Xerneas is a good Pokemon, but there are sets it can run that don't require Geomancy. Might as well give it some variety.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
More serious talk, we should consider letting Xerneas run non-Geomancy sets. Then we can level-scale non-Geomancy Xerneas and Geomancy Xerneas appropriately. (Just like how our current code has Magikarp's Revenge Magikarp at a lower level than regular Magikarp)

**Comment by TheImmortal** [comment]
Haha. Nobody ever complained about Thunder, it's power + par is worth the accuracy loss on this beast. How about this: keep Thunder and add Thunderbolt, Close Combat, HP Fire, Rock Slide, Psyshock. And keep non-Geomancy Xerneas at the default level of 70.

You could also bump up Geomancy Xerneas to 68 since it won't get the best Geomancy set 100% of the time. This change is 50/50.

**Comment by ascriptmaster** [comment]
So, like this?

I also added Megahorn and Substitute because they were on Smogon sets

**Comment by Zarel** [comment]
Actually, people were complaining about Thunder in Staff a lot. It's how this pullreq got made in the first place.

**Comment by TheImmortal** [comment]
No, remove Megahorn and Substitute.

**Comment by ascriptmaster** [comment]
Substitute is still useful, I think, to block status (oh boy! GeoSub Xern!). Megahorn will definitely go.

I'll work on it tomorrow.

**Comment by TheImmortal** [comment]
I'll do it with other changes I have.

**Pull request merged**
