### PR TITLE
Aliases: Add 'uber' as an alias to 'Ubers'

### PR DESCRIPTION
**Pull request by panpawn**
Should this have the [Gen 7] prefix?

### CODE REVIEW

**Comment by Zarel** [comment]
Probably? Haven't you tested it?

**Comment by panpawn** [comment]
ok, i did now, it works

**Comment by MacChaeger** [comment]
won't this interfere with `/ds uber`?

**Comment by Yoshizilla315** [comment]
I wouldn't think so, since it would technically display the same thing.

**Comment by MacChaeger** [comment]
No, `/ds [Gen 7] Ubers` produces no search results, and as far as I know, it won't try the original input. On that note, I'd appreciate it if `/ds ubers` actually did produce search results.

**Comment by Yoshizilla315** [comment]
Oh I see what you're saying, I was just saying that `/ds uber` and searching "uber" in the team builder would show the same content, so I don't see how that would interfere.

**Comment by MacChaeger** [comment]
Sure, they do now. But making `'uber'` an alias for `'[Gen 7] Ubers'` would make `/ds uber` not work at all. That's not to mention that `/ds` and the teambuilder have different functionality; specifically, the chat command can search with multiple bounds, have exclusions, and more, i.e. `/ds speed > 100, attack > 110, !dragon type, recovery`, while the teambuilder allows sorting by base stats.

**Comment by panpawn** [comment]
This won't effect the results of ``/ds uber`` at all

**Comment by MacChaeger** [comment]
You tested it?

**Comment by Yoshizilla315** [comment]
So, since team builder and /ds commands are different, then why would the alias "uber" affect ``/ds uber`` be affected by this change at all?

**Comment by panpawn** [comment]
> You tested it?

Yes

**Pull request merged**
