### PR TITLE
Fix Surf In Generation 3

### PR DESCRIPTION
**Pull request by czn-PS**

### CODE REVIEW

**Comment by czn-PS** [comment]
Surf has a BP of 95 in gen 3 and hits "allAdjacentFoes".

**Comment by czn-PS** [comment]
Will fix desc as well.

**Comment by Marty-D** [comment]
You're overriding the wrong description; what you're looking for is `shortDesc`. That's the one used in battle tooltips and the teambuilder for past gens.

Ideally the description would also match its current one (or other moves with effects like it) as closely as possible. So here it would be "Hits adjacent foes. Power doubles on Dive." (and for Gen 2 "No additional effect.", but there are tons of these to do and I just haven't gotten around to it yet because it's a massive headache, so don't bother with that).

**Comment by czn-PS** [comment]
@Marty-D eh so will I just close this?

**Comment by Zarel** [comment]
I'm not sure if we want to accept commits for all of these individually. Maybe if you do a lot of them?

**Comment by Marty-D** [comment]
@Zarel, in this case it's fine since there's an actual fix to go along with it (the targeting change). Others will get done as batched together as possible.

@czn-PS, you didn't actually change the description to "Hits adjacent foes. Power doubles on Dive." like I asked...

**Pull request closed without merging**
